### ISSUE TITLE
Critical error: ERROR: the renter is idle, but tracking 4 active pieces; resetting to zero

### ISSUE THREAD

**Issue by sdos77** [NebulousLabs/Sia#2319] opened 2017-09-14 05:06 UTC
[siad-output.txt](https://github.com/NebulousLabs/Sia/files/1301756/siad-output.txt)

**Comment by tbenz9** [comment] 2017-09-28 04:41
I'm having the exact same issue.  Sia 1.3.0 on Ubuntu 14.04.

```Loading...
(0/5) Loading siad...
(1/5) Loading gateway...
(2/5) Loading consensus...
(3/5) Loading transaction pool...
(4/5) Loading wallet...
(5/5) Loading renter...
Finished loading in 0.93607286 seconds


goroutine 147 [running]:
runtime/debug.Stack(0x445837, 0x0, 0xc4464c5bf0)
        /usr/local/go/src/runtime/debug/stack.go:24 +0x79
runtime/debug.PrintStack()
        /usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/NebulousLabs/Sia/build.Critical(0xc4464c5d70, 0x3, 0x3)
        /home/luke/go/src/github.com/NebulousLabs/Sia/build/critical.go:16 +0xa7
github.com/NebulousLabs/Sia/persist.(*Logger).Critical(0xc420eff460, 0xc4464c5d70, 0x3, 0x3)
        /home/luke/go/src/github.com/NebulousLabs/Sia/persist/log.go:37 +0xe0
github.com/NebulousLabs/Sia/modules/renter.(*Renter).managedDownloadIteration(0xc421487500, 0xc4464c5f20)
        /home/luke/go/src/github.com/NebulousLabs/Sia/modules/renter/download.go:365 +0x67d
github.com/NebulousLabs/Sia/modules/renter.(*Renter).threadedDownloadLoop(0xc421487500)
        /home/luke/go/src/github.com/NebulousLabs/Sia/modules/renter/download.go:635 +0x37e
created by github.com/NebulousLabs/Sia/modules/renter.newRenter
        /home/luke/go/src/github.com/NebulousLabs/Sia/modules/renter/renter.go:220 +0x3e3
Critical error: ERROR: the renter is idle, but tracking 1 active pieces; resetting to zero
Please submit a bug report here: https://github.com/NebulousLabs/Sia/issues
goroutine 147 [running]:
runtime/debug.Stack(0x445837, 0x0, 0xc4223e1bf0)
        /usr/local/go/src/runtime/debug/stack.go:24 +0x79
runtime/debug.PrintStack()
        /usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/NebulousLabs/Sia/build.Critical(0xc4223e1d70, 0x3, 0x3)
        /home/luke/go/src/github.com/NebulousLabs/Sia/build/critical.go:16 +0xa7
github.com/NebulousLabs/Sia/persist.(*Logger).Critical(0xc420eff460, 0xc4223e1d70, 0x3, 0x3)
        /home/luke/go/src/github.com/NebulousLabs/Sia/persist/log.go:37 +0xe0
github.com/NebulousLabs/Sia/modules/renter.(*Renter).managedDownloadIteration(0xc421487500, 0xc4223e1f20)
        /home/luke/go/src/github.com/NebulousLabs/Sia/modules/renter/download.go:365 +0x67d
github.com/NebulousLabs/Sia/modules/renter.(*Renter).threadedDownloadLoop(0xc421487500)
        /home/luke/go/src/github.com/NebulousLabs/Sia/modules/renter/download.go:635 +0x37e
created by github.com/NebulousLabs/Sia/modules/renter.newRenter
        /home/luke/go/src/github.com/NebulousLabs/Sia/modules/renter/renter.go:220 +0x3e3
Critical error: ERROR: the renter is idle, but tracking 3 active pieces; resetting to zero
Please submit a bug report here: https://github.com/NebulousLabs/Sia/issues```

**Comment by tbenz9** [comment] 2017-10-09 17:34
Duplicate of #2395 

Recommendation to Devs: Close

**Closed** 2017-10-09 18:30 UTC
