### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by drolcak** [NebulousLabs/Sia#2503] opened 2017-12-03 03:32 UTC
Sia UI version: v1.3.0
Sia version: 1.3.0
OS: Windows 10 pro
____________
logs:
 _______________
Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 28.0796663 seconds

Wallet: scanned to height 127527...
Done!
panic: page 10378 already freed

goroutine 10 [running]:
github.com/NebulousLabs/bolt.(*freelist).free(0xc042064c00, 0x4da, 0x5b6a000)
	/home/luke/go/src/github.com/NebulousLabs/bolt/freelist.go:121 +0x2a1
github.com/NebulousLabs/bolt.(*node).spill(0xc0553ebb20, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/bolt/node.go:363 +0x1e7
github.com/NebulousLabs/bolt.(*node).spill(0xc0432869a0, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/bolt/node.go:350 +0xbb
github.com/NebulousLabs/bolt.(*node).spill(0xc0420f62a0, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/bolt/node.go:350 +0xbb
github.com/NebulousLabs/bolt.(*node).spill(0xc0420f60e0, 0xc042065b30, 0xc04246da28)
	/home/luke/go/src/github.com/NebulousLabs/bolt/node.go:350 +0xbb
github.com/NebulousLabs/bolt.(*Bucket).spill(0xc042038480, 0xc042064e00, 0xc04246dc98)
	/home/luke/go/src/github.com/NebulousLabs/bolt/bucket.go:570 +0x182
github.com/NebulousLabs/bolt.(*Bucket).spill(0xc0420f00f8, 0x2f4019f4, 0xee9fe0)
	/home/luke/go/src/github.com/NebulousLabs/bolt/bucket.go:537 +0x8ff
github.com/NebulousLabs/bolt.(*Tx).Commit(0xc0420f00e0, 0xc04203d040, 0xc04246de80)
	/home/luke/go/src/github.com/NebulousLabs/bolt/tx.go:163 +0x12c
github.com/NebulousLabs/Sia/modules/transactionpool.(*TransactionPool).syncDB(0xc0420669a0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/transactionpool/persist.go:54 +0x4e
github.com/NebulousLabs/Sia/modules/transactionpool.(*TransactionPool).threadedRegularSync(0xc0420669a0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/transactionpool/persist.go:44 +0x17e
created by github.com/NebulousLabs/Sia/modules/transactionpool.(*TransactionPool).initPersist
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/transactionpool/persist.go:126 +0x3f6

**Comment by tbenz9** [comment] 2017-12-04 18:11
Duplicate of #2413 

Recommendation to devs: Close

**Closed** 2017-12-04 18:16 UTC
