### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by Tyz49** [NebulousLabs/Sia#3047] opened 2018-05-25 06:02 UTC
# BUG REPORT

**Stack Trace or error message**

**Expected Behavior**

**How to reproduce it (as minimally and precisely as possible)**

**Environment**
* Sia version:
* OS:

**Comment by Tyz49** [comment] 2018-05-25 06:02
Sia Daemon v1.3.2
Git Revision 72938f5
Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
panic: Consensus change series appears to be inconsistent - we are applying the wrong block.

goroutine 1 [running]:
github.com/NebulousLabs/Sia/modules/transactionpool.(*TransactionPool).ProcessConsensusChange(0xc420266160, 0x521f3f24578df471, 0x49af91b88a1beab0, 0xf4963c65d0e92368, 0x68ad3b1a1a912528, 0x0, 0x0, 0x0, 0xc42000fe60, 0x1, ...)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/transactionpool/update.go:223 +0x2b61
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).managedInitializeSubscribe.func2(0xc42005e2a0, 0x16f0928, 0xc42005e2a0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/subscribe.go:187 +0x236
github.com/NebulousLabs/Sia/vendor/github.com/coreos/bbolt.(*DB).View(0xc42012a780, 0xc420129030, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/vendor/github.com/coreos/bbolt/db.go:704 +0x9a
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).managedInitializeSubscribe(0xc4200d1b80, 0x19f0d60, 0xc420266160, 0x5d28d007dda938e6, 0x627290b877d0dd16, 0xf8da359d52801b06, 0x644ceeb36f9a1494, 0xc420242300, 0x1070316, 0x114643115)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/subscribe.go:176 +0x266
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).ConsensusSetSubscribe(0xc4200d1b80, 0x19f0d60, 0xc420266160, 0x5d28d007dda938e6, 0x627290b877d0dd16, 0xf8da359d52801b06, 0x644ceeb36f9a1494, 0xc420242300, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/subscribe.go:216 +0x101
github.com/NebulousLabs/Sia/modules/transactionpool.(*TransactionPool).initPersist(0xc420266160, 0xc420266160, 0xc4201ca8d0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/transactionpool/persist.go:179 +0x97d
github.com/NebulousLabs/Sia/modules/transactionpool.New(0x19fc420, 0xc4200d1b80, 0x19fbf00, 0xc4200c89a0, 0xc420018140, 0x42, 0x0, 0x0, 0x1029968)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/transactionpool/transactionpool.go:101 +0x250
main.(*Server).loadModules(0xc4200a04b0, 0x16f0cb0, 0xc42005a300)
	/home/luke/go/src/github.com/NebulousLabs/Sia/cmd/siad/server.go:514 +0x1875
main.startDaemon(0x0, 0x0, 0x7fff5fbffc9f, 0xe, 0x7fff5fbffccb, 0x5, 0x7fff5fbffcba, 0x5, 0x0, 0x7fff5fbffd1e, ...)
	/home/luke/go/src/github.com/NebulousLabs/Sia/cmd/siad/daemon.go:188 +0x2e7
main.startDaemonCmd(0xc4200b2fc0, 0xc420074550, 0x0, 0x5)
	/home/luke/go/src/github.com/NebulousLabs/Sia/cmd/siad/daemon.go:236 +0x162
github.com/spf13/cobra.(*Command).execute(0xc4200b2fc0, 0xc420078010, 0x5, 0x5, 0xc4200b2fc0, 0xc420078010)
	/home/luke/go/src/github.com/spf13/cobra/command.go:750 +0x2c1
github.com/spf13/cobra.(*Command).ExecuteC(0xc4200b2fc0, 0x16e1b17, 0x3b, 0xc420097ae0)
	/home/luke/go/src/github.com/spf13/cobra/command.go:831 +0x30e
github.com/spf13/cobra.(*Command).Execute(0xc4200b2fc0, 0x1b0a200, 0x16ca346)
	/home/luke/go/src/github.com/spf13/cobra/command.go:784 +0x2b
main.main()
	/home/luke/go/src/github.com/NebulousLabs/Sia/cmd/siad/main.go:174 +0x790

**Comment by tbenz9** [comment] 2018-05-25 17:03
This is a known problem, try restarting Sia a few times and if it persists you'll need to remove your transactionpool.db file.

Duplicate of #2867

**Closed by tbenz9** 2018-05-25 17:03 UTC
