### ISSUE TITLE
Sia-UI error dump

### ISSUE THREAD

**Issue by xuyenvuong** [NebulousLabs/Sia#2059] opened 2017-07-01 20:42 UTC
On my Mac, latest version.

: scanned to height 103963...
Wallet: scanned to height 104481...
Wallet: scanned to height 105094...
Wallet: scanned to height 105763...
Wallet: scanned to height 106440...
Wallet: scanned to height 107047...
Wallet: scanned to height 107590...
Wallet: scanned to height 108102...
Wallet: scanned to height 108718...
Wallet: scanned to height 109098...
Wallet: scanned to height 109496...
Wallet: scanned to height 109879...
Wallet: scanned to height 110269...
Wallet: scanned to height 110664...
Wallet: scanned to height 111020...
Wallet: scanned to height 111401...
Wallet: scanned to height 111765...
Wallet: scanned to height 112145...
Done!
goroutine 1 [running]:
runtime/debug.Stack(0x1043857, 0x0, 0x4220655f8)
/usr/local/go/src/runtime/debug/stack.go:24 +0x79
runtime/debug.PrintStack()
/usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/NebulousLabs/Sia/build.Critical(0x422065948, 0x1, 0x1)
/home/jrh/go/src/github.com/NebulousLabs/Sia/build/critical.go:16 +0xa7
main.startDaemon(0x0, 0x0, 0x7fff5fbffd50, 0xe, 0x7fff5fbffd7c, 0x5, 0x7fff5fbffd6b, 0x5, 0x0, 0x7fff5fbffdd1, ...)
/home/jrh/go/src/github.com/NebulousLabs/Sia/siad/daemon.go:295 +0xaa9
main.startDaemonCmd(0x421c33200, 0x421bc33b0, 0x0, 0x5)
/home/jrh/go/src/github.com/NebulousLabs/Sia/siad/daemon.go:309 +0x6d
github.com/spf13/cobra.(*Command).execute(0x421c33200, 0x421bb80d0, 0x5, 0x5, 0x421c33200, 0x421bb80d0)
/home/jrh/go/src/github.com/spf13/cobra/command.go:651 +0x23a
github.com/spf13/cobra.(*Command).ExecuteC(0x421c33200, 0x16c7c0f, 0x3b, 0x421d028c0)
/home/jrh/go/src/github.com/spf13/cobra/command.go:726 +0x339
github.com/spf13/cobra.(*Command).Execute(0x421c33200, 0x1aa6520, 0x16b10c0)
/home/jrh/go/src/github.com/spf13/cobra/command.go:685 +0x2b
main.main()
/home/jrh/go/src/github.com/NebulousLabs/Sia/siad/main.go:174 +0x79d
Critical error: accept tcp 127.0.0.1:9980: accept: too many open files in system
Please submit a bug report here: https://github.com/NebulousLabs/Sia/issues
Closing renter...
Closing host...

**Comment by lukechampine** [comment] 2017-07-01 22:12
duplicate of #1840

**Closed by lukechampine** 2017-07-01 22:12 UTC
