### ISSUE TITLE
Siad has exited unexpectedly whilst I was trying to open my wallet

### ISSUE THREAD

**Issue by Odoardo** [NebulousLabs/Sia#2087] opened 2017-07-06 00:20 UTC
On my iMac I had the Sia UI open and was simply trying to open my wallet. I pasted in my seed which I had stored elsewhere and some time later I got an error message with an error log. I'm not a techie and would really appreciate it if someone could take a look at the error log below and let me know what the problem is: 

Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 0.612943728 seconds

Wallet: scanned to height 363...
Wallet: scanned to height 758...
Wallet: scanned to height 1133...
Wallet: scanned to height 1502...
Wallet: scanned to height 2048...
Wallet: scanned to height 2744...
Wallet: scanned to height 3417...
Wallet: scanned to height 3920...
Wallet: scanned to height 4186...
Wallet: scanned to height 4513...
Wallet: scanned to height 4777...
Wallet: scanned to height 5067...
Wallet: scanned to height 5330...
Wallet: scanned to height 5585...
Wallet: scanned to height 5914...
Wallet: scanned to height 6229...
Wallet: scanned to height 6543...
Wallet: scanned to height 6845...
Wallet: scanned to height 7074...
Wallet: scanned to height 7351...
Wallet: scanned to height 7631...
Wallet: scanned to height 7911...
Wallet: scanned to height 8192...
Wallet: scanned to height 8485...
Wallet: scanned to height 8785...
Wallet: scanned to height 9045...
Wallet: scanned to height 9285...
Wallet: scanned to height 9523...
Wallet: scanned to height 9766...
Wallet: scanned to height 10092...
Wallet: scanned to height 10390...
Wallet: scanned to height 10695...
Wallet: scanned to height 11020...
Wallet: scanned to height 11347...
Wallet: scanned to height 11661...
Wallet: scanned to height 11986...
Wallet: scanned to height 12343...
Wallet: scanned to height 12727...
Wallet: scanned to height 13024...
Wallet: scanned to height 13385...
Wallet: scanned to height 13720...
Wallet: scanned to height 14022...
Wallet: scanned to height 14447...
Wallet: scanned to height 14873...
Wallet: scanned to height 15210...
Wallet: scanned to height 15517...
Wallet: scanned to height 15902...
Wallet: scanned to height 16249...
Wallet: scanned to height 16571...
Wallet: scanned to height 17030...
Wallet: scanned to height 17654...
Wallet: scanned to height 18088...
Wallet: scanned to height 18453...
Wallet: scanned to height 18910...
Wallet: scanned to height 19566...
Wallet: scanned to height 20047...
Wallet: scanned to height 20353...
Wallet: scanned to height 20740...
Wallet: scanned to height 21133...
Wallet: scanned to height 21640...
Wallet: scanned to height 22031...
Wallet: scanned to height 22395...
Wallet: scanned to height 22733...
Wallet: scanned to height 22959...
Wallet: scanned to height 23345...
Wallet: scanned to height 23816...
Wallet: scanned to height 24298...
Wallet: scanned to height 24717...
Wallet: scanned to height 25096...
Wallet: scanned to height 25575...
Wallet: scanned to height 26069...
Wallet: scanned to height 26472...
Wallet: scanned to height 26881...
Wallet: scanned to height 27322...
Wallet: scanned to height 27783...
Wallet: scanned to height 28252...
Wallet: scanned to height 28688...
Wallet: scanned to height 29072...
Wallet: scanned to height 29331...
Wallet: scanned to height 29788...
Wallet: scanned to height 30358...
Wallet: scanned to height 30767...
Wallet: scanned to height 31267...
Wallet: scanned to height 31617...
Wallet: scanned to height 32097...
Wallet: scanned to height 32558...
Wallet: scanned to height 32867...
Wallet: scanned to height 33182...
Wallet: scanned to height 33499...
Wallet: scanned to height 33784...
Wallet: scanned to height 34097...
Wallet: scanned to height 34288...
Wallet: scanned to height 34471...
Wallet: scanned to height 34628...goroutine 1 [running]:
runtime/debug.Stack(0x1043857, 0x0, 0xc420b475f8)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x79
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/NebulousLabs/Sia/build.Critical(0xc420b47948, 0x1, 0x1)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/build/critical.go:16 +0xa7
main.startDaemon(0x0, 0x0, 0x7fff5fbffcfc, 0xe, 0x7fff5fbffd28, 0x5, 0x7fff5fbffd17, 0x5, 0x0, 0x7fff5fbffd82, ...)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/siad/daemon.go:295 +0xaa9
main.startDaemonCmd(0xc420083200, 0xc420019310, 0x0, 0x5)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/siad/daemon.go:309 +0x6d
github.com/spf13/cobra.(*Command).execute(0xc420083200, 0xc42000e0d0, 0x5, 0x5, 0xc420083200, 0xc42000e0d0)
	/home/jrh/go/src/github.com/spf13/cobra/command.go:651 +0x23a
github.com/spf13/cobra.(*Command).ExecuteC(0xc420083200, 0x16c7c0f, 0x3b, 0xc420150a00)
	/home/jrh/go/src/github.com/spf13/cobra/command.go:726 +0x339
github.com/spf13/cobra.(*Command).Execute(0xc420083200, 0x1aa6520, 0x16b10c0)
	/home/jrh/go/src/github.com/spf13/cobra/command.go:685 +0x2b
main.main()
	/home/jrh/go/src/github.com/NebulousLabs/Sia/siad/main.go:174 +0x79d
Critical error: accept tcp 127.0.0.1:9980: accept: too many open files in system
Please submit a bug report here: https://github.com/NebulousLabs/Sia/issues
Closing renter...

**Comment by lukechampine** [comment] 2017-07-28 23:00
duplicate of #1840

**Closed by lukechampine** 2017-07-28 23:00 UTC
