### ISSUE TITLE
SIA keeps Crashing ON MAC 

### ISSUE THREAD

**Issue by taiwil** [NebulousLabs/Sia#2891] opened 2018-03-19 14:14 UTC
My SIA keeps crashing on MAC...The people in Discord keep giving info on this issue and how to fix it with LINUX.  What do i do with a MAC ??

# BUG REPORT

**Stack Trace or error message**
Sia Daemon v1.3.2
Git Revision 72938f5
Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 20.690603834 seconds

Wallet: scanned to height 146296...
Wallet: scanned to height 146296...
Wallet: scanned to height 146296...
Wallet: scanned to height 146296...
Wallet: scanned to height 146296...
Wallet: scanned to height 146296...
Wallet: scanned to height 146296...
Wallet: scanned to height 146296...
Wallet: scanned to height 146296...
Wallet: scanned to height 146296...
Wallet: scanned to height 146296...
Done!
goroutine 1 [running]:
runtime/debug.Stack(0x1045ec7, 0x0, 0xc420273948)
	/usr/local/go/src/runtime/debug/stack.go:24 +0xa7
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/NebulousLabs/Sia/build.Critical(0xc420273ac8, 0x1, 0x1)
	/home/luke/go/src/github.com/NebulousLabs/Sia/build/critical.go:16 +0x93
main.startDaemon(0x0, 0x0, 0x7fff5fbffd53, 0xe, 0x7fff5fbffd7f, 0x5, 0x7fff5fbffd6e, 0x5, 0x0, 0x7fff5fbffdd3, ...)
	/home/luke/go/src/github.com/NebulousLabs/Sia/cmd/siad/daemon.go:212 +0x588
main.startDaemonCmd(0xc4200acfc0, 0xc42007e550, 0x0, 0x5)
	/home/luke/go/src/github.com/NebulousLabs/Sia/cmd/siad/daemon.go:236 +0x162
github.com/spf13/cobra.(*Command).execute(0xc4200acfc0, 0xc42000e0d0, 0x5, 0x5, 0xc4200acfc0, 0xc42000e0d0)
	/home/luke/go/src/github.com/spf13/cobra/command.go:750 +0x2c1
github.com/spf13/cobra.(*Command).ExecuteC(0xc4200acfc0, 0x16e1b17, 0x3b, 0xc420099a40)
	/home/luke/go/src/github.com/spf13/cobra/command.go:831 +0x30e
github.com/spf13/cobra.(*Command).Execute(0xc4200acfc0, 0x1b0a200, 0x16ca346)
	/home/luke/go/src/github.com/spf13/cobra/command.go:784 +0x2b
main.main()
	/home/luke/go/src/github.com/NebulousLabs/Sia/cmd/siad/main.go:174 +0x790
Critical error: accept tcp 127.0.0.1:9980: accept: too many open files in system
Please submit a bug report here: https://github.com/NebulousLabs/Sia/issues
Shutdown complete.
**Expected Behavior**

**How to reproduce it (as minimally and precisely as possible)**
It happens randomly.  I don't know when or what causes it.  
**Environment**
* Sia version:1.3.2
* OS: 10.11.6

**Comment by tbenz9** [comment] 2018-03-19 17:08
Duplicate of #2406 

I believe the bug actually lies in Sia-UI.

On a MAC follow these instructions to increase your open files limit. 
https://superuser.com/questions/433746/is-there-a-fix-for-the-too-many-open-files-in-system-error-on-os-x-10-7-1

**Closed by tbenz9** 2018-03-19 17:08 UTC

**Comment by taiwil** [comment] 2018-03-19 22:50
I tried to use the commands in the SIA terminal and i get errors.  Should i run the commands in the link you gave me through my computer terminal ?
