### ISSUE TITLE
UI Bug Windows 10 Pro 64-bit

### ISSUE THREAD

**Issue by Leecifer77** [NebulousLabs/Sia#2801] opened 2018-02-27 23:54 UTC
A critical error loading Sia has occured: Siad unexpectedly exited. Error log: Sia Daemon v1.3.1
Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
goroutine 1 [running]:
runtime/debug.Stack(0x446dde, 0x0, 0xc04207ff38)
	/usr/local/go/src/runtime/debug/stack.go:24 +0xae
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x29
github.com/NebulousLabs/Sia/build.Critical(0xc042080240, 0x2, 0x2)
	/home/luke/go/src/github.com/NebulousLabs/Sia/build/critical.go:16 +0x9a
github.com/NebulousLabs/Sia/persist.(*Logger).Critical(0xc0421b95c0, 0xc042080240, 0x2, 0x2)
	/home/luke/go/src/github.com/NebulousLabs/Sia/persist/log.go:37 +0xd3
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).computeConsensusChange(0xc0421d6000, 0xc0421b2540, 0x0, 0x0, 0x0, 0xc0423c6960, 0x1, 0x1, 0x0, 0x0, ...)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/subscribe.go:56 +0x15f4
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).managedInitializeSubscribe.func2(0xc0421b2540, 0xaf1700, 0xc0421b2540)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/subscribe.go:180 +0x1a1
github.com/NebulousLabs/bolt.(*DB).View(0xc0420832c0, 0xc042081070, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/bolt/db.go:634 +0xa1
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).managedInitializeSubscribe(0xc0421d6000, 0xde3ec0, 0xc0420ccc60, 0x829999ad5c2ddaf7, 0x8c9550b5d64ab54e, 0xd1d2966cc291c4dd, 0xfb34277addc5f96a, 0xc042062540, 0x47272d, 0x942f115)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/subscribe.go:173 +0x26d
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).ConsensusSetSubscribe(0xc0421d6000, 0xde3ec0, 0xc0420ccc60, 0x829999ad5c2ddaf7, 0x8c9550b5d64ab54e, 0xd1d2966cc291c4dd, 0xfb34277addc5f96a, 0xc042062540, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/subscribe.go:223 +0x108
github.com/NebulousLabs/Sia/modules/transactionpool.(*TransactionPool).initPersist(0xc0420ccc60, 0xc0420ccc60, 0xc0421b0810)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/transactionpool/persist.go:189 +0x984
github.com/NebulousLabs/Sia/modules/transactionpool.New(0xdeed40, 0xc0421d6000, 0xdee820, 0xc0420cc840, 0xc04200b700, 0x39, 0x0, 0x0, 0x1001000420815a0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/transactionpool/transactionpool.go:101 +0x257
main.(*Server).loadModules(0xc0420a84b0, 0xaf1aa0, 0xc0420a84b0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/cmd/siad/server.go:495 +0x187c
main.startDaemon(0x0, 0x0, 0xc04200c2eb, 0xe, 0xc04200e11b, 0x5, 0xc04200c32c, 0x5, 0x0, 0xc04200e15a, ...)
	/home/luke/go/src/github.com/NebulousLabs/Sia/cmd/siad/daemon.go:164 +0x1ae
main.startDaemonCmd(0xc0420d6d80, 0xc0420ac410, 0x0, 0x5)
	/home/luke/go/src/github.com/NebulousLabs/Sia/cmd/siad/daemon.go:209 +0x169
github.com/spf13/cobra.(*Command).execute(0xc0420d6d80, 0xc042086010, 0x5, 0x7, 0xc0420d6d80, 0xc042086010)
	/home/luke/go/src/github.com/spf13/cobra/command.go:750 +0x2c8
github.com/spf13/cobra.(*Command).ExecuteC(0xc0420d6d80, 0xae2c79, 0x3b, 0xc042067b80)
	/home/luke/go/src/github.com/spf13/cobra/command.go:831 +0x315
github.com/spf13/cobra.(*Command).Execute(0xc0420d6d80, 0xefcd80, 0xacaf03)
	/home/luke/go/src/github.com/spf13/cobra/command.go:784 +0x32
main.main()
	/home/luke/go/src/github.com/NebulousLabs/Sia/cmd/siad/main.go:174 +0x797
Critical error: getBlockMap failed in computeConsensusChange: requested item does not exist
Please submit a bug report here: https://github.com/NebulousLabs/Sia/issues
requested item does not exist

**Comment by tbenz9** [comment] 2018-03-06 19:02
This is a duplicate of #2542.  This issue is usually caused by corruption in the internal Sia database.  There are changes in Sia version 1.3.2 (The new  writeaheadlog and bbolt implementation) which should hopefully prevent this bug from happening in the future.

As a workaround I recommend resyncing the consensus.db file. You can find instructions to do that here: https://gist.github.com/tbenz9/8066d74853ab28c23bd7bc1d3c7cdeda

**Closed by tbenz9** 2018-03-06 19:02 UTC

**Comment by Leecifer77** [comment] 2018-03-08 16:06
Thank you very much, sorry for re-posting the same issue. Cheers.
