### ISSUE TITLE
new contractor ndf 

### ISSUE THREAD

**Issue by marcinja** [NebulousLabs/Sia#2156] opened 2017-07-19 18:28 UTC
From `make-vlong` output:
```
--- FAIL: TestContractorHostRemoval (39.36s)
	renter_test.go:1733: not the right number of new contracts: 1
```

**Comment by tbenz9** [comment] 2017-10-18 22:04
Duplicate of #2359 

Recommendation to Devs: Close

**Closed** 2017-10-18 22:15 UTC
