### ISSUE TITLE
Got error:"transaction spends a nonexisting siacoin output" when submitted valid share(used 1.3.1)

### ISSUE THREAD

**Issue by LgxAtGitHub** [NebulousLabs/Sia#2583] opened 2017-12-26 10:54 UTC
Bug Report
==========
when submitted valid share to siad, got error : **transaction spends a nonexisting siacoin output**

I am miner, I updated my siad from 1.3.0 to 1.3.1 several day ago.

But after upgraded, I did not got any block.
When submitted valid share, I got "transaction spends a nonexisting siacoin output"!!!

**Environment**
* Sia version: 1.3.1
* OS:  ubuntu 16

**Comment by tbenz9** [comment] 2017-12-28 21:35
Duplicate of #2470

**Closed by tbenz9** 2017-12-28 21:35 UTC
