### ISSUE TITLE
ESOCKETTIMEDOUT during resizing (or adding/removing) storage locations

### ISSUE THREAD

**Issue by JamesM424** [NebulousLabs/Sia#1854] opened 2017-05-30 03:37 UTC
Sia-UI version 1.2.2
OS: Win7 x64

I noticed on two [out of two] test systems I have configured as hosts that are upgraded to Sia-UI 1.2.2 that shortly after changing, or adding storage locations in the Sia-UI, they would crash shortly thereafter.  Sia-UI would crash with an error box I don't have a copy of.  siad.exe would not be able to be ended in the task manager or via a KILL command.  But, surprisingly, would gracefully disappear and give it's memory back 15 minutes or so later.

Log messages seem to point to 'contractmanager' where it attempts to over-write contractManager.WAL file with temp file as it receives 'access is denied error'.  This might have been caused by a renter's data usage at the time as one of the hosts likes to write data...allot.  Or not, you would know better.

Proper coding would be to do a try/catch/(finally) (or WTF Go's syntax is) on file handling and if on error proceed with better handled error than a fatal crash.   It would be safer to store it, ask user to restart UI and process then.  Or try again, and again for a count++.  Or revert back to old settings.  Anything is safer than a fatal error 15 minutes after changes are saved.

But!  I do appreciate siad's graceful quiet exit shortly thereafter.  But it not ending on a KILL command was a bit unexpected.

Logs attached for your reference.
[siad-output.txt](https://github.com/NebulousLabs/Sia/files/1037144/siad-output.txt)

June 3 - Screenshot of error attached:
![sia_output](https://cloud.githubusercontent.com/assets/28582587/26754243/d92eb266-4844-11e7-97f6-9df7f5f8340a.jpg)

**Comment by tbenz9** [comment] 2017-10-12 21:56
This will hopefully be fixed in the upcoming new WAL.

Duplicate of #2189

**Closed** 2017-10-12 22:48 UTC
