### ISSUE TITLE
siad crash, delete tpool still crash

### ISSUE THREAD

**Issue by tlightsky** [NebulousLabs/Sia#2331] opened 2017-09-18 09:48 UTC
version: 1.3.0
platform: windows 10

```go
D:\s\sia-win>siad
Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
panic: invalid page type: 0: 0

goroutine 62 [running]:
github.com/NebulousLabs/bolt.(*Cursor).search(0xc04382e3e8, 0xc0450b00a0, 0x20, 0x20, 0xfe840)
        E:/source/go/src/github.com/NebulousLabs/bolt/cursor.go:256 +0x40c
github.com/NebulousLabs/bolt.(*Cursor).searchNode(0xc04382e3e8, 0xc0450b00a0, 0x20, 0x20, 0xc04543c9a0)
        E:/source/go/src/github.com/NebulousLabs/bolt/cursor.go:291 +0x12b
github.com/NebulousLabs/bolt.(*Cursor).search(0xc04382e3e8, 0xc0450b00a0, 0x20, 0x20, 0x11909e)
        E:/source/go/src/github.com/NebulousLabs/bolt/cursor.go:268 +0x17d
github.com/NebulousLabs/bolt.(*Cursor).searchNode(0xc04382e3e8, 0xc0450b00a0, 0x20, 0x20, 0xc04212d570)
        E:/source/go/src/github.com/NebulousLabs/bolt/cursor.go:291 +0x12b
github.com/NebulousLabs/bolt.(*Cursor).search(0xc04382e3e8, 0xc0450b00a0, 0x20, 0x20, 0x878c1)
        E:/source/go/src/github.com/NebulousLabs/bolt/cursor.go:268 +0x17d
github.com/NebulousLabs/bolt.(*Cursor).searchNode(0xc04382e3e8, 0xc0450b00a0, 0x20, 0x20, 0xc0434e0e00)
        E:/source/go/src/github.com/NebulousLabs/bolt/cursor.go:291 +0x12b
github.com/NebulousLabs/bolt.(*Cursor).search(0xc04382e3e8, 0xc0450b00a0, 0x20, 0x20, 0xa0233)
        E:/source/go/src/github.com/NebulousLabs/bolt/cursor.go:268 +0x17d
github.com/NebulousLabs/bolt.(*Cursor).seek(0xc04382e3e8, 0xc0450b00a0, 0x20, 0x20, 0x0, 0x0, 0xc044cf59c0, 0x99, 0x0, 0x0, ...)
        E:/source/go/src/github.com/NebulousLabs/bolt/cursor.go:159 +0xb8
github.com/NebulousLabs/bolt.(*Bucket).Put(0xc043d02680, 0xc0450b00a0, 0x20, 0x20, 0xc043086250, 0x34, 0x40, 0x0, 0x0)
        E:/source/go/src/github.com/NebulousLabs/bolt/bucket.go:300 +0x14d
github.com/NebulousLabs/Sia/modules/consensus.addSiacoinOutput(0xc04275a620, 0x35d06845efca15d6, 0x7624230ef6566e34, 0xfe7359cb3578b6f9, 0x1b1f53f53b7c8b07, 0x0, 0xc0438e85a0, 0x2, 0x6, 0xef93d3922a96361e, ...)
        E:/source/go/src/github.com/NebulousLabs/Sia/modules/consensus/consensusdb.go:312 +0x14b
github.com/NebulousLabs/Sia/modules/consensus.commitSiacoinOutputDiff(0xc04275a620, 0xd06845efca15d601, 0x24230ef6566e3435, 0x7359cb3578b6f976, 0x1f53f53b7c8b07fe, 0x1b, 0x0, 0xc0438e85a0, 0x2, 0x6, ...)
        E:/source/go/src/github.com/NebulousLabs/Sia/modules/consensus/diffs.go:58 +0x8a
github.com/NebulousLabs/Sia/modules/consensus.applySiacoinOutputs(0xc04275a620, 0xc0424b46e0, 0xc046f541e0, 0x1, 0x1, 0xc0424a0000, 0x32, 0x32, 0x0, 0x0, ...)
        E:/source/go/src/github.com/NebulousLabs/Sia/modules/consensus/applytransaction.go:45 +0x254
github.com/NebulousLabs/Sia/modules/consensus.applyTransaction(0xc04275a620, 0xc0424b46e0, 0xc046f541e0, 0x1, 0x1, 0xc0424a0000, 0x32, 0x32, 0x0, 0x0, ...)
        E:/source/go/src/github.com/NebulousLabs/Sia/modules/consensus/applytransaction.go:208 +0xc0
github.com/NebulousLabs/Sia/modules/consensus.generateAndApplyDiff(0xc04275a620, 0xc0424b46e0, 0xc04426e4b0, 0x2)
        E:/source/go/src/github.com/NebulousLabs/Sia/modules/consensus/diffs.go:224 +0x17e
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).applyUntilBlock(0xc042119b80, 0xc04275a620, 0xc0424b46e0, 0x0, 0x0, 0x0, 0x6a01000000000000, 0xbf706298cfc46fda)
        E:/source/go/src/github.com/NebulousLabs/Sia/modules/consensus/fork.go:84 +0x244
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).forkBlockchain(0xc042119b80, 0xc04275a620, 0xc0424b46e0, 0x1c00000000000000, 0x45f4289d6672d624, 0x1d3a0573b41eded8, 0xb064aaa14b329599, 0x1a6c012c0293a344, 0x59b982ab, 0xc04305af80, ...)
        E:/source/go/src/github.com/NebulousLabs/Sia/modules/consensus/fork.go:111 +0xb3
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).addBlockToTree(0xc042119b80, 0xc04275a620, 0x1c00000000000000, 0x45f4289d6672d624, 0x1d3a0573b41eded8, 0xb064aaa14b329599, 0x1a6c012c0293a344, 0x59b982ab, 0xc04305af80, 0x1, ...)
        E:/source/go/src/github.com/NebulousLabs/Sia/modules/consensus/accept.go:164 +0x114
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).managedAcceptBlocks.func1(0xc04275a620, 0xb0ee90, 0xc04275a620)
        E:/source/go/src/github.com/NebulousLabs/Sia/modules/consensus/accept.go:262 +0x23a
github.com/NebulousLabs/bolt.(*DB).Update(0xc0420e6780, 0xc0460352e8, 0x0, 0x0)
        E:/source/go/src/github.com/NebulousLabs/bolt/db.go:603 +0xa6
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).managedAcceptBlocks(0xc042119b80, 0xc04202b000, 0xa, 0xa, 0x0, 0x0, 0x0)
        E:/source/go/src/github.com/NebulousLabs/Sia/modules/consensus/accept.go:283 +0x520
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).managedReceiveBlocks(0xc042119b80, 0xde8200, 0xc04225a0a0, 0x0, 0x0)
        E:/source/go/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:225 +0x5be
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).(github.com/NebulousLabs/Sia/modules/consensus.managedReceiveBlocks)-fm(0xde8200, 0xc04225a0a0, 0x0, 0x0)
        E:/source/go/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:445 +0x45
github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).managedRPC(0xc04205ec60, 0xc042188360, 0x13, 0xae1454, 0xa, 0xc04237a040, 0x0, 0x0)
        E:/source/go/src/github.com/NebulousLabs/Sia/modules/gateway/rpc.go:66 +0x339
github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).RPC(0xc04205ec60, 0xc042188360, 0x13, 0xae1454, 0xa, 0xc04237a040, 0x0, 0x0)
        E:/source/go/src/github.com/NebulousLabs/Sia/modules/gateway/rpc.go:76 +0xd8
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).threadedInitialBlockchainDownload.func1(0xc042119b80, 0xc04382fef0, 0xc04382feb0, 0xc04382feb8, 0x0, 0x0)
        E:/source/go/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:580 +0x133
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).threadedInitialBlockchainDownload(0xc042119b80, 0x0, 0x0)
        E:/source/go/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:601 +0x30e
github.com/NebulousLabs/Sia/modules/consensus.New.func1(0x1, 0xc042242b70, 0xc042119b80, 0xde8480, 0xc04205ec60)
        E:/source/go/src/github.com/NebulousLabs/Sia/modules/consensus/consensusset.go:151 +0x404
created by github.com/NebulousLabs/Sia/modules/consensus.New
        E:/source/go/src/github.com/NebulousLabs/Sia/modules/consensus/consensusset.go:182 +0x641
```

**Comment by tlightsky** [comment] 2017-09-20 03:32
after delete all consensus and tpool, resync,
crash after this log(53.1% progress):

```go
D:\s\sia-win>siad
Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
Closing consensus...
Closing gateway...
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/NebulousLabs/bolt.(*Cursor).nsearch.func2(0x128a, 0x0)
        E:/source/go/src/github.com/NebulousLabs/bolt/cursor.go:334 +0xb1
sort.Search(0x2a60, 0xc042066d80, 0xc042066db8)
        E:/Go/src/sort/search.go:66 +0x6a
github.com/NebulousLabs/bolt.(*Cursor).nsearch(0xc042067308, 0xc042aea440, 0x20, 0x20)
        E:/source/go/src/github.com/NebulousLabs/bolt/cursor.go:335 +0x109
github.com/NebulousLabs/bolt.(*Cursor).search(0xc042067308, 0xc042aea440, 0x20, 0x20, 0x1c99)
        E:/source/go/src/github.com/NebulousLabs/bolt/cursor.go:263 +0x202
github.com/NebulousLabs/bolt.(*Cursor).searchNode(0xc042067308, 0xc042aea440, 0x20, 0x20, 0xc04211a000)
        E:/source/go/src/github.com/NebulousLabs/bolt/cursor.go:291 +0x12b
github.com/NebulousLabs/bolt.(*Cursor).search(0xc042067308, 0xc042aea440, 0x20, 0x20, 0x1635)
        E:/source/go/src/github.com/NebulousLabs/bolt/cursor.go:268 +0x17d
github.com/NebulousLabs/bolt.(*Cursor).searchNode(0xc042067308, 0xc042aea440, 0x20, 0x20, 0xc0423fe2a0)
        E:/source/go/src/github.com/NebulousLabs/bolt/cursor.go:291 +0x12b
github.com/NebulousLabs/bolt.(*Cursor).search(0xc042067308, 0xc042aea440, 0x20, 0x20, 0x1e5e)
        E:/source/go/src/github.com/NebulousLabs/bolt/cursor.go:268 +0x17d
github.com/NebulousLabs/bolt.(*Cursor).searchNode(0xc042067308, 0xc042aea440, 0x20, 0x20, 0xc0421273b0)
        E:/source/go/src/github.com/NebulousLabs/bolt/cursor.go:291 +0x12b
github.com/NebulousLabs/bolt.(*Cursor).search(0xc042067308, 0xc042aea440, 0x20, 0x20, 0x6ba8)
        E:/source/go/src/github.com/NebulousLabs/bolt/cursor.go:268 +0x17d
github.com/NebulousLabs/bolt.(*Cursor).seek(0xc042067308, 0xc042aea440, 0x20, 0x20, 0x0, 0x0, 0xc04247e000, 0x0, 0xfa1ff0, 0x0, ...)
        E:/source/go/src/github.com/NebulousLabs/bolt/cursor.go:159 +0xb8
github.com/NebulousLabs/bolt.(*Bucket).Put(0xc0421ce5c0, 0xc042aea440, 0x20, 0x20, 0xf0abf0, 0x0, 0x0, 0xc042a02a80, 0xde6460)
        E:/source/go/src/github.com/NebulousLabs/bolt/bucket.go:300 +0x14d
github.com/NebulousLabs/Sia/modules/transactionpool.(*TransactionPool).putTransaction(0xc042059080, 0xc0420dc9a0, 0x8bd3b713ccded837, 0xd6b62d7df9cda6dd, 0xd40191bc0133d136, 0x1fc0ef0d94d5f6c8, 0x0, 0x0)
        E:/source/go/src/github.com/NebulousLabs/Sia/modules/transactionpool/database.go:123 +0xf3
github.com/NebulousLabs/Sia/modules/transactionpool.(*TransactionPool).ProcessConsensusChange(0xc042059080, 0x189680968bbbc0e9, 0xdc905da706f2a3a5, 0xff492a07d8fdb0b, 0x877ec8f62eb97013, 0x0, 0x0, 0x0, 0xc0421b8c00, 0x1, ...)
        E:/source/go/src/github.com/NebulousLabs/Sia/modules/transactionpool/update.go:200 +0x49e
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).managedInitializeSubscribe.func2(0xc0420dcb60, 0xb0ee98, 0xc0420dcb60)
        E:/source/go/src/github.com/NebulousLabs/Sia/modules/consensus/subscribe.go:176 +0x160
github.com/NebulousLabs/bolt.(*DB).View(0xc0420e0780, 0xc042069248, 0x0, 0x0)
        E:/source/go/src/github.com/NebulousLabs/bolt/db.go:634 +0xa6
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).managedInitializeSubscribe(0xc042113b80, 0xdddde0, 0xc042059080, 0x1edf91ff7530cf6f, 0xb434e46500727608, 0xc3b2c840f78eea4, 0x54bdda8174387303, 0x8d98fe, 0x9fab115)
        E:/source/go/src/github.com/NebulousLabs/Sia/modules/consensus/subscribe.go:180 +0x256
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).ConsensusSetSubscribe(0xc042113b80, 0xdddde0, 0xc042059080, 0x1edf91ff7530cf6f, 0xb434e46500727608, 0xc3b2c840f78eea4, 0x54bdda8174387303, 0x0, 0x0)
        E:/source/go/src/github.com/NebulousLabs/Sia/modules/consensus/subscribe.go:203 +0xf5
github.com/NebulousLabs/Sia/modules/transactionpool.(*TransactionPool).initPersist(0xc042059080, 0xc042059080, 0xc042182c90)
        E:/source/go/src/github.com/NebulousLabs/Sia/modules/transactionpool/persist.go:183 +0x94b
github.com/NebulousLabs/Sia/modules/transactionpool.New(0xde90a0, 0xc042113b80, 0xde8480, 0xc042058c60, 0xae77cd, 0xf, 0x0, 0x0, 0x0)
        E:/source/go/src/github.com/NebulousLabs/Sia/modules/transactionpool/transactionpool.go:101 +0x27d
main.startDaemon(0x0, 0x0, 0xae6a0e, 0xe, 0xad5c52, 0x5, 0xad5c57, 0x5, 0x0, 0xad8635, ...)
        E:/source/go/src/github.com/NebulousLabs/Sia/siad/daemon.go:202 +0x169a
main.startDaemonCmd(0xc04205f200, 0xf0abf0, 0x0, 0x0)
        E:/source/go/src/github.com/NebulousLabs/Sia/siad/daemon.go:335 +0x169
github.com/spf13/cobra.(*Command).execute(0xc04205f200, 0xc0420081f0, 0x0, 0x0, 0xc04205f200, 0xc0420081f0)
        E:/source/go/src/github.com/spf13/cobra/command.go:653 +0x2a0
github.com/spf13/cobra.(*Command).ExecuteC(0xc04205f200, 0xb03bca, 0x3b, 0xc042122aa0)
        E:/source/go/src/github.com/spf13/cobra/command.go:728 +0x340
github.com/spf13/cobra.(*Command).Execute(0xc04205f200, 0xeee360, 0xaebd2e)
        E:/source/go/src/github.com/spf13/cobra/command.go:687 +0x32
main.main()
        E:/source/go/src/github.com/NebulousLabs/Sia/siad/main.go:174 +0x7b1
```

**Comment by tlightsky** [comment] 2017-09-21 02:55
start from a new folder with copied consensus, 
still crash, it seems i can't recover it

```go
D:\s\sia-new>siad
Sia Daemon v1.3.1
Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
panic: invalid page type: 0: 0
```

**Comment by jaaneh** [comment] 2017-09-21 05:31
Getting this error as well. Have no access to my Sia-UI at all.

**Comment by tlightsky** [comment] 2017-09-21 10:39
@jaaneh try to start all over in a new folder(including consensus)

**Comment by tlightsky** [comment] 2017-09-22 08:46
on resync,
not crash yet

```go
D:\s\sia-new>siad
Sia Daemon v1.3.1
Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 1.6811707999999999 seconds
goroutine 493089 [running]:
runtime/debug.Stack(0x446dee, 0xc042b1fe20, 0xc042b1fde8)
        /usr/local/go/src/runtime/debug/stack.go:24 +0xae
runtime/debug.PrintStack()
        /usr/local/go/src/runtime/debug/stack.go:16 +0x29
github.com/NebulousLabs/Sia/build.Severe(0xc042b1ffa0, 0x2, 0x2)
        /home/luke/go/src/github.com/NebulousLabs/Sia/build/critical.go:32 +0x8c
github.com/NebulousLabs/Sia/persist.(*Logger).Severe(0xc04225dc00, 0xc042b1ffa0, 0x2, 0x2)
        /home/luke/go/src/github.com/NebulousLabs/Sia/persist/log.go:71 +0xd3
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).syncResources.func1(0xc043d3e3c0, 0xc042208548)
        /home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:50 +0x402
created by github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).syncResources
        /home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:25 +0x9a
Severe error: ERROR: unable to atomically copy the contract manager settings: rename host\contractmanager\contractmanager.json_temp host\contractmanager\contractmanager.json: Access is denied.
goroutine 880155 [running]:
runtime/debug.Stack(0x446dee, 0xc0421b7e20, 0xc0421b7de8)
        /usr/local/go/src/runtime/debug/stack.go:24 +0xae
runtime/debug.PrintStack()
        /usr/local/go/src/runtime/debug/stack.go:16 +0x29
github.com/NebulousLabs/Sia/build.Severe(0xc0421b7fa0, 0x2, 0x2)
        /home/luke/go/src/github.com/NebulousLabs/Sia/build/critical.go:32 +0x8c
github.com/NebulousLabs/Sia/persist.(*Logger).Severe(0xc04225dc00, 0xc0421b7fa0, 0x2, 0x2)
        /home/luke/go/src/github.com/NebulousLabs/Sia/persist/log.go:71 +0xd3
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).syncResources.func1(0xc046160000, 0xc042208548)
        /home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:50 +0x402
created by github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).syncResources
        /home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:25 +0x9a
Severe error: ERROR: unable to atomically copy the contract manager settings: rename host\contractmanager\contractmanager.json_temp host\contractmanager\contractmanager.json: Access is denied.
goroutine 1082603 [running]:
runtime/debug.Stack(0x446dee, 0xc044f71e20, 0xc044f71de8)
        /usr/local/go/src/runtime/debug/stack.go:24 +0xae
runtime/debug.PrintStack()
        /usr/local/go/src/runtime/debug/stack.go:16 +0x29
github.com/NebulousLabs/Sia/build.Severe(0xc044f71fa0, 0x2, 0x2)
        /home/luke/go/src/github.com/NebulousLabs/Sia/build/critical.go:32 +0x8c
github.com/NebulousLabs/Sia/persist.(*Logger).Severe(0xc04225dc00, 0xc044f71fa0, 0x2, 0x2)
        /home/luke/go/src/github.com/NebulousLabs/Sia/persist/log.go:71 +0xd3
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).syncResources.func1(0xc0464be160, 0xc042208548)
        /home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:50 +0x402
created by github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).syncResources
        /home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:25 +0x9a
Severe error: ERROR: unable to atomically copy the contract manager settings: rename host\contractmanager\contractmanager.json_temp host\contractmanager\contractmanager.json: Access is denied.
```

**Comment by jaaneh** [comment] 2017-09-22 21:48
@tlightsky tried a new fresh install, and let it resync the blockchain. Seems to work fine now. Thanks!

**Comment by tbenz9** [comment] 2017-10-17 18:24
Duplicate of #2247 

Recommendation to Devs: Close

**Closed** 2017-10-17 20:21 UTC
