### ISSUE TITLE
"exited unexpectedly" - won't restart

### ISSUE THREAD

**Issue by mikeSawicki** [NebulousLabs/Sia#2048] opened 2017-06-29 01:51 UTC
After putting my computer in hibernate mode, sia gives me an error "Siad has exited unexpectedly. Please submit a bug report including the error log here." and will not restart

**Comment by Paulserv** [comment] 2017-07-04 02:00
I have a similar issue after sleep mode...
A critical error loading Sia has occured: Siad unexpectedly exited. Error log: Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
goroutine 717 [running]:
runtime/debug.Stack(0x4442be, 0x0, 0xc042bcba78)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x80
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x29
github.com/NebulousLabs/Sia/build.Severe(0xc042bcbbf0, 0x2, 0x2)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/build/critical.go:32 +0x99
github.com/NebulousLabs/Sia/persist.(*Logger).Severe(0xc0441247e0, 0xc042bcbbf0, 0x2, 0x2)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/persist/log.go:71 +0xe7
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).syncResources(0xc04469c428)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/wr

**Comment by keithlovett** [comment] 2017-07-04 09:27
I have a number of issues with sleep mode and whether or not wallet is locked.

Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 1.0100664 seconds

Wallet: scanned to height 111597...
Wallet: scanned to height 111987...
Done!
goroutine 94108 [running]:
runtime/debug.Stack(0x4442be, 0x0, 0xc045917dc8)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x80
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x29
github.com/NebulousLabs/Sia/build.Severe(0xc045917f20, 0x2, 0x2)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/build/critical.go:32 +0x99
github.com/NebulousLabs/Sia/persist.(*Logger).Severe(0xc0421aee00, 0xc045917f20, 0x2, 0x2)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/persist/log.go:71 +0xe7
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).syncResources.func1(0xc04ffd8aa0, 0xc04224c788)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:50 +0x4f1
created by github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).syncResources
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:52 +0x9a
Severe error: ERROR: unable to atomically copy the contract manager settings: rename C:\Users\Keith\AppData\Roaming\Sia-UI\sia\host\contractmanager\contractmanager.json_temp C:\Users\Keith\AppData\Roaming\Sia-UI\sia\host\contractmanager\contractmanager.json: Access is denied.
goroutine 517193 [running]:
runtime/debug.Stack(0x4442be, 0x0, 0xc04ef8fdc8)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x80
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x29
github.com/NebulousLabs/Sia/build.Severe(0xc04ef8ff20, 0x2, 0x2)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/build/critical.go:32 +0x99
github.com/NebulousLabs/Sia/persist.(*Logger).Severe(0xc0421aee00, 0xc04ef8ff20, 0x2, 0x2)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/persist/log.go:71 +0xe7
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).syncResources.func1(0xc0434b5520, 0xc04224c788)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:50 +0x4f1
created by github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).syncResources
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:52 +0x9a
Severe error: ERROR: unable to atomically copy the contract manager settings: rename C:\Users\Keith\AppData\Roaming\Sia-UI\sia\host\contractmanager\contractmanager.json_temp C:\Users\Keith\AppData\Roaming\Sia-UI\sia\host\contractmanager\contractmanager.json: Access is denied.
goroutine 51 [running]:
runtime/debug.Stack(0x4442be, 0x0, 0xc04244fa78)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x80
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x29
github.com/NebulousLabs/Sia/build.Severe(0xc04244fbf0, 0x2, 0x2)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/build/critical.go:32 +0x99
github.com/NebulousLabs/Sia/persist.(*Logger).Severe(0xc0421aee00, 0xc04244fbf0, 0x2, 0x2)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/persist/log.go:71 +0xe7
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).syncResources(0xc04224c788)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:110 +0x6b0
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).commit(0xc04224c788)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:147 +0x47
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).threadedSyncLoop(0xc04224c788, 0xc04233ca80, 0xc04233cae0)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:276 +0x149
created by github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).spawnSyncLoop
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:223 +0x103
Severe error: ERROR: could not rename temporary write-ahead-log in contract manager: rename C:\Users\Keith\AppData\Roaming\Sia-UI\sia\host\contractmanager\contractmanager.wal_temp C:\Users\Keith\AppData\Roaming\Sia-UI\sia\host\contractmanager\contractmanager.wal: Access is denied.
goroutine 51 [running]:
runtime/debug.Stack(0x4442be, 0x0, 0xc04244fa78)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x80
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x29
github.com/NebulousLabs/Sia/build.Severe(0xc04244fbf0, 0x2, 0x2)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/build/critical.go:32 +0x99
github.com/NebulousLabs/Sia/persist.(*Logger).Severe(0xc0421aee00, 0xc04244fbf0, 0x2, 0x2)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/persist/log.go:71 +0xe7
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).syncResources(0xc04224c788)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:110 +0x6b0
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).commit(0xc04224c788)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:147 +0x47
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).threadedSyncLoop(0xc04224c788, 0xc04233ca80, 0xc04233cae0)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:276 +0x149
created by github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).spawnSyncLoop
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:223 +0x103
Severe error: ERROR: could not rename temporary write-ahead-log in contract manager: rename C:\Users\Keith\AppData\Roaming\Sia-UI\sia\host\contractmanager\contractmanager.wal_temp C:\Users\Keith\AppData\Roaming\Sia-UI\sia\host\contractmanager\contractmanager.wal: Access is denied.
goroutine 51 [running]:
runtime/debug.Stack(0x4442be, 0x0, 0xc04819fa78)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x80
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x29
github.com/NebulousLabs/Sia/build.Severe(0xc04819fbf0, 0x2, 0x2)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/build/critical.go:32 +0x99
github.com/NebulousLabs/Sia/persist.(*Logger).Severe(0xc0421aee00, 0xc04819fbf0, 0x2, 0x2)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/persist/log.go:71 +0xe7
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).syncResources(0xc04224c788)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:110 +0x6b0
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).commit(0xc04224c788)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:147 +0x47
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).threadedSyncLoop(0xc04224c788, 0xc04233ca80, 0xc04233cae0)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:276 +0x149
created by github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).spawnSyncLoop
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:223 +0x103
Severe error: ERROR: could not rename temporary write-ahead-log in contract manager: rename C:\Users\Keith\AppData\Roaming\Sia-UI\sia\host\contractmanager\contractmanager.wal_temp C:\Users\Keith\AppData\Roaming\Sia-UI\sia\host\contractmanager\contractmanager.wal: Access is denied.
goroutine 868334 [running]:
runtime/debug.Stack(0x4442be, 0x0, 0xc04e827dc8)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x80
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x29
github.com/NebulousLabs/Sia/build.Severe(0xc04e827f20, 0x2, 0x2)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/build/critical.go:32 +0x99
github.com/NebulousLabs/Sia/persist.(*Logger).Severe(0xc0421aee00, 0xc04e827f20, 0x2, 0x2)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/persist/log.go:71 +0xe7
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).syncResources.func1(0xc051960960, 0xc04224c788)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:50 +0x4f1
created by github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).syncResources
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:52 +0x9a
Severe error: ERROR: unable to atomically copy the contract manager settings: rename C:\Users\Keith\AppData\Roaming\Sia-UI\sia\host\contractmanager\contractmanager.json_temp C:\Users\Keith\AppData\Roaming\Sia-UI\sia\host\contractmanager\contractmanager.json: Access is denied.
Closing renter...
Closing host...

**Comment by keithlovett** [comment] 2017-07-04 09:46
I have a number of issues which may be a consequence of my noob status but mainly I can't close down app. Received following after attempting to stop daemon in terminal. Siad unexpectedly exited.

Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 1.0100664 seconds

Wallet: scanned to height 111597...
Wallet: scanned to height 111987...
Done!
goroutine 94108 [running]:
runtime/debug.Stack(0x4442be, 0x0, 0xc045917dc8)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x80
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x29
github.com/NebulousLabs/Sia/build.Severe(0xc045917f20, 0x2, 0x2)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/build/critical.go:32 +0x99
github.com/NebulousLabs/Sia/persist.(*Logger).Severe(0xc0421aee00, 0xc045917f20, 0x2, 0x2)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/persist/log.go:71 +0xe7
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).syncResources.func1(0xc04ffd8aa0, 0xc04224c788)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:50 +0x4f1
created by github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).syncResources
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:52 +0x9a
Severe error: ERROR: unable to atomically copy the contract manager settings: rename C:\Users\Keith\AppData\Roaming\Sia-UI\sia\host\contractmanager\contractmanager.json_temp C:\Users\Keith\AppData\Roaming\Sia-UI\sia\host\contractmanager\contractmanager.json: Access is denied.
goroutine 517193 [running]:
runtime/debug.Stack(0x4442be, 0x0, 0xc04ef8fdc8)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x80
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x29
github.com/NebulousLabs/Sia/build.Severe(0xc04ef8ff20, 0x2, 0x2)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/build/critical.go:32 +0x99
github.com/NebulousLabs/Sia/persist.(*Logger).Severe(0xc0421aee00, 0xc04ef8ff20, 0x2, 0x2)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/persist/log.go:71 +0xe7
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).syncResources.func1(0xc0434b5520, 0xc04224c788)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:50 +0x4f1
created by github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).syncResources
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:52 +0x9a
Severe error: ERROR: unable to atomically copy the contract manager settings: rename C:\Users\Keith\AppData\Roaming\Sia-UI\sia\host\contractmanager\contractmanager.json_temp C:\Users\Keith\AppData\Roaming\Sia-UI\sia\host\contractmanager\contractmanager.json: Access is denied.
goroutine 51 [running]:
runtime/debug.Stack(0x4442be, 0x0, 0xc04244fa78)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x80
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x29
github.com/NebulousLabs/Sia/build.Severe(0xc04244fbf0, 0x2, 0x2)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/build/critical.go:32 +0x99
github.com/NebulousLabs/Sia/persist.(*Logger).Severe(0xc0421aee00, 0xc04244fbf0, 0x2, 0x2)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/persist/log.go:71 +0xe7
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).syncResources(0xc04224c788)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:110 +0x6b0
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).commit(0xc04224c788)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:147 +0x47
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).threadedSyncLoop(0xc04224c788, 0xc04233ca80, 0xc04233cae0)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:276 +0x149
created by github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).spawnSyncLoop
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:223 +0x103
Severe error: ERROR: could not rename temporary write-ahead-log in contract manager: rename C:\Users\Keith\AppData\Roaming\Sia-UI\sia\host\contractmanager\contractmanager.wal_temp C:\Users\Keith\AppData\Roaming\Sia-UI\sia\host\contractmanager\contractmanager.wal: Access is denied.
goroutine 51 [running]:
runtime/debug.Stack(0x4442be, 0x0, 0xc04244fa78)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x80
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x29
github.com/NebulousLabs/Sia/build.Severe(0xc04244fbf0, 0x2, 0x2)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/build/critical.go:32 +0x99
github.com/NebulousLabs/Sia/persist.(*Logger).Severe(0xc0421aee00, 0xc04244fbf0, 0x2, 0x2)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/persist/log.go:71 +0xe7
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).syncResources(0xc04224c788)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:110 +0x6b0
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).commit(0xc04224c788)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:147 +0x47
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).threadedSyncLoop(0xc04224c788, 0xc04233ca80, 0xc04233cae0)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:276 +0x149
created by github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).spawnSyncLoop
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:223 +0x103
Severe error: ERROR: could not rename temporary write-ahead-log in contract manager: rename C:\Users\Keith\AppData\Roaming\Sia-UI\sia\host\contractmanager\contractmanager.wal_temp C:\Users\Keith\AppData\Roaming\Sia-UI\sia\host\contractmanager\contractmanager.wal: Access is denied.
goroutine 51 [running]:
runtime/debug.Stack(0x4442be, 0x0, 0xc04819fa78)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x80
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x29
github.com/NebulousLabs/Sia/build.Severe(0xc04819fbf0, 0x2, 0x2)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/build/critical.go:32 +0x99
github.com/NebulousLabs/Sia/persist.(*Logger).Severe(0xc0421aee00, 0xc04819fbf0, 0x2, 0x2)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/persist/log.go:71 +0xe7
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).syncResources(0xc04224c788)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:110 +0x6b0
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).commit(0xc04224c788)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:147 +0x47
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).threadedSyncLoop(0xc04224c788, 0xc04233ca80, 0xc04233cae0)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:276 +0x149
created by github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).spawnSyncLoop
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:223 +0x103
Severe error: ERROR: could not rename temporary write-ahead-log in contract manager: rename C:\Users\Keith\AppData\Roaming\Sia-UI\sia\host\contractmanager\contractmanager.wal_temp C:\Users\Keith\AppData\Roaming\Sia-UI\sia\host\contractmanager\contractmanager.wal: Access is denied.
goroutine 868334 [running]:
runtime/debug.Stack(0x4442be, 0x0, 0xc04e827dc8)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x80
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x29
github.com/NebulousLabs/Sia/build.Severe(0xc04e827f20, 0x2, 0x2)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/build/critical.go:32 +0x99
github.com/NebulousLabs/Sia/persist.(*Logger).Severe(0xc0421aee00, 0xc04e827f20, 0x2, 0x2)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/persist/log.go:71 +0xe7
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).syncResources.func1(0xc051960960, 0xc04224c788)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:50 +0x4f1
created by github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).syncResources
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:52 +0x9a
Severe error: ERROR: unable to atomically copy the contract manager settings: rename C:\Users\Keith\AppData\Roaming\Sia-UI\sia\host\contractmanager\contractmanager.json_temp C:\Users\Keith\AppData\Roaming\Sia-UI\sia\host\contractmanager\contractmanager.json: Access is denied.
Closing renter...
Closing host...

**Comment by tbenz9** [comment] 2017-11-09 23:55
It looks like @Paulserv's logs get cut off.  Without an intact log file the devs don't have much they can do.  I also suspect that the upcoming release with the new writeaheadlog will dramatically improve Sia's ability to recover from a sleep or hibernation event.  I'm going to recommend this issue get closed, but if you have more information or a clear reproducer after the next release feel free to reopen it.

Recommendation to devs: close

**Closed** 2017-11-10 18:41 UTC
