### ISSUE TITLE
Odd Race Condition

### ISSUE THREAD

**Issue by DavidVorick** [NebulousLabs/Sia#546] opened 2015-06-03 05:17 UTC
renter/negotiate.go:164 and renter/negotiate.go:230 will race eachother sometimes.

Assigning this to Luke as it's related to the tee-reader he implemented.

**Comment by lukechampine** [comment] 2015-06-03 17:04
I believe this is caused by `uploadWriter` [updating a field in the file piece](https://github.com/NebulousLabs/Sia/blob/ea15d311d6834c647c1922f1c9381617110c5a00/modules/renter/negotiate.go#L71), which enables upload progress. Not sure what the best way to approach this is. Dead simple would be to add a lock around the modification, but I worry that it would noticeably affect upload speed.

**Comment by DavidVorick** [comment] 2015-06-03 18:48
atomic?

**Comment by lukechampine** [comment] 2015-06-03 20:28
that might solve it. If we can reliably reproduce it, that's the first approach I would try.

**Comment by lukechampine** [comment] 2015-06-03 21:32
the dangerous result here would be once we implement upload resuming. If you continue transferring bytes after saving the renter state, then you could get out of sync when you reload.

**Comment by DavidVorick** [comment] 2015-06-04 01:02
you can reset the two to be in sync, worst case I think you'd just end up downloading parts of the file a second time.

**Closed** 2015-06-26 13:09 UTC
