### ISSUE TITLE
DEBUG io.goobox.sync.sia.SiaDaemon -Critical error negative currency not allowed

### ISSUE THREAD

**Issue by MeijeSibbel** [NebulousLabs/Sia#2543] opened 2017-12-14 21:46 UTC
Bug Report
==========
Check to see if a bug report already exists.  If you still want to create a new issue please include the information below.

**Stack Trace or error message**

**Environment**
* Sia version: v1.3.1 RC2
* OS: windows 10 home 

**Any useful logs**

[DEBUG io.goobox.sync.sia.SiaDaemon -Critical error negative currency not allowed.txt](https://github.com/NebulousLabs/Sia/files/1560845/DEBUG.io.goobox.sync.sia.SiaDaemon.-Critical.error.negative.currency.not.allowed.txt)
[contractor.log](https://github.com/NebulousLabs/Sia/files/1560849/contractor.log)
[renter.log](https://github.com/NebulousLabs/Sia/files/1560850/renter.log)
[hostdb.log](https://github.com/NebulousLabs/Sia/files/1560851/hostdb.log)

Feature Request
===============
Check to see if the feature is on the roadmap.  If it is not on the roadmap then clearly describe your feature request and why it would benefit Sia.

[Sia roadmap](https://trello.com/b/Io1dDyuI/sia-public-roadmap)

**Comment by tbenz9** [comment] 2017-12-14 22:06
Duplicate of #2346.

Thanks for uploading your logs, they'll be linked to the active ticket.

**Closed by tbenz9** 2017-12-14 22:06 UTC
