### ISSUE TITLE
Critical error with the renter ..

### ISSUE THREAD

**Issue by mannp** [NebulousLabs/Sia#2453] opened 2017-10-31 09:09 UTC
Please submit a bug report here: https://github.com/NebulousLabs/Sia/issues

This error occurred repeatedly overnight and didn't get resolved until the server rebooted after a backup.

> goroutine 2625 [running]:
> runtime/debug.Stack(0x445917, 0x0, 0xc448627bf0)
> /usr/local/go/src/runtime/debug/stack.go:24 +0x79
> runtime/debug.PrintStack()
> /usr/local/go/src/runtime/debug/stack.go:16 +0x22
> github.com/NebulousLabs/Sia/build.Critical(0xc448627d70, 0x3, 0x3)
> /go/src/github.com/NebulousLabs/Sia/build/critical.go:16 +0xa7
> github.com/NebulousLabs/Sia/persist.(*Logger).Critical(0xc420e24720, 0xc448627d70, 0x3, 0x3)
> /go/src/github.com/NebulousLabs/Sia/persist/log.go:37 +0xe0
> github.com/NebulousLabs/Sia/modules/renter.(*Renter).managedDownloadIteration(0xc421dca000, 0xc448627f20)
> /go/src/github.com/NebulousLabs/Sia/modules/renter/download.go:365 +0x67d
> github.com/NebulousLabs/Sia/modules/renter.(*Renter).threadedDownloadLoop(0xc421dca000)
> /go/src/github.com/NebulousLabs/Sia/modules/renter/download.go:635 +0x37e
> created by github.com/NebulousLabs/Sia/modules/renter.newRenter
> /go/src/github.com/NebulousLabs/Sia/modules/renter/renter.go:220 +0x3e3
> Critical error: ERROR: the renter is idle, but tracking 11 active pieces; resetting to zero

**Comment by tbenz9** [comment] 2017-10-31 17:41
`Critical error: ERROR: the renter is idle, but tracking 11 active pieces; resetting to zero`

Duplicate of #2395

**Comment by mannp** [comment] 2017-10-31 17:43
Perhaps a duplicate result but I don't use duplicati, so the cause of the problem is not related to that ...

**Comment by tbenz9** [comment] 2017-10-31 17:45
That's a good point, I'll let the devs decide if they want to tag this one as a separate bug or lump it in with #2395.

**Comment by tbenz9** [comment] 2017-10-31 17:56
It looks like #2435 and #2319 were the same problem and are also being tracked with #2395 despite not using Duplicati.  Sounds like this issue is not exclusive to the Duplicati integration but is being tracked in that ticket.

Recommendation to devs: Close

**Closed** 2017-10-31 19:12 UTC
