### ISSUE TITLE
SIA crashes via miner

### ISSUE THREAD

**Issue by cryptographicgold** [NebulousLabs/Sia#2389] opened 2017-10-03 00:26 UTC
Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 0.4067288 seconds

When I go to restart said the program loops back to the entry above and will not let me enter my password

Mining via marlin

**Comment by cryptographicgold** [comment] 2017-10-03 00:36
Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 0.9539994 seconds
panic: runtime error: slice bounds out of range

goroutine 65 [running]:
github.com/NebulousLabs/bolt.(*Cursor).searchPage.func1(0x47af, 0xc0423f3d00)
	/home/luke/go/src/github.com/NebulousLabs/bolt/cursor.go:302 +0xc8
sort.Search(0x5f94, 0xc0423f3e18, 0x72a74a)
	/usr/local/go/src/sort/search.go:66 +0x6a
github.com/NebulousLabs/bolt.(*Cursor).searchPage(0xc0423f43e8, 0xc042449580, 0x20, 0x20, 0x85424000)
	/home/luke/go/src/github.com/NebulousLabs/bolt/cursor.go:307 +0xdc
github.com/NebulousLabs/bolt.(*Cursor).search(0xc0423f43e8, 0xc042449580, 0x20, 0x20, 0x5434)
	/home/luke/go/src/github.com/NebulousLabs/bolt/cursor.go:271 +0x1c2
github.com/NebulousLabs/bolt.(*Cursor).searchPage(0xc0423f43e8, 0xc042449580, 0x20, 0x20, 0x84cc7000)
	/home/luke/go/src/github.com/NebulousLabs/bolt/cursor.go:314 +0x15d
github.com/NebulousLabs/bolt.(*Cursor).search(0xc0423f43e8, 0xc042449580, 0x20, 0x20, 0x4cd7)
	/home/luke/go/src/github.com/NebulousLabs/bolt/cursor.go:271 +0x1c2
github.com/NebulousLabs/bolt.(*Cursor).searchPage(0xc0423f43e8, 0xc042449580, 0x20, 0x20, 0x879ae000)
	/home/luke/go/src/github.com/NebulousLabs/bolt/cursor.go:314 +0x15d
github.com/NebulousLabs/bolt.(*Cursor).search(0xc0423f43e8, 0xc042449580, 0x20, 0x20, 0x79be)
	/home/luke/go/src/github.com/NebulousLabs/bolt/cursor.go:271 +0x1c2
github.com/NebulousLabs/bolt.(*Cursor).searchNode(0xc0423f43e8, 0xc042449580, 0x20, 0x20, 0xc0420e3030)
	/home/luke/go/src/github.com/NebulousLabs/bolt/cursor.go:291 +0x12b
github.com/NebulousLabs/bolt.(*Cursor).search(0xc0423f43e8, 0xc042449580, 0x20, 0x20, 0x87893)
	/home/luke/go/src/github.com/NebulousLabs/bolt/cursor.go:268 +0x17d
github.com/NebulousLabs/bolt.(*Cursor).seek(0xc0423f43e8, 0xc042449580, 0x20, 0x20, 0x0, 0x0, 0xc043516540, 0x99, 0x0, 0x0, ...)
	/home/luke/go/src/github.com/NebulousLabs/bolt/cursor.go:159 +0xb8
github.com/NebulousLabs/bolt.(*Bucket).Put(0xc042be7a40, 0xc042449580, 0x20, 0x20, 0xc0420125d0, 0x34, 0x40, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/bolt/bucket.go:300 +0x14d
github.com/NebulousLabs/Sia/modules/consensus.addSiacoinOutput(0xc0420dc000, 0x6a950c9adfe5c506, 0x68908a0aad082d44, 0xad5fd99d5f5c4840, 0x8f509a4710437373, 0x0, 0xc042deae70, 0x2, 0x6, 0xb9dac77cd78ba7d2, ...)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/consensusdb.go:312 +0x14b
github.com/NebulousLabs/Sia/modules/consensus.commitSiacoinOutputDiff(0xc0420dc000, 0x950c9adfe5c50601, 0x908a0aad082d446a, 0x5fd99d5f5c484068, 0x509a4710437373ad, 0x8f, 0x0, 0xc042deae70, 0x2, 0x6, ...)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/diffs.go:58 +0x8a
github.com/NebulousLabs/Sia/modules/consensus.applySiacoinOutputs(0xc0420dc000, 0xc04205ba20, 0xc04356da40, 0x1, 0x1, 0xc043ae2000, 0x32, 0x32, 0x0, 0x0, ...)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/applytransaction.go:45 +0x254
github.com/NebulousLabs/Sia/modules/consensus.applyTransaction(0xc0420dc000, 0xc04205ba20, 0xc04356da40, 0x1, 0x1, 0xc043ae2000, 0x32, 0x32, 0x0, 0x0, ...)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/applytransaction.go:208 +0xc0
github.com/NebulousLabs/Sia/modules/consensus.generateAndApplyDiff(0xc0420dc000, 0xc04205ba20, 0xc042c55e40, 0x2)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/diffs.go:224 +0x17e
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).applyUntilBlock(0xc042113b80, 0xc0420dc000, 0xc04205ba20, 0x0, 0x0, 0x0, 0x6402000000000000, 0xff74ecaa256e024c)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/fork.go:84 +0x244
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).forkBlockchain(0xc042113b80, 0xc0420dc000, 0xc04205ba20, 0x6a00000000000000, 0xd2fac7f55bfb71af, 0x2d42aca033b81b6a, 0x77d02bf0062c0bd1, 0x475c04e104020148, 0x59d2d778, 0xc043468b80, ...)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/fork.go:111 +0xb3
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).addBlockToTree(0xc042113b80, 0xc0420dc000, 0x6a00000000000000, 0xd2fac7f55bfb71af, 0x2d42aca033b81b6a, 0x77d02bf0062c0bd1, 0x475c04e104020148, 0x59d2d778, 0xc043468b80, 0x1, ...)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/accept.go:164 +0x114
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).managedAcceptBlocks.func1(0xc0420dc000, 0xb0b570, 0xc0420dc000)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/accept.go:262 +0x23a
github.com/NebulousLabs/bolt.(*DB).Update(0xc0420e0780, 0xc0432bf2e8, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/bolt/db.go:603 +0xa6
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).managedAcceptBlocks(0xc042113b80, 0xc04335ad80, 0x4, 0x4, 0x0, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/accept.go:283 +0x520
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).managedReceiveBlocks(0xc042113b80, 0xde41c0, 0xc042e501a0, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:225 +0x5be
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).(github.com/NebulousLabs/Sia/modules/consensus.managedReceiveBlocks)-fm(0xde41c0, 0xc042e501a0, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:445 +0x45
github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).managedRPC(0xc04205ac60, 0xc0421c9600, 0x11, 0xaddb78, 0xa, 0xc042efc100, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/rpc.go:66 +0x339
github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).RPC(0xc04205ac60, 0xc0421c9600, 0x11, 0xaddb78, 0xa, 0xc042efc100, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/rpc.go:76 +0xd8
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).threadedInitialBlockchainDownload.func1(0xc042113b80, 0xc0423f5ef0, 0xc0423f5eb0, 0xc0423f5eb8, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:580 +0x133
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).threadedInitialBlockchainDownload(0xc042113b80, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:601 +0x30e
github.com/NebulousLabs/Sia/modules/consensus.New.func1(0x1, 0xc04228cdb0, 0xc042113b80, 0xde4440, 0xc04205ac60)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/consensusset.go:151 +0x404
created by github.com/NebulousLabs/Sia/modules/consensus.New
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/consensusset.go:182 +0x641

**Comment by cryptographicgold** [comment] 2017-10-03 01:04
I solved the immediate problem of SIA UI crashing by closing the GPU and logging on and off computer but now the password does not unlock the wallet (and I have successfully unlocked the wallet many times)

**Comment by tbenz9** [comment] 2017-10-19 16:23
`panic: runtime error: slice bounds out of range` is duplicate of #2183.

If you're still having trouble unlocking your wallet try asking for help in the Discord or opening a new issue.  We only want one bug per issue.

Recommendation to devs: Close as duplicate.

**Closed** 2017-10-19 21:36 UTC
