### ISSUE TITLE
Critical Error: accept tcp 127.0.0.1:9980: accept: too many open files in system

### ISSUE THREAD

**Issue by geoguide** [NebulousLabs/Sia#2082] opened 2017-07-05 16:27 UTC
Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 0.260642637 seconds
goroutine 1 [running]:
runtime/debug.Stack(0x1043857, 0x0, 0x422abd5f8)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x79
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/NebulousLabs/Sia/build.Critical(0x422abd948, 0x1, 0x1)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/build/critical.go:16 +0xa7
main.startDaemon(0x0, 0x0, 0x7fff5fbffce4, 0xe, 0x7fff5fbffd10, 0x5, 0x7fff5fbffcff, 0x5, 0x0, 0x7fff5fbffd6c, ...)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/siad/daemon.go:295 +0xaa9
main.startDaemonCmd(0x421c31200, 0x421bc3400, 0x0, 0x5)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/siad/daemon.go:309 +0x6d
github.com/spf13/cobra.(*Command).execute(0x421c31200, 0x421bb80d0, 0x5, 0x5, 0x421c31200, 0x421bb80d0)
	/home/jrh/go/src/github.com/spf13/cobra/command.go:651 +0x23a
github.com/spf13/cobra.(*Command).ExecuteC(0x421c31200, 0x16c7c0f, 0x3b, 0x421d028c0)
	/home/jrh/go/src/github.com/spf13/cobra/command.go:726 +0x339
github.com/spf13/cobra.(*Command).Execute(0x421c31200, 0x1aa6520, 0x16b10c0)
	/home/jrh/go/src/github.com/spf13/cobra/command.go:685 +0x2b
main.main()
	/home/jrh/go/src/github.com/NebulousLabs/Sia/siad/main.go:174 +0x79d
Critical error: accept tcp 127.0.0.1:9980: accept: too many open files in system
Please submit a bug report here: https://github.com/NebulousLabs/Sia/issues
Closing renter...

**Comment by geoguide** [comment] 2017-07-05 16:27
This happens consistently.

**Comment by S-anasol** [comment] 2017-07-05 16:29
https://github.com/NebulousLabs/Sia/issues/1957#issuecomment-309315944

**Comment by lukechampine** [comment] 2017-07-28 22:59
duplicate of #1840

**Closed by lukechampine** 2017-07-28 22:59 UTC
