### ISSUE TITLE
Severe error: api call is taking more than 60 minutes to return (stack trace included)

### ISSUE THREAD

**Issue by mannp** [NebulousLabs/Sia#2483] opened 2017-11-21 18:24 UTC
Bug Report
==========

Severe error: api call is taking more than 60 minutes to return.

**Environment**
* Sia version: 1.3
* OS: Linux

**Stack Trace or error message**
**Any useful logs**

Running with debugging enabled
Loading...
(0/5) Loading siad...
(1/5) Loading gateway...
(2/5) Loading consensus...
(3/5) Loading transaction pool...
(4/5) Loading wallet...
(5/5) Loading renter...
Finished loading in 6.003079669 seconds
Done!
goroutine 139725 [running]:
runtime/debug.Stack(0x4463a7, 0x0, 0xc4213fce88)
/usr/local/go/src/runtime/debug/stack.go:24 +0x79
runtime/debug.PrintStack()
/usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/NebulousLabs/Sia/build.Severe(0xc4217b3f20, 0x2, 0x2)
/go/src/github.com/NebulousLabs/Sia/build/critical.go:32 +0x92
github.com/NebulousLabs/Sia/api.cleanCloseHandler.func1.2(0xc460a1ed20, 0xc421a84200)
/go/src/github.com/NebulousLabs/Sia/api/api.go:146 +0x1b3
created by github.com/NebulousLabs/Sia/api.cleanCloseHandler.func1
/go/src/github.com/NebulousLabs/Sia/api/api.go:148 +0x182
Severe error: api call is taking more than 60 minutes to return: /renter/upload/endtoend-whitepaper.pdf

**panic: Severe error: api call is taking more than 60 minutes to return: /renter/upload/endtoend-whitepaper.pdf**

goroutine 139725 [running]:
github.com/NebulousLabs/Sia/build.Severe(0xc4217b3f20, 0x2, 0x2)
/go/src/github.com/NebulousLabs/Sia/build/critical.go:36 +0xfc
github.com/NebulousLabs/Sia/api.cleanCloseHandler.func1.2(0xc460a1ed20, 0xc421a84200)
/go/src/github.com/NebulousLabs/Sia/api/api.go:146 +0x1b3
created by github.com/NebulousLabs/Sia/api.cleanCloseHandler.func1
/go/src/github.com/NebulousLabs/Sia/api/api.go:148 +0x182

**Comment by tbenz9** [comment] 2017-11-22 21:52
This appears to be an isolated incident, I haven't seen this issue before in the past.  I would guess you have some network configuration or firewall config that is preventing the API from returning in a timely fashion.  I'll let the devs decide what they want to do, but it may be closed without a fix.

**Comment by mannp** [comment] 2017-11-22 23:13
Its not going near a firewall as the api call is from nextcloud to the sia api, as per the nextcloud plugin setup on the same machine.

As I haven't been able to upload for over a month it feels more like an issue related to that (already acknowledged bug)

The nextcloud plugin shows green with no errors but this error occurs trying to upload anything via the nextcloud interface now.

**Comment by DavidVorick** [comment] 2017-11-23 17:02
We will investigate. We've had some problems with the API in the past that got fixed.

If you are running the master branch, uploading is almost completely broken at the moment. We're working through the issues to get it smooth again, we're getting pretty close.

**Comment by mannp** [comment] 2017-11-23 17:17
No I am currently on 1.3.0 as taek mentioned on discord that the master branch was currently missing some key items that hadn't been merged yet, so I stayed away.

I am hoping all my issues over the past month will get resolved with the 1.3.1 update :) so am ok if this waits until after that has been released, as I am unclear if it is related to my not being able to upload at all, even with 80 contracts in place.

**Comment by harshavardhana** [comment] 2017-11-24 00:43
We also saw this with `minio gateway sia` as well while testing.

**Comment by mannp** [comment] 2017-11-24 09:18
Thanks @harshavardhana, so its perhaps not related to my other issues around uploading.

**Comment by Fornax96** [comment] 2017-11-26 22:08
This happens very frequently on pixeldrain too. From my experience it seems like the first upload call in a long time hangs  (usually between 10 and 30 minutes, I capped it at 30), and all the upload calls that happen after that only take a few seconds each (pixeldrain uploads in batches).

I think this may also have something to do with the "renter is idle, but tracking x active pieces" error (https://github.com/NebulousLabs/Sia/issues/2395), since I've only seen it happen after that error has been logged. A restart of the Sia daemon always fixes the problem. Pixeldrain now runs a cron job which restarts Sia every 6 hours.

**Comment by Wlinc** [comment] 2017-12-12 21:28
This error happened for me today. 

Wallet: 1.3.0
Environment: Windows 10 Home evaluation version. 
I've seen it before, but have been able to reboot the client and sync the wallet. I do not need to upload files or host, so it's more of an annoyance than a blocker. Let me know if there are questions. Happy bug swatting!

Loading...
(0/6) Loading siad...
listen tcp 127.0.0.1:9980: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted.
goroutine 193531 [running]:
runtime/debug.Stack(0x44439e, 0x0, 0xc045ba9e98)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x80
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x29
github.com/NebulousLabs/Sia/build.Severe(0xc045ba9f20, 0x2, 0x2)
	/home/luke/go/src/github.com/NebulousLabs/Sia/build/critical.go:32 +0x99
github.com/NebulousLabs/Sia/api.cleanCloseHandler.func1.2(0xc04419fe00, 0xc048e4f200)
	/home/luke/go/src/github.com/NebulousLabs/Sia/api/api.go:146 +0x1ba
created by github.com/NebulousLabs/Sia/api.cleanCloseHandler.func1
	/home/luke/go/src/github.com/NebulousLabs/Sia/api/api.go:148 +0x189
Severe error: api call is taking more than 60 minutes to return: /consensus
goroutine 193548 [running]:
runtime/debug.Stack(0x44439e, 0x0, 0xc04534be98)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x80
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x29
github.com/NebulousLabs/Sia/build.Severe(0xc04534bf20, 0x2, 0x2)
	/home/luke/go/src/github.com/NebulousLabs/Sia/build/critical.go:32 +0x99
github.com/NebulousLabs/Sia/api.cleanCloseHandler.func1.2(0xc04a9747e0, 0xc048e4f400)
	/home/luke/go/src/github.com/NebulousLabs/Sia/api/api.go:146 +0x1ba
created by github.com/NebulousLabs/Sia/api.cleanCloseHandler.func1
	/home/luke/go/src/github.com/NebulousLabs/Sia/api/api.go:148 +0x189
Severe error: api call is taking more than 60 minutes to return: /consensus
goroutine 193587 [running]:
runtime/debug.Stack(0x44439e, 0x0, 0xc0488ede98)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x80
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x29
github.com/NebulousLabs/Sia/build.Severe(0xc0488edf20, 0x2, 0x2)
	/home/luke/go/src/github.com/NebulousLabs/Sia/build/critical.go:32 +0x99
github.com/NebulousLabs/Sia/api.cleanCloseHandler.func1.2(0xc0431f6de0, 0xc0444c4300)
	/home/luke/go/src/github.com/NebulousLabs/Sia/api/api.go:146 +0x1ba
created by github.com/NebulousLabs/Sia/api.cleanCloseHandler.func1
	/home/luke/go/src/github.com/NebulousLabs/Sia/api/api.go:148 +0x189
Severe error: api call is taking more than 60 minutes to return: /consensus
goroutine 193550 [running]:
runtime/debug.Stack(0x44439e, 0x0, 0xc04533be98)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x80
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x29
github.com/NebulousLabs/Sia/build.Severe(0xc04533bf20, 0x2, 0x2)
	/home/luke/go/src/github.com/NebulousLabs/Sia/build/critical.go:32 +0x99
github.com/NebulousLabs/Sia/api.cleanCloseHandler.func1.2(0xc0431f6ea0, 0xc0444c4400)
	/home/luke/go/src/github.com/NebulousLabs/Sia/api/api.go:146 +0x1ba
created by github.com/NebulousLabs/Sia/api.cleanCloseHandler.func1
	/home/luke/go/src/github.com/NebulousLabs/Sia/api/api.go:148 +0x189
Severe error: api call is taking more than 60 minutes to return: /consensus
goroutine 193624 [running]:
runtime/debug.Stack(0x44439e, 0x0, 0xc048903e98)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x80
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x29
github.com/NebulousLabs/Sia/build.Severe(0xc048903f20, 0x2, 0x2)
	/home/luke/go/src/github.com/NebulousLabs/Sia/build/critical.go:32 +0x99
github.com/NebulousLabs/Sia/api.cleanCloseHandler.func1.2(0xc04a974f60, 0xc0444c4700)
	/home/luke/go/src/github.com/NebulousLabs/Sia/api/api.go:146 +0x1ba
created by github.com/NebulousLabs/Sia/api.cleanCloseHandler.func1
	/home/luke/go/src/github.com/NebulousLabs/Sia/api/api.go:148 +0x189
Severe error: api call is taking more than 60 minutes to return: /consensus
goroutine 193612 [running]:
runtime/debug.Stack(0x44439e, 0x0, 0xc048905e98)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x80
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x29
github.com/NebulousLabs/Sia/build.Severe(0xc048905f20, 0x2, 0x2)
	/home/luke/go/src/github.com/NebulousLabs/Sia/build/critical.go:32 +0x99
github.com/NebulousLabs/Sia/api.cleanCloseHandler.func1.2(0xc0490774a0, 0xc0444c4a00)
	/home/luke/go/src/github.com/NebulousLabs/Sia/api/api.go:146 +0x1ba
created by github.com/NebulousLabs/Sia/api.cleanCloseHandler.func1
	/home/luke/go/src/github.com/NebulousLabs/Sia/api/api.go:148 +0x189
Severe error: api call is taking more than 60 minutes to return: /consensus
goroutine 193657 [running]:
runtime/debug.Stack(0x44439e, 0x0, 0xc045359e98)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x80
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x29
github.com/NebulousLabs/Sia/build.Severe(0xc045359f20, 0x2, 0x2)
	/home/luke/go/src/github.com/NebulousLabs/Sia/build/critical.go:32 +0x99
github.com/NebulousLabs/Sia/api.cleanCloseHandler.func1.2(0xc04419e780, 0xc04911b100)
	/home/luke/go/src/github.com/NebulousLabs/Sia/api/api.go:146 +0x1ba
created by github.com/NebulousLabs/Sia/api.cleanCloseHandler.func1
	/home/luke/go/src/github.com/NebulousLabs/Sia/api/api.go:148 +0x189
Severe error: api call is taking more than 60 minutes to return: /consensus
goroutine 193683 [running]:
runtime/debug.Stack(0x44439e, 0x0, 0xc046419e98)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x80
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x29
github.com/NebulousLabs/Sia/build.Severe(0xc046419f20, 0x2, 0x2)
	/home/luke/go/src/github.com/NebulousLabs/Sia/build/critical.go:32 +0x99
github.com/NebulousLabs/Sia/api.cleanCloseHandler.func1.2(0xc045460a80, 0xc0444c4e00)
	/home/luke/go/src/github.com/NebulousLabs/Sia/api/api.go:146 +0x1ba
created by github.com/NebulousLabs/Sia/api.cleanCloseHandler.func1
	/home/luke/go/src/github.com/NebulousLabs/Sia/api/api.go:148 +0x189
Severe error: api call is taking more than 60 minutes to return: /consensus
goroutine 193658 [running]:
runtime/debug.Stack(0x44439e, 0x0, 0xc0450dfe98)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x80
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x29
github.com/NebulousLabs/Sia/build.Severe(0xc0450dff20, 0x2, 0x2)
	/home/luke/go/src/github.com/NebulousLabs/Sia/build/critical.go:32 +0x99
github.com/NebulousLabs/Sia/api.cleanCloseHandler.func1.2(0xc049077e60, 0xc048e4fc00)
	/home/luke/go/src/github.com/NebulousLabs/Sia/api/api.go:146 +0x1ba
created by github.com/NebulousLabs/Sia/api.cleanCloseHandler.func1
	/home/luke/go/src/github.com/NebulousLabs/Sia/api/api.go:148 +0x189
Severe error: api call is taking more than 60 minutes to return: /consensus
goroutine 193702 [running]:
runtime/debug.Stack(0x44439e, 0x0, 0xc048917e98)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x80
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x29
github.com/NebulousLabs/Sia/build.Severe(0xc048917f20, 0x2, 0x2)
	/home/luke/go/src/github.com/NebulousLabs/Sia/build/critical.go:32 +0x99
github.com/NebulousLabs/Sia/api.cleanCloseHandler.func1.2(0xc0439f8900, 0xc043a7e100)
	/home/luke/go/src/github.com/NebulousLabs/Sia/api/api.go:146 +0x1ba
created by github.com/NebulousLabs/Sia/api.cleanCloseHandler.func1
	/home/luke/go/src/github.com/NebulousLabs/Sia/api/api.go:148 +0x189
Severe error: api call is taking more than 60 minutes to return: /consensus
goroutine 193716 [running]:
runtime/debug.Stack(0x44439e, 0x0, 0xc048913e98)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x80
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x29
github.com/NebulousLabs/Sia/build.Severe(0xc048913f20, 0x2, 0x2)
	/home/luke/go/src/github.com/NebulousLabs/Sia/build/critical.go:32 +0x99
github.com/NebulousLabs/Sia/api.cleanCloseHandler.func1.2(0xc045461b60, 0xc048e4fe00)
	/home/luke/go/src/github.com/NebulousLabs/Sia/api/api.go:146 +0x1ba
created by github.com/NebulousLabs/Sia/api.cleanCloseHandler.func1
	/home/luke/go/src/github.com/NebulousLabs/Sia/api/api.go:148 +0x189
Severe error: api call is taking more than 60 minutes to return: /consensus
goroutine 193718 [running]:
runtime/debug.Stack(0x44439e, 0x0, 0xc0450e1e98)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x80
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x29
github.com/NebulousLabs/Sia/build.Severe(0xc0450e1f20, 0x2, 0x2)
	/home/luke/go/src/github.com/NebulousLabs/Sia/build/critical.go:32 +0x99
github.com/NebulousLabs/Sia/api.cleanCloseHandler.func1.2(0xc04ad5f140, 0xc04487a200)
	/home/luke/go/src/github.com/NebulousLabs/Sia/api/api.go:146 +0x1ba
created by github.com/NebulousLabs/Sia/api.cleanCloseHandler.func1
	/home/luke/go/src/github.com/NebulousLabs/Sia/api/api.go:148 +0x189
Severe error: api call is taking more than 60 minutes to return: /consensus
goroutine 193763 [running]:
runtime/debug.Stack(0x44439e, 0x0, 0xc04a717e98)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x80
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x29
github.com/NebulousLabs/Sia/build.Severe(0xc04a717f20, 0x2, 0x2)
	/home/luke/go/src/github.com/NebulousLabs/Sia/build/critical.go:32 +0x99
github.com/NebulousLabs/Sia/api.cleanCloseHandler.func1.2(0xc045a57980, 0xc04487a300)
	/home/luke/go/src/github.com/NebulousLabs/Sia/api/api.go:146 +0x1ba
created by github.com/NebulousLabs/Sia/api.cleanCloseHandler.func1
	/home/luke/go/src/github.com/NebulousLabs/Sia/api/api.go:148 +0x189
Severe error: api call is taking more than 60 minutes to return: /consensus
goroutine 193769 [running]:
runtime/debug.Stack(0x44439e, 0x0, 0xc04641fe98)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x80
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x29
github.com/NebulousLabs/Sia/build.Severe(0xc04641ff20, 0x2, 0x2)
	/home/luke/go/src/github.com/NebulousLabs/Sia/build/critical.go:32 +0x99
github.com/NebulousLabs/Sia/api.cleanCloseHandler.func1.2(0xc0431bf560, 0xc04487a700)
	/home/luke/go/src/github.com/NebulousLabs/Sia/api/api.go:146 +0x1ba
created by github.com/NebulousLabs/Sia/api.cleanCloseHandler.func1
	/home/luke/go/src/github.com/NebulousLabs/Sia/api/api.go:148 +0x189
Severe error: api call is taking more than 60 minutes to return: /consensus
goroutine 193776 [running]:
runtime/debug.Stack(0x44439e, 0x0, 0xc04891be98)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x80
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x29
github.com/NebulousLabs/Sia/build.Severe(0xc04891bf20, 0x2, 0x2)
	/home/luke/go/src/github.com/NebulousLabs/Sia/build/critical.go:32 +0x99
github.com/NebulousLabs/Sia/api.cleanCloseHandler.func1.2(0xc046064960, 0xc04487a800)
	/home/luke/go/src/github.com/NebulousLabs/Sia/api/api.go:146 +0x1ba
created by github.com/NebulousLabs/Sia/api.cleanCloseHandler.func1
	/home/luke/go/src/github.com/NebulousLabs/Sia/api/api.go:148 +0x189
Severe error: api call is taking more than 60 minutes to return: /consensus
goroutine 193803 [running]:
runtime/debug.Stack(0x44439e, 0x0, 0xc048907e98)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x80
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x29
github.com/NebulousLabs/Sia/build.Severe(0xc048907f20, 0x2, 0x2)
	/home/luke/go/src/github.com/NebulousLabs/Sia/build/critical.go:32 +0x99
github.com/NebulousLabs/Sia/api.cleanCloseHandler.func1.2(0xc049077380, 0xc0444c4800)
	/home/luke/go/src/github.com/NebulousLabs/Sia/api/api.go:146 +0x1ba
created by github.com/NebulousLabs/Sia/api.cleanCloseHandler.func1
	/home/luke/go/src/github.com/NebulousLabs/Sia/api/api.go:148 +0x189
Severe error: api call is taking more than 60 minutes to return: /consensus
goroutine 193874 [running]:
runtime/debug.Stack(0x44439e, 0x0, 0xc048911e98)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x80
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x29
github.com/NebulousLabs/Sia/build.Severe(0xc048911f20, 0x2, 0x2)
	/home/luke/go/src/github.com/NebulousLabs/Sia/build/critical.go:32 +0x99
github.com/NebulousLabs/Sia/api.cleanCloseHandler.func1.2(0xc044cc4a80, 0xc0444c5800)
	/home/luke/go/src/github.com/NebulousLabs/Sia/api/api.go:146 +0x1ba
created by github.com/NebulousLabs/Sia/api.cleanCloseHandler.func1
	/home/luke/go/src/github.com/NebulousLabs/Sia/api/api.go:148 +0x189
Severe error: api call is taking more than 60 minutes to return: /consensus
goroutine 193877 [running]:
runtime/debug.Stack(0x44439e, 0x0, 0xc048b6de98)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x80
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x29
github.com/NebulousLabs/Sia/build.Severe(0xc048b6df20, 0x2, 0x2)
	/home/luke/go/src/github.com/NebulousLabs/Sia/build/critical.go:32 +0x99
github.com/NebulousLabs/Sia/api.cleanCloseHandler.func1.2(0xc042b95980, 0xc043a7e900)
	/home/luke/go/src/github.com/NebulousLabs/Sia/api/api.go:146 +0x1ba
created by github.com/NebulousLabs/Sia/api.cleanCloseHandler.func1
	/home/luke/go/src/github.com/NebulousLabs/Sia/api/api.go:148 +0x189
Severe error: api call is taking more than 60 minutes to return: /consensus
goroutine 193871 [running]:
runtime/debug.Stack(0x44439e, 0x0, 0xc0450e5e98)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x80
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x29
github.com/NebulousLabs/Sia/build.Severe(0xc0450e5f20, 0x2, 0x2)
	/home/luke/go/src/github.com/NebulousLabs/Sia/build/critical.go:32 +0x99
github.com/NebulousLabs/Sia/api.cleanCloseHandler.func1.2(0xc046205320, 0xc0444c5d00)
	/home/luke/go/src/github.com/NebulousLabs/Sia/api/api.go:146 +0x1ba
created by github.com/NebulousLabs/Sia/api.cleanCloseHandler.func1
	/home/luke/go/src/github.com/NebulousLabs/Sia/api/api.go:148 +0x189
Severe error: api call is taking more than 60 minutes to return: /consensus
goroutine 193907 [running]:
runtime/debug.Stack(0x44439e, 0x0, 0xc04641de98)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x80
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x29
github.com/NebulousLabs/Sia/build.Severe(0xc04641df20, 0x2, 0x2)
	/home/luke/go/src/github.com/NebulousLabs/Sia/build/critical.go:32 +0x99
github.com/NebulousLabs/Sia/api.cleanCloseHandler.func1.2(0xc049a9c060, 0xc0444c5e00)
	/home/luke/go/src/github.com/NebulousLabs/Sia/api/api.go:146 +0x1ba
created by github.com/NebulousLabs/Sia/api.cleanCloseHandler.func1
	/home/luke/go/src/github.com/NebulousLabs/Sia/api/api.go:148 +0x189
Severe error: api call is taking more than 60 minutes to return: /consensus
goroutine 193935 [running]:
runtime/debug.Stack(0x44439e, 0x0, 0xc04a723e98)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x80
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x29
github.com/NebulousLabs/Sia/build.Severe(0xc04a723f20, 0x2, 0x2)
	/home/luke/go/src/github.com/NebulousLabs/Sia/build/critical.go:32 +0x99
github.com/NebulousLabs/Sia/api.cleanCloseHandler.func1.2(0xc0445c0660, 0xc04c960100)
	/home/luke/go/src/github.com/NebulousLabs/Sia/api/api.go:146 +0x1ba
created by github.com/NebulousLabs/Sia/api.cleanCloseHandler.func1
	/home/luke/go/src/github.com/NebulousLabs/Sia/api/api.go:148 +0x189
Severe error: api call is taking more than 60 minutes to return: /consensus
goroutine 193939 [running]:
runtime/debug.Stack(0x44439e, 0x0, 0xc048b91e98)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x80
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x29
github.com/NebulousLabs/Sia/build.Severe(0xc048b91f20, 0x2, 0x2)
	/home/luke/go/src/github.com/NebulousLabs/Sia/build/critical.go:32 +0x99
github.com/NebulousLabs/Sia/api.cleanCloseHandler.func1.2(0xc042bfcb40, 0xc04c960200)
	/home/luke/go/src/github.com/NebulousLabs/Sia/api/api.go:146 +0x1ba
created by github.com/NebulousLabs/Sia/api.cleanCloseHandler.func1
	/home/luke/go/src/github.com/NebulousLabs/Sia/api/api.go:148 +0x189
Severe error: api call is taking more than 60 minutes to return: /consensus
goroutine 193920 [running]:
runtime/debug.Stack(0x44439e, 0x0, 0xc044b11e98)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x80
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x29
github.com/NebulousLabs/Sia/build.Severe(0xc044b11f20, 0x2, 0x2)
	/home/luke/go/src/github.com/NebulousLabs/Sia/build/critical.go:32 +0x99
github.com/NebulousLabs/Sia/api.cleanCloseHandler.func1.2(0xc049a9cde0, 0xc04487b800)
	/home/luke/go/src/github.com/NebulousLabs/Sia/api/api.go:146 +0x1ba
created by github.com/NebulousLabs/Sia/api.cleanCloseHandler.func1
	/home/luke/go/src/github.com/NebulousLabs/Sia/api/api.go:148 +0x189
Severe error: api call is taking more than 60 minutes to return: /consensus
goroutine 193959 [running]:
runtime/debug.Stack(0x44439e, 0x0, 0xc048b85e98)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x80
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x29
github.com/NebulousLabs/Sia/build.Severe(0xc048b85f20, 0x2, 0x2)
	/home/luke/go/src/github.com/NebulousLabs/Sia/build/critical.go:32 +0x99
github.com/NebulousLabs/Sia/api.cleanCloseHandler.func1.2(0xc0445c0de0, 0xc04487b900)
	/home/luke/go/src/github.com/NebulousLabs/Sia/api/api.go:146 +0x1ba
created by github.com/NebulousLabs/Sia/api.cleanCloseHandler.func1
	/home/luke/go/src/github.com/NebulousLabs/Sia/api/api.go:148 +0x189
Severe error: api call is taking more than 60 minutes to return: /consensus
goroutine 194002 [running]:
runtime/debug.Stack(0x44439e, 0x0, 0xc048b73e98)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x80
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x29
github.com/NebulousLabs/Sia/build.Severe(0xc048b73f20, 0x2, 0x2)
	/home/luke/go/src/github.com/NebulousLabs/Sia/build/critical.go:32 +0x99
github.com/NebulousLabs/Sia/api.cleanCloseHandler.func1.2(0xc049a9d740, 0xc043a7ee00)
	/home/luke/go/src/github.com/NebulousLabs/Sia/api/api.go:146 +0x1ba
created by github.com/NebulousLabs/Sia/api.cleanCloseHandler.func1
	/home/luke/go/src/github.com/NebulousLabs/Sia/api/api.go:148 +0x189
Severe error: api call is taking more than 60 minutes to return: /consensus
goroutine 194018 [running]:
runtime/debug.Stack(0x44439e, 0x0, 0xc04a8e1e98)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x80
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x29
github.com/NebulousLabs/Sia/build.Severe(0xc04a8e1f20, 0x2, 0x2)
	/home/luke/go/src/github.com/NebulousLabs/Sia/build/critical.go:32 +0x99
github.com/NebulousLabs/Sia/api.cleanCloseHandler.func1.2(0xc049a9db00, 0xc043a7f000)
	/home/luke/go/src/github.com/NebulousLabs/Sia/api/api.go:146 +0x1ba
created by github.com/NebulousLabs/Sia/api.cleanCloseHandler.func1
	/home/luke/go/src/github.com/NebulousLabs/Sia/api/api.go:148 +0x189
Severe error: api call is taking more than 60 minutes to return: /consensus
goroutine 194034 [running]:
runtime/debug.Stack(0x44439e, 0x0, 0xc048b77e98)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x80
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x29
github.com/NebulousLabs/Sia/build.Severe(0xc048b77f20, 0x2, 0x2)
	/home/luke/go/src/github.com/NebulousLabs/Sia/build/critical.go:32 +0x99
github.com/NebulousLabs/Sia/api.cleanCloseHandler.func1.2(0xc0441b26c0, 0xc04487b000)
	/home/luke/go/src/github.com/NebulousLabs/Sia/api/api.go:146 +0x1ba
created by github.com/NebulousLabs/Sia/api.cleanCloseHandler.func1
	/home/luke/go/src/github.com/NebulousLabs/Sia/api/api.go:148 +0x189
Severe error: api call is taking more than 60 minutes to return: /consensus
goroutine 194027 [running]:
runtime/debug.Stack(0x44439e, 0x0, 0xc048b83e98)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x80
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x29
github.com/NebulousLabs/Sia/build.Severe(0xc048b83f20, 0x2, 0x2)
	/home/luke/go/src/github.com/NebulousLabs/Sia/build/critical.go:32 +0x99
github.com/NebulousLabs/Sia/api.cleanCloseHandler.func1.2(0xc042bfdda0, 0xc04c960900)
	/home/luke/go/src/github.com/NebulousLabs/Sia/api/api.go:146 +0x1ba
created by github.com/NebulousLabs/Sia/api.cleanCloseHandler.func1
	/home/luke/go/src/github.com/NebulousLabs/Sia/api/api.go:148 +0x189
Severe error: api call is taking more than 60 minutes to return: /consensus
goroutine 194035 [running]:
runtime/debug.Stack(0x44439e, 0x0, 0xc0488e1e98)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x80
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x29
github.com/NebulousLabs/Sia/build.Severe(0xc0488e1f20, 0x2, 0x2)
	/home/luke/go/src/github.com/NebulousLabs/Sia/build/critical.go:32 +0x99
github.com/NebulousLabs/Sia/api.cleanCloseHandler.func1.2(0xc0435f6420, 0xc043a7f400)
	/home/luke/go/src/github.com/NebulousLabs/Sia/api/api.go:146 +0x1ba
created by github.com/NebulousLabs/Sia/api.cleanCloseHandler.func1
	/home/luke/go/src/github.com/NebulousLabs/Sia/api/api.go:148 +0x189
Severe error: api call is taking more than 60 minutes to return: /consensus
goroutine 194048 [running]:
runtime/debug.Stack(0x44439e, 0x0, 0xc04a71fe98)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x80
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x29
github.com/NebulousLabs/Sia/build.Severe(0xc04a71ff20, 0x2, 0x2)
	/home/luke/go/src/github.com/NebulousLabs/Sia/build/critical.go:32 +0x99
github.com/NebulousLabs/Sia/api.cleanCloseHandler.func1.2(0xc0449b0ba0, 0xc048b10000)
	/home/luke/go/src/github.com/NebulousLabs/Sia/api/api.go:146 +0x1ba
created by github.com/NebulousLabs/Sia/api.cleanCloseHandler.func1
	/home/luke/go/src/github.com/NebulousLabs/Sia/api/api.go:148 +0x189
Severe error: api call is taking more than 60 minutes to return: /consensus

**Comment by Wlinc** [comment] 2017-12-13 19:29
@lukechampine I don't know if there were multiple instances running at that time. 

I have some automation in place to open and close the wallet at certain intervals, so it's possible there was some overlap, but I cannot say for sure.

**Comment by tbenz9** [comment] 2018-02-23 18:41
I'm going to go ahead and close this issue.  Sia v1.3.1 and v1.3.2 have several upload enhancements such as the buffered channel.  From Chris: "We introduced a buffered channel 4 days ago that should make the upload endpoint return almost instantly for the first 2500 files."

If you run into this issue after upgrading to v1.3.2 (release due next week) please reopen this issue.  Alternatively if you can provide a clear reproducer we can ensure that the bug is indeed fixed before 1.3.2 officially ships.

**Closed by tbenz9** 2018-02-23 18:41 UTC
Labels: Bug
