### ISSUE TITLE
Upload speed drop with larger files

### ISSUE THREAD

**Issue by keepmote** [NebulousLabs/Sia#2107] opened 2017-07-11 14:24 UTC
Uploading 4 video files causes huge drop in upload speed after 4 hours or so.  I've tested this on multiple systems, with different wallets, on both Mac and PC.  Speed goes from 40mbps to .1mbps.  I gave it several days, and speeds never pick back up.  I've also tried restarting the computer and re-launching Sia, and the speed stay at .1mbps.
![screen shot 2017-07-11 at 9 16 07 am](https://user-images.githubusercontent.com/15126267/28073023-30cc6e76-661a-11e7-9a14-46e77635a6d3.jpg)

**Comment by lukechampine** [comment] 2017-07-28 23:08
duplicate of https://github.com/NebulousLabs/Sia/issues/2040

**Closed by lukechampine** 2017-07-28 23:08 UTC
