### ISSUE TITLE
Sia Crashing on Start

### ISSUE THREAD

**Issue by atomicwheeler** [NebulousLabs/Sia#2615] opened 2018-01-05 23:48 UTC
**Environment**
* Sia version: 1.3.1
* OS:Win 10 64bit

Sia Daemon v1.3.1
Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 3.6542623 seconds
panic: invalid page type: 0: 0

goroutine 10 [running]:
github.com/NebulousLabs/bolt.(*Cursor).search(0xc051712c50, 0xc053528d40, 0x20, 0x20, 0x1a725d)
	/home/luke/go/src/github.com/NebulousLabs/bolt/cursor.go:256 +0x413
github.com/NebulousLabs/bolt.(*Cursor).searchPage(0xc051712c50, 0xc053528d40, 0x20, 0x20, 0x16c52b000)
	/home/luke/go/src/github.com/NebulousLabs/bolt/cursor.go:314 +0x161
github.com/NebulousLabs/bolt.(*Cursor).search(0xc051712c50, 0xc053528d40, 0x20, 0x20, 0xec53b)
	/home/luke/go/src/github.com/NebulousLabs/bolt/cursor.go:271 +0x1a9
github.com/NebulousLabs/bolt.(*Cursor).searchPage(0xc051712c50, 0xc053528d40, 0x20, 0x20, 0x16c797000)
	/home/luke/go/src/github.com/NebulousLabs/bolt/cursor.go:314 +0x161
github.com/NebulousLabs/bolt.(*Cursor).search(0xc051712c50, 0xc053528d40, 0x20, 0x20, 0xec7a7)
	/home/luke/go/src/github.com/NebulousLabs/bolt/cursor.go:271 +0x1a9
github.com/NebulousLabs/bolt.(*Cursor).searchPage(0xc051712c50, 0xc053528d40, 0x20, 0x20, 0x16c9f2000)
	/home/luke/go/src/github.com/NebulousLabs/bolt/cursor.go:314 +0x161
github.com/NebulousLabs/bolt.(*Cursor).search(0xc051712c50, 0xc053528d40, 0x20, 0x20, 0xeca02)
	/home/luke/go/src/github.com/NebulousLabs/bolt/cursor.go:271 +0x1a9
github.com/NebulousLabs/bolt.(*Cursor).seek(0xc051712c50, 0xc053528d40, 0x20, 0x20, 0x0, 0x0, 0xc05533c7f8, 0xde13f0, 0x8, 0x8, ...)
	/home/luke/go/src/github.com/NebulousLabs/bolt/cursor.go:159 +0xb8
github.com/NebulousLabs/bolt.(*Bucket).Get(0xc04837eb80, 0xc053528d40, 0x20, 0x20, 0xde4200, 0xc04837eb80, 0x8cd798)
	/home/luke/go/src/github.com/NebulousLabs/bolt/bucket.go:267 +0xed
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).validateHeaderAndBlock(0xc04221a000, 0xde5880, 0xc05533c7e0, 0x1900000000000000, 0x93f0e84e30b90945, 0x98f426d1ce7ff84, 0x74e1f7d9360f99c9, 0x5c09ee0156972d, 0x5a444fe7, 0xc04a471b80, ...)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/accept.go:46 +0x15e
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).managedAcceptBlocks.func1(0xc05533c7e0, 0xaf16f8, 0xc05533c7e0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/accept.go:248 +0x1ca
github.com/NebulousLabs/bolt.(*DB).Update(0xc0421765a0, 0xc0517132e8, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/bolt/db.go:603 +0xa1
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).managedAcceptBlocks(0xc04221a000, 0xc0484be400, 0xa, 0xa, 0x0, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/accept.go:245 +0x4f9
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).managedReceiveBlocks(0xc04221a000, 0xdee020, 0xc053c640a0, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:225 +0x500
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).(github.com/NebulousLabs/Sia/modules/consensus.managedReceiveBlocks)-fm(0xdee020, 0xc053c640a0, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:445 +0x45
github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).managedRPC(0xc04216c000, 0xc0421d1880, 0x11, 0xac0d00, 0xa, 0xc04628b060, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/rpc.go:66 +0x2c9
github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).RPC(0xc04216c000, 0xc0421d1880, 0x11, 0xac0d00, 0xa, 0xc04628b060, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/rpc.go:76 +0xd8
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).threadedInitialBlockchainDownload.func1(0xc04221a000, 0xc051713ef0, 0xc051713e98, 0xc051713ea0, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:580 +0x12e
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).threadedInitialBlockchainDownload(0xc04221a000, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:601 +0x151
github.com/NebulousLabs/Sia/modules/consensus.New.func1(0x1, 0xc04217a130, 0xc04221a000, 0xdee820, 0xc04216c000)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/consensusset.go:151 +0x3eb
created by github.com/NebulousLabs/Sia/modules/consensus.New
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/consensusset.go:144 +0x656

**Comment by tbenz9** [comment] 2018-01-05 23:52
Duplicate of #2247 

Steps to fix: https://gist.github.com/tbenz9/8066d74853ab28c23bd7bc1d3c7cdeda

**Closed by tbenz9** 2018-01-05 23:52 UTC
