### ISSUE TITLE
siacoin 1.3.0 load ui

### ISSUE THREAD

**Issue by dustydumptruck** [NebulousLabs/Sia#2557] opened 2017-12-19 06:42 UTC
Bug Report
==========
**Stack Trace or error message**
A critical error loading Sia has occured: Siad unexpectedly exited. Error log: Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...

**Environment** 
* Sia version: 1.3.0
* OS: Windows 10 64-bit
Just tried doing a windows update but it failed so had to roll back. I believe the update was Feature update to Windows 10, version 1709.

**Any useful logs**

attached
[sialog.txt](https://github.com/NebulousLabs/Sia/files/1570600/sialog.txt)

**Comment by dustydumptruck** [comment] 2017-12-19 06:44
If I delete my consensus db it opens.

**Comment by tbenz9** [comment] 2017-12-19 17:31
Glad you got it working.  Duplicate of #1799

**Closed by tbenz9** 2017-12-19 17:31 UTC
