### ISSUE TITLE
Siad has exited unexpectedly.

### ISSUE THREAD

**Issue by shorivishal** [NebulousLabs/Sia#1757] opened 2017-05-01 17:20 UTC
Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 1.779312144 seconds

Wallet: scanned to height 91959...
...
Wallet: scanned to height 95298...2017/05/01 22:47:30 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms

Wallet: scanned to height 95322...2017/05/01 22:47:33 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
2017/05/01 22:47:33 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 10ms
2017/05/01 22:47:33 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
2017/05/01 22:47:33 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
2017/05/01 22:47:33 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms

Wallet: scanned to height 95332...2017/05/01 22:47:34 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
2017/05/01 22:47:34 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 10ms
2017/05/01 22:47:34 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 20ms
2017/05/01 22:47:34 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 40ms
2017/05/01 22:47:34 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 80ms
2017/05/01 22:47:34 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
2017/05/01 22:47:34 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 10ms
2017/05/01 22:47:34 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 20ms
2017/05/01 22:47:34 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 40ms
2017/05/01 22:47:34 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 80ms
2017/05/01 22:47:35 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 160ms
2017/05/01 22:47:35 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 320ms
2017/05/01 22:47:35 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 640ms
2017/05/01 22:47:36 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/01 22:47:37 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/01 22:47:38 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
2017/05/01 22:47:38 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
2017/05/01 22:47:38 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
2017/05/01 22:47:38 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
2017/05/01 22:47:38 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
2017/05/01 22:47:38 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
2017/05/01 22:47:38 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 10ms
2017/05/01 22:47:38 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 20ms
2017/05/01 22:47:38 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 40ms
2017/05/01 22:47:38 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 80ms
2017/05/01 22:47:38 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 160ms

Wallet: scanned to height 95350...2017/05/01 22:47:38 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
2017/05/01 22:47:38 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
2017/05/01 22:47:38 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
2017/05/01 22:47:38 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 10ms
2017/05/01 22:47:38 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 20ms
2017/05/01 22:47:38 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 40ms
2017/05/01 22:47:38 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 80ms
2017/05/01 22:47:38 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 160ms
2017/05/01 22:47:38 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 320ms
2017/05/01 22:47:39 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 640ms
2017/05/01 22:47:39 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
2017/05/01 22:47:39 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
2017/05/01 22:47:39 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 10ms
2017/05/01 22:47:39 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 20ms
2017/05/01 22:47:39 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 40ms
2017/05/01 22:47:39 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 80ms
2017/05/01 22:47:39 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 160ms
2017/05/01 22:47:40 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 320ms
2017/05/01 22:47:40 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 640ms
2017/05/01 22:47:41 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s

Wallet: scanned to height 95373...2017/05/01 22:47:42 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/01 22:47:43 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/01 22:47:44 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s

Wallet: scanned to height 95399...2017/05/01 22:47:45 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/01 22:47:46 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/01 22:47:47 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s

Wallet: scanned to height 95428...2017/05/01 22:47:48 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/01 22:47:49 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/01 22:47:50 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
2017/05/01 22:47:50 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
2017/05/01 22:47:50 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
2017/05/01 22:47:50 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 10ms
2017/05/01 22:47:50 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 20ms
2017/05/01 22:47:50 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 40ms
2017/05/01 22:47:50 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 80ms

**Comment by johnathanhowell** [comment] 2017-05-01 17:25
I have an idea why this is happening, Sia-UI is leaking file descriptors because it uses one connection per API request and certain systems (OSX, Fedora) have very low file descriptor limits.

The fix for this is here https://github.com/NebulousLabs/Nodejs-Sia/pull/47 and will be pushed out in the next point release

**Comment by mertimiks** [comment] 2017-05-15 08:51
I ran, ulimit -n 2048, on my terminal and sia wallet is still not working.

**Comment by DavidVorick** [comment] 2017-05-15 12:30
How long does it take until it crashes? Or is it just refusing to start in the first place?

**Comment by mertimiks** [comment] 2017-05-16 09:56
I typed the seed, and wallet prompts that I have to wait several minutes until the wallet is opened, and I wait several minutes, then this bug appeared

**Comment by mertimiks** [comment] 2017-05-16 14:59
This is the error I got when I ran it on Sia's termninal:
```
ulimit -n 2048

Error: unknown command "ulimit" for "/home/........./........./........./Sia-UI-v1.2.1-linux-x64/resources/app/Sia/siac"
Run '/home/........./........./........./Sia-UI-v1.2.1-linux-x64/resources/app/Sia/siac --help' for usage.
```
I also ran ulimit -n 2048 on ubuntu's terminal, and nothing happened.

**Comment by lukechampine** [comment] 2017-05-16 15:35
When you say "nothing happened" do you mean it didn't print anything? That is the expected behavior. Did you try running siad again after that?

**Comment by mertimiks** [comment] 2017-05-16 20:00
I am sending the all screenshots which indicates how I got the error step by step.
![1](https://cloud.githubusercontent.com/assets/19364945/26125620/789f9ac6-3a8b-11e7-96cb-4456a0f92b9a.png)
![2](https://cloud.githubusercontent.com/assets/19364945/26125621/78cb8866-3a8b-11e7-924c-58764c0b258d.png)
![3](https://cloud.githubusercontent.com/assets/19364945/26125622/78cc2f50-3a8b-11e7-9b87-79a20e3c7272.png)

**Comment by lukechampine** [comment] 2017-07-28 21:02
duplicate of #1840

**Closed by lukechampine** 2017-07-28 21:02 UTC
