### ISSUE TITLE
Siad has exited unexpectedly

### ISSUE THREAD

**Issue by antgeo** [NebulousLabs/Sia#2012] opened 2017-06-26 04:09 UTC
Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 1.150301572 seconds

Wallet: scanned to height 3799...
Wallet: scanned to height 5877...
Wallet: scanned to height 8814...
Wallet: scanned to height 9699...
Wallet: scanned to height 10381...
Wallet: scanned to height 13399...
Wallet: scanned to height 15527...
Wallet: scanned to height 18200...
Wallet: scanned to height 20499...
Wallet: scanned to height 22777...
Wallet: scanned to height 23399...
Wallet: scanned to height 26015...
Wallet: scanned to height 26900...
Wallet: scanned to height 28599...
Wallet: scanned to height 30089...
Wallet: scanned to height 32112...
Wallet: scanned to height 33018...
Wallet: scanned to height 33915...
Wallet: scanned to height 34275...
Wallet: scanned to height 34469...
Wallet: scanned to height 34644...
Wallet: scanned to height 34802...
Wallet: scanned to height 34959...
Wallet: scanned to height 35191...
Wallet: scanned to height 35666...
Wallet: scanned to height 36171...
Wallet: scanned to height 36545...
Wallet: scanned to height 36993...
Wallet: scanned to height 37375...
Wallet: scanned to height 37858...
Wallet: scanned to height 38436...
Wallet: scanned to height 38658...
Wallet: scanned to height 38887...
Wallet: scanned to height 39229...
Wallet: scanned to height 39469...
Wallet: scanned to height 39612...
Wallet: scanned to height 39814...
Wallet: scanned to height 40124...
Wallet: scanned to height 40421...
Wallet: scanned to height 40984...
Wallet: scanned to height 41648...
Wallet: scanned to height 41839...
Wallet: scanned to height 42187...
Wallet: scanned to height 42557...
Wallet: scanned to height 43659...
Wallet: scanned to height 44289...
Wallet: scanned to height 44411...
Wallet: scanned to height 44584...
Wallet: scanned to height 44744...
Wallet: scanned to height 44955...
Wallet: scanned to height 45128...
Wallet: scanned to height 45437...
Wallet: scanned to height 45657...
Wallet: scanned to height 46009...
Wallet: scanned to height 46603...
Wallet: scanned to height 47180...
Wallet: scanned to height 47540...
Wallet: scanned to height 47807...
Wallet: scanned to height 48495...
Wallet: scanned to height 49418...
Wallet: scanned to height 50492...
Wallet: scanned to height 50991...
Wallet: scanned to height 51671...
Wallet: scanned to height 52774...
Wallet: scanned to height 53480...
Wallet: scanned to height 54069...
Wallet: scanned to height 54480...
Wallet: scanned to height 55720...
Wallet: scanned to height 56525...
Wallet: scanned to height 57737...
Wallet: scanned to height 59625...
Wallet: scanned to height 60406...
Wallet: scanned to height 60979...
Wallet: scanned to height 61667...
Wallet: scanned to height 62206...
Wallet: scanned to height 62618...
Wallet: scanned to height 63159...
Wallet: scanned to height 63658...
Wallet: scanned to height 64110...
Wallet: scanned to height 64587...
Wallet: scanned to height 65028...
Wallet: scanned to height 65372...
Wallet: scanned to height 65795...
Wallet: scanned to height 66307...
Wallet: scanned to height 66821...
Wallet: scanned to height 67420...
Wallet: scanned to height 67988...
Wallet: scanned to height 68439...
Wallet: scanned to height 68986...
Wallet: scanned to height 69537...
Wallet: scanned to height 70000...
Wallet: scanned to height 70415...
Wallet: scanned to height 70840...
Wallet: scanned to height 71099...
Wallet: scanned to height 71534...
Wallet: scanned to height 72022...
Wallet: scanned to height 72524...
Wallet: scanned to height 72939...
Wallet: scanned to height 73471...
Wallet: scanned to height 73932...
Wallet: scanned to height 74409...
Wallet: scanned to height 74939...
Wallet: scanned to height 75460...
Wallet: scanned to height 75941...
Wallet: scanned to height 76462...
Wallet: scanned to height 76939...
Wallet: scanned to height 77593...
Wallet: scanned to height 78214...
Wallet: scanned to height 78856...
Wallet: scanned to height 79448...
Wallet: scanned to height 79928...
Wallet: scanned to height 80507...
Wallet: scanned to height 81200...
Wallet: scanned to height 81943...
Wallet: scanned to height 82649...
Wallet: scanned to height 83356...
Wallet: scanned to height 84026...
Wallet: scanned to height 84773...
Wallet: scanned to height 85471...
Wallet: scanned to height 86204...
Wallet: scanned to height 86848...
Wallet: scanned to height 87533...
Wallet: scanned to height 88120...
Wallet: scanned to height 88813...
Wallet: scanned to height 89542...
Wallet: scanned to height 90273...
Wallet: scanned to height 91003...
Wallet: scanned to height 91583...
Wallet: scanned to height 92238...
Wallet: scanned to height 92870...
Wallet: scanned to height 93484...
Wallet: scanned to height 94047...
Wallet: scanned to height 94496...
Wallet: scanned to height 95158...
Wallet: scanned to height 95869...
Wallet: scanned to height 96492...
Wallet: scanned to height 96996...
Wallet: scanned to height 97658...
Wallet: scanned to height 98165...
Wallet: scanned to height 98710...
Wallet: scanned to height 99334...
Wallet: scanned to height 99762...
Wallet: scanned to height 100190...
Wallet: scanned to height 100651...
Wallet: scanned to height 101103...
Wallet: scanned to height 101551...
Wallet: scanned to height 101948...
Wallet: scanned to height 102396...
Wallet: scanned to height 102813...
Wallet: scanned to height 103200...
Wallet: scanned to height 103554...
Wallet: scanned to height 103899...
Wallet: scanned to height 104282...
Wallet: scanned to height 104723...
Wallet: scanned to height 105237...
Wallet: scanned to height 105777...
Wallet: scanned to height 106314...
Wallet: scanned to height 106845...
Wallet: scanned to height 107334...
Wallet: scanned to height 107778...
Wallet: scanned to height 108223...
Wallet: scanned to height 108710...
Wallet: scanned to height 109030...
Wallet: scanned to height 109388...
Wallet: scanned to height 109747...
Wallet: scanned to height 110088...
Wallet: scanned to height 110459...
Wallet: scanned to height 110806...
Done!
goroutine 1 [running]:
runtime/debug.Stack(0x1043857, 0x0, 0xc422e155f8)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x79
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/NebulousLabs/Sia/build.Critical(0xc422e15948, 0x1, 0x1)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/build/critical.go:16 +0xa7
main.startDaemon(0x0, 0x0, 0x7fff5fbffcbc, 0xe, 0x7fff5fbffce8, 0x5, 0x7fff5fbffcd7, 0x5, 0x0, 0x7fff5fbffd3f, ...)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/siad/daemon.go:295 +0xaa9
main.startDaemonCmd(0xc420081200, 0xc4200193b0, 0x0, 0x5)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/siad/daemon.go:309 +0x6d
github.com/spf13/cobra.(*Command).execute(0xc420081200, 0xc42000e0d0, 0x5, 0x5, 0xc420081200, 0xc42000e0d0)
	/home/jrh/go/src/github.com/spf13/cobra/command.go:651 +0x23a
github.com/spf13/cobra.(*Command).ExecuteC(0xc420081200, 0x16c7c0f, 0x3b, 0xc420156820)
	/home/jrh/go/src/github.com/spf13/cobra/command.go:726 +0x339
github.com/spf13/cobra.(*Command).Execute(0xc420081200, 0x1aa6520, 0x16b10c0)
	/home/jrh/go/src/github.com/spf13/cobra/command.go:685 +0x2b
main.main()
	/home/jrh/go/src/github.com/NebulousLabs/Sia/siad/main.go:174 +0x79d
Critical error: accept tcp 127.0.0.1:9980: accept: too many open files in system
Please submit a bug report here: https://github.com/NebulousLabs/Sia/issues
Closing renter...
Closing host...
Closing wallet...
Closing transaction pool...
Closing consensus set...
Closing gateway...
Shutdown complete.

**Comment by lukechampine** [comment] 2017-06-26 07:07
duplicate of https://github.com/NebulousLabs/Sia/issues/1840

**Closed by lukechampine** 2017-06-26 07:07 UTC
