### ISSUE TITLE
[Feature] Timestamp added to file api calls i.e. /renter/files [GET]

### ISSUE THREAD

**Issue by sgraves66** [NebulousLabs/Sia#2109] opened 2017-07-11 17:19 UTC
It would be beneficial to receive creation date/time when retrieving file info. I currently have to store/maintain creation times in an external location when implementing FUSE.

**Comment by tbenz9** [comment] 2017-10-12 21:41
recommendation to devs: Tag "feature request" and "programming task"

**Comment by DavidVorick** [comment] 2017-11-29 05:11
Closing as a duplicate of #2479 (though submitted later, the header contains more information)

**Closed by DavidVorick** 2017-11-29 05:11 UTC
Labels: Feature Request
