### ISSUE TITLE
siad crash report

### ISSUE THREAD

**Issue by tlightsky** [NebulousLabs/Sia#2239] opened 2017-08-16 07:28 UTC
```golang
D:\s\sia-win>siad
Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 7.3585774 seconds
panic: invalid page type: 0: 0

goroutine 1310259 [running]:
github.com/NebulousLabs/bolt.(*Cursor).search(0xc0a44366e8, 0xc0a44368b0, 0x20, 0x20, 0x6f82)
        E:/source/go/src/github.com/NebulousLabs/bolt/cursor.go:256 +0x40c
github.com/NebulousLabs/bolt.(*Cursor).searchPage(0xc0a44366e8, 0xc0a44368b0, 0x20, 0x20, 0x8d725000)
        E:/source/go/src/github.com/NebulousLabs/bolt/cursor.go:314 +0x15d
github.com/NebulousLabs/bolt.(*Cursor).search(0xc0a44366e8, 0xc0a44368b0, 0x20, 0x20, 0xd735)
        E:/source/go/src/github.com/NebulousLabs/bolt/cursor.go:271 +0x1c2
github.com/NebulousLabs/bolt.(*Cursor).searchPage(0xc0a44366e8, 0xc0a44368b0, 0x20, 0x20, 0x8e595000)
        E:/source/go/src/github.com/NebulousLabs/bolt/cursor.go:314 +0x15d
github.com/NebulousLabs/bolt.(*Cursor).search(0xc0a44366e8, 0xc0a44368b0, 0x20, 0x20, 0xe5a5)
        E:/source/go/src/github.com/NebulousLabs/bolt/cursor.go:271 +0x1c2
github.com/NebulousLabs/bolt.(*Cursor).searchPage(0xc0a44366e8, 0xc0a44368b0, 0x20, 0x20, 0x11c92c000)
        E:/source/go/src/github.com/NebulousLabs/bolt/cursor.go:314 +0x15d
github.com/NebulousLabs/bolt.(*Cursor).search(0xc0a44366e8, 0xc0a44368b0, 0x20, 0x20, 0x9c93c)
        E:/source/go/src/github.com/NebulousLabs/bolt/cursor.go:271 +0x1c2
github.com/NebulousLabs/bolt.(*Cursor).seek(0xc0a44366e8, 0xc0a44368b0, 0x20, 0x20, 0x0, 0x0, 0x2, 0x6, 0xc1153c4100, 0x2, ...)
        E:/source/go/src/github.com/NebulousLabs/bolt/cursor.go:159 +0xb8
github.com/NebulousLabs/bolt.(*Bucket).Get(0xc08f6c7900, 0xc0a44368b0, 0x20, 0x20, 0x0, 0xc1132acb70, 0x2)
        E:/source/go/src/github.com/NebulousLabs/bolt/bucket.go:267 +0xf6
github.com/NebulousLabs/Sia/modules/consensus.validSiacoins(0xc0455a87e0, 0xc115248a80, 0x23, 0x23, 0xc0db2c0880, 0x1, 0x1, 0x0, 0x0, 0x0, ...)
        E:/source/go/src/github.com/NebulousLabs/Sia/modules/consensus/validtransaction.go:37 +0x193
github.com/NebulousLabs/Sia/modules/consensus.validTransaction(0xc0455a87e0, 0xc115248a80, 0x23, 0x23, 0xc0db2c0880, 0x1, 0x1, 0x0, 0x0, 0x0, ...)
        E:/source/go/src/github.com/NebulousLabs/Sia/modules/consensus/validtransaction.go:297 +0xcc
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).tryTransactionSet.func1(0xc0455a87e0, 0xb0d2f0, 0xc0455a87e0)
        E:/source/go/src/github.com/NebulousLabs/Sia/modules/consensus/validtransaction.go:337 +0x146
github.com/NebulousLabs/bolt.(*DB).Update(0xc042212000, 0xc086606e40, 0x0, 0x0)
        E:/source/go/src/github.com/NebulousLabs/bolt/db.go:603 +0xa6
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).tryTransactionSet(0xc042131b80, 0xc1222981e0, 0x2, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        E:/source/go/src/github.com/NebulousLabs/Sia/modules/consensus/validtransaction.go:344 +0x157
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).(github.com/NebulousLabs/Sia/modules/consensus.tryTransactionSet)-fm(0xc1222981e0, 0x2, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        E:/source/go/src/github.com/NebulousLabs/Sia/modules/consensus/subscribe.go:92 +0x8b
github.com/NebulousLabs/Sia/modules/transactionpool.(*TransactionPool).acceptTransactionSet(0xc042348000, 0xc1222981e0, 0x2, 0x2, 0xc12b4fe870, 0x0, 0xeecd40)
        E:/source/go/src/github.com/NebulousLabs/Sia/modules/transactionpool/accept.go:289 +0x7f3
github.com/NebulousLabs/Sia/modules/transactionpool.(*TransactionPool).AcceptTransactionSet.func1(0xc12b4fe870, 0x0, 0x0)
        E:/source/go/src/github.com/NebulousLabs/Sia/modules/transactionpool/accept.go:337 +0xe5
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).LockedTryTransactionSet(0xc042131b80, 0xc10a92ccc0, 0x0, 0x0)
        E:/source/go/src/github.com/NebulousLabs/Sia/modules/consensus/validtransaction.go:385 +0x122
github.com/NebulousLabs/Sia/modules/transactionpool.(*TransactionPool).AcceptTransactionSet(0xc042348000, 0xc122298000, 0x2, 0x2, 0x1e8480, 0x0)
        E:/source/go/src/github.com/NebulousLabs/Sia/modules/transactionpool/accept.go:345 +0xf2
github.com/NebulousLabs/Sia/modules/transactionpool.(*TransactionPool).relayTransactionSet(0xc042348000, 0xde6200, 0xc12228a3a0, 0x0, 0x0)
        E:/source/go/src/github.com/NebulousLabs/Sia/modules/transactionpool/accept.go:373 +0x23b
github.com/NebulousLabs/Sia/modules/transactionpool.(*TransactionPool).(github.com/NebulousLabs/Sia/modules/transactionpool.relayTransactionSet)-fm(0xde6200, 0xc12228a3a0, 0x29, 0xc0421a3f48)
        E:/source/go/src/github.com/NebulousLabs/Sia/modules/transactionpool/transactionpool.go:107 +0x45
github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).threadedHandleConn(0xc04206ac60, 0xde6200, 0xc12228a3a0)
        E:/source/go/src/github.com/NebulousLabs/Sia/modules/gateway/rpc.go:220 +0x3cb
created by github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).threadedListenPeer
        E:/source/go/src/github.com/NebulousLabs/Sia/modules/gateway/rpc.go:180 +0x2f1
```

**Comment by tlightsky** [comment] 2017-08-16 07:30
D:\s\sia-win>siad
Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 1.2500271 seconds
panic: invalid page type: 0: 0

goroutine 50 [running]:
github.com/NebulousLabs/bolt.(*Cursor).search(0xc044436528, 0xc0444366f0, 0x20, 0x20, 0x6f82)
        /home/luke/go/src/github.com/NebulousLabs/bolt/cursor.go:256 +0x40c
github.com/NebulousLabs/bolt.(*Cursor).searchPage(0xc044436528, 0xc0444366f0, 0x20, 0x20, 0x8d725000)
        /home/luke/go/src/github.com/NebulousLabs/bolt/cursor.go:314 +0x15d
github.com/NebulousLabs/bolt.(*Cursor).search(0xc044436528, 0xc0444366f0, 0x20, 0x20, 0xd735)
        /home/luke/go/src/github.com/NebulousLabs/bolt/cursor.go:271 +0x1c2
github.com/NebulousLabs/bolt.(*Cursor).searchNode(0xc044436528, 0xc0444366f0, 0x20, 0x20, 0xc044d8b730)
        /home/luke/go/src/github.com/NebulousLabs/bolt/cursor.go:291 +0x12b
github.com/NebulousLabs/bolt.(*Cursor).search(0xc044436528, 0xc0444366f0, 0x20, 0x20, 0xe5a5)
        /home/luke/go/src/github.com/NebulousLabs/bolt/cursor.go:268 +0x17d
github.com/NebulousLabs/bolt.(*Cursor).searchNode(0xc044436528, 0xc0444366f0, 0x20, 0x20, 0xc044d8b340)
        /home/luke/go/src/github.com/NebulousLabs/bolt/cursor.go:291 +0x12b
github.com/NebulousLabs/bolt.(*Cursor).search(0xc044436528, 0xc0444366f0, 0x20, 0x20, 0x9c93c)
        /home/luke/go/src/github.com/NebulousLabs/bolt/cursor.go:268 +0x17d
github.com/NebulousLabs/bolt.(*Cursor).seek(0xc044436528, 0xc0444366f0, 0x20, 0x20, 0x0, 0x0, 0x2, 0x6, 0xc044019780, 0x2, ...)
        /home/luke/go/src/github.com/NebulousLabs/bolt/cursor.go:159 +0xb8
github.com/NebulousLabs/bolt.(*Bucket).Get(0xc044397e00, 0xc0444366f0, 0x20, 0x20, 0x0, 0xc044abc840, 0x2)
        /home/luke/go/src/github.com/NebulousLabs/bolt/bucket.go:267 +0xf6
github.com/NebulousLabs/Sia/modules/consensus.validSiacoins(0xc044849340, 0xc04370f500, 0x23, 0x23, 0xc045176f00, 0x1, 0x1, 0x0, 0x0, 0x0, ...)
        /home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/validtransaction.go:37 +0x193
github.com/NebulousLabs/Sia/modules/consensus.validTransaction(0xc044849340, 0xc04370f500, 0x23, 0x23, 0xc045176f00, 0x1, 0x1, 0x0, 0x0, 0x0, ...)
        /home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/validtransaction.go:297 +0xcc
github.com/NebulousLabs/Sia/modules/consensus.generateAndApplyDiff(0xc044849340, 0xc048ee89a0, 0xc0443ab720, 0x2)
        /home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/diffs.go:220 +0x124
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).applyUntilBlock(0xc042113b80, 0xc044849340, 0xc048ee89a0, 0x0, 0x0, 0x0, 0x7e01000000000000, 0x6e44d45cdd493be1)
        /home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/fork.go:84 +0x244
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).forkBlockchain(0xc042113b80, 0xc044849340, 0xc048ee89a0, 0x3800000000000000, 0x1e553db4d683ce4d, 0x517c539519186f02, 0x174883a52dc20ca6, 0xa3370a2301bac30d, 0x59939934, 0xc043c94ac0, ...)
        /home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/fork.go:111 +0xb3
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).addBlockToTree(0xc042113b80, 0xc044849340, 0x3800000000000000, 0x1e553db4d683ce4d, 0x517c539519186f02, 0x174883a52dc20ca6, 0xa3370a2301bac30d, 0x59939934, 0xc043c94ac0, 0x1, ...)
        /home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/accept.go:164 +0x114
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).managedAcceptBlocks.func1(0xc044849340, 0xb0b570, 0xc044849340)
        /home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/accept.go:262 +0x23a
github.com/NebulousLabs/bolt.(*DB).Update(0xc0420e0780, 0xc0445bd2e8, 0x0, 0x0)
        /home/luke/go/src/github.com/NebulousLabs/bolt/db.go:603 +0xa6
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).managedAcceptBlocks(0xc042113b80, 0xc04202b400, 0xa, 0xa, 0x0, 0x0, 0x0)
        /home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/accept.go:283 +0x520
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).managedReceiveBlocks(0xc042113b80, 0xde41c0, 0xc0467aa040, 0x0, 0x0)
        /home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:225 +0x5be
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).(github.com/NebulousLabs/Sia/modules/consensus.managedReceiveBlocks)-fm(0xde41c0, 0xc0467aa040, 0x0, 0x0)
        /home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:445 +0x45
github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).managedRPC(0xc042058c60, 0xc04217fac0, 0x11, 0xaddb78, 0xa, 0xc04a0c8000, 0x0, 0x0)
        /home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/rpc.go:66 +0x339
github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).RPC(0xc042058c60, 0xc04217fac0, 0x11, 0xaddb78, 0xa, 0xc04a0c8000, 0x0, 0x0)
        /home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/rpc.go:76 +0xd8
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).threadedInitialBlockchainDownload.func1(0xc042113b80, 0xc044437ef0, 0xc044437eb0, 0xc044437eb8, 0x0, 0x0)
        /home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:580 +0x133
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).threadedInitialBlockchainDownload(0xc042113b80, 0x0, 0x0)
        /home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:601 +0x30e
github.com/NebulousLabs/Sia/modules/consensus.New.func1(0x1, 0xc04220c9f0, 0xc042113b80, 0xde4440, 0xc042058c60)
        /home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/consensusset.go:151 +0x404
created by github.com/NebulousLabs/Sia/modules/consensus.New
        /home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/consensusset.go:182 +0x641


switch to v1.3.0 with no luck

**Comment by tlightsky** [comment] 2017-08-16 07:43
```golang
D:\s\sia-win>siad
Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
Closing consensus...
Closing gateway...
panic: assertion failed: tx closed

goroutine 1 [running]:
github.com/NebulousLabs/bolt._assert(0xc04245f100, 0xadba96, 0x9, 0x0, 0x0, 0x0)
        /home/luke/go/src/github.com/NebulousLabs/bolt/db.go:1034 +0xfd
github.com/NebulousLabs/bolt.(*Cursor).Next(0xc04245f1d8, 0x20, 0x20, 0xfa11490, 0x0, 0x0, 0x0)
        /home/luke/go/src/github.com/NebulousLabs/bolt/cursor.go:74 +0x76
github.com/NebulousLabs/bolt.(*Bucket).ForEach(0xc0423b20c0, 0xc04245f290, 0x15, 0x15)
        /home/luke/go/src/github.com/NebulousLabs/bolt/bucket.go:389 +0x123
github.com/NebulousLabs/bolt.(*Bucket).DeleteBucket(0xc0421640f8, 0xdd81e0, 0x15, 0x15, 0xee9fe0, 0xdcc6b4)
        /home/luke/go/src/github.com/NebulousLabs/bolt/bucket.go:244 +0x205
github.com/NebulousLabs/bolt.(*Tx).DeleteBucket(0xc0421640e0, 0xdd81e0, 0x15, 0x15, 0xc0422ce140, 0x43)
        /home/luke/go/src/github.com/NebulousLabs/bolt/tx.go:121 +0x56
github.com/NebulousLabs/Sia/modules/transactionpool.(*TransactionPool).resetDB(0xc042446420, 0xc0421640e0, 0x1, 0x1)
        /home/luke/go/src/github.com/NebulousLabs/Sia/modules/transactionpool/persist.go:67 +0x5a
github.com/NebulousLabs/Sia/modules/transactionpool.(*TransactionPool).initPersist(0xc042446420, 0xc042446420, 0xc0423b61e0)
        /home/luke/go/src/github.com/NebulousLabs/Sia/modules/transactionpool/persist.go:188 +0xb44
github.com/NebulousLabs/Sia/modules/transactionpool.New(0xde5060, 0xc0421e0000, 0xde4440, 0xc042166000, 0xae3ef1, 0xf, 0x0, 0x0, 0x0)
        /home/luke/go/src/github.com/NebulousLabs/Sia/modules/transactionpool/transactionpool.go:101 +0x27d
main.startDaemon(0x0, 0x0, 0xae3132, 0xe, 0xad2392, 0x5, 0xad2397, 0x5, 0x0, 0xad4d6a, ...)
        /home/luke/go/src/github.com/NebulousLabs/Sia/siad/daemon.go:202 +0x169a
main.startDaemonCmd(0xc042065200, 0xf06bb0, 0x0, 0x0)
        /home/luke/go/src/github.com/NebulousLabs/Sia/siad/daemon.go:335 +0x169
github.com/spf13/cobra.(*Command).execute(0xc042065200, 0xc0420081f0, 0x0, 0x0, 0xc042065200, 0xc0420081f0)
        /home/luke/go/src/github.com/spf13/cobra/command.go:653 +0x2a0
github.com/spf13/cobra.(*Command).ExecuteC(0xc042065200, 0xb002aa, 0x3b, 0xc04212c820)
        /home/luke/go/src/github.com/spf13/cobra/command.go:728 +0x340
github.com/spf13/cobra.(*Command).Execute(0xc042065200, 0xeea320, 0xae8452)
        /home/luke/go/src/github.com/spf13/cobra/command.go:687 +0x32
main.main()
        /home/luke/go/src/github.com/NebulousLabs/Sia/siad/main.go:174 +0x7b1
```
after restore consensus.db, still have some problem

**Comment by tbenz9** [comment] 2017-10-17 18:23
Duplicate of #2247 

Recommendation to Devs: close

**Closed** 2017-10-17 20:21 UTC
