### ISSUE TITLE
SIA keeps Closing on Mac Part 2 ...

### ISSUE THREAD

**Issue by taiwil** [NebulousLabs/Sia#2894] opened 2018-03-20 13:38 UTC
Although I was given direct info how to fix the issue, I can't seem to permanently increase the number of ~n files.  I sign is administrator on my terminal and yet, it still says i don't have permission.  I can increase the numbers temporarily, but, i still have SIA shutting down and showing me the same error.   

I tried to run sysctl -w kern.maxfiles=20480 in Terminal for a Permanent increase in Max Files...It says I don't have permission.  

THIS IS the REPORT i get back From Terminal as TO what is running:
Wils-Main-Computer:~ admin$ sudo lsof -n | cut -f1 -d' ' | uniq -c | sort | tail
Password:
 189 Bitcoin-Q
 198 Spotlight
 199 iconservi
 269 siad
 283 Vertcoin-
 460 mds_store
 662 firefox
 683 plugin-co
1711 plugin-co
2136 Electron

This is the report i get from terminal AFTER i increase the file numbers ~n
Wils-Main-Computer:~ admin$ ulimit -a
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
file size               (blocks, -f) unlimited
max locked memory       (kbytes, -l) unlimited
max memory size         (kbytes, -m) unlimited

# open files                     #  *_*(-n) 2048**_    THIS IS INCREASED FROM 256 !!!!!!
pipe size            (512 bytes, -p) 1

stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 709
virtual memory          (kbytes, -v) unlimited
# BUG REPORT
Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 20.690603834 seconds

Wallet: scanned to height 146296...
Wallet: scanned to height 146296...
Wallet: scanned to height 146296...
Wallet: scanned to height 146296...
Wallet: scanned to height 146296...
Wallet: scanned to height 146296...
Wallet: scanned to height 146296...
Wallet: scanned to height 146296...
Wallet: scanned to height 146296...
Wallet: scanned to height 146296...
Wallet: scanned to height 146296...
Done!
goroutine 1 [running]:
runtime/debug.Stack(0x1045ec7, 0x0, 0xc420273948)
/usr/local/go/src/runtime/debug/stack.go:24 +0xa7
runtime/debug.PrintStack()
/usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/NebulousLabs/Sia/build.Critical(0xc420273ac8, 0x1, 0x1)
/home/luke/go/src/github.com/NebulousLabs/Sia/build/critical.go:16 +0x93
main.startDaemon(0x0, 0x0, 0x7fff5fbffd53, 0xe, 0x7fff5fbffd7f, 0x5, 0x7fff5fbffd6e, 0x5, 0x0, 0x7fff5fbffdd3, ...)
/home/luke/go/src/github.com/NebulousLabs/Sia/cmd/siad/daemon.go:212 +0x588
main.startDaemonCmd(0xc4200acfc0, 0xc42007e550, 0x0, 0x5)
/home/luke/go/src/github.com/NebulousLabs/Sia/cmd/siad/daemon.go:236 +0x162
github.com/spf13/cobra.(*Command).execute(0xc4200acfc0, 0xc42000e0d0, 0x5, 0x5, 0xc4200acfc0, 0xc42000e0d0)
/home/luke/go/src/github.com/spf13/cobra/command.go:750 +0x2c1
github.com/spf13/cobra.(*Command).ExecuteC(0xc4200acfc0, 0x16e1b17, 0x3b, 0xc420099a40)
/home/luke/go/src/github.com/spf13/cobra/command.go:831 +0x30e
github.com/spf13/cobra.(*Command).Execute(0xc4200acfc0, 0x1b0a200, 0x16ca346)
/home/luke/go/src/github.com/spf13/cobra/command.go:784 +0x2b
main.main()
/home/luke/go/src/github.com/NebulousLabs/Sia/cmd/siad/main.go:174 +0x790
Critical error: accept tcp 127.0.0.1:9980: accept: too many open files in system
Please submit a bug report here: https://github.com/NebulousLabs/Sia/issues
Shutdown complete.
**Stack Trace or error message**

**Expected Behavior**
Randomly SIA SHUTS DOWN.  
**How to reproduce it (as minimally and precisely as possible)**
Not SURE how to Reproduce it ...

**Environment**
* Sia version:1.3.2
* OS:10.11.6
@tbenz9

**Comment by tbenz9** [comment] 2018-03-28 20:57
From what you've provided this looks like an issue with Sia-UI and the bug report probably belongs in the Sia-UI repo.  Duplicate of https://github.com/NebulousLabs/Sia-UI/issues/670

If you need help getting past the issue I recommend you ask in the #help channel on Discord.

**Closed by tbenz9** 2018-03-28 20:57 UTC
