### ISSUE TITLE
Siad has exited unexpectedly

### ISSUE THREAD

**Issue by dedamrazdeda** [NebulousLabs/Sia#2648] opened 2018-01-11 20:25 UTC
# BUG REPORT

Sia Daemon v1.3.1
Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 1.5647155000000001 seconds
panic: page 10537 already freed

goroutine 28 [running]:
github.com/NebulousLabs/bolt.(*freelist).free(0xc0421b88d0, 0x14a, 0x475b9000)
	/home/luke/go/src/github.com/NebulousLabs/bolt/freelist.go:121 +0x308
github.com/NebulousLabs/bolt.(*node).spill(0xc0421210a0, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/bolt/node.go:363 +0x217
github.com/NebulousLabs/bolt.(*node).spill(0xc0487570a0, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/bolt/node.go:350 +0xc6
github.com/NebulousLabs/bolt.(*node).spill(0xc048f28c40, 0xc0455fe140, 0xdeaa80)
	/home/luke/go/src/github.com/NebulousLabs/bolt/node.go:350 +0xc6
github.com/NebulousLabs/bolt.(*node).spill(0xc048f28540, 0xc042204840, 0xc04594da18)
	/home/luke/go/src/github.com/NebulousLabs/bolt/node.go:350 +0xc6
github.com/NebulousLabs/bolt.(*Bucket).spill(0xc045b5cf00, 0xc04594db00, 0x9)
	/home/luke/go/src/github.com/NebulousLabs/bolt/bucket.go:570 +0x4da
github.com/NebulousLabs/bolt.(*Bucket).spill(0xc048a93438, 0x39330b1fb4, 0xefca20)
	/home/luke/go/src/github.com/NebulousLabs/bolt/bucket.go:537 +0x41e
github.com/NebulousLabs/bolt.(*Tx).Commit(0xc048a93420, 0x2, 0x2)
	/home/luke/go/src/github.com/NebulousLabs/bolt/tx.go:163 +0x130
github.com/NebulousLabs/Sia/modules/transactionpool.(*TransactionPool).syncDB(0xc0420c2f20)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/transactionpool/persist.go:54 +0x4e
github.com/NebulousLabs/Sia/modules/transactionpool.(*TransactionPool).threadedRegularSync(0xc0420c2f20)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/transactionpool/persist.go:44 +0xbd
created by github.com/NebulousLabs/Sia/modules/transactionpool.(*TransactionPool).initPersist
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/transactionpool/persist.go:132 +0x3ae

* Sia version:  v1.3.1
* OS: Windows 10

**Comment by tbenz9** [comment] 2018-01-12 18:52
Duplicate of #2413

**Closed by tbenz9** 2018-01-12 18:52 UTC
