### ISSUE TITLE
Siac complaints

### ISSUE THREAD

**Issue by lukechampine** [NebulousLabs/Sia#1128] opened 2016-05-02 18:30 UTC
- [ ] `siac renter setallowance` should use days/months instead of blocks
- [ ] `siac wallet send` should tell you how much it spent on transaction fees.
- [x] `siac hostdb` should have an `add` command that lets you manually add a host to your db. This would require a new API call, though, so it's lower priority.
- [x] `siac hostdb` should display prices in TB/month, not GB/month
- [x] `siac host config minimumstorageprice` does not convert months to blocks

**Comment by DavidVorick** [comment] 2016-05-06 19:39
I can add another to this list. The renter info displays what appears to be incorrect information for `Total Allocated` and `Unspent Funds`. After setting an allowance of 5 KS, the total allocated will be some multiple of that.

Based on the wallet's behavior, I believe the problem is with the siac units and not with the renter actually allocating too much money. But the problem potentially is that the renter is allocating too much money.

**Comment by DavidVorick** [comment] 2016-05-06 19:53
oh, also we definitely need to fix the parts of `siac` that don't work on Windows, the big one is that you currently can't use the path `C:\stuff` because the api is expecting a leading slash. It might be simple enough to just add a leading slash, but maybe not.

**Comment by DavidVorick** [comment] 2016-07-02 06:59
closing this for now, improving siac is going to be an iterative process and some of the things mentioned here may require expanding the api

**Closed by DavidVorick** 2016-07-02 06:59 UTC
Labels: ready
