### ISSUE TITLE
Crash in AppVeyor: panic: Critical error: action item queued improperly

### ISSUE THREAD

**Issue by starius** [NebulousLabs/Sia#2387] opened 2017-10-02 22:49 UTC
https://ci.appveyor.com/project/lukechampine/sia/build/320#L235

```
panic: Critical error: action item queued improperly
Please submit a bug report here: https://github.com/NebulousLabs/Sia/issues
goroutine 29623 [running]:
github.com/NebulousLabs/Sia/build.Critical(0xc04319f408, 0x1, 0x1)
	c:/GOPATH/src/github.com/NebulousLabs/Sia/build/critical.go:20 +0xd5
github.com/NebulousLabs/Sia/persist.(*Logger).Critical(0xc0422ac820, 0xc04319f408, 0x1, 0x1)
	c:/GOPATH/src/github.com/NebulousLabs/Sia/persist/log.go:37 +0x126
github.com/NebulousLabs/Sia/modules/host.(*Host).queueActionItem(0xc042286b00, 0x1b, 0x7dcc5f76acc240c1, 0x450647a3f310acc8, 0x5b43fa0a6c5d59ea, 0x3403a57af5b9b32f, 0x0, 0x0)
	c:/GOPATH/src/github.com/NebulousLabs/Sia/modules/host/storageobligations.go:290 +0x1d6
github.com/NebulousLabs/Sia/modules/host.(*Host).managedAddStorageObligation(0xc042286b00, 0xc042b44200, 0x1, 0x4, 0x0, 0xc04207a540, 0x2, 0x7, 0x0, 0xc042e68d50, ...)
	c:/GOPATH/src/github.com/NebulousLabs/Sia/modules/host/storageobligations.go:407 +0x5cd
github.com/NebulousLabs/Sia/modules/host.(*Host).managedFinalizeContract.func2(0xc0431a02c0, 0xc042286b00, 0xc0431a0990, 0x116e6e0, 0xc042d2a000, 0x0, 0x0)
	c:/GOPATH/src/github.com/NebulousLabs/Sia/modules/host/negotiate.go:252 +0xb7
github.com/NebulousLabs/Sia/modules/host.(*Host).managedFinalizeContract(0xc042286b00, 0x116e6e0, 0xc042d2a000, 0xfd538a41fcbdafcc, 0x99b2d9e4bf73e636, 0x6437157d54884919, 0xa6bde912e0425d6e, 0xc042e7ab40, 0x1, 0x1, ...)
	c:/GOPATH/src/github.com/NebulousLabs/Sia/modules/host/negotiate.go:267 +0xce6
github.com/NebulousLabs/Sia/modules/host.(*Host).managedRPCRenewContract(0xc042286b00, 0x116cf60, 0xc042f487a0, 0x0, 0x0)
	c:/GOPATH/src/github.com/NebulousLabs/Sia/modules/host/negotiaterenewcontract.go:189 +0x10d5
github.com/NebulousLabs/Sia/modules/host.(*Host).threadedHandleConn(0xc042286b00, 0x116cf60, 0xc042f487a0)
	c:/GOPATH/src/github.com/NebulousLabs/Sia/modules/host/network.go:286 +0x11c5
created by github.com/NebulousLabs/Sia/modules/host.(*Host).threadedListen
	c:/GOPATH/src/github.com/NebulousLabs/Sia/modules/host/network.go:322 +0xf3
FAIL	github.com/NebulousLabs/Sia/api	217.711s
```

**Comment by starius** [comment] 2017-10-21 20:02
add "Bug" Label

**Comment by tbenz9** [comment] 2018-03-14 21:38
I'm going to close this, I haven't been able to reproduce the bug and appveyor seems to have intermittent false positives with the test suite.  Testing locally seems to be more reliable in the case where AppVeyor fails.

**Closed by tbenz9** 2018-03-14 21:38 UTC
Labels: Bug
