### ISSUE TITLE
Issues running Sia across different users on MacOs

### ISSUE THREAD

**Issue by TacoByte** [NebulousLabs/Sia#1796] opened 2017-05-15 10:07 UTC
Sia 1.2.1
MacOs 10.12.4

I created a new user on my computer and tried running Sia. I get the following error message at launch:

```
A JavaScript error occurred in the main process

Uncaught Exception:
Error: EACCES: permission denied, open '/Applications/Sia-UI.app/Contents/Resources/app/config.json'
    at Object.fs.openSync (fs.js:558:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:173:20)
    at Object.fs.writeFileSync (fs.js:1233:33)
    at Object.e.save (/Applications/Sia-UI.app/Contents/Resources/app/dist/main.js:1:10793)
    at o (/Applications/Sia-UI.app/Contents/Resources/app/dist/main.js:1:10888)
    at Object.0 (/Applications/Sia-UI.app/Contents/Resources/app/dist/main.js:1:525)
    at e (/Applications/Sia-UI.app/Contents/Resources/app/dist/main.js:1:262)
    at t.0.t.__esModule.default (/Applications/Sia-UI.app/Contents/Resources/app/dist/main.js:1:349)
    at Object.<anonymous> (/Applications/Sia-UI.app/Contents/Resources/app/dist/main.js:1:354)
    at Object.<anonymous> (/Applications/Sia-UI.app/Contents/Resources/app/dist/main.js:2:3)
```

Reinstalling Sia on the new user environment fixes it.

However, now I get this same error on the original user. It seems that I have to keep reinstalling Sia every time I switch user sessions.

**Comment by johnathanhowell** [comment] 2017-05-15 16:33
This will be fixed in the upcoming release due to changes to where `config.json` is located, but different users will still have entirely different Sia data directories. This is by design, but unfortunately means that each user will have to sync their own copy of the blockchain.

**Comment by vitaliy-kuzmich** [comment] 2017-06-26 07:05
A JavaScript error occurred in the main process
Uncaught Exception:
Error: ENOENT: no such file or directory, open '/home/user/.config/Sia-UI/config.json'

had this exception when run from different folder then ~ on linix.

**Closed** 2017-07-28 21:12 UTC
