### ISSUE TITLE
Siad has exited unexpectedly, still no updates?

### ISSUE THREAD

**Issue by mertimiks** [NebulousLabs/Sia#1809] opened 2017-05-18 10:27 UTC
Still I am getting the same bug when I try to access my wallet. My all blocks are synecd, and I am using Ubuntu. This is the error message I got: Siad has exited unexpectedly. Please submit a bug report including the error log here. Screenshots are uploaded below for illustration.
![789f9ac6-3a8b-11e7-96cb-4456a0f92b9a](https://cloud.githubusercontent.com/assets/19364945/26198133/99070ffe-3bcd-11e7-9e8a-707b2c3c639d.png)
![78cb8866-3a8b-11e7-924c-58764c0b258d](https://cloud.githubusercontent.com/assets/19364945/26198139/9d8eac30-3bcd-11e7-82d7-e46968b2860d.png)
![78cc2f50-3a8b-11e7-9b87-79a20e3c7272](https://cloud.githubusercontent.com/assets/19364945/26198143/a181b13e-3bcd-11e7-8bc3-d553750caab0.png)

**Comment by johnathanhowell** [comment] 2017-05-18 16:45
This was fixed in the latest master a few weeks ago and will be pushed out in the next release (v1.2.2). We released a beta releaes candidate last night, you can download that here: https://pixeldra.in/api/getfile/K5c1px

I'm closing this issue because it's a duplicate of #1757.

**Closed by johnathanhowell** 2017-05-18 16:45 UTC
