### ISSUE TITLE
siad constantly crashing after a few minutes

### ISSUE THREAD

**Issue by Flowdalic** [NebulousLabs/Sia#2118] opened 2017-07-12 07:23 UTC
I'm running siad build from 9ab6692ae568292b3093bccbcd6cad1217773b23 (latest master), but unfortunately it does constantly crash after a few minutes. Here is the log

```
Sia.service: Service hold-off time over, scheduling restart.
Sia.service: Failed with result 'exit-code'.
Sia.service: Unit entered failed state.
Sia.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
        /var/tmp/portage/net-p2p/Sia-9999/work/Sia-9999/src/github.com/NebulousLabs/Sia/modules/consensus/consensusset.go:182 +0x63a
created by github.com/NebulousLabs/Sia/modules/consensus.New
        /var/tmp/portage/net-p2p/Sia-9999/work/Sia-9999/src/github.com/NebulousLabs/Sia/modules/consensus/consensusset.go:151 +0x3fd
github.com/NebulousLabs/Sia/modules/consensus.New.func1(0x1, 0xc42030cb70, 0xc420151b80, 0xdcd780, 0xc42008b1e0)
        /var/tmp/portage/net-p2p/Sia-9999/work/Sia-9999/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:604 +0x307
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).threadedInitialBlockchainDownload(0xc420151b80, 0x0, 0x0)
        /var/tmp/portage/net-p2p/Sia-9999/work/Sia-9999/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:578 +0x12c
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).threadedInitialBlockchainDownload.func1(0xc420151b80, 0xc420411ef0, 0xc420411eb0, 0xc420411eb8, 0x0, 0x0)
        /var/tmp/portage/net-p2p/Sia-9999/work/Sia-9999/src/github.com/NebulousLabs/Sia/modules/gateway/rpc.go:69 +0xd1
github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).RPC(0xc42008b1e0, 0xc4201e2e00, 0x11, 0xac6525, 0xa, 0xc420c821e0, 0x0, 0x0)
        /var/tmp/portage/net-p2p/Sia-9999/work/Sia-9999/src/github.com/NebulousLabs/Sia/modules/gateway/rpc.go:59 +0x319
github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).managedRPC(0xc42008b1e0, 0xc4201e2e00, 0x11, 0xac6525, 0xa, 0xc420c821e0, 0x0, 0x0)
        /var/tmp/portage/net-p2p/Sia-9999/work/Sia-9999/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:434 +0x3e
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).(github.com/NebulousLabs/Sia/modules/consensus.managedReceiveBlocks)-fm(0xdcd500, 0xc4204e4300, 0x0, 0x0)
        /var/tmp/portage/net-p2p/Sia-9999/work/Sia-9999/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:216 +0x5b7
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).managedReceiveBlocks(0xc420151b80, 0xdcd500, 0xc4204e4300, 0x0, 0x0)
        /var/tmp/portage/net-p2p/Sia-9999/work/Sia-9999/src/github.com/NebulousLabs/Sia/modules/consensus/accept.go:282 +0x519
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).managedAcceptBlocks(0xc420151b80, 0xc4211bc400, 0xa, 0xa, 0x0, 0x0, 0x0)
        /var/tmp/portage/net-p2p/Sia-9999/work/Sia-9999/src/github.com/NebulousLabs/bolt/db.go:598 +0x9f
github.com/NebulousLabs/bolt.(*DB).Update(0xc42011e780, 0xc42181b328, 0x0, 0x0)
        /var/tmp/portage/net-p2p/Sia-9999/work/Sia-9999/src/github.com/NebulousLabs/Sia/modules/consensus/accept.go:261 +0x233
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).managedAcceptBlocks.func1(0xc4210b2000, 0xaf2cd8, 0xc4210b2000)
        /var/tmp/portage/net-p2p/Sia-9999/work/Sia-9999/src/github.com/NebulousLabs/Sia/modules/consensus/accept.go:150 +0x9c
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).addBlockToTree(0xc420151b80, 0xc4210b2000, 0x4e00000000000000, 0xf7281393cbbb60be, 0x8e931da2c45d8683, 0xcf51d7b161e5ca91, 0x2339003804912f81, 0x59635635, 0xc42107b900, 0x1, ...)
        /var/tmp/portage/net-p2p/Sia-9999/work/Sia-9999/src/github.com/NebulousLabs/Sia/modules/consensus/processedblock.go:135 +0x1a1
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).newChild(0xc420151b80, 0xc4210b2000, 0xc42008a840, 0x4e00000000000000, 0xf7281393cbbb60be, 0x8e931da2c45d8683, 0xcf51d7b161e5ca91, 0x2339003804912f81, 0x59635635, 0xc42107b900, ...)
        /var/tmp/portage/net-p2p/Sia-9999/work/Sia-9999/src/github.com/NebulousLabs/Sia/modules/consensus/difficulty.go:120 +0x134
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).getBlockTotals(0xc420151b80, 0xc4210b2000, 0x4e00000000000000, 0xf7281393cbbb60be, 0x8e931da2c45d8683, 0xcf51d7b161e5ca91, 0xc42107b900, 0x0, 0x0, 0x0, ...)
goroutine 30 [running]:
panic: runtime error: slice bounds out of range

```

**Comment by lukechampine** [comment] 2017-07-12 14:54
@DavidVorick looks like an empty bolt entry: https://github.com/NebulousLabs/Sia/blob/master/modules/consensus/difficulty.go#L120

**Comment by Flowdalic** [comment] 2017-07-21 10:31
Let me know if I can help you fixing this issue. Right now, I had to shut down my siad instance hosting a few contracts.

**Comment by lukechampine** [comment] 2017-07-28 23:19
duplicate of #2183.

**Closed by lukechampine** 2017-07-28 23:19 UTC
