### ISSUE TITLE
High DPC while sync

### ISSUE THREAD

**Issue by HelFixCZ** [NebulousLabs/Sia#1705] opened 2017-04-15 20:10 UTC
Hello, 
when i running sia 1.2.0 (synchronization) my sound start crackling/lagging. I checked with LatencyMon and i getting very high numbers.

7k+ µs peaks

My system:
OS version: Windows 10 , 10.0, build: 15063 (x64)
Hardware: MS-7693, MSI, 970A-G43 (MS-7693)
CPU: AuthenticAMD AMD FX(tm)-6300 Six-Core Processor 
RAM: 8140 MB total
HDD: Samsung SSD 840 EVO 120GB

**Comment by DavidVorick** [comment] 2017-04-16 02:24
That is pretty amusing. Sia is very heavy on Disk I/O, you can fix the crackling by increasing the amount of buffering that your audio player does. I'm guessing it's set low enough (like 32kb or less) that it needs to go to disk multiple times per second.

This is not really a Sia problem, your audio player should be able to function while your disk is under load.

**Comment by DavidVorick** [comment] 2017-04-16 02:27
Also, it should stop once syncing is complete.

But also, the disk I/O stuff comes from calling fsync, which really shouldn't affect your audio performance at all (because an fsync takes time but the disk is not busy during that time). Are you sure it's not just a coincidence?

**Comment by HelFixCZ** [comment] 2017-04-16 02:45
No, right after i start sia that cracklink will also start and ssd seems like 20% performance (about write 10MB/s), i even tried to run some disk benchmarks but everythink was ok seems i can't reprodce that same situation like with sia.

**Comment by DavidVorick** [comment] 2017-04-16 21:16
That's just really strange. I don't know what we would be doing that would be more punishing than disk benchmarks. We only use standard file calls.

**Comment by gowithplanb** [comment] 2017-04-21 22:28
@DavidVorick Could this be the result of IRQ sharing/IRQ resources depletion or possible lack of resources available for enough sound buffering due to the forced syncs (fsync)? Calling fsync requires the OS to flush any disk buffers physically to the disk before continuing and synchronization can stress that perhaps more than regular benchmarks? Is it necessary to do the fsyncs or could this also be left to the OS to do it at a slightly more efficient moment?

**Comment by lukechampine** [comment] 2017-04-21 23:52
it's true that we do a lot of `fsync`ing. In particular, when downloading the blockchain, there can be multiple `fsync`s per block. Ideally we could disable `fsync` during the initial blockchain download, or at least reduce it. (We have indeed made efforts to reduce `fsync`ing in the wallet and transaction pool.) Some `fsync`s are unavoidable though.

**Comment by trecchia** [comment] 2017-06-03 22:30
Having this exact same issue. Brand new, just built Ryzen 7/MSI x370 machine. As soon as I launch Sia the distortion and crackling begins.

**Comment by lukechampine** [comment] 2017-07-28 20:56
Closing for now since we can't reproduce locally. If the root cause can be identified, maybe we can fix this, but it's more likely to be a bug in electron than siad.

**Closed by lukechampine** 2017-07-28 20:56 UTC
