### ISSUE TITLE
SIA UX won't sync , shows Synchronized at lower block

### ISSUE THREAD

**Issue by MichelSakr** [NebulousLabs/Sia#2751] opened 2018-02-08 22:41 UTC
<img width="336" alt="screen shot 2018-02-08 at 5 35 29 pm" src="https://user-images.githubusercontent.com/33501576/36002567-9efc6498-0cf8-11e8-869c-392dac349dd2.png">

# BUG REPORT

**Stack Trace or error message**
No error -- Consensus message

Synced: Yes
Block:      0000000000000000a6782e0d2135824d8a805a77bd3ce4a6f55c208df9c2db31
Height:     139885
Target:     [0 0 0 0 0 0 0 1 135 86 149 82 119 137 176 210 32 156 155 79 149 249 127 113 128 109 31 95 96 119 227 226]
Difficulty: 12067225458940426763

Gateway peers connected, tried with different peers (over 20 from https://siastats.info/nodes.html ) not synching still
Not a firewall issue as tried through different Networks on of which was working previously.
**Expected Behavior**
Consensus should be at block 140912, however App shows Synchronized at block 139885
**How to reproduce it (as minimally and precisely as possible)**
Not applicable
**Environment**
* Sia version: 1.3.1
* OS: Mac OSX 10.13.3

**Comment by ChrisSchinnerl** [comment] 2018-02-09 13:58
Thanks for the report. We are aware of that issue and are currently working on a fix. The problem is that the database we use (boltdb) is unable to retrieve an object that was inserted into the database. That causes the next block to be invalid and stops the consensus set from syncing.
For now the only workaround is a fresh install with a complete resync of the blockchain.

**Comment by MichelSakr** [comment] 2018-02-09 14:06
Hi
Thanks, or the way I did and it worked to download the latest consensus db

**Comment by tbenz9** [comment] 2018-02-16 20:11
Closing this as the devs are currently working on a fix, and the Sia team recently posted a workaround on Discord.
https://medium.com/@sia_steve/sia-support-update-transactions-and-syncing-52dad5858711

**Closed by tbenz9** 2018-02-16 20:11 UTC
