### ISSUE TITLE
Crash related to ContractManager/AddSectorBatch/sectorupdate

### ISSUE THREAD

**Issue by cryptagoras** [NebulousLabs/Sia#2337] opened 2017-09-19 12:10 UTC
I've had my node running and renting space fine for over 3 months, updated to 1.3.0 when it got released.

A week or so ago I got the first crash of this kind, I restarted the node and got the same error very soon after.

```
goroutine 984648 [runnable]:
syscall.Syscall6(0x12, 0x11, 0xc424a48820, 0xe, 0x34ec64, 0x0, 0x0, 0xe, 0xe, 0x0)
        /usr/local/go/src/syscall/asm_linux_amd64.s:44 +0x5
syscall.Pwrite(0x11, 0xc424a48820, 0xe, 0xe, 0x34ec64, 0xc43f03ec00, 0x7f79dc235960, 0x0)
        /usr/local/go/src/syscall/zsyscall_linux_amd64.go:1389 +0x77
os.(*File).pwrite(0xc42000e008, 0xc424a48820, 0xe, 0xe, 0x34ec64, 0x9ea920, 0xc43ed23b01, 0xc424a48820)
        /usr/local/go/src/os/file_unix.go:212 +0x59
os.(*File).WriteAt(0xc42000e008, 0xc424a48820, 0xe, 0xe, 0x34ec64, 0xe, 0x3, 0xc43ed23c20)
        /usr/local/go/src/os/file.go:166 +0xb3
github.com/NebulousLabs/Sia/modules/host/contractmanager.writeSectorMetadata(0xde2540, 0xc42000e008, 0x562287f0003c7be, 0x5d6802d93238ac39, 0xc422d00002, 0x0, 0x0)
        /home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/sector.go:103 +0x106
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).writeSectorMetadata(0xc420248308, 0xc4200d9200, 0x562287f7a500002, 0x5d6802d93238ac39, 0x3c7be, 0x0, 0x0)
        /home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/sectorupdate.go:358 +0x77
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).managedAddVirtualSector(0xc420248308, 0x3238ac390562287f, 0x3c7be5d6802d9, 0xc400027a50, 0x19ec81485d680201, 0x3238ac390562287f)
        /home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/sectorupdate.go:199 +0x328
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*ContractManager).AddSectorBatch.func1(0xc427b27100, 0xc420248240, 0xa82fd7cb62f7f363, 0x12717ea29d268e88, 0x1ea74b8baf4b922, 0x19ec81480bb22ef9)
        /home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/sectorupdate.go:429 +0x1f5
created by github.com/NebulousLabs/Sia/modules/host/contractmanager.(*ContractManager).AddSectorBatch
        /home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/sectorupdate.go:431 +0x196

goroutine 984649 [runnable]:
syscall.Syscall6(0x12, 0x11, 0xc424a48780, 0xe, 0xaa86d8, 0x0, 0x0, 0xe, 0xe, 0x0)
        /usr/local/go/src/syscall/asm_linux_amd64.s:44 +0x5
syscall.Pwrite(0x11, 0xc424a48780, 0xe, 0xe, 0xaa86d8, 0xc43eddf400, 0x7f79dc235960, 0x0)
        /usr/local/go/src/syscall/zsyscall_linux_amd64.go:1389 +0x77
os.(*File).pwrite(0xc42000e008, 0xc424a48780, 0xe, 0xe, 0xaa86d8, 0x9ea920, 0xc43ed39b01, 0xc424a48780)
        /usr/local/go/src/os/file_unix.go:212 +0x59
os.(*File).WriteAt(0xc42000e008, 0xc424a48780, 0xe, 0xe, 0xaa86d8, 0xe, 0x3, 0xc43ed39c20)
        /usr/local/go/src/os/file.go:166 +0xb3
github.com/NebulousLabs/Sia/modules/host/contractmanager.writeSectorMetadata(0xde2540, 0xc42000e008, 0x291b7576000c2e34, 0x494802654c063034, 0xc422d00002, 0x0, 0x0)
        /home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/sector.go:103 +0x106
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).writeSectorMetadata(0xc420248308, 0xc4200d9200, 0x291b75767a500002, 0x494802654c063034, 0xc2e34, 0x0, 0x0)
        /home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/sectorupdate.go:358 +0x77
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).managedAddVirtualSector(0xc420248308, 0x4c063034291b7576, 0xc2e3449480265, 0xc400027a50, 0xe4cc84f249480201, 0x4c063034291b7576)
        /home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/sectorupdate.go:199 +0x328
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*ContractManager).AddSectorBatch.func1(0xc427b27100, 0xc420248240, 0x6b9383ec36d50fb8, 0x4e68d86c45405f5f, 0xd37493324aa002cb, 0xe4cc84f21cbbc152)
        /home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/sectorupdate.go:429 +0x1f5
created by github.com/NebulousLabs/Sia/modules/host/contractmanager.(*ContractManager).AddSectorBatch
        /home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/sectorupdate.go:431 +0x196

goroutine 984650 [runnable]:
syscall.Syscall6(0x12, 0x11, 0xc420c9f5a0, 0xe, 0x83df4, 0x0, 0x0, 0xe, 0xe, 0x0)
        /usr/local/go/src/syscall/asm_linux_amd64.s:44 +0x5
syscall.Pwrite(0x11, 0xc420c9f5a0, 0xe, 0xe, 0x83df4, 0xc44118a400, 0x7f79dc236c20, 0x0)
        /usr/local/go/src/syscall/zsyscall_linux_amd64.go:1389 +0x77
os.(*File).pwrite(0xc42000e008, 0xc420c9f5a0, 0xe, 0xe, 0x83df4, 0x9ea920, 0xc43a213b01, 0xc420c9f5a0)
        /usr/local/go/src/os/file_unix.go:212 +0x59
os.(*File).WriteAt(0xc42000e008, 0xc420c9f5a0, 0xe, 0xe, 0x83df4, 0xe, 0x3, 0xc43a213c20)
        /usr/local/go/src/os/file.go:166 +0xb3
github.com/NebulousLabs/Sia/modules/host/contractmanager.writeSectorMetadata(0xde2540, 0xc42000e008, 0xd543db25000096b6, 0x635509fdf08ccd21, 0xc422d00002, 0x0, 0x0)
        /home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/sector.go:103 +0x106
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).writeSectorMetadata(0xc420248308, 0xc4200d9200, 0xd543db257a500002, 0x635509fdf08ccd21, 0x96b6, 0x0, 0x0)
        /home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/sectorupdate.go:358 +0x77
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).managedAddVirtualSector(0xc420248308, 0xf08ccd21d543db25, 0x96b6635509fd, 0xc400027a50, 0x125f0be563550901, 0xf08ccd21d543db25)
        /home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/sectorupdate.go:199 +0x328
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*ContractManager).AddSectorBatch.func1(0xc427b27100, 0xc420248240, 0xab4adf54cf9563b0, 0x54627b69f202e538, 0x9cc6cc591ef98556, 0x125f0be5a87c45e6)
        /home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/sectorupdate.go:429 +0x1f5
created by github.com/NebulousLabs/Sia/modules/host/contractmanager.(*ContractManager).AddSectorBatch
        /home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/sectorupdate.go:431 +0x196
```

Any ideas?

**Comment by tbenz9** [comment] 2017-10-17 03:00
I'm no expert but this looks like a pretty low level crash.  This could be caused by out of space issues, or RAM errors, or a bad kernel.  Have you been able to reproduce the crash?  Are other processes on your machine acting up?

**Comment by lukechampine** [comment] 2017-10-17 20:04
this stack trace doesn't include the actual error, so this isn't actionable unless you have a full trace saved somewhere. Closing for now; will reopen if the full log is posted

**Closed by lukechampine** 2017-10-17 20:04 UTC
