### ISSUE TITLE
Some crashes during first blockchain scanning

### ISSUE THREAD

**Issue by EO2** [NebulousLabs/Sia#2890] opened 2018-03-18 22:55 UTC
Sia app on osx 10.13.3
Started friday, so a bit slow on this lowspec macmini. 
A few crashes along the way.
Gives errors, shown in text box in main app. (pasted below)
Its hard to see if it stalls, since the % indicator is moving slowly and has no info on process/network.
Had to turn it off a few times, cause it stalled the system a bit. 

Got it going again after manually terminating a sia process from terminal.
Seems to be running fine now. 88.8% Almost there - looks good! :)

# BUG REPORT

**Stack Trace or error message**

**Expected Behavior**

**How to reproduce it (as minimally and precisely as possible)**

**Environment**
* Sia version:
* OS:

------------------------
Sia Daemon v1.3.2
Git Revision 72938f5
Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 43.011208925 seconds
panic: Consensus change series appears to be inconsistent - we are applying the wrong block.

goroutine 18 [running]:
github.com/NebulousLabs/Sia/modules/transactionpool.(*TransactionPool).ProcessConsensusChange(0xc420278160, 0xd93b19dff2b6814c, 0xa77aaec7111fa20c, 0xd9df97d8cdd46997, 0x52d239164ff45056, 0x0, 0x0, 0x0, 0xc425672ba0, 0x1, ...)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/transactionpool/update.go:223 +0x2b61
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).updateSubscribers(0xc4200bbb80, 0x0, 0x0, 0x0, 0xc428dec740, 0x1, 0x1)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/subscribe.go:118 +0x178
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).managedAcceptBlocks(0xc4200bbb80, 0xc424f04800, 0xa, 0xa, 0x0, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/accept.go:311 +0x617
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).managedReceiveBlocks(0xc4200bbb80, 0x19fb800, 0xc42125bd20, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:225 +0x4f9
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).(github.com/NebulousLabs/Sia/modules/consensus.managedReceiveBlocks)-fm(0x19fb800, 0xc42125bd20, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:445 +0x3e
github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).managedRPC(0xc4200b29a0, 0xc4201ba940, 0x12, 0x16c0900, 0xa, 0xc42015e500, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/rpc.go:66 +0x2c2
github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).RPC(0xc4200b29a0, 0xc4201ba940, 0x12, 0x16c0900, 0xa, 0xc42015e500, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/rpc.go:76 +0xd1
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).threadedInitialBlockchainDownload.func1(0xc4200bbb80, 0xc422c63ef0, 0xc422c63e98, 0xc422c63ea0, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:580 +0x127
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).threadedInitialBlockchainDownload(0xc4200bbb80, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:601 +0x14a
github.com/NebulousLabs/Sia/modules/consensus.New.func1(0x1, 0xc42015e5e0, 0xc4200bbb80, 0x19fbf00, 0xc4200b29a0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/consensusset.go:151 +0x3e4
created by github.com/NebulousLabs/Sia/modules/consensus.New
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/consensusset.go:144 +0x64f

**Comment by Bojak4616** [comment] 2018-03-19 01:53
Looks like the same issue as https://github.com/NebulousLabs/Sia/issues/2885 try restarting and then resycning the blockchain if necessary

**Comment by tbenz9** [comment] 2018-03-19 17:10
Duplicate of #2867

**Closed by tbenz9** 2018-03-19 17:10 UTC
