### ISSUE TITLE
the problem with the wallet sia

### ISSUE THREAD

**Issue by sherhan05** [NebulousLabs/Sia#2889] opened 2018-03-18 17:39 UTC
# BUG REPORT

**Stack Trace or error message**

**Expected Behavior**

**How to reproduce it (as minimally and precisely as possible)**

**Environment**
* Sia version:
* OS:
![img_2546](https://user-images.githubusercontent.com/37513182/37568860-05f0ce4e-2aec-11e8-8052-6c38a068d2ce.JPG)
Hello. after updating the SIA IU wallet, it is impossible to enter the program for several days. what could be the reason? photo attach

**Comment by Bojak4616** [comment] 2018-03-18 20:00
Can you provide a little more information? How did you do the upgrade? Are you on a HDD? It could take quite some time if you don't have an SSD to rescan the blockchain

**Comment by sherhan05** [comment] 2018-03-18 20:14
5 days ago I downloaded the wallet from the official website version 1.3.1. Then I registered my wallet and started synchronization. after 2 days, I downloaded the update through my wallet, then removed the old version and launched a new one, since then I have nothing changed. yesterday I tried to remove everything from the computer and download again, in the end it turned out the same. I have a HDD. I attach a photo in the applicationThank you for not ignoring my problem 18.03.2018, 21:00, "Jesse B" <notifications@github.com>:Can you provide a little more information? How did you do the upgrade? Are you on a HDD? It could take quite some time if you don't have an SSD to rescan the blockchain—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by sherhan05** [comment] 2018-03-18 20:21
only that appeared here is such window
![img_2550](https://user-images.githubusercontent.com/37513182/37570629-085ff4ea-2b03-11e8-9b36-13faf1d3ac88.JPG)

**Comment by Bojak4616** [comment] 2018-03-18 20:28
You might have to resync the blockchain. Stop Sia completely then go to `Users\<user>\appdata\roaming\Sia-UI\sia\` and look for the folder that says `consensus` go ahead and delete `consensus.db`.  Then start Sia again and it should begin resyncing the blockchain, this could take a bit. 

For a quicker sync you can follow this guide: https://siawiki.tech/daemon/bootstrapping_the_blockchain

**Comment by sherhan05** [comment] 2018-03-18 20:37
I don't have those files anymore. When I uninstalled the program probably deleted this folder
![img_2551](https://user-images.githubusercontent.com/37513182/37570785-3b10b148-2b05-11e8-80c0-1d43dea0df93.JPG)

**Comment by sherhan05** [comment] 2018-03-18 20:41
![img_2552](https://user-images.githubusercontent.com/37513182/37570830-d05b31ce-2b05-11e8-8006-97f44091f8b7.JPG)

**Comment by sherhan05** [comment] 2018-03-18 20:43
in my computer file there is no "consensus" even no where

**Comment by sherhan05** [comment] 2018-03-18 20:49
I you responded in github 18.03.2018, 21:28, "Jesse B" <notifications@github.com>:You might have to resync the blockchain. Stop Sia completely then go to Users\<user>\appdata\roaming\Sia-UI\sia\ and look for the folder that says consensus go ahead and delete consensus.db. Then start Sia again and it should begin resyncing the blockchain, this could take a bit.For a quicker sync you can follow this guide: https://siawiki.tech/daemon/bootstrapping_the_blockchain—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by sherhan05** [comment] 2018-03-18 20:50
in my computer file there is no "consensus" even no where 18.03.2018, 21:28, "Jesse B" <notifications@github.com>:You might have to resync the blockchain. Stop Sia completely then go to Users\<user>\appdata\roaming\Sia-UI\sia\ and look for the folder that says consensus go ahead and delete consensus.db. Then start Sia again and it should begin resyncing the blockchain, this could take a bit.For a quicker sync you can follow this guide: https://siawiki.tech/daemon/bootstrapping_the_blockchain—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by Bojak4616** [comment] 2018-03-19 01:52
Sounds like your best bet is to reinstall everything from scratch. Try that

**Comment by sherhan05** [comment] 2018-03-19 07:18
the problem is, I've done it a few times and nothing's changed. I completely deleted all sia files, then re-downloaded from the official site. And after window updates and weighs a very long time 19.03.2018, 02:52, "Jesse B" <notifications@github.com>:Sounds like your best bet is to reinstall everything from scratch. Try that—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by tbenz9** [comment] 2018-03-19 17:14
Duplicate of #2867 

If you need help deleting the consensus or reinstalling Sia please join the Sia Discord server.  Double check that you have "how hidden files" enabled when trying to browse to the Sia config files.  Instructions here: https://support.microsoft.com/en-us/help/14201/windows-show-hidden-files

**Closed by tbenz9** 2018-03-19 17:14 UTC

**Comment by sherhan05** [comment] 2018-03-20 06:47
I looked through all the hidden folders. there's nothing there either 19.03.2018, 18:15, "Thomas Bennett" <notifications@github.com>:Duplicate of #2867If you need help deleting the consensus or reinstalling Sia please join the Sia Discord server. Double check that you have "how hidden files" enabled when trying to browse to the Sia config files. Instructions here: https://support.microsoft.com/en-us/help/14201/windows-show-hidden-files—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by sherhan05** [comment] 2018-03-20 06:49
почему закрыли мой вопрос? у меня проблема не ушла
