### ISSUE TITLE
Error Log

### ISSUE THREAD

**Issue by lvoids** [NebulousLabs/Sia#2495] opened 2017-11-27 14:05 UTC
Bug Report
==========
Check to see if a bug report already exists.  If you still want to create a new issue please include the information below.

Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 1.1680668 seconds
panic: page 41351 already freed

goroutine 15 [running]:
github.com/NebulousLabs/bolt.(*freelist).free(0xc0421b8900, 0x26c, 0xcdf7000)
	/home/luke/go/src/github.com/NebulousLabs/bolt/freelist.go:121 +0x2a1
github.com/NebulousLabs/bolt.(*node).spill(0xc0441ee380, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/bolt/node.go:363 +0x1e7
github.com/NebulousLabs/bolt.(*node).spill(0xc04202e3f0, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/bolt/node.go:350 +0xbb
github.com/NebulousLabs/bolt.(*node).spill(0xc04202e070, 0xc0421b8c00, 0xc042353a28)
	/home/luke/go/src/github.com/NebulousLabs/bolt/node.go:350 +0xbb
github.com/NebulousLabs/bolt.(*Bucket).spill(0xc042128980, 0xc042353b00, 0x15)
	/home/luke/go/src/github.com/NebulousLabs/bolt/bucket.go:570 +0x182
github.com/NebulousLabs/bolt.(*Bucket).spill(0xc0420d4a98, 0x3ac10a40, 0xee9fe0)
	/home/luke/go/src/github.com/NebulousLabs/bolt/bucket.go:537 +0x8ff
github.com/NebulousLabs/bolt.(*Tx).Commit(0xc0420d4a80, 0xc0421e2ea0, 0xc042353e80)
	/home/luke/go/src/github.com/NebulousLabs/bolt/tx.go:163 +0x12c
github.com/NebulousLabs/Sia/modules/transactionpool.(*TransactionPool).syncDB(0xc042057340)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/transactionpool/persist.go:54 +0x4e
github.com/NebulousLabs/Sia/modules/transactionpool.(*TransactionPool).threadedRegularSync(0xc042057340)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/transactionpool/persist.go:44 +0x17e
created by github.com/NebulousLabs/Sia/modules/transactionpool.(*TransactionPool).initPersist
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/transactionpool/persist.go:126 +0x3f6

![sshot-1](https://user-images.githubusercontent.com/16975238/33270594-8bdc7b40-d3bf-11e7-9328-8c53b715e55f.png)

**Environment**
* Sia version: Sia-UI-v1.3.0-win32-x64
* OS: win7 64bit

**Any useful logs**

![sshot-1](https://user-images.githubusercontent.com/16975238/33270626-a47b7976-d3bf-11e7-9e62-c47b745edb1b.png)

Feature Request
===============
Check to see if the feature is on the roadmap.  If it is not on the roadmap then clearly describe your feature request and why it would benefit Sia.

[Sia roadmap](https://trello.com/b/Io1dDyuI/sia-public-roadmap)

**Comment by tbenz9** [comment] 2017-11-27 17:25
This looks like a duplicate of #2413.  

Recommendation to devs: Close.

**Closed** 2017-11-27 19:21 UTC
