### ISSUE TITLE
Siad has exited unexpectedly.

### ISSUE THREAD

**Issue by gabayim** [NebulousLabs/Sia#2905] opened 2018-03-25 17:51 UTC
# BUG REPORT
Sia Daemon v1.3.2
Git Revision 72938f5
Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 3.6152068 seconds
panic: bolt.DB.meta(): invalid meta pages
	panic: bolt.DB.meta(): invalid meta pages

goroutine 49 [running]:
github.com/NebulousLabs/Sia/vendor/github.com/coreos/bbolt.(*DB).meta(0xc0420632c0, 0xdc8)
	/home/luke/go/src/github.com/NebulousLabs/Sia/vendor/github.com/coreos/bbolt/db.go:894 +0xc9
github.com/NebulousLabs/Sia/vendor/github.com/coreos/bbolt.(*Tx).rollback(0xc044b30000)
	/home/luke/go/src/github.com/NebulousLabs/Sia/vendor/github.com/coreos/bbolt/tx.go:267 +0x88
github.com/NebulousLabs/Sia/vendor/github.com/coreos/bbolt.(*DB).Update.func1(0xc044b30000)
	/home/luke/go/src/github.com/NebulousLabs/Sia/vendor/github.com/coreos/bbolt/db.go:665 +0x45
panic(0x9dd9c0, 0xb5fb10)
	/usr/local/go/src/runtime/panic.go:491 +0x291
github.com/NebulousLabs/Sia/vendor/github.com/coreos/bbolt.(*DB).meta(0xc0420632c0, 0xdc8)
	/home/luke/go/src/github.com/NebulousLabs/Sia/vendor/github.com/coreos/bbolt/db.go:894 +0xc9
github.com/NebulousLabs/Sia/vendor/github.com/coreos/bbolt.(*Tx).rollback(0xc044b30000)
	/home/luke/go/src/github.com/NebulousLabs/Sia/vendor/github.com/coreos/bbolt/tx.go:267 +0x88
github.com/NebulousLabs/Sia/vendor/github.com/coreos/bbolt.(*Tx).Commit(0xc044b30000, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/vendor/github.com/coreos/bbolt/tx.go:161 +0x5fe
github.com/NebulousLabs/Sia/vendor/github.com/coreos/bbolt.(*DB).Update(0xc0420632c0, 0xc0429592f8, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/vendor/github.com/coreos/bbolt/db.go:680 +0xf9
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).managedAcceptBlocks(0xc0420bbb80, 0xc046286400, 0xa, 0xa, 0x0, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/accept.go:244 +0x424
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).managedReceiveBlocks(0xc0420bbb80, 0xdf80e0, 0xc047734ea0, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:225 +0x500
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).(github.com/NebulousLabs/Sia/modules/consensus.managedReceiveBlocks)-fm(0xdf80e0, 0xc047734ea0, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:445 +0x45
github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).managedRPC(0xc0420aec60, 0xc04200b400, 0x12, 0xac7049, 0xa, 0xc047dac3f0, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/rpc.go:66 +0x2c9
github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).RPC(0xc0420aec60, 0xc04200b400, 0x12, 0xac7049, 0xa, 0xc047dac3f0, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/rpc.go:76 +0xd8
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).threadedInitialBlockchainDownload.func1(0xc0420bbb80, 0xc042959ef0, 0xc042959e98, 0xc042959ea0, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:580 +0x12e
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).threadedInitialBlockchainDownload(0xc0420bbb80, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:601 +0x151
github.com/NebulousLabs/Sia/modules/consensus.New.func1(0x1, 0xc042146500, 0xc0420bbb80, 0xdf87e0, 0xc0420aec60)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/consensusset.go:151 +0x3eb
created by github.com/NebulousLabs/Sia/modules/consensus.New
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/consensusset.go:144 +0x656

**Stack Trace or error message**

**Expected Behavior**

**How to reproduce it (as minimally and precisely as possible)**

**Environment**
* Sia version:
* OS:

**Comment by acdop100** [comment] 2018-03-27 17:54
This happens to me as well. I am trying to use Sia w/ Duplicati and while Duplicati is running through it's "Verifying backup files..." I will get this error at some at seemingly random times.

**Comment by tbenz9** [comment] 2018-03-27 23:53
Duplicate of #2318 

Follow these steps for a workaround: https://gist.github.com/tbenz9/8066d74853ab28c23bd7bc1d3c7cdeda

**Closed by tbenz9** 2018-03-27 23:53 UTC

**Comment by tbenz9** [comment] 2018-03-27 23:54
@lukechampine this does appear to be the first time I've seen this reported on v1.3.2.  It's possible the consensus was bad before 1.3.2. but I don't think we can assume this issue is fixed with the new bbolt implementation yet.
