### ISSUE TITLE
Bug Report ---- erors !!!!

### ISSUE THREAD

**Issue by BARUCHER777** [NebulousLabs/Sia#2489] opened 2017-11-25 09:15 UTC
Bug Report ---- erors !!!!
[wallet.log](https://github.com/NebulousLabs/Sia/files/1502939/wallet.log)

**Environment**
* Sia version: -----  1.3.0
* OS:  ---- Win 10 64-bit

[Sia roadmap](https://trello.com/b/Io1dDyuI/sia-public-roadmap)
![sia-error321](https://user-images.githubusercontent.com/18327150/33229119-947d9e7e-d1d9-11e7-87b4-3d7ba6bd4dfe.jpg)
![sia-errors123](https://user-images.githubusercontent.com/18327150/33229121-9a3158c4-d1d9-11e7-9efc-5acc425cb19e.jpg)
[host.log](https://github.com/NebulousLabs/Sia/files/1502938/host.log)
[gateway.log](https://github.com/NebulousLabs/Sia/files/1502940/gateway.log)
[siad-output.log](https://github.com/NebulousLabs/Sia/files/1502941/siad-output.log)

**Comment by BARUCHER777** [comment] 2017-11-25 09:28
Please dear developers fix these problems! .... or explain how to fix them yourself!

**Comment by tbenz9** [comment] 2017-11-26 17:42
This looks like a duplicate of #1605.

Recommendation to devs: Close as duplicate.

**Closed** 2017-11-27 19:21 UTC
