### ISSUE TITLE
Siad has exited unexpectedly

### ISSUE THREAD

**Issue by jaeheller** [NebulousLabs/Sia#1756] opened 2017-05-01 01:13 UTC
Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 0.091603734 seconds

**Comment by jaeheller** [comment] 2017-05-01 01:36
Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 1.161026418 seconds
goroutine 3571 [running]:
runtime/debug.Stack(0x10437e7, 0x0, 0xc42022fc80)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x79
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/NebulousLabs/Sia/build.Severe(0xc42022fe78, 0x2, 0x2)
	/home/luke/go/src/github.com/NebulousLabs/Sia/build/critical.go:29 +0x92
github.com/NebulousLabs/Sia/persist.(*Logger).Severe(0xc42000a320, 0xc42022fe78, 0x2, 0x2)
	/home/luke/go/src/github.com/NebulousLabs/Sia/persist/log.go:71 +0xe0
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).commit.func2(0xc422e52e80, 0xc42008a668, 0x0, 0x0, 0x0, 0x1ac0ed0, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:190 +0x236
created by github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).commit
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:203 +0x1e5
goroutine 3570 [running]:
runtime/debug.Stack(0x10437e7, 0x0, 0xc42022dd68)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x79
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/NebulousLabs/Sia/build.Severe(0xc42022dec0, 0x2, 0x2)
	/home/luke/go/src/github.com/NebulousLabs/Sia/build/critical.go:29 +0x92
github.com/NebulousLabs/Sia/persist.(*Logger).Severe(0xc42000a320, 0xc42022dec0, 0x2, 0x2)
	/home/luke/go/src/github.com/NebulousLabs/Sia/persist/log.go:71 +0xe0
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).commit.func1(0xc422e52e80, 0xc42008a668)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:161 +0x227
created by github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).commit
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:178 +0x15d
Severe error: Unable to open temporary settings file for writing: open /Users/jeaJeanineninehellerHeller/Library/Application Support/Sia-UI/sia/host/contractmanager/contractmanager.json_temp: no space left on device
Severe error: ERROR: unable to create write-ahead-log: open /Users/jeaJeanineninehellerHeller/Library/Application Support/Sia-UI/sia/host/contractmanager/contractmanager.wal_temp: no space left on device
goroutine 3571 [running]:
runtime/debug.Stack(0x10437e7, 0x0, 0xc42022fc80)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x79
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/NebulousLabs/Sia/build.Severe(0xc42022fe58, 0x2, 0x2)
	/home/luke/go/src/github.com/NebulousLabs/Sia/build/critical.go:29 +0x92
github.com/NebulousLabs/Sia/persist.(*Logger).Severe(0xc42000a320, 0xc42022fe58, 0x2, 0x2)
	/home/luke/go/src/github.com/NebulousLabs/Sia/persist/log.go:71 +0xe0
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).commit.func2(0xc422e52e80, 0xc42008a668, 0x0, 0x0, 0x0, 0x1ac0ed0, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:195 +0x357
created by github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).commit
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:203 +0x1e5
Severe error: Unable to properly initialize WAL file, crashing to prevent corruption: unable to write WAL metadata: invalid argument
goroutine 3571 [running]:
runtime/debug.Stack(0x10437e7, 0x0, 0xc42022faa0)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x79
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/NebulousLabs/Sia/build.Severe(0xc42022fc18, 0x2, 0x2)
	/home/luke/go/src/github.com/NebulousLabs/Sia/build/critical.go:29 +0x92
github.com/NebulousLabs/Sia/persist.(*Logger).Severe(0xc42000a320, 0xc42022fc18, 0x2, 0x2)
	/home/luke/go/src/g

**Comment by lukechampine** [comment] 2017-05-06 01:48
duplicate of #1761

**Closed by lukechampine** 2017-05-06 01:48 UTC
