### ISSUE TITLE
active contracts count not updating in Sia UI and also not in Sia Terminal

### ISSUE THREAD

**Issue by cycleworm** [NebulousLabs/Sia#1751] opened 2017-04-28 19:41 UTC
I am using Sia UI 1.2.1 on my 2 hosts. also siad in the background is already 1.2.1. 
Both machines are on Windows 10 64 Bit. 

What i have experienced in the latest version is that the number of active contracts in the 
Sia UI and in the terminal output "host -v" is not updated proberly. 

Here you can see 665 active contracts in Sia UI.
![grafik](https://cloud.githubusercontent.com/assets/493769/25544339/4e393588-2c5a-11e7-80f6-7ac08844b04c.png)

Here you can see 665 active contracts in Sia terminal (host -v)
![grafik](https://cloud.githubusercontent.com/assets/493769/25544455/d161bc50-2c5a-11e7-80ce-17927fdea2a8.png)

But what i can see in the terminal output is that i have new "FormContract Call". So i think the 
number of active contracts should be updated. 

After i restart Sia UI the active contracts count gets updated in the UI and also in the Sia
Terminal output (host -v)
![grafik](https://cloud.githubusercontent.com/assets/493769/25544581/5dd83812-2c5b-11e7-91d2-24d910fbaaba.png)

![grafik](https://cloud.githubusercontent.com/assets/493769/25544566/5257de20-2c5b-11e7-9ca4-82466dacd48d.png)

**Comment by DcyMatrix** [comment] 2017-04-28 19:52
I can confirm this behavior in siad 1.2.1 as well, the contract count first
gets updated when siad is restarted.

**Comment by kreiseder** [comment] 2017-04-30 21:01
i think it adds the "real active contracts" count to the actual value whenever you restart SIA UI. it gets more and more when you restart SIA UI.

**Comment by tbenz9** [comment] 2018-04-19 17:32
Issue #2938 appears to be a duplicate of this one.  I'm going to close this issue and track the bug in #2938 as #2938 is a little more clear what is going on and the devs responded.

**Closed by tbenz9** 2018-04-19 17:32 UTC
Labels: Bug
