### ISSUE TITLE
"too many open files in system" 1.2.2 on OSX

### ISSUE THREAD

**Issue by nicexe** [NebulousLabs/Sia#1840] opened 2017-05-25 23:08 UTC
siad crashed in Sia-UI giving out this:
```
Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 1.16275065 seconds
goroutine 1 [running]:
runtime/debug.Stack(0x1043857, 0x0, 0x4227835f8)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x79
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/NebulousLabs/Sia/build.Critical(0x422783948, 0x1, 0x1)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/build/critical.go:16 +0xa7
main.startDaemon(0x0, 0x0, 0x7fff5fbffcfc, 0xe, 0x7fff5fbffd28, 0x5, 0x7fff5fbffd17, 0x5, 0x0, 0x7fff5fbffd38, ...)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/siad/daemon.go:295 +0xaa9
main.startDaemonCmd(0x421c27200, 0x421c293b0, 0x0, 0x5)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/siad/daemon.go:309 +0x6d
github.com/spf13/cobra.(*Command).execute(0x421c27200, 0x421bfe070, 0x5, 0x5, 0x421c27200, 0x421bfe070)
	/home/jrh/go/src/github.com/spf13/cobra/command.go:651 +0x23a
github.com/spf13/cobra.(*Command).ExecuteC(0x421c27200, 0x16c7c0f, 0x3b, 0x421cfcbe0)
	/home/jrh/go/src/github.com/spf13/cobra/command.go:726 +0x339
github.com/spf13/cobra.(*Command).Execute(0x421c27200, 0x1aa6520, 0x16b10c0)
	/home/jrh/go/src/github.com/spf13/cobra/command.go:685 +0x2b
main.main()
	/home/jrh/go/src/github.com/NebulousLabs/Sia/siad/main.go:174 +0x79d
Critical error: accept tcp 127.0.0.1:9980: accept: too many open files in system
Please submit a bug report here: https://github.com/NebulousLabs/Sia/issues
Closing renter...
Closing host...

```

**Comment by johnathanhowell** [comment] 2017-05-26 01:29
Please try re-download 1.2.2; we fixed this bug in one of our dependencies but it didn't get compiled into the original release. We've since patched and re-uploaded.

**Comment by DavidVorick** [comment] 2017-05-26 16:09
Why doesn't the build process ensure a clean slate for dependencies?

**Comment by johnathanhowell** [comment] 2017-05-26 16:11
It does; the problem was that Luke manually skipped the `prepublish` step of `sia.js`, leading to 0.4.0 being published without being compiled (the compiled source is actually `sia.js 0.3.x`)

**Comment by droghio** [comment] 2017-06-04 01:45
@nicexe Any word if reinstalling Sia fixed the issue? A few other users are reporting a similar issue.

**Comment by uvizhe** [comment] 2017-06-18 08:50
I downloaded Sia 1.2.2 yesterday and today I got this error.

**Comment by nicexe** [comment] 2017-06-18 11:44
I might be an odd case after I found out that my non-working laptop battery was resulting in some weird IO scheduling issues.

Battery is removed now, yet I haven't run Sia for long enough to see if the same problems occur.

**Comment by lukechampine** [comment] 2017-07-28 21:16
Closing for now. Please reopen if this is reproducible in v1.3.0

**Closed by lukechampine** 2017-07-28 21:16 UTC
