### ISSUE TITLE
Sia does not respect storage limits

### ISSUE THREAD

**Issue by mtlynch** [NebulousLabs/Sia#837] opened 2015-11-10 03:42 UTC
I've always had my host settings set to limit to 200 GB and it seems to have gone way over:

```bash
$ ./siac host status
Host settings:
Storage:      214.748 GB (796.089 GB used)
Price:        0.000 SC per GB per month
Collateral:   0
Max Filesize: 1000000000
Max Duration: 8640
Contracts:    5704

$ du -h host/
742G    host/

$ ./siac version
Sia Client v0.4.8
```

**Comment by DavidVorick** [comment] 2015-11-10 15:06
oh my.

I'm impressed that we got to 800GB. That's worth a congradulations, even if it wasn't supposed to happen. There were 10GB nodes running and the hosts seemed to respect that just fine. I'm wondering if our recent changes to the way revisions are handled means that hosts will accept contracts...

When you open a revision-based upload, the initial size is zero. I'm guessing that the host is not checking whether there is space on-disk before accepting a revision. Thanks for bringing this up quickly, hope nobody has been burned too badly by it.

**Comment by lukechampine** [comment] 2015-11-10 15:53
Hmm. Not sure why this is happening. Here is the check in question: https://github.com/NebulousLabs/Sia/blob/master/modules/host/negotiate.go#L146
```
case rev.NewFileSize > uint64(h.spaceRemaining) || rev.NewFileSize > h.MaxFilesize:
	return errors.New("revision file size is too large")
```
It seems okay to me. Actually, it seems *overly* restrictive; it should be comparing `h.spaceRemaining` to the filesize delta, not the new file size.

**Comment by mtlynch** [comment] 2015-11-11 00:19
Happy to help debug if you need me to run any commands, share any logs

**Comment by mtlynch** [comment] 2015-11-11 00:34
Still climbing:

```
$ ./siac host status
Host settings:
Storage:      214.748 GB (830.252 GB used)
Price:        0.000 SC per GB per month
Collateral:   0
Max Filesize: 1000000000
Max Duration: 8640
Contracts:    5742
```

I'm going to raise my hosting price so that it stops expanding.

**Comment by DavidVorick** [comment] 2015-11-11 14:51
That's a good temporary solution. If you put it over 500 SC / GB / Mo, none of the 0.4.8 clients will select you under any circumstance.

**Comment by lukechampine** [comment] 2015-11-11 16:49
I think I fixed this in https://github.com/NebulousLabs/Sia/commit/5a07ddcb66b1911eb8d3aa7152e19a46c33ba675
should be merged soon

**Comment by DavidVorick** [comment] 2015-11-13 15:09
should be fixed at this point, maybe @mtlynch can confirm?

**Comment by DavidVorick** [comment] 2015-11-13 15:10
hmm, we should add a test for this.

**Comment by mtlynch** [comment] 2015-11-17 01:46
I upgraded to c74e22a4d105ef159d24836a0380cb0a672fd8ed, so I'll let you know if it recurs. Expected behavior is that my contracts will expire until I'm back under 200 GB, right?

```shell
$ $GOPATH/bin/siac host status
Host settings:
Storage:      214.748 GB (826.415 GB used)
Price:        1.000 SC per GB per month
Collateral:   0
Max Filesize: 1000000000
Max Duration: 8640
Contracts:    5649
```

**Comment by DavidVorick** [comment] 2015-11-17 04:10
That is the expected behavior. Also worth noting that your file contracts are likely going to fail until block 27,000 due to a hardfork that we didn't catch in time.

Sorry about that

**Closed** 2015-11-26 15:22 UTC
