### ISSUE TITLE
Issue opening/unlocking wallet

### ISSUE THREAD

**Issue by justfra** [NebulousLabs/Sia#2507] opened 2017-12-05 08:56 UTC
Bug Report
==========

Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 2.501179277 seconds
panic: invalid page type: 0: 0

goroutine 8102 [running]:
github.com/NebulousLabs/bolt.(*Cursor).search(0xc423178a80, 0xc423178b20, 0x20, 0x20, 0x706eb)
	/home/luke/go/src/github.com/NebulousLabs/bolt/cursor.go:256 +0x405
github.com/NebulousLabs/bolt.(*Cursor).searchPage(0xc423178a80, 0xc423178b20, 0x20, 0x20, 0x7fa4fd0b0000)
	/home/luke/go/src/github.com/NebulousLabs/bolt/cursor.go:314 +0x156
github.com/NebulousLabs/bolt.(*Cursor).search(0xc423178a80, 0xc423178b20, 0x20, 0x20, 0x10b0)
	/home/luke/go/src/github.com/NebulousLabs/bolt/cursor.go:271 +0x1bb
github.com/NebulousLabs/bolt.(*Cursor).searchPage(0xc423178a80, 0xc423178b20, 0x20, 0x20, 0x7fa500d6c000)
	/home/luke/go/src/github.com/NebulousLabs/bolt/cursor.go:314 +0x156
github.com/NebulousLabs/bolt.(*Cursor).search(0xc423178a80, 0xc423178b20, 0x20, 0x20, 0x4d6c)
	/home/luke/go/src/github.com/NebulousLabs/bolt/cursor.go:271 +0x1bb
github.com/NebulousLabs/bolt.(*Cursor).searchPage(0xc423178a80, 0xc423178b20, 0x20, 0x20, 0x7fa4fec35000)
	/home/luke/go/src/github.com/NebulousLabs/bolt/cursor.go:314 +0x156
github.com/NebulousLabs/bolt.(*Cursor).search(0xc423178a80, 0xc423178b20, 0x20, 0x20, 0x2c35)
	/home/luke/go/src/github.com/NebulousLabs/bolt/cursor.go:271 +0x1bb
github.com/NebulousLabs/bolt.(*Cursor).seek(0xc423178a80, 0xc423178b20, 0x20, 0x20, 0x0, 0x0, 0x6da243, 0xc42193b278, 0xc4218e6600, 0x3, ...)
	/home/luke/go/src/github.com/NebulousLabs/bolt/cursor.go:159 +0xb1
github.com/NebulousLabs/bolt.(*Bucket).Get(0xc421811a00, 0xc423178b20, 0x20, 0x20, 0xc421811a00, 0x544c4425469649a7, 0x72ec1dcd30c3354f)
	/home/luke/go/src/github.com/NebulousLabs/bolt/bucket.go:267 +0xef
github.com/NebulousLabs/Sia/modules/consensus.getBlockMap(0xc42193b260, 0xad5b000000000000, 0x2155a2fa08a167ba, 0xa86660b3fae7164f, 0x1c421b04397222c, 0xc42174d080, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/consensusdb.go:185 +0x7d
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).computeConsensusChange(0xc420135b80, 0xc42193b260, 0x0, 0x0, 0x0, 0xc4211d8540, 0x1, 0x1, 0x0, 0x0, ...)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/subscribe.go:53 +0x818
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).managedInitializeSubscribe.func2(0xc42193b260, 0xb036d0, 0xc42193b260)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/subscribe.go:172 +0xe0
github.com/NebulousLabs/bolt.(*DB).View(0xc420102780, 0xc423179ab0, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/bolt/db.go:634 +0x9f
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).managedInitializeSubscribe(0xc420135b80, 0xdd7f20, 0xc4201c0420, 0x9c50327208e25dbe, 0x77796cb7dae3b287, 0x890a90de12130a19, 0x90577869d19d0d62, 0x0, 0xc423053bc8)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/subscribe.go:180 +0x24f
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).ConsensusSetSubscribe(0xc420135b80, 0xdd7f20, 0xc4201c0420, 0x9c50327208e25dbe, 0x77796cb7dae3b287, 0x890a90de12130a19, 0x90577869d19d0d62, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/subscribe.go:203 +0xee
github.com/NebulousLabs/Sia/modules/wallet.(*Wallet).managedUnlock(0xc4201c0420, 0xff1a80a95b2e01e6, 0xf0871f53f8366a37, 0xc8220758f8cc56bd, 0x300d8caae09d2096, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/wallet/encrypt.go:205 +0x3e1
github.com/NebulousLabs/Sia/modules/wallet.(*Wallet).Unlock(0xc4201c0420, 0xff1a80a95b2e01e6, 0xf0871f53f8366a37, 0xc8220758f8cc56bd, 0x300d8caae09d2096, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/wallet/encrypt.go:581 +0x19a
github.com/NebulousLabs/Sia/api.(*API).walletUnlockHandler(0xc42001d200, 0xddefe0, 0xc4216587e0, 0xc42000b000, 0x0, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/api/wallet.go:547 +0x114
github.com/NebulousLabs/Sia/api.(*API).(github.com/NebulousLabs/Sia/api.walletUnlockHandler)-fm(0xddefe0, 0xc4216587e0, 0xc42000b000, 0x0, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/api/api.go:295 +0x66
github.com/julienschmidt/httprouter.(*Router).ServeHTTP(0xc420edf100, 0xddefe0, 0xc4216587e0, 0xc42000b000)
	/home/luke/go/src/github.com/julienschmidt/httprouter/router.go:344 +0x813
github.com/NebulousLabs/Sia/api.RequireUserAgent.func1(0xddefe0, 0xc4216587e0, 0xc42000b000)
	/home/luke/go/src/github.com/NebulousLabs/Sia/api/api.go:99 +0xba
net/http.HandlerFunc.ServeHTTP(0xc4208e8420, 0xddefe0, 0xc4216587e0, 0xc42000b000)
	/usr/local/go/src/net/http/server.go:1942 +0x44
github.com/NebulousLabs/Sia/api.cleanCloseHandler.func1.1(0xc4220e29c0, 0xdda320, 0xc4208e8420, 0xddefe0, 0xc4216587e0, 0xc42000b000)
	/home/luke/go/src/github.com/NebulousLabs/Sia/api/api.go:132 +0x79
created by github.com/NebulousLabs/Sia/api.cleanCloseHandler.func1
	/home/luke/go/src/github.com/NebulousLabs/Sia/api/api.go:133 +0xbc

Lubuntu 17.10 x64
1.3.0

**Comment by tbenz9** [comment] 2017-12-05 17:52
Duplicate of #2247

**Closed** 2017-12-05 18:33 UTC
