### ISSUE TITLE
active pieces

### ISSUE THREAD

**Issue by doctord919** [NebulousLabs/Sia#2435] opened 2017-10-19 14:36 UTC
Win8.1 x64 ..Sia-1.3.0
I try 80GB Upload(2 days ... 72% upload) ... I rebooted the computer, but the problem is the same:
The download speed jumps that grows to 30mbits (2-3 seconds), then drops to 100kbits (10-15 seconds) and then again again.
goroutine 572 [running]:
runtime/debug.Stack(0x44441e, 0x0, 0xc06f017bf0)
        /usr/local/go/src/runtime/debug/stack.go:24 +0x80
runtime/debug.PrintStack()
        /usr/local/go/src/runtime/debug/stack.go:16 +0x29
github.com/NebulousLabs/Sia/build.Critical(0xc06f017d70, 0x3, 0x3)
        /home/luke/go/src/github.com/NebulousLabs/Sia/build/critical.go:16 +0xae
github.com/NebulousLabs/Sia/persist.(*Logger).Critical(0xc04257b700, 0xc06f017d70, 0x3, 0x3)
        /home/luke/go/src/github.com/NebulousLabs/Sia/persist/log.go:37 +0xe7
github.com/NebulousLabs/Sia/modules/renter.(*Renter).managedDownloadIteration(0xc043674840, 0xc06f017f20)
        /home/luke/go/src/github.com/NebulousLabs/Sia/modules/renter/download.go:365 +0x684
github.com/NebulousLabs/Sia/modules/renter.(*Renter).threadedDownloadLoop(0xc043674840)
        /home/luke/go/src/github.com/NebulousLabs/Sia/modules/renter/download.go:635 +0x385
created by github.com/NebulousLabs/Sia/modules/renter.newRenter
        /home/luke/go/src/github.com/NebulousLabs/Sia/modules/renter/renter.go:220 +0x3ea
Critical error: ERROR: the renter is idle, but tracking 32 active pieces; resetting to zero
Please submit a bug report here: https://github.com/NebulousLabs/Sia/issues
Caught stop signal, quitting...
Closing renter...
Closing host...
Closing wallet...
Closing transaction pool...
Closing consensus...
Closing gateway...
Shutdown complete.

**Comment by tbenz9** [comment] 2017-10-19 16:17
Duplicate of #2395 and #2319

**Closed** 2017-10-19 18:10 UTC
