### ISSUE TITLE
Can't announce host: transaction spends a nonexisting siacoin output

### ISSUE THREAD

**Issue by mtlynch** [NebulousLabs/Sia#1497] opened 2016-11-11 14:50 UTC
I have a 1.0.3 host that's sync'ed, but I can't `host announce` because of an error about nonexisting siacoin output. Known issue?

```shell
$ ./siac host announce
Could not announce host: consensus conflict: transaction spends a nonexisting siacoin output
```

```shell
$ ./siac wallet
Wallet status:
Encrypted, Unlocked
Confirmed Balance:   612.2 KS
Unconfirmed Delta:  -2.5 SC
Exact:               612206746536472847764919502080 H
Siafunds:            0 SF
Siafund Claims:      0 H
```

```shell
$ ./siac
Synced: Yes
Block:  000000000000043b09a95f21125d88f535c92def83f5de96c51a86b787b72987
Height: 77544
Target: [0 0 0 0 0 0 8 120 13 110 80 161 124 155 76 18 75 49 224 136 164 79 167 21 168 56 212 97 63 92 83 236]
```

```shell
$ ./siac host -v
General Info:
        Estimated Competitive Price: 490 SC

Host Internal Settings:
        acceptingcontracts:   Yes
        maxduration:          25 Weeks
        maxdownloadbatchsize: 17.83 MB
        maxrevisebatchsize:   17.83 MB
        netaddress:           [snip] (automatically determined)
        windowsize:           24 Hours

        collateral:       250 SC / TB / Month
        collateralbudget: 2 MS
        maxcollateral:    100 KS Per Contract

        mincontractprice:          1 SC
        mindownloadbandwidthprice: 999 SC / TB
        minstorageprice:           700 SC / TB / Month
        minuploadbandwidthprice:   100 SC / TB

Host Financials:
        Contract Count:               0
        Transaction Fee Compensation: 0 H
        Potential Fee Compensation:   0 H
        Transaction Fee Expenses:     0 H

        Storage Revenue:           0 H
        Potential Storage Revenue: 0 H

        Locked Collateral: 0 H
        Risked Collateral: 0 H
        Lost Collateral:   0 H

        Download Revenue:           0 H
        Potential Download Revenue: 0 H
        Upload Revenue :            0 H
        Potential Upload Revenue:   0 H

RPC Stats:
        Error Calls:        6965
        Unrecognized Calls: 4
        Download Calls:     0
        Renew Calls:        0
        Revise Calls:       6965
        Settings Calls:     1260
        FormContract Calls: 1

Storage Folders:
    Used    Capacity      % Used    Path
    0 B     500.000 GB    0.00      /mnt/sia/host-storage
```

**Comment by DavidVorick** [comment] 2016-11-11 17:21
This is a known issue, I'm not 100% sure what the cause is, but it should resolve after a few blocks. It's related to the fact that you've spent all of your outputs into unconfirmed transactions, and because they haven't confirmed yet the wallet is confused about which money is available to you.

I think the real source of the issue is that you restarted the wallet. If I am guessing, you made an announcement, then for some unrelated reason you restarted siad, and now you've got a transaction spending your money but the wallet doesn't realize it's yours.

I believe that the changes we've made in the wallet branch already solve this issue, though we'll need to be able to reproduce this problem and write a regression test to be sure.

But my guess is this will reproduce the issue:

1. start with clean wallet
2. send it 1 transaction from another wallet, such that there's only 1 output.
3. send a transaction with the wallet
4. restart the wallet before the transaction confirms
5. try to send another transaction (such as a host announcement) before the first transaction has confirmed

This problem can happen even if you have more than one output available, but it requires more complex conditions. The root cause would be the same though.

**Comment by mtlynch** [comment] 2016-11-12 13:42
>I'm not 100% sure what the cause is, but it should resolve after a few blocks.

It's ~200 blocks later and I'm still seeing the same issue.

**Comment by DavidVorick** [comment] 2016-11-15 04:35
oh. Okay, that's a different issue entirely then. Hmm.

**Comment by lukechampine** [comment] 2017-04-07 02:01
Closing due to age, please reopen if you run into this problem again.

**Closed by lukechampine** 2017-04-07 02:01 UTC
