### ISSUE TITLE
Keep getting bug report and program does not close down on exit and will not Sync past 24.3% 

### ISSUE THREAD

**Issue by sparkie73** [NebulousLabs/Sia#3129] opened 2018-06-29 17:13 UTC
# BUG REPORT

**Stack Trace or error message**

**Expected Behavior**

**How to reproduce it (as minimally and precisely as possible)**

**Environment**
* Sia version:
* OS:

**Comment by sparkie73** [comment] 2018-06-29 17:14
Sia Daemon v1.3.3
Git Revision 94ea84e
Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 0.4907004 seconds
panic: bolt.DB.meta(): invalid meta pages
	panic: bolt.DB.meta(): invalid meta pages

goroutine 24 [running]:
github.com/NebulousLabs/Sia/vendor/github.com/coreos/bbolt.(*DB).meta(0xc0421325a0, 0x1064)
	/home/luke/go/src/github.com/NebulousLabs/Sia/vendor/github.com/coreos/bbolt/db.go:894 +0xc9
github.com/NebulousLabs/Sia/vendor/github.com/coreos/bbolt.(*Tx).rollback(0xc04241ae00)
	/home/luke/go/src/github.com/NebulousLabs/Sia/vendor/github.com/coreos/bbolt/tx.go:267 +0x88
github.com/NebulousLabs/Sia/vendor/github.com/coreos/bbolt.(*DB).Update.func1(0xc04241ae00)
	/home/luke/go/src/github.com/NebulousLabs/Sia/vendor/github.com/coreos/bbolt/db.go:665 +0x45
panic(0x9ca4e0, 0xb567f0)
	/usr/local/go/src/runtime/panic.go:502 +0x237
github.com/NebulousLabs/Sia/vendor/github.com/coreos/bbolt.(*DB).meta(0xc0421325a0, 0x1064)
	/home/luke/go/src/github.com/NebulousLabs/Sia/vendor/github.com/coreos/bbolt/db.go:894 +0xc9
github.com/NebulousLabs/Sia/vendor/github.com/coreos/bbolt.(*Tx).rollback(0xc04241ae00)
	/home/luke/go/src/github.com/NebulousLabs/Sia/vendor/github.com/coreos/bbolt/tx.go:267 +0x88
github.com/NebulousLabs/Sia/vendor/github.com/coreos/bbolt.(*Tx).Commit(0xc04241ae00, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/vendor/github.com/coreos/bbolt/tx.go:161 +0x58c
github.com/NebulousLabs/Sia/vendor/github.com/coreos/bbolt.(*DB).Update(0xc0421325a0, 0xc042047330, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/vendor/github.com/coreos/bbolt/db.go:680 +0xef
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).managedAcceptBlocks(0xc042014500, 0xc0421a0800, 0xa, 0xa, 0x0, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/accept.go:243 +0x41a
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).managedReceiveBlocks(0xc042014500, 0xb62660, 0xc0424cebe0, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:225 +0x4dc
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).(github.com/NebulousLabs/Sia/modules/consensus.managedReceiveBlocks)-fm(0xb62660, 0xc0424cebe0, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:445 +0x45
github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).managedRPC(0xc0420d6580, 0xc04201a480, 0x11, 0xabd392, 0xa, 0xc042166d00, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/rpc.go:66 +0x2b2
github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).RPC(0xc0420d6580, 0xc04201a480, 0x11, 0xabd392, 0xa, 0xc042166d00, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/rpc.go:76 +0xcb
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).threadedInitialBlockchainDownload.func1(0xc042014500, 0xc044b59f18, 0xc044b59ec0, 0xc044b59ec8, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:580 +0x11f
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).threadedInitialBlockchainDownload(0xc042014500, 0xc042269fb0, 0x83deb0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:601 +0x151
github.com/NebulousLabs/Sia/modules/consensus.NewCustomConsensusSet.func1(0x1, 0xc042014500, 0xc042024230, 0xb634a0, 0xc0420d6580)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/consensusset.go:160 +0x37a
created by github.com/NebulousLabs/Sia/modules/consensus.NewCustomConsensusSet
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/consensusset.go:153 +0x626

**Comment by sparkie73** [comment] 2018-06-29 17:14
newest version just downloaded

**Comment by tbenz9** [comment] 2018-06-29 22:10
Duplicate of #2318 

Follow these instructions to delete your consensus.db file and try syncing again: https://gist.github.com/tbenz9/8066d74853ab28c23bd7bc1d3c7cdeda

**Closed by tbenz9** 2018-06-29 22:10 UTC
