### ISSUE TITLE
Address Already in use

### ISSUE THREAD

**Issue by deccap** [NebulousLabs/Sia#2485] opened 2017-11-23 15:31 UTC
Loading...
(0/6) Loading siad...
listen tcp 127.0.0.1:9980: bind: address already in use
error while loading contract manager atomic data: error loading the contract manager settings file: unable to read persisted json object from disk: unable to read header from persisted json object file: EOF

Bug Report
==========
Check to see if a bug report already exists.  If you still want to create a new issue please include the information below.

**Stack Trace or error message**

**Environment**
* Sia version:
* OS:

**Any useful logs**

Feature Request
===============
Check to see if the feature is on the roadmap.  If it is not on the roadmap then clearly describe your feature request and why it would benefit Sia.

[Sia roadmap](https://trello.com/b/Io1dDyuI/sia-public-roadmap)

**Comment by S-anasol** [comment] 2017-11-23 15:32
kill all siad and restart sia wallet

**Comment by deccap** [comment] 2017-11-23 15:34
Now I get this error:
A critical error loading Sia has occured: Siad unexpectedly exited. Error
log: Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
Closing wallet...
Closing transaction pool...
Closing consensus...
Closing gateway...
error while loading contract manager atomic data: error loading the
contract manager settings file: unable to read persisted json object from
disk: unable to read header from persisted json object file: EOF

**Comment by tbenz9** [comment] 2017-12-05 17:55
Duplicate of #2486 Please try to fix listed on that issue.

Recommendation to devs: close

**Closed** 2017-12-05 18:33 UTC
