### ISSUE TITLE
1.3.2 won't load

### ISSUE THREAD

**Issue by Wlinc** [NebulousLabs/Sia#2896] opened 2018-03-21 18:22 UTC
# BUG REPORT

No error message provided

I'm expecting my wallet to load, but it only shows the attached message. It's been over a full day
![screen shot 2018-03-21 at 11 15 19 am](https://user-images.githubusercontent.com/12769724/37729188-88886240-2cf9-11e8-8639-5328eddc3ec1.png)

To reproduce the error, I simply open SiaUI 1.3.2

The problem started when I updated from 1.3.1 -- the first error I got was this: https://github.com/NebulousLabs/Sia/issues/2867

Troubleshooting steps I've taken:
Per suggestion on issue 2867, I deleted the transactionpool folder. 
I've also done a fresh install

**Environment**
* Sia version: SiaUI 1.3.2
* OS:  Windows 10 Pro

**Comment by JamesM424** [comment] 2018-03-23 05:08
Could you upload the siad-output.log folder from %AppData%\Roaming\Sia-UI\sia.  That file gets re-created every time you go to load the daemon and will likely better identify which module is causing a problem.

**Comment by kingsley22** [comment] 2018-03-26 15:06
I got the same error, I deleted both concensus and transactionpool .db files, and since then it's been syncing fine.

**Comment by Wlinc** [comment] 2018-03-27 20:34
@JamesM424 here you go -- note that now I've tried deleting the consensus.db and replacing it with a bootstrap. 

Sia Daemon v1.3.2
Git Revision 72938f5
Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
panic: Consensus change series appears to be inconsistent - we are applying the wrong block.

goroutine 7 [running]:
github.com/NebulousLabs/Sia/modules/transactionpool.(*TransactionPool).ProcessConsensusChange(0xc04229a160, 0x363f3a3439fdbc38, 0xf7492be2710796c1, 0xe1403ed84dc4c87d, 0x4658938a28113c53, 0x0, 0x0, 0x0, 0xc046ba7500, 0x1, ...)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/transactionpool/update.go:223 +0x2b68
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).updateSubscribers(0xc0420cfb80, 0x0, 0x0, 0x0, 0xc044440a40, 0x1, 0x1)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/subscribe.go:118 +0x17f
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).managedAcceptBlocks(0xc0420cfb80, 0xc042d0b400, 0xa, 0xa, 0x0, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/accept.go:311 +0x61e
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).managedReceiveBlocks(0xc0420cfb80, 0xdf80e0, 0xc042204780, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:225 +0x500
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).(github.com/NebulousLabs/Sia/modules/consensus.managedReceiveBlocks)-fm(0xdf80e0, 0xc042204780, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:445 +0x45
github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).managedRPC(0xc0420c2840, 0xc042048a60, 0x11, 0xac7049, 0xa, 0xc04215e420, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/rpc.go:66 +0x2c9
github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).RPC(0xc0420c2840, 0xc042048a60, 0x11, 0xac7049, 0xa, 0xc04215e420, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/rpc.go:76 +0xd8
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).threadedInitialBlockchainDownload.func1(0xc0420cfb80, 0xc049457ef0, 0xc049457e98, 0xc049457ea0, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:580 +0x12e
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).threadedInitialBlockchainDownload(0xc0420cfb80, 0xc0421033c0, 0xc042041440)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:601 +0x151
github.com/NebulousLabs/Sia/modules/consensus.New.func1(0x1, 0xc04215e4f0, 0xc0420cfb80, 0xdf87e0, 0xc0420c2840)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/consensusset.go:151 +0x3eb
created by github.com/NebulousLabs/Sia/modules/consensus.New
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/consensusset.go:144 +0x656

**Comment by tbenz9** [comment] 2018-03-27 23:56
Duplicate of #2867

**Closed by tbenz9** 2018-03-27 23:56 UTC
