### ISSUE TITLE
Siad has exited unexpectedly. Please submit a bug report including the error log here.

### ISSUE THREAD

**Issue by Si4Vit** [NebulousLabs/Sia#2545] opened 2017-12-15 01:31 UTC
Good Day. Any ideas how to solve? Thank You.

Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 5.0562892 seconds

Wallet: scanned to height 123290...
Wallet: scanned to height 123320...
Wallet: scanned to height 123320...
Wallet: scanned to height 123320...
Done!
panic: page 23663 already freed

goroutine 66 [running]:
github.com/NebulousLabs/bolt.(*freelist).free(0xc04204cf60, 0x204, 0x8def000)
	/home/luke/go/src/github.com/NebulousLabs/bolt/freelist.go:121 +0x2a1
github.com/NebulousLabs/bolt.(*node).spill(0xc047de91f0, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/bolt/node.go:363 +0x1e7
github.com/NebulousLabs/bolt.(*node).spill(0xc044dcbb20, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/bolt/node.go:350 +0xbb
github.com/NebulousLabs/bolt.(*node).spill(0xc0420eea10, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/bolt/node.go:350 +0xbb
github.com/NebulousLabs/bolt.(*node).spill(0xc0420e83f0, 0xc0420c24b0, 0xc04206fa28)
	/home/luke/go/src/github.com/NebulousLabs/bolt/node.go:350 +0xbb
github.com/NebulousLabs/bolt.(*Bucket).spill(0xc04223c580, 0xc04206fb00, 0x15)
	/home/luke/go/src/github.com/NebulousLabs/bolt/bucket.go:570 +0x182
github.com/NebulousLabs/bolt.(*Bucket).spill(0xc0422481d8, 0x10431ca4, 0xee9fe0)
	/home/luke/go/src/github.com/NebulousLabs/bolt/bucket.go:537 +0x8ff
github.com/NebulousLabs/bolt.(*Tx).Commit(0xc0422481c0, 0xc0424604e0, 0xc04206fe80)
	/home/luke/go/src/github.com/NebulousLabs/bolt/tx.go:163 +0x12c
github.com/NebulousLabs/Sia/modules/transactionpool.(*TransactionPool).syncDB(0xc04200e9a0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/transactionpool/persist.go:54 +0x4e
github.com/NebulousLabs/Sia/modules/transactionpool.(*TransactionPool).threadedRegularSync(0xc04200e9a0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/transactionpool/persist.go:44 +0x17e
created by github.com/NebulousLabs/Sia/modules/transactionpool.(*TransactionPool).initPersist
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/transactionpool/persist.go:126 +0x3f6

**Comment by tbenz9** [comment] 2017-12-15 04:20
Duplicate of #2413

**Comment by tbenz9** [comment] 2017-12-15 04:21
unfortunately we don't currently have a workaround for this, other than ensuring you have enough free disk space and redownloading the blockchain.

**Closed by tbenz9** 2017-12-15 04:20 UTC
