### ISSUE TITLE
Crash when unlocking wallet first time on 1.2.0

### ISSUE THREAD

**Issue by TacoByte** [NebulousLabs/Sia#1702] opened 2017-04-15 00:14 UTC
Hey, I've been carrying around my wallet for a while from update to update.

macos 10.12.4

Just now, after installing 1.2.0 and trying to unlock wallet for the first time:

`Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 1115.488339097 seconds

Wallet: scanned to height 3625...
Wallet: scanned to height 6889...
Wallet: scanned to height 9020...
Wallet: scanned to height 9456...
Wallet: scanned to height 11909...
Wallet: scanned to height 14641...
Wallet: scanned to height 15449...
Wallet: scanned to height 17387...
Wallet: scanned to height 19950...
Wallet: scanned to height 21133...
Wallet: scanned to height 22689...
Wallet: scanned to height 22879...
Wallet: scanned to height 24162...
Wallet: scanned to height 25935...
Wallet: scanned to height 27447...
Wallet: scanned to height 28953...
Wallet: scanned to height 30340...
Wallet: scanned to height 31471...
Wallet: scanned to height 32506...
Wallet: scanned to height 32670...
Wallet: scanned to height 33483...
Wallet: scanned to height 33902...
Wallet: scanned to height 34126...
Wallet: scanned to height 34276...
Wallet: scanned to height 34407...
Wallet: scanned to height 34557...
Wallet: scanned to height 34594...
Wallet: scanned to height 34674...
Wallet: scanned to height 34766...
Wallet: scanned to height 34842...
Wallet: scanned to height 34933...
Wallet: scanned to height 34993...
Wallet: scanned to height 35097...
Wallet: scanned to height 35260...
Wallet: scanned to height 35469...
Wallet: scanned to height 35845...
Wallet: scanned to height 36150...
Wallet: scanned to height 36345...
Wallet: scanned to height 36598...
Wallet: scanned to height 36892...
Wallet: scanned to height 37021...
Wallet: scanned to height 37286...
Wallet: scanned to height 37422...
Wallet: scanned to height 37609...
Wallet: scanned to height 37996...
Wallet: scanned to height 38367...
Wallet: scanned to height 38531...
Wallet: scanned to height 38644...
Wallet: scanned to height 38777...
Wallet: scanned to height 39046...
Wallet: scanned to height 39249...
Wallet: scanned to height 39384...
Wallet: scanned to height 39512...
Wallet: scanned to height 39620...
Wallet: scanned to height 39786...
Wallet: scanned to height 39936...
Wallet: scanned to height 40205...
Wallet: scanned to height 40433...
Wallet: scanned to height 40737...
Wallet: scanned to height 41115...
Wallet: scanned to height 41604...
Wallet: scanned to height 41701...
Wallet: scanned to height 41765...
Wallet: scanned to height 41917...
Wallet: scanned to height 42088...
Wallet: scanned to height 42235...
Wallet: scanned to height 42385...
Wallet: scanned to height 42942...
Wallet: scanned to height 43473...
Wallet: scanned to height 43658...
Wallet: scanned to height 43817...
Wallet: scanned to height 44014...
Wallet: scanned to height 44294...
Wallet: scanned to height 44341...
Wallet: scanned to height 44407...
Wallet: scanned to height 44478...
Wallet: scanned to height 44579...
Wallet: scanned to height 44635...
Wallet: scanned to height 44705...
Wallet: scanned to height 44830...
Wallet: scanned to height 44900...
Wallet: scanned to height 44988...
Wallet: scanned to height 45058...
Wallet: scanned to height 45136...
Wallet: scanned to height 45292...
Wallet: scanned to height 45394...
Wallet: scanned to height 45506...
Wallet: scanned to height 45574...
Wallet: scanned to height 45671...
Wallet: scanned to height 45855...
Wallet: scanned to height 45985...
Wallet: scanned to height 46145...
Wallet: scanned to height 46358...
Wallet: scanned to height 46802...
Wallet: scanned to height 47020...
Wallet: scanned to height 47209...
Wallet: scanned to height 47379...
Wallet: scanned to height 47544...
Wallet: scanned to height 47624...
Wallet: scanned to height 47768...
Wallet: scanned to height 47957...
Wallet: scanned to height 48324...
Wallet: scanned to height 48533...
Wallet: scanned to height 48864...
Wallet: scanned to height 49303...
Wallet: scanned to height 49647...
Wallet: scanned to height 50411...
Wallet: scanned to height 50690...
Wallet: scanned to height 50992...
Wallet: scanned to height 51280...
Wallet: scanned to height 51676...
Wallet: scanned to height 52426...
Wallet: scanned to height 53048...
Wallet: scanned to height 53269...
Wallet: scanned to height 53432...
Wallet: scanned to height 53556...
Wallet: scanned to height 53714...
Wallet: scanned to height 53832...
Wallet: scanned to height 53982...
Wallet: scanned to height 54172...
Wallet: scanned to height 54302...
Wallet: scanned to height 54449...
Wallet: scanned to height 54538...
Wallet: scanned to height 54653...
Wallet: scanned to height 54919...
Wallet: scanned to height 55083...
Wallet: scanned to height 55634...
Wallet: scanned to height 55966...
Wallet: scanned to height 56220...
Wallet: scanned to height 56419...
Wallet: scanned to height 56583...
Wallet: scanned to height 56910...
Wallet: scanned to height 57139...
Wallet: scanned to height 57878...
Wallet: scanned to height 58591...
Wallet: scanned to height 59345...
Wallet: scanned to height 59979...
Wallet: scanned to height 60242...
Wallet: scanned to height 60454...
Wallet: scanned to height 60626...
Wallet: scanned to height 60778...
Wallet: scanned to height 60985...
Wallet: scanned to height 61194...
Wallet: scanned to height 61428...
Wallet: scanned to height 61662...
Wallet: scanned to height 61786...
Wallet: scanned to height 61848...
Wallet: scanned to height 61898...
Wallet: scanned to height 61995...
Wallet: scanned to height 62078...
Wallet: scanned to height 62199...
Wallet: scanned to height 62326...
Wallet: scanned to height 62467...
Wallet: scanned to height 62602...
Wallet: scanned to height 62769...
Wallet: scanned to height 62901...
Wallet: scanned to height 63107...
Wallet: scanned to height 63202...
Wallet: scanned to height 63386...
Wallet: scanned to height 63570...
Wallet: scanned to height 63675...
Wallet: scanned to height 63763...
Wallet: scanned to height 63862...
Wallet: scanned to height 63963...
Wallet: scanned to height 64078...
Wallet: scanned to height 64177...
Wallet: scanned to height 64295...
Wallet: scanned to height 64422...
Wallet: scanned to height 64568...
Wallet: scanned to height 64694...
Wallet: scanned to height 64842...
Wallet: scanned to height 64985...
Wallet: scanned to height 65134...
Wallet: scanned to height 65300...
Wallet: scanned to height 65458...
Wallet: scanned to height 65634...
Wallet: scanned to height 65751...
Wallet: scanned to height 65851...
Wallet: scanned to height 65934...
Wallet: scanned to height 66037...
Wallet: scanned to height 66154...
Wallet: scanned to height 66280...
Wallet: scanned to height 66421...
Wallet: scanned to height 66562...
Wallet: scanned to height 66733...
Wallet: scanned to height 66899...
Wallet: scanned to height 67063...
Wallet: scanned to height 67213...
Wallet: scanned to height 67370...
Wallet: scanned to height 67512...
Wallet: scanned to height 67646...
Wallet: scanned to height 67765...
Wallet: scanned to height 67907...
Wallet: scanned to height 68049...
Wallet: scanned to height 68176...
Wallet: scanned to height 68315...
Wallet: scanned to height 68431...
Wallet: scanned to height 68581...
Wallet: scanned to height 68720...
Wallet: scanned to height 68869...
Wallet: scanned to height 68979...
Wallet: scanned to height 69040...
Wallet: scanned to height 69107...
Wallet: scanned to height 69180...
Wallet: scanned to height 69275...
Wallet: scanned to height 69360...
Wallet: scanned to height 69473...
Wallet: scanned to height 69616...
Wallet: scanned to height 69700...
Wallet: scanned to height 69793...
Wallet: scanned to height 69881...
Wallet: scanned to height 69977...
Wallet: scanned to height 70103...
Wallet: scanned to height 70179...
Wallet: scanned to height 70267...
Wallet: scanned to height 70385...
Wallet: scanned to height 70495...
Wallet: scanned to height 70617...
Wallet: scanned to height 70744...
Wallet: scanned to height 70839...
Wallet: scanned to height 70935...
Wallet: scanned to height 71021...
Wallet: scanned to height 71118...
Wallet: scanned to height 71207...
Wallet: scanned to height 71299...
Wallet: scanned to height 71395...
Wallet: scanned to height 71482...
Wallet: scanned to height 71572...
Wallet: scanned to height 71661...
Wallet: scanned to height 71761...
Wallet: scanned to height 71854...
Wallet: scanned to height 71948...
Wallet: scanned to height 72038...
Wallet: scanned to height 72138...
Wallet: scanned to height 72218...
Wallet: scanned to height 72324...2017/04/15 02:10:29 http: Accept error: accept tcp 127.0.0.1:9980: accept: too many open files; retrying in 5ms
2017/04/15 02:10:29 http: Accept error: accept tcp 127.0.0.1:9980: accept: too many open files; retrying in 5ms
2017/04/15 02:10:30 http: Accept error: accept tcp 127.0.0.1:9980: accept: too many open files; retrying in 5ms
2017/04/15 02:10:30 http: Accept error: accept tcp 127.0.0.1:9980: accept: too many open files; retrying in 10ms
2017/04/15 02:10:30 http: Accept error: accept tcp 127.0.0.1:9980: accept: too many open files; retrying in 20ms
2017/04/15 02:10:30 http: Accept error: accept tcp 127.0.0.1:9980: accept: too many open files; retrying in 40ms

Wallet: scanned to height 72410...2017/04/15 02:10:32 http: Accept error: accept tcp 127.0.0.1:9980: accept: too many open files; retrying in 5ms`

**Comment by TacoByte** [comment] 2017-04-15 00:24
this doesn't seem too severe - i just quit, relaunched sia ui, tried again, and it just worked. maybe it ran out of memory the first time doing all those blocks in a row or something

**Comment by blackouter9901** [comment] 2017-04-15 02:16
I have this same issue. Quit and relaunch of the SIA UI didn't solve the problem. I still cannot unlock my wallet. Any other methods to solve this?

**Comment by DavidVorick** [comment] 2017-04-15 03:52
Hmm. It looks like the UI might be polling the wallet in the background and opening a ton of files? Approximately how long was the scan running for?

**Comment by TacoByte** [comment] 2017-04-15 05:41
Not sure, a little while?

@blackouter9901 Try again. I think it picks up where it left off. You might be able to finish converting the database and get going

**Comment by DavidVorick** [comment] 2017-04-15 06:11
That is true, seems like users are having some success just powering through it and going a few thousand blocks at a time.

I'm glad that there's a workaround, but we're definitely also looking for the root cause.

@blackouter9901 @TacoByte you guys are both using the UI, right?

**Comment by TacoByte** [comment] 2017-04-15 07:13
@DavidVorick yes

**Comment by blackouter9901** [comment] 2017-04-15 12:46
Yes I'm using the UI. @DavidVorick successfully unlocked the wallet after more than 10 times restarting SIAD.

**Comment by DavidVorick** [comment] 2017-04-16 02:40
Okay, I think we've found the source of the issue, should have a fix out for it in the next week or two.

Thanks for putting up with the crashing, and also for making a bug report :)

**Comment by TacoByte** [comment] 2017-04-17 11:09
Always a pleasure ;)

**Comment by lukechampine** [comment] 2017-04-17 20:02
Now that Sia-UI#562 is merged, can someone try to reproduce this? If you aren't able to compile Sia-UI yourself, I can provide a build.

**Comment by TacoByte** [comment] 2017-04-18 15:01
i'll try building it but i need to resync from scratch with a <1.2.0 install to reproduce and that might take ages...

**Comment by TacoByte** [comment] 2017-04-18 17:39
sorry can't do. you'll have to find somebody else on a mac build that hasn't upgraded yet (my mac box is a special environment and i don't want to start messing around with my existing sia install)

**Comment by johnathanhowell** [comment] 2017-04-18 17:51
I was able to reproduce by artificially lowering my ulimit to 256

**Comment by DavidVorick** [comment] 2017-04-18 20:57
We've also found a second, memory-related bug that is sometimes causing memory leaks and wallet crashing.

That one will be fixed this week as well.

**Comment by lukechampine** [comment] 2017-07-28 20:59
Duplicate of #1840

**Closed by lukechampine** 2017-07-28 20:59 UTC
