### ISSUE TITLE
Crashes everytime I start up. Can't sync blocks

### ISSUE THREAD

**Issue by mrrealer** [NebulousLabs/Sia#2948] opened 2018-04-19 21:57 UTC
# BUG REPORT
Sia Daemon v1.3.2
Git Revision 72938f5
Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 0.1837967 seconds
panic: bolt.DB.meta(): invalid meta pages

goroutine 227 [running]:
github.com/NebulousLabs/Sia/vendor/github.com/coreos/bbolt.(*DB).meta(0xc0420652c0, 0xc04206c000)
	/home/luke/go/src/github.com/NebulousLabs/Sia/vendor/github.com/coreos/bbolt/db.go:894 +0xc9
github.com/NebulousLabs/Sia/vendor/github.com/coreos/bbolt.(*meta).copy(...)
	/home/luke/go/src/github.com/NebulousLabs/Sia/vendor/github.com/coreos/bbolt/tx.go:50
github.com/NebulousLabs/Sia/vendor/github.com/coreos/bbolt.(*Tx).init(0xc042fca000, 0xc0420652c0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/vendor/github.com/coreos/bbolt/tx.go:50 +0xb3
github.com/NebulousLabs/Sia/vendor/github.com/coreos/bbolt.(*DB).beginTx(0xc0420652c0, 0xc0420cdd44, 0x4426f9, 0x3a2058df4)
	/home/luke/go/src/github.com/NebulousLabs/Sia/vendor/github.com/coreos/bbolt/db.go:546 +0xab
github.com/NebulousLabs/Sia/vendor/github.com/coreos/bbolt.(*DB).Begin(0xc0420652c0, 0xc000000000, 0xc0424846c0, 0x473424, 0x7a9737)
	/home/luke/go/src/github.com/NebulousLabs/Sia/vendor/github.com/coreos/bbolt/db.go:523 +0x75
github.com/NebulousLabs/Sia/vendor/github.com/coreos/bbolt.(*DB).View(0xc0420652c0, 0xc042337c38, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/vendor/github.com/coreos/bbolt/db.go:688 +0x4d
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).CurrentBlock(0xc0420cdb80, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/consensusset.go:259 +0x114
github.com/NebulousLabs/Sia/node/api.(*API).consensusHandler(0xc0421603f0, 0xdf48e0, 0xc0426095e0, 0xc042272f00, 0x0, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/node/api/consensus.go:24 +0x52
github.com/NebulousLabs/Sia/node/api.(*API).(github.com/NebulousLabs/Sia/node/api.consensusHandler)-fm(0xdf48e0, 0xc0426095e0, 0xc042272f00, 0x0, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/node/api/routes.go:23 +0x6d
github.com/julienschmidt/httprouter.(*Router).ServeHTTP(0xc042041b40, 0xdf48e0, 0xc0426095e0, 0xc042272f00)
	/home/luke/go/src/github.com/julienschmidt/httprouter/router.go:344 +0x7a0
github.com/NebulousLabs/Sia/node/api.RequireUserAgent.func1(0xdf48e0, 0xc0426095e0, 0xc042272f00)
	/home/luke/go/src/github.com/NebulousLabs/Sia/node/api/routes.go:173 +0xc1
net/http.HandlerFunc.ServeHTTP(0xc0421c09f0, 0xdf48e0, 0xc0426095e0, 0xc042272f00)
	/usr/local/go/src/net/http/server.go:1918 +0x4b
github.com/NebulousLabs/Sia/node/api.cleanCloseHandler.func1.1(0xc042263560, 0xdeff60, 0xc0421c09f0, 0xdf48e0, 0xc0426095e0, 0xc042272f00)
	/home/luke/go/src/github.com/NebulousLabs/Sia/node/api/routes.go:144 +0x80
created by github.com/NebulousLabs/Sia/node/api.cleanCloseHandler.func1
	/home/luke/go/src/github.com/NebulousLabs/Sia/node/api/routes.go:142 +0xa7

**Comment by tbenz9** [comment] 2018-04-19 21:59
Duplicate of #2318 

Use these instructions to work around the issue: https://gist.github.com/tbenz9/8066d74853ab28c23bd7bc1d3c7cdeda

**Closed by tbenz9** 2018-04-19 21:59 UTC
