### ISSUE TITLE
Bug report: Siad has exited unexpectedly 

### ISSUE THREAD

**Issue by Wlinc** [NebulousLabs/Sia#2043] opened 2017-06-28 15:07 UTC
Hi - the error log is below. 

Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 0.145852306 seconds
goroutine 1 [running]:
runtime/debug.Stack(0x1043857, 0x0, 0xc4203e35f8)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x79
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/NebulousLabs/Sia/build.Critical(0xc4203e3948, 0x1, 0x1)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/build/critical.go:16 +0xa7
main.startDaemon(0x0, 0x0, 0x7fff5fbffca7, 0xe, 0x7fff5fbffcd3, 0x5, 0x7fff5fbffcc2, 0x5, 0x0, 0x7fff5fbffd2e, ...)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/siad/daemon.go:295 +0xaa9
main.startDaemonCmd(0xc420081200, 0xc4200153b0, 0x0, 0x5)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/siad/daemon.go:309 +0x6d
github.com/spf13/cobra.(*Command).execute(0xc420081200, 0xc42000e0d0, 0x5, 0x5, 0xc420081200, 0xc42000e0d0)
	/home/jrh/go/src/github.com/spf13/cobra/command.go:651 +0x23a
github.com/spf13/cobra.(*Command).ExecuteC(0xc420081200, 0x16c7c0f, 0x3b, 0xc420150aa0)
	/home/jrh/go/src/github.com/spf13/cobra/command.go:726 +0x339
github.com/spf13/cobra.(*Command).Execute(0xc420081200, 0x1aa6520, 0x16b10c0)
	/home/jrh/go/src/github.com/spf13/cobra/command.go:685 +0x2b
main.main()
	/home/jrh/go/src/github.com/NebulousLabs/Sia/siad/main.go:174 +0x79d
Critical error: accept tcp 127.0.0.1:9980: accept: too many open files in system
Please submit a bug report here: https://github.com/NebulousLabs/Sia/issues
Closing renter...

**Comment by travishoyt** [comment] 2017-07-04 12:12
Having the same issue on Mac OS X v10.12.5

**Comment by Merkin** [comment] 2017-07-04 15:54
Having similar issue but not as detailed log:

Siad has exited unexpectedly. Please submit a bug report including the error log here.

Error Log:
Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 0.057619671 seconds

**Comment by ninjabini** [comment] 2017-07-10 20:04
Having the same exact problem as Merkin here

**Comment by lukechampine** [comment] 2017-07-28 22:52
duplicate of #1840

**Closed by lukechampine** 2017-07-28 22:52 UTC
