### ISSUE TITLE
Host earnings are not reflected in Wallet

### ISSUE THREAD

**Issue by JamesM424** [NebulousLabs/Sia#1933] opened 2017-06-14 19:42 UTC
Here's the thing.  With my current problem with error https://github.com/NebulousLabs/Sia/issues/1880 I've had to monitor my wallet a bit more than would be expected.  

I took a screenshot of of my hosting module on 10-June as I've been a bit skeptical which shows 287.48 as "earned".  

![6-10](https://user-images.githubusercontent.com/28582587/27150536-9def295e-5115-11e7-823e-6b961a768659.jpg)

Today after some system maintenance, I loaded the Sia-UI and it displayed 307.5SC earned.  Yay!  I earned  30 cents. 

![6-14 2](https://user-images.githubusercontent.com/28582587/27150632-f506ab04-5115-11e7-9c06-fd8f248da3d1.jpg)

 (Ok - back to business after a bad joke)  I looked back through my wallet history to see there were no transactions giving me that 20 SC for the last 4 days... Thinking ok, maybe it just wasn't refreshed as is reported in bug 1751 https://github.com/NebulousLabs/Sia/issues/1751

![6-14](https://user-images.githubusercontent.com/28582587/27150623-f12d5884-5115-11e7-87ba-eb4f0aa082e0.jpg)

Confused.  I dumped my entire wallet history for both my renters and hosts for the last 2 months.  Not a single deposit even though my secondary host has been having contracts come up for renewal/completion as it's been up longer and I started with just offering 12 week contracts.

[SiaWallet1.xlsx](https://github.com/NebulousLabs/Sia/files/1075701/SiaWallet1.xlsx)

What's even more confusing, is on the secondary host, I can see in the logs it is renewing or attempting to renew contracts.  But the collateral has also never been returned...

**Comment by tbenz9** [comment] 2017-10-12 21:51
Based on your comments on #2138 you have an understanding of what went happened.  If you want to submit a feature request or bug report I suggest you open a new Github Issue that more specifically requests a feature or outlines what you think the bug is.  I'm not sure if this is Sia-UI or Sia core related but if it's UI related make sure you open it in the Sia-UI repo.

Recommendation to devs: close

**Comment by JamesM424** [comment] 2017-10-12 22:16
tbenz9 - What would be the purpose of closing one and opening another worded slightly different?  

The title is stated as "Host earnings are not reflected in Wallet".  It could be phrased as "Host earnings should be reflected in wallet", but I think it's easy to understand.

If you want me too, I certainly can.  

On average, I link to this bug about 3 times a month from generally new users who are confused.

**Comment by tbenz9** [comment] 2017-10-12 22:22
It's totally up to you, and you're right the title is very clear.  When I read the issue it sounded like you were confused and I didn't see a specific suggestion.  Perhaps you could include a specific action you would like the devs to take?  Something like "Feature Request: The Sia wallet should show deposits from hosting."

Cheers!

**Comment by JamesM424** [comment] 2017-10-12 23:08
Hows this...
https://github.com/NebulousLabs/Sia/issues/2420

**Comment by tbenz9** [comment] 2017-10-12 23:22
@lukechampine, this can now be closed as a duplicate of #2420

**Closed** 2017-10-12 23:23 UTC
Labels: Feature Request
