### ISSUE TITLE
Too many open files err

### ISSUE THREAD

**Issue by zzzmanzzz** [NebulousLabs/Sia#2035] opened 2017-06-27 15:04 UTC
Env ubuntu 16.04
Sia 1.2.2

2017/06/27 09:02:36 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s

Wallet: scanned to height 63081...2017/06/27 09:02:37 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
2017/06/27 09:02:37 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
2017/06/27 09:02:37 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
2017/06/27 09:02:37 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
2017/06/27 09:02:37 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
2017/06/27 09:02:37 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
2017/06/27 09:02:37 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
2017/06/27 09:02:37 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 10ms
2017/06/27 09:02:37 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 20ms
2017/06/27 09:02:37 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 40ms
2017/06/27 09:02:37 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 80ms
2017/06/27 09:02:37 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 160ms
2017/06/27 09:02:37 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 320ms
2017/06/27 09:02:38 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 640ms
2017/06/27 09:02:38 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s

Wallet: scanned to height 63251...2017/06/27 09:02:39 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
2017/06/27 09:02:39 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
2017/06/27 09:02:39 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
2017/06/27 09:02:39 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
2017/06/27 09:02:39 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 10ms
2017/06/27 09:02:39 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 20ms
2017/06/27 09:02:39 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 40ms
2017/06/27 09:02:40 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
2017/06/27 09:02:40 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
2017/06/27 09:02:40 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 10ms
2017/06/27 09:02:40 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 20ms
2017/06/27 09:02:40 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 40ms
2017/06/27 09:02:40 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 80ms
2017/06/27 09:02:40 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 160ms
2017/06/27 09:02:40 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 320ms
2017/06/27 09:02:40 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 640ms
2017/06/27 09:02:41 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/06/27 09:02:42 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s

Wallet: scanned to height 63439...2017/06/27 09:02:43 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/06/27 09:02:44 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
2017/06/27 09:02:44 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
2017/06/27 09:02:44 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 10ms
2017/06/27 09:02:44 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 20ms
2017/06/27 09:02:44 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 40ms
2017/06/27 09:02:44 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 80ms
2017/06/27 09:02:44 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
2017/06/27 09:02:44 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
2017/06/27 09:02:44 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 10ms
2017/06/27 09:02:44 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 20ms
2017/06/27 09:02:44 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 40ms
2017/06/27 09:02:44 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 80ms
2017/06/27 09:02:44 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 160ms
2017/06/27 09:02:44 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 320ms
2017/06/27 09:02:45 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 640ms
2017/06/27 09:02:45 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
2017/06/27 09:02:45 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 10ms
2017/06/27 09:02:45 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 20ms
2017/06/27 09:02:45 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 40ms
2017/06/27 09:02:45 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 80ms

Wallet: scanned to height 63635...2017/06/27 09:02:45 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 160ms
2017/06/27 09:02:46 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 320ms
2017/06/27 09:02:46 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 640ms
2017/06/27 09:02:47 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/06/27 09:02:48 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s

Wallet: scanned to height 63802...2017/06/27 09:02:49 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
goroutine 567439 [running]:
runtime/debug.Stack(0x445617, 0x0, 0xc422fcad68)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x79
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/NebulousLabs/Sia/build.Severe(0xc422fcaec0, 0x2, 0x2)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/build/critical.go:32 +0x92
github.com/NebulousLabs/Sia/persist.(*Logger).Severe(0xc4203f6c40, 0xc422fcaec0, 0x2, 0x2)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/persist/log.go:71 +0xe0
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).commit.func1(0xc4216e4020, 0xc420286668)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:167 +0x227
created by github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).commit
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:184 +0x15d
Severe error: Unable to open temporary settings file for writing: open /home/zzzman/.config/Sia-UI/sia/host/contractmanager/contractmanager.json_temp: too many open files
2017/06/27 09:02:49 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
2017/06/27 09:02:49 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 10ms
2017/06/27 09:02:49 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 20ms
2017/06/27 09:02:49 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 40ms
2017/06/27 09:02:49 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
2017/06/27 09:02:49 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
2017/06/27 09:02:49 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
2017/06/27 09:02:49 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 10ms
2017/06/27 09:02:49 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 20ms
2017/06/27 09:02:49 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 40ms
2017/06/27 09:02:49 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 80ms
2017/06/27 09:02:49 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 160ms
2017/06/27 09:02:49 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 320ms
goroutine 567491 [running]:
runtime/debug.Stack(0x445617, 0x0, 0xc422fcadc8)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x79
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/NebulousLabs/Sia/build.Severe(0xc422fcaf60, 0x2, 0x2)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/build/critical.go:32 +0x92
github.com/NebulousLabs/Sia/persist.(*Logger).Severe(0xc4203f6c40, 0xc422fcaf60, 0x2, 0x2)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/persist/log.go:71 +0xe0
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).syncResources.func1(0xc4262a27e0, 0xc420286668)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:32 +0x269
created by github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).syncResources
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:52 +0x93
Severe error: ERROR: unable to sync the contract manager settings: invalid argument
goroutine 567491 [running]:
runtime/debug.Stack(0x445617, 0x0, 0xc422fcadc8)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x79
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/NebulousLabs/Sia/build.Severe(0xc422fcaf20, 0x2, 0x2)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/build/critical.go:32 +0x92
github.com/NebulousLabs/Sia/persist.(*Logger).Severe(0xc4203f6c40, 0xc422fcaf20, 0x2, 0x2)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/persist/log.go:71 +0xe0
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).syncResources.func1(0xc4262a27e0, 0xc420286668)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:50 +0x4ea
created by github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).syncResources
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:52 +0x93
Severe error: ERROR: unable to atomically copy the contract manager settings: rename /home/zzzman/.config/Sia-UI/sia/host/contractmanager/contractmanager.json_temp /home/zzzman/.config/Sia-UI/sia/host/contractmanager/contractmanager.json: no such file or directory
goroutine 567493 [running]:
runtime/debug.Stack(0x445617, 0x0, 0xc422fcad68)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x79
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/NebulousLabs/Sia/build.Severe(0xc422fcaec0, 0x2, 0x2)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/build/critical.go:32 +0x92
github.com/NebulousLabs/Sia/persist.(*Logger).Severe(0xc4203f6c40, 0xc422fcaec0, 0x2, 0x2)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/persist/log.go:71 +0xe0
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).commit.func1(0xc4262a27f0, 0xc420286668)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:167 +0x227
created by github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).commit
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:184 +0x15d
Severe error: Unable to open temporary settings file for writing: open /home/zzzman/.config/Sia-UI/sia/host/contractmanager/contractmanager.json_temp: too many open files
2017/06/27 09:02:49 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 640ms
goroutine 567495 [running]:
runtime/debug.Stack(0x445617, 0x0, 0xc42d5a5dc8)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x79
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/NebulousLabs/Sia/build.Severe(0xc42d5a5f60, 0x2, 0x2)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/build/critical.go:32 +0x92
github.com/NebulousLabs/Sia/persist.(*Logger).Severe(0xc4203f6c40, 0xc42d5a5f60, 0x2, 0x2)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/persist/log.go:71 +0xe0
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).syncResources.func1(0xc440d8c000, 0xc420286668)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:32 +0x269
created by github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).syncResources
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:52 +0x93
Severe error: ERROR: unable to sync the contract manager settings: invalid argument
goroutine 567495 [running]:
runtime/debug.Stack(0x445617, 0x0, 0xc42d5a5dc8)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x79
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/NebulousLabs/Sia/build.Severe(0xc42d5a5f20, 0x2, 0x2)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/build/critical.go:32 +0x92
github.com/NebulousLabs/Sia/persist.(*Logger).Severe(0xc4203f6c40, 0xc42d5a5f20, 0x2, 0x2)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/persist/log.go:71 +0xe0
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).syncResources.func1(0xc440d8c000, 0xc420286668)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:50 +0x4ea
created by github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).syncResources
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:52 +0x93
Severe error: ERROR: unable to atomically copy the contract manager settings: rename /home/zzzman/.config/Sia-UI/sia/host/contractmanager/contractmanager.json_temp /home/zzzman/.config/Sia-UI/sia/host/contractmanager/contractmanager.json: no such file or directory
goroutine 567497 [running]:
runtime/debug.Stack(0x445617, 0x0, 0xc42d5a5d68)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x79
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/NebulousLabs/Sia/build.Severe(0xc42d5a5ec0, 0x2, 0x2)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/build/critical.go:32 +0x92
github.com/NebulousLabs/Sia/persist.(*Logger).Severe(0xc4203f6c40, 0xc42d5a5ec0, 0x2, 0x2)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/persist/log.go:71 +0xe0
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).commit.func1(0xc440d8c010, 0xc420286668)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:167 +0x227
created by github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).commit
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:184 +0x15d
Severe error: Unable to open temporary settings file for writing: open /home/zzzman/.config/Sia-UI/sia/host/contractmanager/contractmanager.json_temp: too many open files
2017/06/27 09:02:50 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
goroutine 567499 [running]:
runtime/debug.Stack(0x445617, 0x0, 0xc43184cdc8)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x79
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/NebulousLabs/Sia/build.Severe(0xc43184cf60, 0x2, 0x2)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/build/critical.go:32 +0x92
github.com/NebulousLabs/Sia/persist.(*Logger).Severe(0xc4203f6c40, 0xc43184cf60, 0x2, 0x2)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/persist/log.go:71 +0xe0
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).syncResources.func1(0xc440d8c040, 0xc420286668)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:32 +0x269
created by github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).syncResources
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:52 +0x93
Severe error: ERROR: unable to sync the contract manager settings: invalid argument
goroutine 567499 [running]:
runtime/debug.Stack(0x445617, 0x0, 0xc43184cdc8)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x79
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/NebulousLabs/Sia/build.Severe(0xc43184cf20, 0x2, 0x2)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/build/critical.go:32 +0x92
github.com/NebulousLabs/Sia/persist.(*Logger).Severe(0xc4203f6c40, 0xc43184cf20, 0x2, 0x2)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/persist/log.go:71 +0xe0
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).syncResources.func1(0xc440d8c040, 0xc420286668)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:50 +0x4ea
created by github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).syncResources
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:52 +0x93
Severe error: ERROR: unable to atomically copy the contract manager settings: rename /home/zzzman/.config/Sia-UI/sia/host/contractmanager/contractmanager.json_temp /home/zzzman/.config/Sia-UI/sia/host/contractmanager/contractmanager.json: no such file or directory
2017/06/27 09:02:51 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s

Wallet: scanned to height 63983...2017/06/27 09:02:52 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
2017/06/27 09:02:52 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 10ms
2017/06/27 09:02:52 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 20ms
2017/06/27 09:02:52 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 40ms
2017/06/27 09:02:52 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 80ms
2017/06/27 09:02:52 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 160ms
2017/06/27 09:02:52 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 320ms
2017/06/27 09:02:53 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 640ms
2017/06/27 09:02:53 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/06/27 09:02:54 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s

Wallet: scanned to height 64175...2017/06/27 09:02:55 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/06/27 09:02:56 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/06/27 09:02:57 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
2017/06/27 09:02:57 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
2017/06/27 09:02:57 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 10ms
2017/06/27 09:02:57 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 20ms
2017/06/27 09:02:57 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 40ms
2017/06/27 09:02:57 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
2017/06/27 09:02:57 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 10ms
2017/06/27 09:02:57 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 20ms
2017/06/27 09:02:57 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 40ms
2017/06/27 09:02:57 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 80ms

Wallet: scanned to height 64328...2017/06/27 09:02:57 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 160ms
2017/06/27 09:02:58 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 320ms
2017/06/27 09:02:58 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 640ms
2017/06/27 09:02:59 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/06/27 09:03:00 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
2017/06/27 09:03:00 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
2017/06/27 09:03:00 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 10ms
2017/06/27 09:03:00 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 20ms
2017/06/27 09:03:00 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 40ms
2017/06/27 09:03:00 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 80ms
2017/06/27 09:03:00 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 160ms
2017/06/27 09:03:00 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 320ms
2017/06/27 09:03:00 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 640ms

Wallet: scanned to height 64487...2017/06/27 09:03:01 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/06/27 09:03:02 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/06/27 09:03:03 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s

Wallet: scanned to height 64670...2017/06/27 09:03:04 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
2017/06/27 09:03:04 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 10ms
2017/06/27 09:03:04 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 20ms
2017/06/27 09:03:04 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 40ms
2017/06/27 09:03:04 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 80ms
2017/06/27 09:03:04 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
2017/06/27 09:03:04 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
2017/06/27 09:03:04 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
goroutine 567629 [running]:
runtime/debug.Stack(0x445617, 0x0, 0xc434158c80)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x79
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/NebulousLabs/Sia/build.Severe(0xc434158e78, 0x2, 0x2)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/build/critical.go:32 +0x92
github.com/NebulousLabs/Sia/persist.(*Logger).Severe(0xc4203f6c40, 0xc434158e78, 0x2, 0x2)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/persist/log.go:71 +0xe0
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).commit.func2(0xc435b41680, 0xc420286668, 0x0, 0x0, 0x0, 0xebc2b0, 0x0, 0x0)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:196 +0x236
created by github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).commit
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:209 +0x1e5
Severe error: ERROR: unable to create write-ahead-log: open /home/zzzman/.config/Sia-UI/sia/host/contractmanager/contractmanager.wal_temp: too many open files
goroutine 567629 [running]:
runtime/debug.Stack(0x445617, 0x0, 0xc434158c80)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x79
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/NebulousLabs/Sia/build.Severe(0xc434158e58, 0x2, 0x2)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/build/critical.go:32 +0x92
github.com/NebulousLabs/Sia/persist.(*Logger).Severe(0xc4203f6c40, 0xc434158e58, 0x2, 0x2)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/persist/log.go:71 +0xe0
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).commit.func2(0xc435b41680, 0xc420286668, 0x0, 0x0, 0x0, 0xebc2b0, 0x0, 0x0)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:201 +0x357
created by github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).commit
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:209 +0x1e5
Severe error: Unable to properly initialize WAL file, crashing to prevent corruption: unable to write WAL metadata: invalid argument
goroutine 567629 [running]:
runtime/debug.Stack(0x445617, 0x0, 0xc434158aa0)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x79
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/NebulousLabs/Sia/build.Severe(0xc434158c18, 0x2, 0x2)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/build/critical.go:32 +0x92
github.com/NebulousLabs/Sia/persist.(*Logger).Severe(0xc4203f6c40, 0xc434158c18, 0x2, 0x2)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/persist/log.go:71 +0xe0
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).appendChange(0xc420286668, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlog.go:151 +0x46e
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).commit.func2(0xc435b41680, 0xc420286668, 0x0, 0x0, 0x0, 0xebc2b0, 0x0, 0x0)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:208 +0x423
created by github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).commit
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:209 +0x1e5
Severe error: Unable to write state change to WAL: invalid argument
panic: unable to append a change to the WAL, crashing to prevent corruption

goroutine 567629 [running]:
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).appendChange(0xc420286668, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlog.go:152 +0x4b8
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).commit.func2(0xc435b41680, 0xc420286668, 0x0, 0x0, 0x0, 0xebc2b0, 0x0, 0x0)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:208 +0x423
created by github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).commit
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:209 +0x1e5

**Comment by lukechampine** [comment] 2017-06-27 16:43
duplicate of https://github.com/NebulousLabs/Sia/issues/1840

**Closed by lukechampine** 2017-06-27 16:43 UTC
