### ISSUE TITLE
Critical error: negative currency not allowed

### ISSUE THREAD

**Issue by hackneyb** [NebulousLabs/Sia#2924] opened 2018-04-07 00:12 UTC
# BUG REPORT

**Stack Trace or error message**

```
C:\Users\Admin\Desktop>"C:\Program Files\Sia-UI-v1.3.2-win32-x64\resources\app\Sia\siad.exe" -M gctwhr -d C:\Users\Admin\AppData\Roaming\Sia-UI\sia
Sia Daemon v1.3.2
Git Revision 72938f5
Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 30.7052031 seconds
goroutine 61365779 [running]:
runtime/debug.Stack(0x446dee, 0x0, 0xc04c9bbef8)
        /usr/local/go/src/runtime/debug/stack.go:24 +0xae
runtime/debug.PrintStack()
        /usr/local/go/src/runtime/debug/stack.go:16 +0x29
github.com/NebulousLabs/Sia/build.Critical(0xc04c9bbfa0, 0x1, 0x1)
        /home/luke/go/src/github.com/NebulousLabs/Sia/build/critical.go:16 +0x9a
github.com/NebulousLabs/Sia/types.Currency.Sub(0x0, 0xc042b8c600, 0x2, 0x6, 0x0, 0xc0441d9540, 0x2, 0x7, 0xf83b00, 0xc042b8c600, ...)
        /home/luke/go/src/github.com/NebulousLabs/Sia/types/currency.go:179 +0x14c
github.com/NebulousLabs/Sia/modules/host.renewContractCollateral(0xc042062000, 0x3, 0x4, 0x0, 0xc045f21bc0, 0x2, 0x5, 0x0, 0xc045f21bf0, 0x2, ...)
        /home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/negotiaterenewcontract.go:44 +0xad
github.com/NebulousLabs/Sia/modules/host.(*Host).managedVerifyRenewedContract(0xc0420a8580, 0xc042062000, 0x3, 0x4, 0x0, 0xc045f21bc0, 0x2, 0x5, 0x0, 0xc045f21bf0, ...)
        /home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/negotiaterenewcontract.go:266 +0x65c
github.com/NebulousLabs/Sia/modules/host.(*Host).managedRPCRenewContract(0xc0420a8580, 0xdf7d80, 0xc042168288, 0x0, 0x0)
        /home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/negotiaterenewcontract.go:126 +0x434
github.com/NebulousLabs/Sia/modules/host.(*Host).threadedHandleConn(0xc0420a8580, 0xdf7d80, 0xc042168288)
        /home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/network.go:286 +0x80b
created by github.com/NebulousLabs/Sia/modules/host.(*Host).threadedListen
        /home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/network.go:322 +0xca
Critical error: negative currency not allowed
Please submit a bug report here: https://github.com/NebulousLabs/Sia/issues

```

**Expected Behavior**
No known issue reported - only the debug trace above and these host.log entries which COULD be related.  Unable to pinpoint exact error time.

```
2018/04/05 16:44:21.917236 storageobligations.go:735: Error submitting transaction to transaction pool consensus conflict: provided transaction set has prereqs, but is still invalid: siacoin inputs do not equal siacoin outputs for transaction
2018/04/05 16:55:53.065787 errors.go:151: internal error: error with 35.231.148.56:39918: incoming RPCFormContract failed: contract verification failed: host has reached its collateral budget and cannot accept the file contract
2018/04/05 17:02:23.865222 storageobligations.go:723: Error funding transaction fees wallet has coins spent in incomplete transactions - not enough remaining coins
2018/04/05 17:02:23.865222 storageobligations.go:727: Error adding miner fees wallet has coins spent in incomplete transactions - not enough remaining coins
2018/04/05 17:02:24.120233 storageobligations.go:735: Error submitting transaction to transaction pool consensus conflict: provided transaction set is standalone and invalid: siacoin inputs do not equal siacoin outputs for transaction
2018/04/05 17:02:24.322513 storageobligations.go:723: Error funding transaction fees wallet has coins spent in incomplete transactions - not enough remaining coins
2018/04/05 17:02:24.322513 storageobligations.go:727: Error adding miner fees wallet has coins spent in incomplete transactions - not enough remaining coins
2018/04/05 17:02:24.471523 storageobligations.go:735: Error submitting transaction to transaction pool consensus conflict: provided transaction set has prereqs, but is still invalid: siacoin inputs do not equal siacoin outputs for transaction
2018/04/05 17:02:24.472523 storageobligations.go:723: Error funding transaction fees wallet has coins spent in incomplete transactions - not enough remaining coins
2018/04/05 17:02:24.472523 storageobligations.go:727: Error adding miner fees wallet has coins spent in incomplete transactions - not enough remaining coins
2018/04/05 17:02:24.518524 storageobligations.go:723: Error funding transaction fees wallet has coins spent in incomplete transactions - not enough remaining coins
2018/04/05 17:02:24.518524 storageobligations.go:727: Error adding miner fees wallet has coins spent in incomplete transactions - not enough remaining coins
```

**How to reproduce it (as minimally and precisely as possible)**
Host for 3 months.  Run out of collateral budget.  Possibly.  

**Environment**
* Sia version: 1.3.2
* OS: Windows Server 2012 R2

**Comment by Bojak4616** [comment] 2018-04-07 14:31
I saw this on my host as well, not sure what the root cause could be. Host.log wasn't very helping in digging around. @hackneyb is your host still able to function? A while after I saw that my host stopped responding and was showing up as not connectable with close to 0 RPC calls.

**Comment by hackneyb** [comment] 2018-04-08 15:31
Yes, still functional, getting contracts, increasing storage use, changing stats.  siad hasn't crashed or stopped.    My host.log is full of messages I don't understand fully, and error in siade console isn't dated, so hard to pinpoint to any specific log entry.

**Comment by tbenz9** [comment] 2018-04-19 17:46
Duplicate of #2733

If you wait for a few blocks to pass do you still get this error?

**Closed by tbenz9** 2018-04-19 17:46 UTC
