### ISSUE TITLE
Forming contracts stuck

### ISSUE THREAD

**Issue by hosiawak** [NebulousLabs/Sia#1559] opened 2017-01-24 12:18 UTC
I tried paying 2000 SC to test uploading of some files.
It's been stuck with a spinning circle and "Forming contracts" message for the past hour.

**Comment by Fornax96** [comment] 2017-01-24 12:45
That's normal. Are you seeing outgoing transactions in your wallet? The forming of contracts will be done once all outgoing transactions are confirmed.

**Comment by DavidVorick** [comment] 2017-01-25 07:08
Closing because it seems to be a non-issue, feel free to re-open if your contracts still haven't finished forming.

Would like to add that we have a development plan in place to get this time down from about 40 minutes to less than 3 minutes, though there's a pretty big development backlog at the moment, so it might be a few weeks.

**Closed by DavidVorick** 2017-01-25 07:08 UTC
