### ISSUE TITLE
Sia Bug

### ISSUE THREAD

**Issue by LLLminer** [NebulousLabs/Sia#3095] opened 2018-06-11 02:34 UTC
# BUG REPORT
Sia Daemon v1.3.2
Git Revision 72938f5
Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 0.5930503 seconds

**Comment by MSevey** [comment] 2018-06-11 15:19
@LLLminer this is not a bug, this is how siad loads.  Now in a separate terminal screen you should be able to use `siac` commands.

Please take a look at some of the documentation or reach out to the help channel on discord if you have more questions.  I will close this issue.

**Closed by MSevey** 2018-06-11 15:19 UTC
