### ISSUE TITLE
error log

### ISSUE THREAD

**Issue by nuriberberoglu** [NebulousLabs/Sia#2033] opened 2017-06-27 02:51 UTC
Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 0.644206856 seconds

Wallet: scanned to height 102258...
Wallet: scanned to height 102469...
Wallet: scanned to height 102655...
Wallet: scanned to height 102827...
Wallet: scanned to height 102978...
Wallet: scanned to height 103127...
Wallet: scanned to height 103232...
Wallet: scanned to height 103364...
Wallet: scanned to height 103463...
Wallet: scanned to height 103540...
Wallet: scanned to height 103616...
Wallet: scanned to height 103734...
Wallet: scanned to height 103844...
Wallet: scanned to height 103966...
Wallet: scanned to height 104139...
Wallet: scanned to height 104296...
Wallet: scanned to height 104473...
Wallet: scanned to height 104602...
Wallet: scanned to height 104779...
Wallet: scanned to height 104999...
Wallet: scanned to height 105201...
Wallet: scanned to height 105432...
Wallet: scanned to height 105872...
Wallet: scanned to height 106193...
Wallet: scanned to height 106633...
Wallet: scanned to height 107073...
Wallet: scanned to height 107311...
Wallet: scanned to height 107531...
Wallet: scanned to height 107742...
Wallet: scanned to height 107961...
Wallet: scanned to height 108353...
Wallet: scanned to height 108652...
Wallet: scanned to height 108939...
Wallet: scanned to height 109281...
Wallet: scanned to height 109618...
Wallet: scanned to height 109897...
Wallet: scanned to height 110146...
Wallet: scanned to height 110357...
Wallet: scanned to height 110644...
Wallet: scanned to height 110903...
Wallet: scanned to height 111077...
Wallet: scanned to height 111394...
Done!
goroutine 1 [running]:
runtime/debug.Stack(0x1043857, 0x0, 0xc42101b5f8)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x79
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/NebulousLabs/Sia/build.Critical(0xc42101b948, 0x1, 0x1)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/build/critical.go:16 +0xa7
main.startDaemon(0x0, 0x0, 0x7fff5fbffcef, 0xe, 0x7fff5fbffd1b, 0x5, 0x7fff5fbffd0a, 0x5, 0x0, 0x7fff5fbffd78, ...)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/siad/daemon.go:295 +0xaa9
main.startDaemonCmd(0xc42008b200, 0xc42008d2c0, 0x0, 0x5)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/siad/daemon.go:309 +0x6d
github.com/spf13/cobra.(*Command).execute(0xc42008b200, 0xc420060070, 0x5, 0x5, 0xc42008b200, 0xc420060070)
	/home/jrh/go/src/github.com/spf13/cobra/command.go:651 +0x23a
github.com/spf13/cobra.(*Command).ExecuteC(0xc42008b200, 0x16c7c0f, 0x3b, 0xc42015eaa0)
	/home/jrh/go/src/github.com/spf13/cobra/command.go:726 +0x339
github.com/spf13/cobra.(*Command).Execute(0xc42008b200, 0x1aa6520, 0x16b10c0)
	/home/jrh/go/src/github.com/spf13/cobra/command.go:685 +0x2b
main.main()
	/home/jrh/go/src/github.com/NebulousLabs/Sia/siad/main.go:174 +0x79d
Critical error: accept tcp 127.0.0.1:9980: accept: too many open files in system
Please submit a bug report here: https://github.com/NebulousLabs/Sia/issues
Closing renter...
Closing host...

**Comment by lukechampine** [comment] 2017-07-28 22:49
duplicate of #1840

**Closed by lukechampine** 2017-07-28 22:49 UTC
