### ISSUE TITLE
SIGSEGV on siac host folder add

### ISSUE THREAD

**Issue by galeone** [NebulousLabs/Sia#2267] opened 2017-08-29 07:18 UTC
I'm trying to set up a sia host following the official guide: https://blog.sia.tech/how-to-run-a-host-on-sia-2159ebc4725

Everything was running fine until I executed `siac host folder add /home/plox/sia/storage/ 250GB`.
This command made `siad` crash with a SIGSEVG. Here's the output:

```
Loading...                                                         
(0/5) Loading siad...                                              
(1/5) Loading gateway...                                           
(2/5) Loading consensus...                                         
(3/5) Loading transaction pool...                                  
(4/5) Loading wallet...                                            
(5/5) Loading host...                                              
Finished loading in 5.046611144 seconds                            
panic: runtime error: invalid memory address or nil pointer dereference                                                                
[signal SIGSEGV: segmentation violation code=0x1 addr=0x4 pc=0x11c50]                                                                  

goroutine 308 [running]:                                           
sync/atomic.addUint64(0x10f5844c, 0x100000, 0x0, 0x10c68020, 0x1fd64)                                                                  
        /usr/lib/go/src/sync/atomic/64bit_arm.go:31 +0x4c          
github.com/NebulousLabs/Sia/sync.(*TryRWMutex).Lock(0x10f5844c)    
        /home/plox/go/src/github.com/NebulousLabs/Sia/sync/tryrwmutex.go:30 +0x30                                                      
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).managedAddStorageFolder(0x11071648, 0x10f583f0, 0x0, 0x0)    
        /home/plox/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/storagefolderadd.go:97 +0x38                        
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*ContractManager).AddStorageFolder(0x110715c0, 0x10ffeba5, 0x16, 0x30000000, 0x3a, 0x0, 0x0)                                                                                                                         
        /home/plox/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/storagefolderadd.go:370 +0x2a4                      
github.com/NebulousLabs/Sia/modules/host.(*Host).AddStorageFolder(0x10c78e00, 0x10ffeba5, 0x16, 0x30000000, 0x3a, 0x1, 0x0)            
        <autogenerated>:38 +0x6c                                   
github.com/NebulousLabs/Sia/api.(*API).storageFoldersAddHandler(0x10c9a280, 0x834ab8, 0x10f582d0, 0x10ec2100, 0x0, 0x0, 0x0)           
        /home/plox/go/src/github.com/NebulousLabs/Sia/api/host.go:300 +0x108                                                           
github.com/NebulousLabs/Sia/api.(*API).(github.com/NebulousLabs/Sia/api.storageFoldersAddHandler)-fm(0x834ab8, 0x10f582d0, 0x10ec2100, 0x0, 0x0, 0x0)                                                                                                                          
        /home/plox/go/src/github.com/NebulousLabs/Sia/api/api.go:222 +0x4c                                                             
github.com/julienschmidt/httprouter.(*Router).ServeHTTP(0x10e5b060, 0x834ab8, 0x10f582d0, 0x10ec2100)                                  
        /home/plox/go/src/github.com/julienschmidt/httprouter/router.go:344 +0x698                                                     
github.com/NebulousLabs/Sia/api.RequireUserAgent.func1(0x834ab8, 0x10f582d0, 0x10ec2100)                                               
        /home/plox/go/src/github.com/NebulousLabs/Sia/api/api.go:99 +0x98                                                              
net/http.HandlerFunc.ServeHTTP(0x10e5b140, 0x834ab8, 0x10f582d0, 0x10ec2100)                                                           
        /usr/lib/go/src/net/http/server.go:1942 +0x34              
github.com/NebulousLabs/Sia/api.cleanCloseHandler.func1.1(0x10e3a400, 0x832498, 0x10e5b140, 0x834ab8, 0x10f582d0, 0x10ec2100)          
        /home/plox/go/src/github.com/NebulousLabs/Sia/api/api.go:132 +0x60                                                             
created by github.com/NebulousLabs/Sia/api.cleanCloseHandler.func1 
        /home/plox/go/src/github.com/NebulousLabs/Sia/api/api.go:133 +0x84         
```

I'm running it on a raspberry pi 3.

**Comment by lukechampine** [comment] 2017-08-29 13:35
Looks like a duplicate of https://github.com/NebulousLabs/Sia/issues/2250. Please try the fix posted there

**Closed by lukechampine** 2017-08-29 13:35 UTC
