### ISSUE TITLE
Siad has crashed unexpectedly.

### ISSUE THREAD

**Issue by dpetrek** [NebulousLabs/Sia#2655] opened 2018-01-14 17:33 UTC
# BUG REPORT

**Stack Trace or error message**
Sia Daemon v1.3.1
Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 15.984375 seconds
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x18 pc=0x502d7a]

goroutine 743751 [running]:
bufio.(*Writer).Available(...)
	/usr/local/go/src/bufio/bufio.go:584
bufio.(*Writer).Write(0x0, 0xc0872c4000, 0x24b60, 0x32d50, 0xc042c11ae8, 0x1, 0x1)
	/usr/local/go/src/bufio/bufio.go:594 +0x7a
net/http.(*chunkWriter).Write(0xc080486e38, 0xc0872c4000, 0x24b60, 0x32d50, 0xc043d31b28, 0xc042c11b48, 0xc042c11b68)
	/usr/local/go/src/net/http/server.go:364 +0xb2
bufio.(*Writer).Write(0xc08dd18c40, 0xc0872c4000, 0x24b60, 0x32d50, 0x0, 0xc042c11be8, 0x5256d9)
	/usr/local/go/src/bufio/bufio.go:599 +0x156
net/http.(*response).write(0xc080486e00, 0x24b60, 0xc0872c4000, 0x24b60, 0x32d50, 0x0, 0x0, 0xc0430fa690, 0x99, 0x100)
	/usr/local/go/src/net/http/server.go:1500 +0x157
net/http.(*response).Write(0xc080486e00, 0xc0872c4000, 0x24b60, 0x32d50, 0x0, 0x0, 0xac206e)
	/usr/local/go/src/net/http/server.go:1470 +0x6b
encoding/json.(*Encoder).Encode(0xc042c11d08, 0xa31060, 0xc0430fa690, 0xde4cc0, 0xc080486e00)
	/usr/local/go/src/encoding/json/stream.go:218 +0x1e9
github.com/NebulousLabs/Sia/api.WriteJSON(0xdea8c0, 0xc080486e00, 0xa31060, 0xc0430fa690)
	/home/luke/go/src/github.com/NebulousLabs/Sia/api/api.go:151 +0x112
github.com/NebulousLabs/Sia/api.(*API).walletTransactionsHandler(0xc042144360, 0xdea8c0, 0xc080486e00, 0xc07fca8d00, 0x0, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/api/wallet.go:522 +0x30b
github.com/NebulousLabs/Sia/api.(*API).(github.com/NebulousLabs/Sia/api.walletTransactionsHandler)-fm(0xdea8c0, 0xc080486e00, 0xc07fca8d00, 0x0, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/api/routes.go:121 +0x6d
github.com/julienschmidt/httprouter.(*Router).ServeHTTP(0xc042de46c0, 0xdea8c0, 0xc080486e00, 0xc07fca8d00)
	/home/luke/go/src/github.com/julienschmidt/httprouter/router.go:344 +0x7a0
github.com/NebulousLabs/Sia/api.RequireUserAgent.func1(0xdea8c0, 0xc080486e00, 0xc07fca8d00)
	/home/luke/go/src/github.com/NebulousLabs/Sia/api/routes.go:173 +0xc1
net/http.HandlerFunc.ServeHTTP(0xc043da43f0, 0xdea8c0, 0xc080486e00, 0xc07fca8d00)
	/usr/local/go/src/net/http/server.go:1918 +0x4b
github.com/NebulousLabs/Sia/api.cleanCloseHandler.func1.1(0xc0442a4480, 0xde5f80, 0xc043da43f0, 0xdea8c0, 0xc080486e00, 0xc07fca8d00)
	/home/luke/go/src/github.com/NebulousLabs/Sia/api/routes.go:143 +0x80
created by github.com/NebulousLabs/Sia/api.cleanCloseHandler.func1
	/home/luke/go/src/github.com/NebulousLabs/Sia/api/routes.go:141 +0xbe

**Expected Behavior**

**How to reproduce it (as minimally and precisely as possible)**
One file was uploading while this crashed, nothing fancy happening.
I found it like this.

**Environment**
* Sia version:
1.3.1
* OS:
Windows 7 64 bit

**Comment by tbenz9** [comment] 2018-01-16 00:40
Duplicate of #2374

**Closed by tbenz9** 2018-01-16 00:40 UTC
