### ISSUE TITLE
Siad has exited unexpectedly. Please submit a bug report including the error log 

### ISSUE THREAD

**Issue by JerryLerman** [NebulousLabs/Sia#2553] opened 2017-12-18 03:08 UTC
Windows 10 
Sia UI version: v1.3.0

Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 941.4885704 seconds

Wallet: scanned to height 135196...
Wallet: scanned to height 135196...
Wallet: scanned to height 135196...
Wallet: scanned to height 135196...
Wallet: scanned to height 135196...
Wallet: scanned to height 135196...
Wallet: scanned to height 135196...
Wallet: scanned to height 135196...
Wallet: scanned to height 135196...
Wallet: scanned to height 135196...
Wallet: scanned to height 135196...
Wallet: scanned to height 135196...
Wallet: scanned to height 135196...
Wallet: scanned to height 135196...
Wallet: scanned to height 135208...
Wallet: scanned to height 135238...
Wallet: scanned to height 135257...
Wallet: scanned to height 135275...
Wallet: scanned to height 135313...
Wallet: scanned to height 135338...
Wallet: scanned to height 135364...
Wallet: scanned to height 135423...
Wallet: scanned to height 135468...
Wallet: scanned to height 135498...
Wallet: scanned to height 135523...
Wallet: scanned to height 135561...
Wallet: scanned to height 135594...
Wallet: scanned to height 135616...
Wallet: scanned to height 135639...
Wallet: scanned to height 135673...
Wallet: scanned to height 135715...
Wallet: scanned to height 135772...
Wallet: scanned to height 135850...
Wallet: scanned to height 135907...
Wallet: scanned to height 135957...
Wallet: scanned to height 136022...
Wallet: scanned to height 136049...
Wallet: scanned to height 136085...
Wallet: scanned to height 136114...
Wallet: scanned to height 136153...
Wallet: scanned to height 136191...
Wallet: scanned to height 136224...
Wallet: scanned to height 136255...
Wallet: scanned to height 136272...
Wallet: scanned to height 136355...
Wallet: scanned to height 136355...
Wallet: scanned to height 136355...
Wallet: scanned to height 136355...
Wallet: scanned to height 136355...
Wallet: scanned to height 136355...
Wallet: scanned to height 136355...
Wallet: scanned to height 136355...
Wallet: scanned to height 136355...
Wallet: scanned to height 136355...
Wallet: scanned to height 136355...
Wallet: scanned to height 136355...
Wallet: scanned to height 136355...
Wallet: scanned to height 136355...
Wallet: scanned to height 136355...
Wallet: scanned to height 136355...
Wallet: scanned to height 136355...
Wallet: scanned to height 136355...
Wallet: scanned to height 136355...
Wallet: scanned to height 136355...
Wallet: scanned to height 136355...
Wallet: scanned to height 136355...
Wallet: scanned to height 136355...
Wallet: scanned to height 136355...
Wallet: scanned to height 136355...
Wallet: scanned to height 136355...
Wallet: scanned to height 136355...
Wallet: scanned to height 136355...
Wallet: scanned to height 136355...
Wallet: scanned to height 136355...
Wallet: scanned to height 136355...
Wallet: scanned to height 136355...
Wallet: scanned to height 136355...
Wallet: scanned to height 136355...
Wallet: scanned to height 136355...
Wallet: scanned to height 136355...
Wallet: scanned to height 136355...
Wallet: scanned to height 136355...
Wallet: scanned to height 136355...
Wallet: scanned to height 136355...
Wallet: scanned to height 136355...
Wallet: scanned to height 136355...
Wallet: scanned to height 136355...
Wallet: scanned to height 136355...
Wallet: scanned to height 136355...
Wallet: scanned to height 136355...
Wallet: scanned to height 136355...
Wallet: scanned to height 136355...
Wallet: scanned to height 136355...
Wallet: scanned to height 136355...
Wallet: scanned to height 136355...
Wallet: scanned to height 136355...
Wallet: scanned to height 136355...
Wallet: scanned to height 136355...
Wallet: scanned to height 136355...
Done!
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x28 pc=0x611bb2]

goroutine 3458688 [running]:
bufio.(*Writer).Write(0x0, 0xdd7160, 0x2, 0x2, 0xad7425, 0x7, 0xc04200c17c)

**Comment by tbenz9** [comment] 2017-12-18 21:49
Duplicate of #2374

**Closed by tbenz9** 2017-12-18 21:49 UTC
