### ISSUE TITLE
panic: page 38351 already freed during starting and sync

### ISSUE THREAD

**Issue by theporve** [NebulousLabs/Sia#2708] opened 2018-01-31 03:13 UTC
Hello this is the first time I tried to install the wallet. After install and wallet created. I have seen and error every time and can not continues with the sync stopping at 78.9 % since two days ago...  I closed the app a couple of time with the same results.

* OS: Win10 64 bits

Sia Daemon v1.3.1
Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 0.9526351 seconds
panic: page 38351 already freed

goroutine 15 [running]:
github.com/NebulousLabs/bolt.(*freelist).free(0xc0421c8240, 0x2d86, 0x895bf000)
	/home/luke/go/src/github.com/NebulousLabs/bolt/freelist.go:121 +0x308
github.com/NebulousLabs/bolt.(*node).spill(0xc043aab110, 0xc0434bc560, 0xdeaa80)
	/home/luke/go/src/github.com/NebulousLabs/bolt/node.go:363 +0x217
github.com/NebulousLabs/bolt.(*node).spill(0xc043aab0a0, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/bolt/node.go:350 +0xc6
github.com/NebulousLabs/bolt.(*node).spill(0xc042428460, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/bolt/node.go:350 +0xc6
github.com/NebulousLabs/bolt.(*node).spill(0xc04280a3f0, 0xc043066420, 0xc044ecac50)
	/home/luke/go/src/github.com/NebulousLabs/bolt/node.go:350 +0xc6
github.com/NebulousLabs/bolt.(*Bucket).spill(0xc042668ec0, 0xc044ecad00, 0x3)
	/home/luke/go/src/github.com/NebulousLabs/bolt/bucket.go:570 +0x4da
github.com/NebulousLabs/bolt.(*Bucket).spill(0xc0421cbcf8, 0x521c4a754, 0xefca20)
	/home/luke/go/src/github.com/NebulousLabs/bolt/bucket.go:537 +0x41e
github.com/NebulousLabs/bolt.(*Tx).Commit(0xc0421cbce0, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/bolt/tx.go:163 +0x130
github.com/NebulousLabs/bolt.(*DB).Update(0xc04205d2c0, 0xc042af12e8, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/bolt/db.go:610 +0xf9
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).managedAcceptBlocks(0xc0420b1b80, 0xc04248cc00, 0xa, 0xa, 0x0, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/accept.go:245 +0x4f9
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).managedReceiveBlocks(0xc0420b1b80, 0xdee020, 0xc043023880, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:225 +0x500
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).(github.com/NebulousLabs/Sia/modules/consensus.managedReceiveBlocks)-fm(0xdee020, 0xc043023880, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:445 +0x45
github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).managedRPC(0xc0420a69a0, 0xc0421d1680, 0x12, 0xac0d00, 0xa, 0xc0421589f0, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/rpc.go:66 +0x2c9
github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).RPC(0xc0420a69a0, 0xc0421d1680, 0x12, 0xac0d00, 0xa, 0xc0421589f0, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/rpc.go:76 +0xd8
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).threadedInitialBlockchainDownload.func1(0xc0420b1b80, 0xc044ecbef0, 0xc044ecbe98, 0xc044ecbea0, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:580 +0x12e
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).threadedInitialBlockchainDownload(0xc0420b1b80, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:601 +0x151
github.com/NebulousLabs/Sia/modules/consensus.New.func1(0x1, 0xc042142490, 0xc0420b1b80, 0xdee820, 0xc0420a69a0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/consensusset.go:151 +0x3eb
created by github.com/NebulousLabs/Sia/modules/consensus.New
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/consensusset.go:144 +0x656

**Comment by theporve** [comment] 2018-02-01 14:31
I have also this other issue:

Sia Daemon v1.3.1
Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 1.1667759 seconds
panic: page 38351 already freed

goroutine 66 [running]:
github.com/NebulousLabs/bolt.(*freelist).free(0xc04221a240, 0x2d88, 0x895bf000)
	/home/luke/go/src/github.com/NebulousLabs/bolt/freelist.go:121 +0x308
github.com/NebulousLabs/bolt.(*node).spill(0xc04417a0e0, 0xc045a18840, 0xdeaa80)
	/home/luke/go/src/github.com/NebulousLabs/bolt/node.go:363 +0x217
github.com/NebulousLabs/bolt.(*node).spill(0xc04417a070, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/bolt/node.go:350 +0xc6
github.com/NebulousLabs/bolt.(*node).spill(0xc042d89c00, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/bolt/node.go:350 +0xc6
github.com/NebulousLabs/bolt.(*node).spill(0xc04273bb90, 0xc0428060f0, 0xc044d0ac50)
	/home/luke/go/src/github.com/NebulousLabs/bolt/node.go:350 +0xc6
github.com/NebulousLabs/bolt.(*Bucket).spill(0xc042032cc0, 0xc044d0ad00, 0xd)
	/home/luke/go/src/github.com/NebulousLabs/bolt/bucket.go:570 +0x4da
github.com/NebulousLabs/bolt.(*Bucket).spill(0xc042d94018, 0x93beb8a04, 0xefca20)
	/home/luke/go/src/github.com/NebulousLabs/bolt/bucket.go:537 +0x41e
github.com/NebulousLabs/bolt.(*Tx).Commit(0xc042d94000, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/bolt/tx.go:163 +0x130
github.com/NebulousLabs/bolt.(*DB).Update(0xc04205d2c0, 0xc042d7d2e8, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/bolt/db.go:610 +0xf9
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).managedAcceptBlocks(0xc0420b1b80, 0xc04309f800, 0xa, 0xa, 0x0, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/accept.go:245 +0x4f9
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).managedReceiveBlocks(0xc0420b1b80, 0xdee020, 0xc04267e360, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:225 +0x500
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).(github.com/NebulousLabs/Sia/modules/consensus.managedReceiveBlocks)-fm(0xdee020, 0xc04267e360, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:445 +0x45
github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).managedRPC(0xc0420a66e0, 0xc042229360, 0x11, 0xac0d00, 0xa, 0xc0421fc6b0, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/rpc.go:66 +0x2c9
github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).RPC(0xc0420a66e0, 0xc042229360, 0x11, 0xac0d00, 0xa, 0xc0421fc6b0, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/rpc.go:76 +0xd8
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).threadedInitialBlockchainDownload.func1(0xc0420b1b80, 0xc044bafef0, 0xc044bafe98, 0xc044bafea0, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:580 +0x12e
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).threadedInitialBlockchainDownload(0xc0420b1b80, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:601 +0x151
github.com/NebulousLabs/Sia/modules/consensus.New.func1(0x1, 0xc042144490, 0xc0420b1b80, 0xdee820, 0xc0420a66e0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/consensusset.go:151 +0x3eb
created by github.com/NebulousLabs/Sia/modules/consensus.New
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/consensusset.go:144 +0x656

**Comment by tbenz9** [comment] 2018-02-07 21:26
Duplicate of #2413 

Workaround here: https://gist.github.com/tbenz9/8066d74853ab28c23bd7bc1d3c7cdeda

**Closed by tbenz9** 2018-02-07 21:26 UTC
