### ISSUE TITLE
Siad has exited unexpectedly

### ISSUE THREAD

**Issue by polygonlab** [NebulousLabs/Sia#1768] opened 2017-05-04 10:09 UTC
Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 0.017867945 seconds

Wallet: scanned to height 14848...
Wallet: scanned to height 92602...goroutine 1 [running]:
runtime/debug.Stack(0x1043857, 0x0, 0x4220435f8)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x79
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/NebulousLabs/Sia/build.Critical(0x422043948, 0x1, 0x1)
	/home/luke/go/src/github.com/NebulousLabs/Sia/build/critical.go:15 +0xa7
main.startDaemon(0x0, 0x0, 0x7fff5fbffd25, 0xe, 0x7fff5fbffd51, 0x5, 0x7fff5fbffd40, 0x5, 0x0, 0x7fff5fbffd61, ...)
	/home/luke/go/src/github.com/NebulousLabs/Sia/siad/daemon.go:295 +0xaa9
main.startDaemonCmd(0x421c4b200, 0x421c4d2c0, 0x0, 0x5)
	/home/luke/go/src/github.com/NebulousLabs/Sia/siad/daemon.go:309 +0x6d
github.com/spf13/cobra.(*Command).execute(0x421c4b200, 0x421c1a070, 0x5, 0x5, 0x421c4b200, 0x421c1a070)
	/home/luke/go/src/github.com/spf13/cobra/command.go:648 +0x234
github.com/spf13/cobra.(*Command).ExecuteC(0x421c4b200, 0x16c6004, 0x3b, 0x421d24a00)
	/home/luke/go/src/github.com/spf13/cobra/command.go:734 +0x339
github.com/spf13/cobra.(*Command).Execute(0x421c4b200, 0x1aa4520, 0x16af49d)
	/home/luke/go/src/github.com/spf13/cobra/command.go:693 +0x2b
main.main()
	/home/luke/go/src/github.com/NebulousLabs/Sia/siad/main.go:174 +0x7ac
Critical error: accept tcp 127.0.0.1:9980: accept: too many open files in system
Please submit a bug report here: https://github.com/NebulousLabs/Sia/issues
Closing renter...

**Comment by lukechampine** [comment] 2017-05-04 17:04
duplicate of #1757

**Closed by lukechampine** 2017-05-04 17:04 UTC
