### ISSUE TITLE
Siad quit unexpectedly:  MacOS Sierra 10.12.5

### ISSUE THREAD

**Issue by glad-zilla** [NebulousLabs/Sia#1882] opened 2017-06-04 08:40 UTC
Bug report and error log below:

Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 1.421170292 seconds

Wallet: scanned to height 9080...
Wallet: scanned to height 9080...
Wallet: scanned to height 9080...
Wallet: scanned to height 9080...
Wallet: scanned to height 9084...
Wallet: scanned to height 9096...
Wallet: scanned to height 9112...
Wallet: scanned to height 9129...
Wallet: scanned to height 9130...
Wallet: scanned to height 9135...
Wallet: scanned to height 9145...
Wallet: scanned to height 9148...
Wallet: scanned to height 9151...
Wallet: scanned to height 9154...
Wallet: scanned to height 9167...
Wallet: scanned to height 9168...
Wallet: scanned to height 9176...
Wallet: scanned to height 9180...
Wallet: scanned to height 9180...
Wallet: scanned to height 9186...
Wallet: scanned to height 9201...
Wallet: scanned to height 9222...
Wallet: scanned to height 9247...
Wallet: scanned to height 9277...
Wallet: scanned to height 9280...
Wallet: scanned to height 9306...
Wallet: scanned to height 9339...
Wallet: scanned to height 9380...
Wallet: scanned to height 9413...
Wallet: scanned to height 9447...
Wallet: scanned to height 9485...
Wallet: scanned to height 9615...
Wallet: scanned to height 9742...
Wallet: scanned to height 9993...
Wallet: scanned to height 10106...
Wallet: scanned to height 10248...
Wallet: scanned to height 10415...
Wallet: scanned to height 10526...
Wallet: scanned to height 10660...
Wallet: scanned to height 10806...
Wallet: scanned to height 11008...
Wallet: scanned to height 11231...
Wallet: scanned to height 11386...
Wallet: scanned to height 11497...
Wallet: scanned to height 11711...
Wallet: scanned to height 11935...
Wallet: scanned to height 12101...
Wallet: scanned to height 12305...
Wallet: scanned to height 12492...
Wallet: scanned to height 12655...
Wallet: scanned to height 12923...
Wallet: scanned to height 13145...
Wallet: scanned to height 13338...
Wallet: scanned to height 13564...
Wallet: scanned to height 13781...
Wallet: scanned to height 14010...
Wallet: scanned to height 14262...
Wallet: scanned to height 14493...
Wallet: scanned to height 14651...
Wallet: scanned to height 14758...
Wallet: scanned to height 14892...
Wallet: scanned to height 15016...
Wallet: scanned to height 15086...
Wallet: scanned to height 15163...
Wallet: scanned to height 15235...
Wallet: scanned to height 15330...
Wallet: scanned to height 15377...
Wallet: scanned to height 15422...
Wallet: scanned to height 15460...
Wallet: scanned to height 15489...
Wallet: scanned to height 15629...
Wallet: scanned to height 15783...
Wallet: scanned to height 15888...
Wallet: scanned to height 16034...
Wallet: scanned to height 16134...
Wallet: scanned to height 16246...
Wallet: scanned to height 16391...
Wallet: scanned to height 16630...
Wallet: scanned to height 16858...
Wallet: scanned to height 17139...
Wallet: scanned to height 17470...
Wallet: scanned to height 17638...
Wallet: scanned to height 17912...
Wallet: scanned to height 18084...
Wallet: scanned to height 18178...
Wallet: scanned to height 18321...
Wallet: scanned to height 18524...
Wallet: scanned to height 18820...
Wallet: scanned to height 19080...
Wallet: scanned to height 19432...
Wallet: scanned to height 19657...
Wallet: scanned to height 19930...
Wallet: scanned to height 20109...
Wallet: scanned to height 20168...
Wallet: scanned to height 20226...
Wallet: scanned to height 20311...
Wallet: scanned to height 20362...
Wallet: scanned to height 20464...
Wallet: scanned to height 20595...
Wallet: scanned to height 20762...
Wallet: scanned to height 20938...
Wallet: scanned to height 21133...
Wallet: scanned to height 21362...
Wallet: scanned to height 21585...
Wallet: scanned to height 21728...
Wallet: scanned to height 21954...
Wallet: scanned to height 22071...
Wallet: scanned to height 22112...
Wallet: scanned to height 22155...
Wallet: scanned to height 22259...
Wallet: scanned to height 22397...
Wallet: scanned to height 22561...
Wallet: scanned to height 22680...
Wallet: scanned to height 22694...
Wallet: scanned to height 22770...
Wallet: scanned to height 22778...
Wallet: scanned to height 22786...
Wallet: scanned to height 22793...
Wallet: scanned to height 22795...
Wallet: scanned to height 22816...
Wallet: scanned to height 22853...
Wallet: scanned to height 22887...
Wallet: scanned to height 22931...
Wallet: scanned to height 22993...
Wallet: scanned to height 23069...
Wallet: scanned to height 23192...
Wallet: scanned to height 23331...
Wallet: scanned to height 23508...
Wallet: scanned to height 23649...
Wallet: scanned to height 23775...
Wallet: scanned to height 24062...
Wallet: scanned to height 24238...
Wallet: scanned to height 24444...
Wallet: scanned to height 24535...
Wallet: scanned to height 24673...
Wallet: scanned to height 24790...
Wallet: scanned to height 24922...
Wallet: scanned to height 25148...
Wallet: scanned to height 25343...
Wallet: scanned to height 25502...
Wallet: scanned to height 25714...
Wallet: scanned to height 25929...
Wallet: scanned to height 26054...
Wallet: scanned to height 26252...
Wallet: scanned to height 26427...
Wallet: scanned to height 26498...
Wallet: scanned to height 26590...
Wallet: scanned to height 26625...
Wallet: scanned to height 26733...
Wallet: scanned to height 26850...
Wallet: scanned to height 26994...
Wallet: scanned to height 27160...
Wallet: scanned to height 27365...
Wallet: scanned to height 27578...
Wallet: scanned to height 27765...
Wallet: scanned to height 27974...
Wallet: scanned to height 28154...
Wallet: scanned to height 28332...
Wallet: scanned to height 28459...
Wallet: scanned to height 28557...
Wallet: scanned to height 28686...
Wallet: scanned to height 28748...
Wallet: scanned to height 28888...
Wallet: scanned to height 28987...
Wallet: scanned to height 29064...
Wallet: scanned to height 29104...
Wallet: scanned to height 29180...
Wallet: scanned to height 29225...
Wallet: scanned to height 29307...
Wallet: scanned to height 29393...
Wallet: scanned to height 29559...
Wallet: scanned to height 29880...
Wallet: scanned to height 30173...
Wallet: scanned to height 30352...
Wallet: scanned to height 30561...
Wallet: scanned to height 30879...
Wallet: scanned to height 31108...
Wallet: scanned to height 31196...
Wallet: scanned to height 31354...
Wallet: scanned to height 31462...
Wallet: scanned to height 31516...
Wallet: scanned to height 31600...
Wallet: scanned to height 31683...
Wallet: scanned to height 31881...
Wallet: scanned to height 32065...
Wallet: scanned to height 32342...
Wallet: scanned to height 32510...
Wallet: scanned to height 32545...
Wallet: scanned to height 32578...
Wallet: scanned to height 32639...
Wallet: scanned to height 32663...
Wallet: scanned to height 32670...
Wallet: scanned to height 32707...
Wallet: scanned to height 32799...
Wallet: scanned to height 32886...
Wallet: scanned to height 33030...
Wallet: scanned to height 33206...
Wallet: scanned to height 33380...
Wallet: scanned to height 33496...
Wallet: scanned to height 33607...
Wallet: scanned to height 33643...
Wallet: scanned to height 33703...
Wallet: scanned to height 33723...
Wallet: scanned to height 33821...
Wallet: scanned to height 33900...
Wallet: scanned to height 33919...
Wallet: scanned to height 34021...
Wallet: scanned to height 34040...
Wallet: scanned to height 34095...
Wallet: scanned to height 34154...
Wallet: scanned to height 34208...
Wallet: scanned to height 34255...
Wallet: scanned to height 34265...
Wallet: scanned to height 34269...
Wallet: scanned to height 34275...
Wallet: scanned to height 34329...
Wallet: scanned to height 34377...
Wallet: scanned to height 34385...
Wallet: scanned to height 34387...
Wallet: scanned to height 34393...
Wallet: scanned to height 34401...
Wallet: scanned to height 34404...
Wallet: scanned to height 34440...
Wallet: scanned to height 34455...
Wallet: scanned to height 34458...
Wallet: scanned to height 34467...
Wallet: scanned to height 34479...
Wallet: scanned to height 34500...
Wallet: scanned to height 34543...
Wallet: scanned to height 34548...
Wallet: scanned to height 34567...
Wallet: scanned to height 34568...
Wallet: scanned to height 34569...
Wallet: scanned to height 34575...
Wallet: scanned to height 34581...
Wallet: scanned to height 34583...
Wallet: scanned to height 34583...
Wallet: scanned to height 34584...
Wallet: scanned to height 34584...
Wallet: scanned to height 34584...
Wallet: scanned to height 34585...
Wallet: scanned to height 34587...
Wallet: scanned to height 34588...
Wallet: scanned to height 34588...
Wallet: scanned to height 34589...
Wallet: scanned to height 34591...
Wallet: scanned to height 34591...
Wallet: scanned to height 34593...
Wallet: scanned to height 34594...
Wallet: scanned to height 34594...
Wallet: scanned to height 34603...
Wallet: scanned to height 34607...
Wallet: scanned to height 34607...
Wallet: scanned to height 34610...
Wallet: scanned to height 34613...
Wallet: scanned to height 34633...
Wallet: scanned to height 34635...
Wallet: scanned to height 34635...
Wallet: scanned to height 34636...
Wallet: scanned to height 34643...
Wallet: scanned to height 34651...
Wallet: scanned to height 34658...
Wallet: scanned to height 34662...
Wallet: scanned to height 34664...
Wallet: scanned to height 34664...
Wallet: scanned to height 34664...
Wallet: scanned to height 34669...
Wallet: scanned to height 34669...
Wallet: scanned to height 34672...
Wallet: scanned to height 34673...
Wallet: scanned to height 34674...
Wallet: scanned to height 34674...
Wallet: scanned to height 34675...
Wallet: scanned to height 34676...
Wallet: scanned to height 34679...
Wallet: scanned to height 34680...
Wallet: scanned to height 34680...
Wallet: scanned to height 34680...
Wallet: scanned to height 34681...
Wallet: scanned to height 34694...
Wallet: scanned to height 34697...
Wallet: scanned to height 34705...
Wallet: scanned to height 34709...
Wallet: scanned to height 34724...
Wallet: scanned to height 34727...
Wallet: scanned to height 34728...
Wallet: scanned to height 34729...
Wallet: scanned to height 34730...goroutine 1 [running]:
runtime/debug.Stack(0x1043857, 0x0, 0xc42095d5f8)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x79
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/NebulousLabs/Sia/build.Critical(0xc42095d948, 0x1, 0x1)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/build/critical.go:16 +0xa7
main.startDaemon(0x0, 0x0, 0x7fff5fbffd14, 0xe, 0x7fff5fbffd40, 0x5, 0x7fff5fbffd2f, 0x5, 0x0, 0x7fff5fbffd93, ...)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/siad/daemon.go:295 +0xaa9
main.startDaemonCmd(0xc42007b200, 0xc420019450, 0x0, 0x5)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/siad/daemon.go:309 +0x6d
github.com/spf13/cobra.(*Command).execute(0xc42007b200, 0xc42000e0d0, 0x5, 0x5, 0xc42007b200, 0xc42000e0d0)
	/home/jrh/go/src/github.com/spf13/cobra/command.go:651 +0x23a
github.com/spf13/cobra.(*Command).ExecuteC(0xc42007b200, 0x16c7c0f, 0x3b, 0xc420148960)
	/home/jrh/go/src/github.com/spf13/cobra/command.go:726 +0x339
github.com/spf13/cobra.(*Command).Execute(0xc42007b200, 0x1aa6520, 0x16b10c0)
	/home/jrh/go/src/github.com/spf13/cobra/command.go:685 +0x2b
main.main()
	/home/jrh/go/src/github.com/NebulousLabs/Sia/siad/main.go:174 +0x79d
Critical error: accept tcp 127.0.0.1:9980: accept: too many open files in system
Please submit a bug report here: https://github.com/NebulousLabs/Sia/issues
Closing renter...

**Comment by lukechampine** [comment] 2017-06-04 16:46
duplicate of #1840

**Closed by lukechampine** 2017-06-04 16:46 UTC
