### ISSUE TITLE
Invalid memory address or nil pointer dereference in explorer

### ISSUE THREAD

**Issue by starius** [NebulousLabs/Sia#2437] opened 2017-10-22 08:28 UTC
```
goroutine 24488924 [running]:
runtime/debug.Stack(0x448057, 0x0, 0xc426740f08)
        /home/ff/.goroot/src/runtime/debug/stack.go:24 +0xa7
runtime/debug.PrintStack()
        /home/ff/.goroot/src/runtime/debug/stack.go:16 +0x22
github.com/NebulousLabs/Sia/build.Critical(0xc426740fb0, 0x2, 0x2)
        /home/ff/src/github.com/NebulousLabs/Sia/build/critical.go:16 +0x93
github.com/NebulousLabs/Sia/modules/explorer.(*Explorer).ProcessConsensusChange(0xc4201849c0, 0xbcf90b0a085b031e, 0x1f559395fd59636e, 0xbfd654157fff4104, 0xe8c882a8ef53ad91, 0xc421e93680, 0x1, 0x1, 0xc422990c00, 0x2, ...)
        /home/ff/src/github.com/NebulousLabs/Sia/modules/explorer/update.go:282 +0xeb
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).updateSubscribers(0xc4200a1b80, 0xc420ee56a0, 0x1, 0x1, 0xc4294b3880, 0x2, 0x2)
        /home/ff/src/github.com/NebulousLabs/Sia/modules/consensus/subscribe.go:115 +0x168
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).managedAcceptBlocks(0xc4200a1b80, 0xc427a57e00, 0x2, 0x2, 0x0, 0x0, 0x0)
        /home/ff/src/github.com/NebulousLabs/Sia/modules/consensus/accept.go:340 +0x6c3
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).managedReceiveBlocks(0xc4200a1b80, 0xe15840, 0xc426344020, 0x0, 0x0)
        /home/ff/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:225 +0x4f9
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).(github.com/NebulousLabs/Sia/modules/consensus.managedReceiveBlocks)-fm(0xe15840, 0xc426344020, 0x0, 0x0)
        /home/ff/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:445 +0x3e
github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).managedRPC(0xc4200bac60, 0xc421dd0140, 0x14, 0xac36c0, 0xa, 0xc4251222d0, 0x0, 0x0)
        /home/ff/src/github.com/NebulousLabs/Sia/modules/gateway/rpc.go:66 +0x2c2
github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).RPC(0xc4200bac60, 0xc421dd0140, 0x14, 0xac36c0, 0xa, 0xc4251222d0, 0x0, 0x0)
        /home/ff/src/github.com/NebulousLabs/Sia/modules/gateway/rpc.go:76 +0xd1
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).threadedRPCRelayHeader.func4(0xc422bb7630, 0xc4200a1b80, 0xe15840, 0xc421df01a0)
        /home/ff/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:445 +0xfd
created by github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).threadedRPCRelayHeader
        /home/ff/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:443 +0x4fe
Critical error: explorer update failed: runtime error: invalid memory address or nil pointer dereference
Please submit a bug report here: https://github.com/NebulousLabs/Sia/issues
```

Version: master after 1.3.1.

`siad` produced several such messages, but didn't crash - it is still working.

It looks like the panic was captured and the original stack is not available. IMHO "invalid memory address or nil pointer dereference" errors (and other panics) should not be caught (because panics are used for programmer's errors) and should result in program crash.

Add label "Bug".

**Comment by tsai1993** [comment] 2017-10-23 01:45
I have this problem several times and I believe there is memory leak.

**Comment by tbenz9** [comment] 2017-10-24 00:12
Duplicate of #2432 

Recommendation to Devs: close

**Closed** 2017-10-24 01:07 UTC
