### ISSUE TITLE
panic: runtime error: slice bounds out of range

### ISSUE THREAD

**Issue by noobee80** [NebulousLabs/Sia#2644] opened 2018-01-11 13:47 UTC
# BUG REPORT
Sia Daemon v1.3.1
Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 0.586532 seconds
panic: runtime error: slice bounds out of range

goroutine 27 [running]:
github.com/NebulousLabs/Sia/modules/consensus.removeFileContract(0xc0421a2700, 0x15fac14fffe925fe, 0xbb32eb8a34c414f4, 0x8bee7632e875c788, 0x76640e37a475df8d)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/consensusdb.go:396 +0x251
github.com/NebulousLabs/Sia/modules/consensus.commitFileContractDiff(0xc0421a2700, 0xfac14fffe925fe00, 0x32eb8a34c414f415, 0xee7632e875c788bb, 0x640e37a475df8d8b, 0x76, 0x0, 0x0, 0x0, 0x0, ...)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/diffs.go:69 +0xd7
github.com/NebulousLabs/Sia/modules/consensus.applyFileContractMaintenance(0xc0421a2700, 0xc042e7eb00)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/maintenance.go:178 +0x4b7
github.com/NebulousLabs/Sia/modules/consensus.applyMaintenance(0xc0421a2700, 0xc042e7eb00)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/maintenance.go:192 +0x6c
github.com/NebulousLabs/Sia/modules/consensus.generateAndApplyDiff(0xc0421a2700, 0xc042e7eb00, 0xc042174240, 0x2)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/diffs.go:231 +0x1ef
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).applyUntilBlock(0xc0420cfb80, 0xc0421a2700, 0xc042e7eb00, 0x0, 0x0, 0x0, 0x50c2090000000000, 0x2db1ec05f5c3f697)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/fork.go:84 +0x228
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).forkBlockchain(0xc0420cfb80, 0xc0421a2700, 0xc042e7eb00, 0x8736010000000000, 0x28c4ab6d6cb2d243, 0xb55563cd1498ca0e, 0x5d0f6f2de37cf639, 0x21c4b11c, 0x55dfb85b, 0xc04301b380, ...)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/fork.go:111 +0xb3
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).addBlockToTree(0xc0420cfb80, 0xc0421a2700, 0x8736010000000000, 0x28c4ab6d6cb2d243, 0xb55563cd1498ca0e, 0x5d0f6f2de37cf639, 0x21c4b11c, 0x55dfb85b, 0xc04301b380, 0x1, ...)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/accept.go:164 +0x10d
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).managedAcceptBlocks.func1(0xc0421a2700, 0xaf16f8, 0xc0421a2700)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/accept.go:262 +0x2b0
github.com/NebulousLabs/bolt.(*DB).Update(0xc04206b2c0, 0xc042b2f2e8, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/bolt/db.go:603 +0xa1
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).managedAcceptBlocks(0xc0420cfb80, 0xc042be6400, 0xa, 0xa, 0x0, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/accept.go:245 +0x4f9
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).managedReceiveBlocks(0xc0420cfb80, 0xdee020, 0xc042c980a0, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:225 +0x500
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).(github.com/NebulousLabs/Sia/modules/consensus.managedReceiveBlocks)-fm(0xdee020, 0xc042c980a0, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:445 +0x45
github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).managedRPC(0xc0420c2420, 0xc0421a83c0, 0x12, 0xac0d00, 0xa, 0xc042e78080, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/rpc.go:66 +0x2c9
github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).RPC(0xc0420c2420, 0xc0421a83c0, 0x12, 0xac0d00, 0xa, 0xc042e78080, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/rpc.go:76 +0xd8
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).threadedInitialBlockchainDownload.func1(0xc0420cfb80, 0xc042c77ef0, 0xc042c77e98, 0xc042c77ea0, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:580 +0x12e
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).threadedInitialBlockchainDownload(0xc0420cfb80, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:601 +0x151
github.com/NebulousLabs/Sia/modules/consensus.New.func1(0x1, 0xc04215c490, 0xc0420cfb80, 0xdee820, 0xc0420c2420)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/consensusset.go:151 +0x3eb
created by github.com/NebulousLabs/Sia/modules/consensus.New
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/consensusset.go:144 +0x656

**How to reproduce it (as minimally and precisely as possible)**
I just startet the SiaUI to synchronize. Before synchronizing I added via terminal Gateways cause I got an error "not synchronizing"

**Environment**
* Sia version: v1.3.1
* OS: win10_x64

**Comment by tbenz9** [comment] 2018-01-11 19:00
Duplicate of #2183

**Closed by tbenz9** 2018-01-11 19:00 UTC
