### ISSUE TITLE
Questions about sia encrypted storage file blocks

### ISSUE THREAD

**Issue by hefengliang** [NebulousLabs/Sia#2732] opened 2018-02-05 05:09 UTC
I am very interested in distributed file storage, is an SC investor, is also a file management software product developer, thank sia team great contribution.

I know that the current sia is the user's file block encrypted stored on the network host, the encrypted file is bound to use the user's private key, does this mean that sia lost web-based file upload to heavy capacity? E.g: A is used to upload a movie file, B users also upload exactly the same file, then the actual data stored on the network host due to private key encryption is completely different.

Host space waste is not the most important, the important thing is to affect future traffic acceleration capabilities, I think this is the biggest advantage of sia distributed storage, because the centralized data center storage is the biggest bottleneck traffic.

When a user uploads a movie to be downloaded, he can only obtain the file data from the host that he originally uploaded. This obviously does not meet the idea of ​​P2P traffic distribution and it is difficult to improve traffic utilization. If there is no traffic advantage, sia will not have the ability to compete with the centralized data center.

Obviously this is contradictory, no encryption will affect user privacy, encryption we will lose a lot of traffic acceleration, anyone can give me some advice?

**Comment by lukechampine** [comment] 2018-02-05 05:57
If you want your file to be available from multiple hosts, you are free to distribute it to as many hosts as you like. The burden is on the uploader. What's the alternative?

Even if there *were* other hosts storing the same data, you'd need some way to find them. We don't intend to provide any sort of file-discovery service, so you'd have to layer that on top of Sia. And if your file-discovery service can figure out which hosts are storing a particular file, it can probably distribute the decryption key to that file too. Problem solved.

btw, encryption isn't mandatory on Sia. Hosts will accept any data you throw at them. But we do recommend that hosts only accept encrypted data, because there are liability concerns otherwise.

**Comment by hefengliang** [comment] 2018-02-06 03:00
Thank you very much for your reply!
If file block based  upload and download, can use the memory access data, similar to the API writefile and readfile, then we can store the file block into the sia network, the use of traditional mysql storage structure information and block index information, so You can build an efficient enterprise-class application.
But I looked at sia's Renter API, which is a simple, file-based operation that obviously can not meet the needs of developing an enterprise-wide software, giving developers a very limited freedom to show off their talent.
Fileblock-based access should be important if sia is positioned as a network storage tier. Developers use traditional databases to store index information when the current distributed network database (DHT?) efficiency is not sufficient. Allows developers to release productive software as soon as possible.

**Comment by lukechampine** [comment] 2018-02-06 05:28
>sia's Renter API, which is a simple, file-based operation that obviously can not meet the needs of developing an enterprise-wide software

I agree. Sia has always been intended as block-level storage, and its low-level protocols are designed to support block-level storage. However, for the convenience of our early users, we have mostly been focused on file-based operations. In 2018 I hope to make block-level operations more accessible to developers who want to build enterprise-grade storage systems on top of Sia.

**Comment by gedw99** [comment] 2018-02-06 11:36
@lukechampine do you think its possible to graphql on top of sia to make a db ?

Also regarding replication, i though sia uses minio and so benefits from the minio replication ?

**Comment by hefengliang** [comment] 2018-02-06 14:18
Thank you, I will always pay attention to sia development progress, you are doing a great thing.

**Comment by lukechampine** [comment] 2018-02-06 19:58
@gedw99 since Sia is block-level storage, in theory you can layer any DB on top of it. The issue is latency + bandwidth. Reading from the DB will require at least two round-trips to each host, and then CPU overhead to decrypt each host's piece and reassemble the erasure-coded shards. Writing is even worse, since Sia has a minimum write size of 4MB -- you'd need to either buffer your writes (tricky), or pad the data to 4MB (wasteful). So while I absolutely believe that it's possible (and I'm sure someone will do it eventually), my guess is that the performance will be pretty bad. Sia performs best as a form of [WORM storage](https://en.wikipedia.org/wiki/Write_once_read_many), and is much less suitable for content that needs to be frequently updated. That said, the technology is still evolving. It's certainly possible that we could remove the 4MB restriction someday, and you can improve performance by tweaking the encryption/redundancy, etc. Where there's a will, there's a way!

btw, you have it backwards: minio has an (optional) Sia backend. Sia's redundancy (sharding data across many hosts via erasure coding) is a core part of the platform.

**Comment by gedw99** [comment] 2018-02-06 20:27
Thanks about correcting me about minio. It was niggling at me today that I had it backwards.

That's a good explanation.
I am trying to build applications on top of ipfs / sia style systems that are eventually consistent using a cqrs style on top. Already hitting the limits of minio 16 server nodes and ipfs cluster.

I work on machine learning with tons and tons of data and lots of users / age TS needing to edit and get network partitioned.
The only real solution is a clock sync which leaves me with:
- quantum entanglement
- atomic clocks like google stashes in each data centre
- hybrid clocks 

Am working on hybrid clocks. Cockroach DB uses it to get all their multi data centers WAL ordered for convergence

**Comment by tbenz9** [comment] 2018-02-07 21:34
I'm going to close this issue as it appears your questions were answered and I don't see any clear action items the Sia devs need to take.  Please feel free to reopen this issue if you think it was prematurely closed.

**Closed by tbenz9** 2018-02-07 21:34 UTC
