### ISSUE TITLE
Siad Crashed - EXT4 Filesystem Corrupted

### ISSUE THREAD

**Issue by kurohage** [NebulousLabs/Sia#2383] opened 2017-10-02 16:17 UTC
I ran siad 1.3 on Debian 8.6 x64. It was in sync a few weeks ago, then I traveled. I came back, powered up my Linux box & ran siad to sync. Meanwhile, there were some package updates which I installed, while siad was running. Siad suddenly froze along with sia-ui and I closed it, then ran it again, and the whole machine died.

In the shell, when I typed "ls" it said "Input/Output Error" and after a reboot, the filesystem was gone. I spent 2 days recovering files and fixing stuff, and now have it half working (can login).

Where do I find the log files? What else do you need to know? I run Debian as the main OS on a Samsung NVMe.

**Comment by lukechampine** [comment] 2017-10-02 19:29
log files are present in the same directory as the blockchain, wallet, etc. If you're using Sia-UI, I believe it's `~/.config/Sia-UI/sia`.
I'm not sure if the logs will tell you anything interesting, though. My guess is that the failure is not attributable to siad or Sia-UI. (Of course, if it is, we'll make it our top priority to fix.)
Sorry about losing your fs, that's a major PITA. There may be some ext4 logs that you can query as well to identify the root cause.

**Comment by kurohage** [comment] 2017-10-03 12:11
Hey Luke,

I checked Sia and didn't find anything useful. I checked system logs and saw many NVMe errors from the kernel side.

It appears that Sia generated enough disk stress that it triggered a bug in kernel 4.8 used in Debian 8.x with NVMe.

However, none of the online reports showed anyone suffering from a filesystem corruption.

I don't think it's Sia's fault at this time, but let this be a warning to anyone using NVMe with 4.8 kernel on Linux.

Should I attach Sia & syslogs for others to see? Or simply close the ticket?

**Comment by lukechampine** [comment] 2017-10-03 17:22
Sia does tax the disk more than we'd like. I'm running a Samsung NVMe myself, so fingers crossed. :P

Logs wouldn't hurt, but yeah I'll close this since I don't think there's anything actionable at this time

**Comment by kurohage** [comment] 2017-10-03 17:43
Alright. I'll post the logs soon and then close the ticket.

**Comment by petabytestorage** [comment] 2017-10-06 18:21
@tbenz9 this can be closed and reopened if/when the logs come. it sounds like it's not (substantially) sia's fault to me for a number of reasons.

**Closed** 2017-10-07 00:06 UTC

**Comment by kurohage** [comment] 2017-10-07 10:52
[auth.log](https://github.com/NebulousLabs/Sia/files/1364537/auth.log)
[daemon.log](https://github.com/NebulousLabs/Sia/files/1364534/daemon.log)
[debug.log](https://github.com/NebulousLabs/Sia/files/1364530/debug.log)
[dmesg-errors.log](https://github.com/NebulousLabs/Sia/files/1364531/dmesg-errors.log)
[dpkg.log](https://github.com/NebulousLabs/Sia/files/1364532/dpkg.log)
[kdm.log](https://github.com/NebulousLabs/Sia/files/1364533/kdm.log)
[kern.log](https://github.com/NebulousLabs/Sia/files/1364535/kern.log)
[messages.log](https://github.com/NebulousLabs/Sia/files/1364538/messages.log)
[syslog.log](https://github.com/NebulousLabs/Sia/files/1364539/syslog.log)
[user.log](https://github.com/NebulousLabs/Sia/files/1364540/user.log)
