### ISSUE TITLE
Siad has exited unexpectedly. Please submit a bug report including the error log here.

### ISSUE THREAD

**Issue by mertimiks** [NebulousLabs/Sia#1795] opened 2017-05-14 17:25 UTC
I got the error below when I was trying to unlock my wallet. I am using ubuntu 64 bit and my blocks are synced. Does anyone know what is going on? Thanks for help.

Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 141.579960974 seconds

Wallet: scanned to height 58824...
Wallet: scanned to height 58828...
Wallet: scanned to height 58848...
Wallet: scanned to height 58860...
Wallet: scanned to height 58872...
Wallet: scanned to height 58890...
Wallet: scanned to height 58913...
Wallet: scanned to height 58926...
Wallet: scanned to height 58936...
Wallet: scanned to height 58958...
Wallet: scanned to height 58965...
Wallet: scanned to height 58968...
Wallet: scanned to height 58977...
Wallet: scanned to height 58990...
Wallet: scanned to height 59006...
Wallet: scanned to height 59016...
Wallet: scanned to height 59029...
Wallet: scanned to height 59046...
Wallet: scanned to height 59060...
Wallet: scanned to height 59081...
Wallet: scanned to height 59085...
Wallet: scanned to height 59091...
Wallet: scanned to height 59110...
Wallet: scanned to height 59134...
Wallet: scanned to height 59147...
Wallet: scanned to height 59175...
Wallet: scanned to height 59186...
Wallet: scanned to height 59200...
Wallet: scanned to height 59221...
Wallet: scanned to height 59228...
Wallet: scanned to height 59242...
Wallet: scanned to height 59267...
Wallet: scanned to height 59285...
Wallet: scanned to height 59301...
Wallet: scanned to height 59329...
Wallet: scanned to height 59347...
Wallet: scanned to height 59367...
Wallet: scanned to height 59392...
Wallet: scanned to height 59411...
Wallet: scanned to height 59420...
Wallet: scanned to height 59444...
Wallet: scanned to height 59453...
Wallet: scanned to height 59470...
Wallet: scanned to height 59471...
Wallet: scanned to height 59486...
Wallet: scanned to height 59504...
Wallet: scanned to height 59521...
Wallet: scanned to height 59536...
Wallet: scanned to height 59557...
Wallet: scanned to height 59576...
Wallet: scanned to height 59594...
Wallet: scanned to height 59614...
Wallet: scanned to height 59627...
Wallet: scanned to height 59646...
Wallet: scanned to height 59660...
Wallet: scanned to height 59671...
Wallet: scanned to height 59677...
Wallet: scanned to height 59681...
Wallet: scanned to height 59691...
Wallet: scanned to height 59694...
Wallet: scanned to height 59695...
Wallet: scanned to height 59711...
Wallet: scanned to height 59720...
Wallet: scanned to height 59730...
Wallet: scanned to height 59748...
Wallet: scanned to height 59770...
Wallet: scanned to height 59779...
Wallet: scanned to height 59800...
Wallet: scanned to height 59813...
Wallet: scanned to height 59827...
Wallet: scanned to height 59833...
Wallet: scanned to height 59850...
Wallet: scanned to height 59860...
Wallet: scanned to height 59871...
Wallet: scanned to height 59889...
Wallet: scanned to height 59897...
Wallet: scanned to height 59915...
Wallet: scanned to height 59933...
Wallet: scanned to height 59940...
Wallet: scanned to height 59949...
Wallet: scanned to height 59957...
Wallet: scanned to height 59959...
Wallet: scanned to height 59965...
Wallet: scanned to height 59970...
Wallet: scanned to height 59973...
Wallet: scanned to height 59983...
Wallet: scanned to height 59986...
Wallet: scanned to height 59989...
Wallet: scanned to height 59993...
Wallet: scanned to height 59999...
Wallet: scanned to height 60018...
Wallet: scanned to height 60022...
Wallet: scanned to height 60029...
Wallet: scanned to height 60044...
Wallet: scanned to height 60053...
Wallet: scanned to height 60064...
Wallet: scanned to height 60085...
Wallet: scanned to height 60096...
Wallet: scanned to height 60103...
Wallet: scanned to height 60112...
Wallet: scanned to height 60115...
Wallet: scanned to height 60118...
Wallet: scanned to height 60120...
Wallet: scanned to height 60123...
Wallet: scanned to height 60125...
Wallet: scanned to height 60138...
Wallet: scanned to height 60147...
Wallet: scanned to height 60155...
Wallet: scanned to height 60167...
Wallet: scanned to height 60175...
Wallet: scanned to height 60182...
Wallet: scanned to height 60192...
Wallet: scanned to height 60202...
Wallet: scanned to height 60212...
Wallet: scanned to height 60229...
Wallet: scanned to height 60232...
Wallet: scanned to height 60234...
Wallet: scanned to height 60242...
Wallet: scanned to height 60249...
Wallet: scanned to height 60256...
Wallet: scanned to height 60269...
Wallet: scanned to height 60271...
Wallet: scanned to height 60273...
Wallet: scanned to height 60275...
Wallet: scanned to height 60278...
Wallet: scanned to height 60280...
Wallet: scanned to height 60282...
Wallet: scanned to height 60291...
Wallet: scanned to height 60301...
Wallet: scanned to height 60309...
Wallet: scanned to height 60314...
Wallet: scanned to height 60319...
Wallet: scanned to height 60333...
Wallet: scanned to height 60348...
Wallet: scanned to height 60355...
Wallet: scanned to height 60363...
Wallet: scanned to height 60378...
Wallet: scanned to height 60386...
Wallet: scanned to height 60399...
Wallet: scanned to height 60401...
Wallet: scanned to height 60406...
Wallet: scanned to height 60410...
Wallet: scanned to height 60414...
Wallet: scanned to height 60417...
Wallet: scanned to height 60423...
Wallet: scanned to height 60429...
Wallet: scanned to height 60439...
Wallet: scanned to height 60450...
Wallet: scanned to height 60456...
Wallet: scanned to height 60459...
Wallet: scanned to height 60465...
Wallet: scanned to height 60468...
Wallet: scanned to height 60470...
Wallet: scanned to height 60475...
Wallet: scanned to height 60479...
Wallet: scanned to height 60481...
Wallet: scanned to height 60486...
Wallet: scanned to height 60492...
Wallet: scanned to height 60494...
Wallet: scanned to height 60498...
Wallet: scanned to height 60502...
Wallet: scanned to height 60504...
Wallet: scanned to height 60508...
Wallet: scanned to height 60517...
Wallet: scanned to height 60529...
Wallet: scanned to height 60532...
Wallet: scanned to height 60544...
Wallet: scanned to height 60549...
Wallet: scanned to height 60559...
Wallet: scanned to height 60563...
Wallet: scanned to height 60567...
Wallet: scanned to height 60572...
Wallet: scanned to height 60579...
Wallet: scanned to height 60593...
Wallet: scanned to height 60595...
Wallet: scanned to height 60602...
Wallet: scanned to height 60617...
Wallet: scanned to height 60627...
Wallet: scanned to height 60637...
Wallet: scanned to height 60645...
Wallet: scanned to height 60651...
Wallet: scanned to height 60660...
Wallet: scanned to height 60664...
Wallet: scanned to height 60687...2017/05/14 20:12:01 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
2017/05/14 20:12:03 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms

Wallet: scanned to height 60691...2017/05/14 20:12:04 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
2017/05/14 20:12:04 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 10ms
2017/05/14 20:12:04 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 20ms
2017/05/14 20:12:04 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 40ms
2017/05/14 20:12:04 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
2017/05/14 20:12:04 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
2017/05/14 20:12:04 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 10ms
2017/05/14 20:12:04 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 20ms
2017/05/14 20:12:04 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 40ms
2017/05/14 20:12:04 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 80ms
2017/05/14 20:12:04 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 160ms
2017/05/14 20:12:04 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 320ms
2017/05/14 20:12:04 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 640ms
2017/05/14 20:12:05 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
2017/05/14 20:12:05 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
2017/05/14 20:12:05 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
2017/05/14 20:12:05 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 10ms
2017/05/14 20:12:05 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 20ms
2017/05/14 20:12:05 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 40ms
2017/05/14 20:12:05 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 80ms
2017/05/14 20:12:05 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 160ms
2017/05/14 20:12:05 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 320ms
2017/05/14 20:12:06 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 640ms
2017/05/14 20:12:06 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/14 20:12:07 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
2017/05/14 20:12:07 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
2017/05/14 20:12:07 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
2017/05/14 20:12:07 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 10ms
2017/05/14 20:12:07 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 20ms
2017/05/14 20:12:07 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 40ms
2017/05/14 20:12:07 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 80ms
2017/05/14 20:12:07 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 160ms
2017/05/14 20:12:08 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 320ms

Wallet: scanned to height 60693...2017/05/14 20:12:08 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 640ms
2017/05/14 20:12:08 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/14 20:12:09 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/14 20:12:10 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s

Wallet: scanned to height 60697...2017/05/14 20:12:11 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/14 20:12:12 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/14 20:12:13 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s

Wallet: scanned to height 60704...2017/05/14 20:12:14 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s

**Comment by lukechampine** [comment] 2017-05-14 17:55
Duplicate of #1757. A fix for this will be included in the next release. See the linked issue for a temporary fix.

**Closed by lukechampine** 2017-05-14 17:55 UTC

**Comment by mertimiks** [comment] 2017-05-14 19:17
So I will copy and paste this command, ulimit -n 2048, to terminal and run?

**Comment by DavidVorick** [comment] 2017-05-15 04:56
yeah, that should help.

**Comment by mertimiks** [comment] 2017-05-15 08:51
But it didn't work.
