### ISSUE TITLE
Hosting Announce over IPv6 not working

### ISSUE THREAD

**Issue by Nutomic** [NebulousLabs/Sia#568] opened 2015-06-09 12:46 UTC
My internet connection uses [DS-Lite](https://en.wikipedia.org/wiki/IPv6_transition_mechanism#Dual-Stack_Lite_.28DS-Lite.29). 

I have forwarded port 9982, and according to [this tool](http://www.subnetonline.com/pages/ipv6-network-tools/online-ipv6-port-scanner.php), it is reachable.

However, clicking Announce in the Hosting section gives the message "host address not reachable; ensure you have forwarded port 9982".

Please tell me if you need any additional info.

**Comment by DavidVorick** [comment] 2015-06-09 13:28
We currently believe that this problem is caused by a timeout - if it's taking more than 1 second for you to bounce to the internet and back, it'll time out and assume you don't have your port forwarded.

We've got a fix in the pipeline. I'm not 100%  sure that it's actually going to fix the issue, but it seems likely.

Thanks for taking the time to make an issue.

**Comment by lukechampine** [comment] 2015-06-09 16:21
We currently use only IPv4 addresses. They are fetched from www.getmyexternalip.com/raw. I'm not familiar with DS-Lite so I don't know if this would cause problems for you.

**Comment by Nutomic** [comment] 2015-06-09 19:10
myexternalip.com returns an IPv6 address. I had to remove the `[]` around it for the port scanner website, but then it worked. (btw, have you considered setting up your own server for this instead of leaking data to a third party?)

`siac gateway` only returns my public IPv4 address.

**Comment by lukechampine** [comment] 2015-06-09 19:23
it's weird because when I view it from my browser I see an IPv6 address, but when I make an HTTP call from Go it always returns an IPv4 address.

All Sia does to check port forwarding is try to open a connection to the provided address and immediately close it. Perhaps there's some NAT subtlety here that I'm not aware of.

**Comment by mgumz** [comment] 2015-07-26 18:21
well, you are using the service wrong: if you want to make sure to connect to an IPV4-Endpoint then use the domain-name that was setup for IPV4: ipv4.myexternalip.com

**Comment by lukechampine** [comment] 2015-07-26 19:38
The fix you suggested is easy to implement, but I wonder if it is the proper behavior. Ideally, Sia should support both IPv4 and IPv6, so it shouldn't matter which address you advertise. I haven't yet seen an IPv6 address advertised though. This bears further investigation.

In the meantime, as of v0.3.3.3 you can force host announcements by using siac's `--force` flag.

**Comment by mgumz** [comment] 2015-07-27 06:47
there is another endpoint: ipv6.myexternalip.com =) 

`http.Get("http://myexternalip.com/raw")` yields v4, should be due to the way net.Dial() selects the "right" host.

**Comment by lukechampine** [comment] 2015-10-08 02:30
I'm seeing IPv6 addresses in peer lists now, and `/host/announce` has supported manual announcing for a while now. If you get the same error, force the announcement using `siac` and you should be ok.

**Closed by lukechampine** 2015-10-08 02:30 UTC
Labels: bug
