### ISSUE TITLE
Unkown problem with SiaD v1.0.3

### ISSUE THREAD

**Issue by xurious** [NebulousLabs/Sia#1509] opened 2016-12-06 17:00 UTC
Deleted the consensus and this output happened at some point in the last 25% from Siad. Not sure if related, but I moved a wallet from .6 to 1.0.3.

> 
goroutine 108955 [sleep, 3 minutes]:
time.Sleep(0x2b8a118e00)
        /usr/local/go/src/runtime/time.go:59 +0xef
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).managedAcceptBlock.func1.1(0xcc03000000000000, 0xd9bc983986330ac0, 0x5036899bad38571f, 0x47d38da4d
574dc5a, 0x5a6800aa01ec0044, 0x5845f63c, 0xc0423c6000, 0x1, 0x1, 0xc04278cf00, ...)
        /home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/accept.go:254 +0x84
created by github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).managedAcceptBlock.func1
        /home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/accept.go:260 +0x190

goroutine 104339 [chan receive]:
github.com/NebulousLabs/muxado/proto.(*Session).Accept(0xc0423b2820, 0xc04202c4f0, 0xc042686580, 0x0, 0xc043411ea8)
        /home/luke/go/src/github.com/NebulousLabs/muxado/proto/session.go:159 +0x62
github.com/NebulousLabs/muxado.(*sessionAdaptor).Accept(0xc044179510, 0xc043411ed0, 0x4f77f9, 0x459010, 0xc043411f10)
        /home/luke/go/src/github.com/NebulousLabs/muxado/adaptor.go:33 +0x3e
github.com/NebulousLabs/Sia/modules/gateway.(*peer).accept(0xc04417d280, 0xa57730, 0xc042068dc0, 0xc9a0a0, 0xc04308a280)
        /home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/peers.go:51 +0x3f
github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).threadedListenPeer(0xc042068dc0, 0xc04417d280)
        /home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/rpc.go:159 +0x117
created by github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).addPeer
        /home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/peers.go:62 +0x91

goroutine 108968 [sleep, 3 minutes]:
time.Sleep(0x2b12dbfa00)
        /usr/local/go/src/runtime/time.go:59 +0xef
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).managedAcceptBlock.func1.1(0xcc03000000000000, 0xd9bc983986330ac0, 0x5036899bad38571f, 0x47d38da4d
574dc5a, 0x5a6800aa01ec0044, 0x5845f63c, 0xc044674600, 0x1, 0x1, 0xc04278d500, ...)
        /home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/accept.go:254 +0x84
created by github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).managedAcceptBlock.func1
        /home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/accept.go:260 +0x190

goroutine 106585 [select]:
github.com/NebulousLabs/muxado/proto/ext.(*Heartbeat).check(0xc0425ed950)
        /home/luke/go/src/github.com/NebulousLabs/muxado/proto/ext/heartbeat.go:57 +0x141
created by github.com/NebulousLabs/muxado/proto/ext.(*Heartbeat).Start
        /home/luke/go/src/github.com/NebulousLabs/muxado/proto/ext/heartbeat.go:48 +0xc4

goroutine 104287 [IO wait]:
net.runtime_pollWait(0x2d5cac0, 0x72, 0xc042534b80)
        /usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).wait(0xc043e0e470, 0x72, 0xc042534b80, 0xc043659c28)
        /usr/local/go/src/net/fd_poll_runtime.go:73 +0x3f
net.(*ioSrv).ExecIO(0xc04205a0f0, 0xc043e0e360, 0x9e764c, 0x7, 0xa57c78, 0x4, 0xc043659d48, 0x445366)
        /usr/local/go/src/net/fd_windows.go:171 +0x183
net.(*netFD).Read(0xc043e0e300, 0xc042928700, 0x8, 0x8, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/fd_windows.go:426 +0x14a
net.(*conn).Read(0xc0423fa070, 0xc042928700, 0x8, 0x8, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/net.go:173 +0x77
github.com/NebulousLabs/muxado/proto/frame.(*BasicTransport).Read(0xc042a4c000, 0xc042928700, 0x8, 0x8, 0xc043659f48, 0x7e4e8b, 0xc042bc8780)
        <autogenerated>:139 +0x72
io.ReadAtLeast(0xc90d00, 0xc042a4c000, 0xc042928700, 0x8, 0x8, 0x8, 0x9c9860, 0x0, 0xc90d00)
        /usr/local/go/src/io/io.go:307 +0xab
io.ReadFull(0xc90d00, 0xc042a4c000, 0xc042928700, 0x8, 0x8, 0x9a8900, 0x0, 0x0)
        /usr/local/go/src/io/io.go:325 +0x5f
github.com/NebulousLabs/muxado/proto/frame.(*BasicTransport).ReadFrame(0xc042a4c000, 0xc965c0, 0xc042a4c070, 0x0, 0x0)
        /home/luke/go/src/github.com/NebulousLabs/muxado/proto/frame/transport.go:34 +0x6e
github.com/NebulousLabs/muxado/proto.(*Session).reader(0xc04215e280)
        /home/luke/go/src/github.com/NebulousLabs/muxado/proto/session.go:276 +0xa8
created by github.com/NebulousLabs/muxado/proto.NewSession
        /home/luke/go/src/github.com/NebulousLabs/muxado/proto/session.go:104 +0x4e3

goroutine 104284 [semacquire]:
sync.runtime_notifyListWait(0xc0428ac810, 0xc0000008c9)
        /usr/local/go/src/runtime/sema.go:267 +0x130
sync.(*Cond).Wait(0xc0428ac800)
        /usr/local/go/src/sync/cond.go:57 +0x87
github.com/NebulousLabs/muxado/proto/buffer.(*Inbound).Read(0xc042573560, 0xc042928a08, 0x4, 0x4, 0x0, 0xc04215e2c8, 0xc0437ffec0)
        /home/luke/go/src/github.com/NebulousLabs/muxado/proto/buffer/inbound.go:155 +0x170
github.com/NebulousLabs/muxado/proto.(*Stream).Read(0xc042bc8880, 0xc042928a08, 0x4, 0x4, 0x0, 0x4, 0x4)
        /home/luke/go/src/github.com/NebulousLabs/muxado/proto/stream.go:73 +0x5e
io.ReadAtLeast(0x2d677d8, 0xc042bc8880, 0xc042928a08, 0x4, 0x4, 0x4, 0x9c94e0, 0x0, 0x2d677d8)
        /usr/local/go/src/io/io.go:307 +0xab
io.ReadFull(0x2d677d8, 0xc042bc8880, 0xc042928a08, 0x4, 0x4, 0x0, 0x0, 0x0)
        /usr/local/go/src/io/io.go:325 +0x5f
github.com/NebulousLabs/muxado/proto/ext.(*Heartbeat).respond(0xc0421a7350)
        /home/luke/go/src/github.com/NebulousLabs/muxado/proto/ext/heartbeat.go:81 +0x121
created by github.com/NebulousLabs/muxado/proto/ext.(*Heartbeat).Start
        /home/luke/go/src/github.com/NebulousLabs/muxado/proto/ext/heartbeat.go:46 +0x80

**Comment by lukechampine** [comment] 2016-12-06 21:50
was there anything above this message? It looks like a partial stack trace, which is usually generated by a panic or a critical error. There should be additional information at the top of the trace containing an error message. Without that, it's hard to diagnose what went wrong.

**Comment by xurious** [comment] 2016-12-06 21:57
Unfortunately, this was the entire buffer. Unless there is a log someplace..

**Comment by lukechampine** [comment] 2016-12-06 22:18
Did siad exit after the message? Can you clarify the steps you took? Something like:
1. Stopped siad
2. Deleted consensus.db
3. Moved old wallet.dat to wallet folder
3. Started siad
4. siad began downloading blocks
5. Problem occurred when siad was within 25% of full sync

There are various logs in the Sia directory. You can check them manually, or you can use the new UI and view them with Ctrl+Shift+L.

**Comment by lukechampine** [comment] 2017-04-07 02:02
Closing this because it's not clear how to reproduce, and it may be fixed. Please reopen if you have the issue again.

**Closed by lukechampine** 2017-04-07 02:02 UTC
