### ISSUE TITLE
WIndows SiaUI 1.2.0 RC1 Crashed overnight

### ISSUE THREAD

**Issue by gwar11d2** [NebulousLabs/Sia#1651] opened 2017-04-05 11:32 UTC
This happened last night w/ SiaUI 1.2.0 RC1(Crashed overnight) and I thought I would report to you guys:

Loading...
(0/7) Loading siad...
(1/7) Loading gateway...
(2/7) Loading consensus...
(3/7) Loading transaction pool...
(4/7) Loading wallet...
(5/7) Loading miner...
(6/7) Loading host...
(7/7) Loading renter...
Finished loading in 30.8025056 seconds
goroutine 1020 [running]:
runtime/debug.Stack(0x44433e, 0x0, 0xc042459c28)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x80
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x29
github.com/NebulousLabs/Sia/build.Critical(0xc042459d80, 0x2, 0x2)
	/home/luke/go/src/github.com/NebulousLabs/Sia/build/critical.go:15 +0xae
github.com/NebulousLabs/Sia/persist.(*Logger).Critical(0xc0427a3f20, 0xc042459d80, 0x2, 0x2)
	/home/luke/go/src/github.com/NebulousLabs/Sia/persist/log.go:37 +0xe7
github.com/NebulousLabs/Sia/modules/renter.(*Renter).managedDownloadIteration(0xc043062600, 0xc042459f20)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/renter/download.go:320 +0x5c5
github.com/NebulousLabs/Sia/modules/renter.(*Renter).threadedDownloadLoop(0xc043062600)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/renter/download.go:585 +0x385
created by github.com/NebulousLabs/Sia/modules/renter.newRenter
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/renter/renter.go:208 +0x3b5
Critical error: ERROR: the renter is idle , but tracking active pieces: 19
Please submit a bug report here: https://github.com/NebulousLabs/Sia/issues
goroutine 1020 [running]:
runtime/debug.Stack(0x44433e, 0x0, 0xc079d6fc28)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x80
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x29
github.com/NebulousLabs/Sia/build.Critical(0xc079d6fd80, 0x2, 0x2)
	/home/luke/go/src/github.com/NebulousLabs/Sia/build/critical.go:15 +0xae
github.com/NebulousLabs/Sia/persist.(*Logger).Critical(0xc0427a3f20, 0xc079d6fd80, 0x2, 0x2)
	/home/luke/go/src/github.com/NebulousLabs/Sia/persist/log.go:37 +0xe7
github.com/NebulousLabs/Sia/modules/renter.(*Renter).managedDownloadIteration(0xc043062600, 0xc079d6ff20)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/renter/download.go:320 +0x5c5
github.com/NebulousLabs/Sia/modules/renter.(*Renter).threadedDownloadLoop(0xc043062600)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/renter/download.go:585 +0x385
created by github.com/NebulousLabs/Sia/modules/renter.newRenter
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/renter/renter.go:208 +0x3b5
Critical error: ERROR: the renter is idle , but tracking active pieces: 26
Please submit a bug report here: https://github.com/NebulousLabs/Sia/issues
goroutine 415834 [running]:
runtime/debug.Stack(0x4442be, 0x0, 0xc045823da8)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x80
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x29
github.com/NebulousLabs/Sia/build.Severe(0xc045823f20, 0x2, 0x2)
	/home/luke/go/src/github.com/NebulousLabs/Sia/build/critical.go:29 +0x99
github.com/NebulousLabs/Sia/persist.(*Logger).Severe(0xc0420a7f80, 0xc045823f20, 0x2, 0x2)
	/home/luke/go/src/github.com/NebulousLabs/Sia/persist/log.go:71 +0xe7
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).syncResources.func1(0xc047b00000, 0xc042066668)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:49 +0x43f
created by github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).syncResources
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:52 +0x9a
Severe error: ERROR: unable to atomically copy the contract manager settings: rename C:\Users\Brian\AppData\Roaming\Sia-UI\sia\host\contractmanager\contractmanager.json_temp C:\Users\Brian\AppData\Roaming\Sia-UI\sia\host\contractmanager\contractmanager.json: Access is denied.
panic: unable to atomically copy contract manager settings, crashing to avoid data corruption

goroutine 415834 [running]:
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).syncResources.func1(0xc047b00000, 0xc042066668)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:50 +0x486
created by github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).syncResources
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:52 +0x9a

**Comment by DavidVorick** [comment] 2017-04-05 13:13
Hmm okay. I think I know what's going on here, I'll see if I can reproduce and debug it.

**Comment by DavidVorick** [comment] 2017-04-05 13:13
Thanks for trying the RC and reporting the bugs with it :)

**Comment by DavidVorick** [comment] 2017-04-05 14:52
Is there any chance that you were viewing the contractmanager.json in a file browser when this crash happened? Or that some other process on your system was scanning/indexing/viewing the file?

**Comment by gwar11d2** [comment] 2017-04-05 15:09
Nope... I was sleeping at the time.

I was however trying to do those downloads, so i wonder if one of those
jobs were left open?

**Comment by betaboot** [comment] 2017-04-05 15:12
Just now i had the same crash. The client was just running. No up- or downloading.

goroutine 1008814 [running]:
runtime/debug.Stack(0x4442be, 0x0, 0xc04b809da8)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x80
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x29
github.com/NebulousLabs/Sia/build.Severe(0xc04b809f20, 0x2, 0x2)
	/home/luke/go/src/github.com/NebulousLabs/Sia/build/critical.go:29 +0x99
github.com/NebulousLabs/Sia/persist.(*Logger).Severe(0xc0420b3860, 0xc04b809f20, 0x2, 0x2)
	/home/luke/go/src/github.com/NebulousLabs/Sia/persist/log.go:71 +0xe7
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).syncResources.func1(0xc043ee71b0, 0xc042182548)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:49 +0x43f
created by github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).syncResources
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:52 +0x9a
Severe error: ERROR: unable to atomically copy the contract manager settings: rename C:\Users\Cube\AppData\Roaming\Sia-UI\sia\host\contractmanager\contractmanager.json_temp C:\Users\Cube\AppData\Roaming\Sia-UI\sia\host\contractmanager\contractmanager.json: Access is denied.
panic: unable to atomically copy contract manager settings, crashing to avoid data corruption

goroutine 1008814 [running]:
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).syncResources.func1(0xc043ee71b0, 0xc042182548)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:50 +0x486
created by github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).syncResources
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:52 +0x9a

**Comment by gowithplanb** [comment] 2017-04-05 15:56
Loading...
(0/7) Loading siad...
(1/7) Loading gateway...
(2/7) Loading consensus...
(3/7) Loading transaction pool...
(4/7) Loading wallet...
(5/7) Loading miner...
(6/7) Loading host...
(7/7) Loading renter...
Finished loading in 0.3960227 seconds
goroutine 9 [running]:
runtime/debug.Stack(0x4442be, 0x0, 0xc0432bfa68)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x80
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x29
github.com/NebulousLabs/Sia/build.Severe(0xc0432bfbf0, 0x2, 0x2)
	/home/luke/go/src/github.com/NebulousLabs/Sia/build/critical.go:29 +0x99
github.com/NebulousLabs/Sia/persist.(*Logger).Severe(0xc04220cde0, 0xc0432bfbf0, 0x2, 0x2)
	/home/luke/go/src/github.com/NebulousLabs/Sia/persist/log.go:71 +0xe7
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).syncResources(0xc042068788)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:108 +0x73b
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).commit(0xc042068788)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:146 +0x47
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).threadedSyncLoop(0xc042068788, 0xc0421bef00, 0xc0421bef60)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:269 +0x149
created by github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).spawnSyncLoop
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:216 +0x103
Severe error: ERROR: could not rename temporary write-ahead-log in contract manager: rename C:\Users\Martijn\AppData\Roaming\Sia-UI\sia\host\contractmanager\contractmanager.wal_temp C:\Users\Martijn\AppData\Roaming\Sia-UI\sia\host\contractmanager\contractmanager.wal: Toegang geweigerd.
panic: unable to copy-on-write the WAL temporary file, crashing to prevent data corruption

goroutine 9 [running]:
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).syncResources(0xc042068788)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:109 +0x78b
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).commit(0xc042068788)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:146 +0x47
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).threadedSyncLoop(0xc042068788, 0xc0421bef00, 0xc0421bef60)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:269 +0x149
created by github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).spawnSyncLoop
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:216 +0x103

**Comment by gowithplanb** [comment] 2017-04-05 17:39
Same error happened again. It's also the same error as @betaboot experienced.

**Comment by DavidVorick** [comment] 2017-04-05 19:56
@gwar11d2 @betaboot @gowithplanb everyone is using Windows, correct? I believe the 'Access is Denied' error is Windows only. I'm really not sure what the issue is, because it performs that rename option basically once a second. Even more confusing, the file that it renames to is never read. It just gets overwritten repeatedly.

Is it possible that the disk is low on space? The new storage manager will create a giant sparse file after the update.

**Comment by gwar11d2** [comment] 2017-04-05 20:09
Yes. I'm on Win 10. Plenty of disk space

**Comment by gowithplanb** [comment] 2017-04-05 20:52
Same here, 23 gigs available, Windows 7

**Comment by DavidVorick** [comment] 2017-04-05 22:55
Good news is I've figured out how to reproduce this error on our Windows test suite. So it's only a matter of time before there's a decisive fix.

**Comment by DavidVorick** [comment] 2017-04-06 04:44
Found the issue, fix will be available soon. Essentially was calling 'sync' and 'rename' in threads where I didn't realize it, when abusing the `persist` package that we have. Definitely a programming error. Unclear if it could have resulted in actual problems for Linux users, but glad that it was discovered overall.

**Comment by DavidVorick** [comment] 2017-04-06 12:37
I'm going to have to backpedal on that. I thought I had found the issue but actually it was late and I was just not reading things correctly.

If you guys could keep running the RC and posting these crash reports, that would be really helpful. We're having trouble reproducing it, and don't have too many Windows machines to test things on. In particular, I'm looking for unique error messages.

Above we have two different crash points. One set of crashes is happening here:
 `github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).syncResources.func1(0xc047b00000, 0xc042066668)
/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:49 +0x43f` => line 49

And another crash here:
`github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).syncResources(0xc042068788)
/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:108 +0x73b` => line 108

Both those lines are a call to `os.Rename`, I am wondering if it is always the rename which causes problems or if there is another point that can fail as well.

**Comment by gwar11d2** [comment] 2017-04-06 12:43
Here is another one from this morning David --

Loading...
(0/7) Loading siad...
(1/7) Loading gateway...
(2/7) Loading consensus...
(3/7) Loading transaction pool...
(4/7) Loading wallet...
(5/7) Loading miner...
(6/7) Loading host...
(7/7) Loading renter...
Finished loading in 15.5911878 seconds
goroutine 764 [running]:
runtime/debug.Stack(0x44433e, 0x0, 0xc042cedc28)
/usr/local/go/src/runtime/debug/stack.go:24 +0x80
runtime/debug.PrintStack()
/usr/local/go/src/runtime/debug/stack.go:16 +0x29
github.com/NebulousLabs/Sia/build.Critical(0xc042cedd80, 0x2, 0x2)
/home/luke/go/src/github.com/NebulousLabs/Sia/build/critical.go:15 +0xae
github.com/NebulousLabs/Sia/persist.(*Logger).Critical(0xc042f11920,
0xc042cedd80, 0x2, 0x2)
/home/luke/go/src/github.com/NebulousLabs/Sia/persist/log.go:37 +0xe7
github.com/NebulousLabs/Sia/modules/renter.(*Renter).managedDownloadIteration(0xc042e5c480,
0xc042cedf20)
/home/luke/go/src/github.com/NebulousLabs/Sia/modules/renter/download.go:320
+0x5c5
github.com/NebulousLabs/Sia/modules/renter.(*Renter).threadedDownloadLoop(0xc042e5c480)
/home/luke/go/src/github.com/NebulousLabs/Sia/modules/renter/download.go:585
+0x385
created by github.com/NebulousLabs/Sia/modules/renter.newRenter
/home/luke/go/src/github.com/NebulousLabs/Sia/modules/renter/renter.go:208
+0x3b5
Critical error: ERROR: the renter is idle , but tracking active pieces: 5
Please submit a bug report here: https://github.com/NebulousLabs/Sia/issues
goroutine 764 [running]:
runtime/debug.Stack(0x44433e, 0x0, 0xc042489c28)
/usr/local/go/src/runtime/debug/stack.go:24 +0x80
runtime/debug.PrintStack()
/usr/local/go/src/runtime/debug/stack.go:16 +0x29
github.com/NebulousLabs/Sia/build.Critical(0xc042489d80, 0x2, 0x2)
/home/luke/go/src/github.com/NebulousLabs/Sia/build/critical.go:15 +0xae
github.com/NebulousLabs/Sia/persist.(*Logger).Critical(0xc042f11920,
0xc042489d80, 0x2, 0x2)
/home/luke/go/src/github.com/NebulousLabs/Sia/persist/log.go:37 +0xe7
github.com/NebulousLabs/Sia/modules/renter.(*Renter).managedDownloadIteration(0xc042e5c480,
0xc042489f20)
/home/luke/go/src/github.com/NebulousLabs/Sia/modules/renter/download.go:320
+0x5c5
github.com/NebulousLabs/Sia/modules/renter.(*Renter).threadedDownloadLoop(0xc042e5c480)
/home/luke/go/src/github.com/NebulousLabs/Sia/modules/renter/download.go:585
+0x385
created by github.com/NebulousLabs/Sia/modules/renter.newRenter
/home/luke/go/src/github.com/NebulousLabs/Sia/modules/renter/renter.go:208
+0x3b5
Critical error: ERROR: the renter is idle , but tracking active pieces: 10
Please submit a bug report here: https://github.com/NebulousLabs/Sia/issues
goroutine 764 [running]:
runtime/debug.Stack(0x44433e, 0x0, 0xc04284fc28)
/usr/local/go/src/runtime/debug/stack.go:24 +0x80
runtime/debug.PrintStack()
/usr/local/go/src/runtime/debug/stack.go:16 +0x29
github.com/NebulousLabs/Sia/build.Critical(0xc04284fd80, 0x2, 0x2)
/home/luke/go/src/github.com/NebulousLabs/Sia/build/critical.go:15 +0xae
github.com/NebulousLabs/Sia/persist.(*Logger).Critical(0xc042f11920,
0xc04284fd80, 0x2, 0x2)
/home/luke/go/src/github.com/NebulousLabs/Sia/persist/log.go:37 +0xe7
github.com/NebulousLabs/Sia/modules/renter.(*Renter).managedDownloadIteration(0xc042e5c480,
0xc04284ff20)
/home/luke/go/src/github.com/NebulousLabs/Sia/modules/renter/download.go:320
+0x5c5
github.com/NebulousLabs/Sia/modules/renter.(*Renter).threadedDownloadLoop(0xc042e5c480)
/home/luke/go/src/github.com/NebulousLabs/Sia/modules/renter/download.go:585
+0x385
created by github.com/NebulousLabs/Sia/modules/renter.newRenter
/home/luke/go/src/github.com/NebulousLabs/Sia/modules/renter/renter.go:208
+0x3b5
Critical error: ERROR: the renter is idle , but tracking active pieces: 16
Please submit a bug report here: https://github.com/NebulousLabs/Sia/issues
goroutine 2045629 [running]:
runtime/debug.Stack(0x4442be, 0x0, 0xc043905da8)
/usr/local/go/src/runtime/debug/stack.go:24 +0x80
runtime/debug.PrintStack()
/usr/local/go/src/runtime/debug/stack.go:16 +0x29
github.com/NebulousLabs/Sia/build.Severe(0xc043905f20, 0x2, 0x2)
/home/luke/go/src/github.com/NebulousLabs/Sia/build/critical.go:29 +0x99
github.com/NebulousLabs/Sia/persist.(*Logger).Severe(0xc0420a7de0,
0xc043905f20, 0x2, 0x2)
/home/luke/go/src/github.com/NebulousLabs/Sia/persist/log.go:71 +0xe7
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).syncResources.func1(0xc044fa4650,
0xc042050788)
/home/luke/go/src/
github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:49
+0x43f
created by
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).syncResources
/home/luke/go/src/
github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:52
+0x9a
Severe error: ERROR: unable to atomically copy the contract manager
settings: rename
C:\Users\Brian\AppData\Roaming\Sia-UI\sia\host\contractmanager\contractmanager.json_temp
C:\Users\Brian\AppData\Roaming\Sia-UI\sia\host\contractmanager\contractmanager.json:
Access is denied.
panic: unable to atomically copy contract manager settings, crashing to
avoid data corruption

goroutine 2045629 [running]:
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).syncResources.func1(0xc044fa4650,
0xc042050788)
/home/luke/go/src/
github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:50
+0x486
created by
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).syncResources
/home/luke/go/src/
github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:52
+0x9a

**Comment by betaboot** [comment] 2017-04-07 04:31
There's another one:

goroutine 64 [running]:
runtime/debug.Stack(0x44433e, 0x0, 0xc0434986e8)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x80
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x29
github.com/NebulousLabs/Sia/build.Critical(0xc043498860, 0x1, 0x1)
	/home/luke/go/src/github.com/NebulousLabs/Sia/build/critical.go:15 +0xae
github.com/NebulousLabs/Sia/persist.(*Logger).Critical(0xc0421c2ec0, 0xc043498860, 0x1, 0x1)
	/home/luke/go/src/github.com/NebulousLabs/Sia/persist/log.go:37 +0xe7
github.com/NebulousLabs/Sia/modules/renter/hostdb.(*HostDB).uptimeAdjustments(0xc0421c6500, 0x1, 0x1100000, 0x6660, 0x1100000, 0xc0484ed350, 0x2d, 0xba27b7400, 0x400000, 0xba43b7400, ...)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/renter/hostdb/hostweight.go:269 +0x267
github.com/NebulousLabs/Sia/modules/renter/hostdb.(*HostDB).calculateHostWeight(0xc0421c6500, 0x1, 0x1100000, 0x6660, 0x1100000, 0xc0484ed350, 0x2d, 0xba27b7400, 0x400000, 0xba43b7400, ...)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/renter/hostdb/hostweight.go:323 +0x219
github.com/NebulousLabs/Sia/modules/renter/hostdb.(*HostDB).(github.com/NebulousLabs/Sia/modules/renter/hostdb.calculateHostWeight)-fm(0x1, 0x1100000, 0x6660, 0x1100000, 0xc0484ed350, 0x2d, 0xba27b7400, 0x400000, 0xba43b7400, 0x3e4ef29e7c45c0ec, ...)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/renter/hostdb/hostdb.go:107 +0x66
github.com/NebulousLabs/Sia/modules/renter/hostdb/hosttree.(*HostTree).Modify(0xc0421c2ee0, 0x1, 0x1100000, 0x6660, 0x1100000, 0xc0484ed350, 0x2d, 0xba27b7400, 0x400000, 0xba43b7400, ...)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/renter/hostdb/hosttree/hosttree.go:257 +0x12f
github.com/NebulousLabs/Sia/modules/renter/hostdb.(*HostDB).updateEntry(0xc0421c6500, 0x1, 0x1100000, 0x6660, 0x1100000, 0xc0484ed350, 0x2d, 0xba27b7400, 0x400000, 0xba43b7400, ...)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/renter/hostdb/scan.go:170 +0x461
github.com/NebulousLabs/Sia/modules/renter/hostdb.(*HostDB).managedScanHost(0xc0421c6500, 0x1, 0x1100000, 0x6660, 0x1100000, 0xc0484ed350, 0x2d, 0xba27b7400, 0x400000, 0xba43b7400, ...)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/renter/hostdb/scan.go:226 +0x3c3
github.com/NebulousLabs/Sia/modules/renter/hostdb.(*HostDB).threadedProbeHosts(0xc0421c6500)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/renter/hostdb/scan.go:263 +0x357
created by github.com/NebulousLabs/Sia/modules/renter/hostdb.newHostDB
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/renter/hostdb/hostdb.go:173 +0x6f2
Critical error: Host entry scan history not sorted.
Please submit a bug report here: https://github.com/NebulousLabs/Sia/issues
goroutine 1198084 [running]:
runtime/debug.Stack(0x4442be, 0x0, 0xc042ac7da8)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x80
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x29
github.com/NebulousLabs/Sia/build.Severe(0xc042ac7f20, 0x2, 0x2)
	/home/luke/go/src/github.com/NebulousLabs/Sia/build/critical.go:29 +0x99
github.com/NebulousLabs/Sia/persist.(*Logger).Severe(0xc0422090a0, 0xc042ac7f20, 0x2, 0x2)
	/home/luke/go/src/github.com/NebulousLabs/Sia/persist/log.go:71 +0xe7
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).syncResources.func1(0xc044603a80, 0xc04217e8a8)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:49 +0x43f
created by github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).syncResources
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:52 +0x9a
Severe error: ERROR: unable to atomically copy the contract manager settings: rename C:\Users\Cube\AppData\Roaming\Sia-UI\sia\host\contractmanager\contractmanager.json_temp C:\Users\Cube\AppData\Roaming\Sia-UI\sia\host\contractmanager\contractmanager.json: Access is denied.
panic: unable to atomically copy contract manager settings, crashing to avoid data corruption

goroutine 1198084 [running]:
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).syncResources.func1(0xc044603a80, 0xc04217e8a8)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:50 +0x486
created by github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).syncResources
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:52 +0x9a

**Comment by gowithplanb** [comment] 2017-04-07 14:42
Loading...
(0/7) Loading siad...
(1/7) Loading gateway...
(2/7) Loading consensus...
(3/7) Loading transaction pool...
(4/7) Loading wallet...
(5/7) Loading miner...
(6/7) Loading host...
(7/7) Loading renter...
Finished loading in 0.4380251 seconds

Wallet: scanned to height 98885...
Wallet: scanned to height 98944...
Done!
goroutine 1447856 [running]:
runtime/debug.Stack(0x4442be, 0x0, 0xc042f31da8)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x80
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x29
github.com/NebulousLabs/Sia/build.Severe(0xc042f31f20, 0x2, 0x2)
	/home/luke/go/src/github.com/NebulousLabs/Sia/build/critical.go:29 +0x99
github.com/NebulousLabs/Sia/persist.(*Logger).Severe(0xc04218d0e0, 0xc042f31f20, 0x2, 0x2)
	/home/luke/go/src/github.com/NebulousLabs/Sia/persist/log.go:71 +0xe7
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).syncResources.func1(0xc0433a1330, 0xc042079088)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:49 +0x43f
created by github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).syncResources
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:52 +0x9a
Severe error: ERROR: unable to atomically copy the contract manager settings: rename C:\Users\Martijn\AppData\Roaming\Sia-UI\sia\host\contractmanager\contractmanager.json_temp C:\Users\Martijn\AppData\Roaming\Sia-UI\sia\host\contractmanager\contractmanager.json: Toegang geweigerd.
panic: unable to atomically copy contract manager settings, crashing to avoid data corruption

goroutine 1447856 [running]:
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).syncResources.func1(0xc0433a1330, 0xc042079088)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:50 +0x486
created by github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).syncResources
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:52 +0x9a

**Comment by DavidVorick** [comment] 2017-04-07 18:07
I have been unable to reproduce this on our Windows machine. For the time being we are addressing this by removing the emergency panic. Long term we will probably replace the rename strategy with an in-place rewrite strategy.

Any chance that you guys are running anti-virus, file indexing, regular backups, or some other program that might be occasionally touching the files?

**Comment by gowithplanb** [comment] 2017-04-10 22:14
The current RC2 code seems to keep siad running on Windows, at least for me.

**Comment by DavidVorick** [comment] 2017-04-13 17:15
fixed by just ignoring (well, logging) the error instead of crashing. We have a new design that'll prevent the error from happening in the first place, but it's going to be a while before that's fully implemented.

**Closed** 2017-04-13 20:05 UTC
