### ISSUE TITLE
Only one usage of each socket address error

### ISSUE THREAD

**Issue by rogerlu88** [NebulousLabs/Sia#2971] opened 2018-04-28 13:58 UTC
# BUG REPORT

**Stack Trace or error message**

Sia Daemon v1.3.2
Git Revision 72938f5
Loading...
listen tcp 127.0.0.1:9980: bind: Only one usage of each socket address (protocol/network address/port) 
is normally permitted.

Kill the process and restart again. I got this error:
Sia Daemon v1.3.2
Git Revision 72938f5
Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 0.0909773 seconds
panic: bolt.DB.meta(): invalid meta pages

goroutine 351 [running]:
github.com/NebulousLabs/Sia/vendor/github.com/coreos/bbolt.(*DB).meta(0xc0422741e0, 0xc0427f0000)
	/home/luke/go/src/github.com/NebulousLabs/Sia/vendor/github.com/coreos/bbolt/db.go:894 +0xc9
github.com/NebulousLabs/Sia/vendor/github.com/coreos/bbolt.(*meta).copy(...)
	/home/luke/go/src/github.com/NebulousLabs/Sia/vendor/github.com/coreos/bbolt/tx.go:50
github.com/NebulousLabs/Sia/vendor/github.com/coreos/bbolt.(*Tx).init(0xc04218e1c0, 0xc0422741e0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/vendor/github.com/coreos/bbolt/tx.go:50 +0xb3
github.com/NebulousLabs/Sia/vendor/github.com/coreos/bbolt.(*DB).beginTx(0xc0422741e0, 0xc0422501c4, 0x4426f9, 0x2d05d97b0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/vendor/github.com/coreos/bbolt/db.go:546 +0xab
github.com/NebulousLabs/Sia/vendor/github.com/coreos/bbolt.(*DB).Begin(0xc0422741e0, 0xc000000000, 0xc04234f080, 0x473424, 0x7a9737)
	/home/luke/go/src/github.com/NebulousLabs/Sia/vendor/github.com/coreos/bbolt/db.go:523 +0x75
github.com/NebulousLabs/Sia/vendor/github.com/coreos/bbolt.(*DB).View(0xc0422741e0, 0xc04216fc38, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/vendor/github.com/coreos/bbolt/db.go:688 +0x4d
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).CurrentBlock(0xc042250000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/consensusset.go:259 +0x114
github.com/NebulousLabs/Sia/node/api.(*API).consensusHandler(0xc042160990, 0xdf48e0, 0xc0426f4380, 0xc04214c900, 0x0, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/node/api/consensus.go:24 +0x52
github.com/NebulousLabs/Sia/node/api.(*API).(github.com/NebulousLabs/Sia/node/api.consensusHandler)-fm(0xdf48e0, 0xc0426f4380, 0xc04214c900, 0x0, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/node/api/routes.go:23 +0x6d
github.com/julienschmidt/httprouter.(*Router).ServeHTTP(0xc042041d00, 0xdf48e0, 0xc0426f4380, 0xc04214c900)
	/home/luke/go/src/github.com/julienschmidt/httprouter/router.go:344 +0x7a0
github.com/NebulousLabs/Sia/node/api.RequireUserAgent.func1(0xdf48e0, 0xc0426f4380, 0xc04214c900)
	/home/luke/go/src/github.com/NebulousLabs/Sia/node/api/routes.go:173 +0xc1
net/http.HandlerFunc.ServeHTTP(0xc042328540, 0xdf48e0, 0xc0426f4380, 0xc04214c900)
	/usr/local/go/src/net/http/server.go:1918 +0x4b
github.com/NebulousLabs/Sia/node/api.cleanCloseHandler.func1.1(0xc0420361e0, 0xdeff60, 0xc042328540, 0xdf48e0, 0xc0426f4380, 0xc04214c900)
	/home/luke/go/src/github.com/NebulousLabs/Sia/node/api/routes.go:144 +0x80
created by github.com/NebulousLabs/Sia/node/api.cleanCloseHandler.func1
	/home/luke/go/src/github.com/NebulousLabs/Sia/node/api/routes.go:142 +0xa7

**Expected Behavior**

**How to reproduce it (as minimally and precisely as possible)**

**Environment**
* Sia version: Sia-UI-v1.3.2-win32-x64
* OS: Windows 10 Pro.

**Comment by rogerlu88** [comment] 2018-04-28 14:07
sorry. I am now to Sia coin and new to error reporting writing.

**Comment by tbenz9** [comment] 2018-05-01 22:39
`listen tcp 127.0.0.1:9980: bind: Only one usage of each socket address (protocol/network address/port)
is normally permitted.` means the Sia daemon was already running.  When you killed it manually it looks like you may have corrupted your database.

Duplicate of #2318 

Use this to work around your problem: https://gist.github.com/tbenz9/8066d74853ab28c23bd7bc1d3c7cdeda

**Closed by tbenz9** 2018-05-01 22:39 UTC
