### ISSUE TITLE
renter crashes siad

### ISSUE THREAD

**Issue by robvanmieghem** [NebulousLabs/Sia#973] opened 2016-02-04 19:25 UTC
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x5fe34]

goroutine 17967 [running]:
github.com/NebulousLabs/Sia/modules/renter/hostdb.(*HostDB).IsOffline(0xc8205b8d00, 0xc8210bf6a0, 0x12, 0xc82ca9ca00)
	/Users/rob/workspace/go/src/github.com/NebulousLabs/Sia/modules/renter/hostdb/hostentry.go:104 +0x6d
github.com/NebulousLabs/Sia/modules/renter.(*file).offlineChunks(0xc8214d0100, 0xfe1b20, 0xc8205b8d00, 0x0)
	/Users/rob/workspace/go/src/github.com/NebulousLabs/Sia/modules/renter/repair.go:171 +0x1ec
github.com/NebulousLabs/Sia/modules/renter.(*Renter).threadedRepairFile(0xc8214d0000, 0xc820fbe680, 0x19, 0xc820ecc030, 0x2e, 0xaaec, 0xc820d40201)
	/Users/rob/workspace/go/src/github.com/NebulousLabs/Sia/modules/renter/repair.go:258 +0x431
github.com/NebulousLabs/Sia/modules/renter.(*Renter).threadedRepairLoop.func1(0xc8298f1870, 0xc820254e40, 0xc8214d0000, 0xc820fbe680, 0x19, 0xc820ecc030, 0x2e, 0xaaec, 0x14e801)
	/Users/rob/workspace/go/src/github.com/NebulousLabs/Sia/modules/renter/repair.go:221 +0xb4
created by github.com/NebulousLabs/Sia/modules/renter.(*Renter).threadedRepairLoop
	/Users/rob/workspace/go/src/github.com/NebulousLabs/Sia/modules/renter/repair.go:223 +0x48d
```

Version: 3e1b184268475836e3cef79edeb4f745011e6843

**Comment by VoidingWarranties** [comment] 2016-02-04 20:47
I think this was fixed in #970. @lukechampine?

**Comment by robvanmieghem** [comment] 2016-02-04 20:55
I'll upgrade and see if it happens again

**Comment by lukechampine** [comment] 2016-02-04 21:17
yes, it is caused by a race condition in the repair loop, which is why it doesn't happen every time.
I'm closing this since it has almost certainly been fixed, but if you can trigger the same panic with the new code, drop a comment.

**Closed by lukechampine** 2016-02-04 21:17 UTC
