### ISSUE TITLE
cannot write to the file after it has been closed

### ISSUE THREAD

**Issue by poiuty** [NebulousLabs/Sia#1599] opened 2017-03-03 15:33 UTC
Sia v1.1.1
Start siad => start sync => ctrl + c
```
sia@sia:~/host$ siad
Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 3.029545589 seconds
Caught stop signal, quitting...
Closing renter...
Closing host...
goroutine 14 [running]:
runtime/debug.Stack(0x445727, 0x0, 0xc4202ffc68)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x79
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/NebulousLabs/Sia/build.Critical(0xc4202ffd18, 0x1, 0x1)
	/home/luke/go/src/github.com/NebulousLabs/Sia/build/critical.go:15 +0xa7
github.com/NebulousLabs/Sia/persist.(*closeableFile).Write(0xc42033a810, 0xc420068180, 0x6e, 0x80, 0x0, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/persist/log.go:114 +0x178
log.(*Logger).Output(0xc420328870, 0x2, 0xc420276910, 0x45, 0x0, 0x0)
	/usr/local/go/src/log/log.go:168 +0x210
log.(*Logger).Println(0xc420328870, 0xc420300010, 0x2, 0x2)
	/usr/local/go/src/log/log.go:184 +0x6a
github.com/NebulousLabs/Sia/modules/renter/contractor.(*Contractor).ProcessConsensusChange(0xc420410280, 0xb2d50653bf2fab59, 0xc83866d605733387, 0xecefeb751431f116, 0x442a68007764ea5c, 0x0, 0x0, 0x0, 0xc42016fce0, 0x1, ...)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/renter/contractor/update.go:57 +0x87c
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).readlockUpdateSubscribers(0xc420133b80, 0x0, 0x0, 0x0, 0xc4201692a0, 0x1, 0x1)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/subscribe.go:113 +0x173
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).managedAcceptBlock(0xc420133b80, 0xf5ec720200000000, 0x1e824afad3fc0c9f, 0xf92d2e5c20f3577b, 0x43febaff316ecaf2, 0xb1200000000334e, 0x55748ce5, 0xc420018100, 0x1, 0x1, ...)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/accept.go:287 +0x1e9
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).managedReceiveBlocks(0xc420133b80, 0xd4a060, 0xc420168800, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:196 +0x5b8
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).(github.com/NebulousLabs/Sia/modules/consensus.managedReceiveBlocks)-fm(0xd4a060, 0xc420168800, 0x9c56e0, 0xc420162698)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:355 +0x3e
github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).managedRPC(0xc4200751e0, 0xa72127, 0x13, 0xa692db, 0xa, 0xc420162680, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/rpc.go:57 +0x25f
github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).RPC(0xc4200751e0, 0xa72127, 0x13, 0xa692db, 0xa, 0xc420162680, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/rpc.go:67 +0xd1
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).threadedInitialBlockchainDownload.func1(0xc420133b80, 0xc420301ee8, 0xc420301ea8, 0xc420301eb0, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:540 +0x12c
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).threadedInitialBlockchainDownload(0xc420133b80, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:566 +0x307
github.com/NebulousLabs/Sia/modules/consensus.New.func1(0x1, 0xc42023f450, 0xc420133b80, 0xd4a360, 0xc4200751e0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/consensusset.go:140 +0x4d9
created by github.com/NebulousLabs/Sia/modules/consensus.New
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/consensusset.go:173 +0x63a
Critical error: cannot write to the file after it has been closed
Please submit a bug report here: https://github.com/NebulousLabs/Sia/issues
```

**Comment by lukechampine** [comment] 2017-03-03 16:36
Thanks! This was caused by the contractor not unsubscribing from new blocks during shutdown. Fixed in #1598.

**Closed by lukechampine** 2017-03-03 16:36 UTC
