### ISSUE TITLE
Error syncing wallet

### ISSUE THREAD

**Issue by NildoSena** [NebulousLabs/Sia#2531] opened 2017-12-13 16:59 UTC
Bug Report
==========
Check to see if a bug report already exists.  If you still want to create a new issue please include the information below.

**Stack Trace or error message**

Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 1.9599609 seconds

**Environment**
* Sia version: 1.3.0

* OS: windows 7 Ultimate 64x

**Any useful logs**

I managed to sync up to 80.7 % and reported error

Feature Request
===============
Check to see if the feature is on the roadmap.  If it is not on the roadmap then clearly describe your feature request and why it would benefit Sia.

[Sia roadmap](https://trello.com/b/Io1dDyuI/sia-public-roadmap)

**Comment by NildoSena** [comment] 2017-12-13 17:01
please help me, I'm having problems synchronizing my wallet, besides delaying 20 hours synchronizing when arriving at 80.7% happens error and for synchronization, help please, thank you

**Comment by tbenz9** [comment] 2017-12-13 17:29
@NildoSena Can you post the logs?  If you are using the Sia-UI press Ctrl+Shift+L and a new screen will appear where you can select and read them.

I would also recommend you ask for help in the Sia Discord, they will be able to help you in real time instead of waiting for a response here.  https://discord.gg/sia

**Comment by tbenz9** [comment] 2017-12-13 17:29
Closing for now, will re-open if logs are attached.

**Closed by tbenz9** 2017-12-13 17:29 UTC

**Comment by NildoSena** [comment] 2017-12-13 17:47
thank you

erro complete:

Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 1.9833984999999998 seconds
panic: page 82341 already freed

goroutine 5 [running]:
github.com/NebulousLabs/bolt.(*freelist).free(0xc0420088d0, 0x449, 0x171e5000)
	/home/luke/go/src/github.com/NebulousLabs/bolt/freelist.go:121 +0x2a1
github.com/NebulousLabs/bolt.(*node).spill(0xc0439ad1f0, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/bolt/node.go:363 +0x1e7
github.com/NebulousLabs/bolt.(*node).spill(0xc0420f6b60, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/bolt/node.go:350 +0xbb
github.com/NebulousLabs/bolt.(*node).spill(0xc042052070, 0xc042008bd0, 0xc0423b5a28)
	/home/luke/go/src/github.com/NebulousLabs/bolt/node.go:350 +0xbb
github.com/NebulousLabs/bolt.(*Bucket).spill(0xc04200a700, 0xc0423b5b00, 0x15)
	/home/luke/go/src/github.com/NebulousLabs/bolt/bucket.go:570 +0x182
github.com/NebulousLabs/bolt.(*Bucket).spill(0xc0422ce2b8, 0xb68a078, 0xee9fe0)
	/home/luke/go/src/github.com/NebulousLabs/bolt/bucket.go:537 +0x8ff
github.com/NebulousLabs/bolt.(*Tx).Commit(0xc0422ce2a0, 0xc042018d00, 0xc0423b5e80)
	/home/luke/go/src/github.com/NebulousLabs/bolt/tx.go:163 +0x12c
github.com/NebulousLabs/Sia/modules/transactionpool.(*TransactionPool).syncDB(0xc0423b8000)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/transactionpool/persist.go:54 +0x4e
github.com/NebulousLabs/Sia/modules/transactionpool.(*TransactionPool).threadedRegularSync(0xc0423b8000)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/transactionpool/persist.go:44 +0x17e
created by github.com/NebulousLabs/Sia/modules/transactionpool.(*TransactionPool).initPersist
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/transactionpool/persist.go:126 +0x3f6

**Comment by tbenz9** [comment] 2017-12-13 17:58
Duplicate of #2413

**Comment by NildoSena** [comment] 2017-12-13 18:24
What can I do to solve it? can you help me? thankful

**Comment by tbenz9** [comment] 2017-12-13 19:26
First, delete the consensus.db file. It is located in:

- Windows: Users\<user>\appdata\roaming\Sia-UI\sia\consensus\consensus.db
- OS X: $HOME/Library/Application Support/Sia-UI/sia/consensus/consensus.db
- Linux: $HOME/.config/Sia-UI/sia/consensus/consensus.db

If this doesn’t resolve, delete the transactionpool.db file as well:

- Windows: Users\<user>\appdata\roaming\Sia-UI\sia\transactionpool\transactionpool.db
- OS X: $HOME/Library/Application Support/Sia-UI/sia/transactionpool/transactionpool.db
- Linux: $HOME/.config/Sia-UI/sia/transactionpool/transactionpool.db
