### ISSUE TITLE
MacOS Sierra

### ISSUE THREAD

**Issue by Davidson777** [NebulousLabs/Sia#1798] opened 2017-05-16 06:47 UTC
Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 0.020540118 seconds

Wallet: scanned to height 9299...
Wallet: scanned to height 20075...
Wallet: scanned to height 24167...
Wallet: scanned to height 31325...
Wallet: scanned to height 34011...
Wallet: scanned to height 34567...
Wallet: scanned to height 34843...
Wallet: scanned to height 35299...
Wallet: scanned to height 36180...
Done!
goroutine 1 [running]:
runtime/debug.Stack(0x1043857, 0x0, 0xc4203455f8)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x79
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/NebulousLabs/Sia/build.Critical(0xc420345948, 0x1, 0x1)
	/home/luke/go/src/github.com/NebulousLabs/Sia/build/critical.go:15 +0xa7
main.startDaemon(0x0, 0x0, 0x7fff5fbffd1c, 0xe, 0x7fff5fbffd48, 0x5, 0x7fff5fbffd37, 0x5, 0x0, 0x7fff5fbffd58, ...)
	/home/luke/go/src/github.com/NebulousLabs/Sia/siad/daemon.go:295 +0xaa9
main.startDaemonCmd(0xc420089200, 0xc420019360, 0x0, 0x5)
	/home/luke/go/src/github.com/NebulousLabs/Sia/siad/daemon.go:309 +0x6d
github.com/spf13/cobra.(*Command).execute(0xc420089200, 0xc42000e0d0, 0x5, 0x5, 0xc420089200, 0xc42000e0d0)
	/home/luke/go/src/github.com/spf13/cobra/command.go:648 +0x234
github.com/spf13/cobra.(*Command).ExecuteC(0xc420089200, 0x16c6004, 0x3b, 0xc42015c780)
	/home/luke/go/src/github.com/spf13/cobra/command.go:734 +0x339
github.com/spf13/cobra.(*Command).Execute(0xc420089200, 0x1aa4520, 0x16af49d)
	/home/luke/go/src/github.com/spf13/cobra/command.go:693 +0x2b
main.main()
	/home/luke/go/src/github.com/NebulousLabs/Sia/siad/main.go:174 +0x7ac
Critical error: accept tcp 127.0.0.1:9980: accept: too many open files in system
Please submit a bug report here: https://github.com/NebulousLabs/Sia/issues
Closing renter...
Closing host...

![image](https://cloud.githubusercontent.com/assets/28724563/26093050/b153a958-3a1c-11e7-8f38-be37061d85cf.png)

**Comment by lukechampine** [comment] 2017-05-16 06:51
duplicate of #1757

**Closed by lukechampine** 2017-05-16 06:51 UTC
