### ISSUE TITLE
Siad has exited unexpectedly

### ISSUE THREAD

**Issue by jedo75** [NebulousLabs/Sia#2154] opened 2017-07-19 10:00 UTC
Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 1.161965226 seconds
2017/07/19 10:54:57 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
2017/07/19 10:55:00 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
2017/07/19 10:55:00 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
2017/07/19 10:55:00 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
2017/07/19 10:55:00 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 10ms
2017/07/19 10:55:00 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 20ms
2017/07/19 10:55:00 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
2017/07/19 10:55:00 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
2017/07/19 10:55:00 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
2017/07/19 10:55:00 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
2017/07/19 10:55:00 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
2017/07/19 10:55:00 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
2017/07/19 10:55:00 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
2017/07/19 10:55:00 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
2017/07/19 10:55:01 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
2017/07/19 10:55:01 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 10ms
2017/07/19 10:55:01 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 20ms
2017/07/19 10:55:01 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 40ms
2017/07/19 10:55:01 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 80ms
2017/07/19 10:55:01 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 160ms
2017/07/19 10:55:01 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 320ms
2017/07/19 10:55:01 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 640ms
2017/07/19 10:55:02 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/07/19 10:55:03 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/07/19 10:55:04 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/07/19 10:55:05 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/07/19 10:55:06 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/07/19 10:55:07 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/07/19 10:55:08 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/07/19 10:55:09 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/07/19 10:55:10 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/07/19 10:55:11 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/07/19 10:55:12 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/07/19 10:55:13 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/07/19 10:55:14 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/07/19 10:55:15 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/07/19 10:55:16 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/07/19 10:55:17 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/07/19 10:55:18 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/07/19 10:55:19 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/07/19 10:55:20 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/07/19 10:55:21 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/07/19 10:55:22 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/07/19 10:55:23 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/07/19 10:55:24 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/07/19 10:55:25 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
2017/07/19 10:55:25 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
2017/07/19 10:55:25 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
2017/07/19 10:55:25 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
2017/07/19 10:55:25 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 10ms
2017/07/19 10:55:25 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 20ms
2017/07/19 10:55:25 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
2017/07/19 10:55:25 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 10ms
2017/07/19 10:55:25 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 20ms
2017/07/19 10:55:25 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
2017/07/19 10:55:25 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 10ms
2017/07/19 10:55:25 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
2017/07/19 10:55:25 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 10ms
2017/07/19 10:55:25 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 20ms
2017/07/19 10:55:25 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 40ms
goroutine 23215 [running]:
runtime/debug.Stack(0x445617, 0x0, 0xc4418a6c80)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x79
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/NebulousLabs/Sia/build.Severe(0xc4418a6e78, 0x2, 0x2)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/build/critical.go:32 +0x92
github.com/NebulousLabs/Sia/persist.(*Logger).Severe(0xc420452700, 0xc4418a6e78, 0x2, 0x2)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/persist/log.go:71 +0xe0
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).commit.func2(0xc4378c24f0, 0xc4200a3e08, 0x0, 0x0, 0x0, 0xebc2b0, 0x0, 0x0)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:196 +0x236
created by github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).commit
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:209 +0x1e5
Severe error: ERROR: unable to create write-ahead-log: open /home/rozman/.config/Sia-UI/sia/host/contractmanager/contractmanager.wal_temp: too many open files
goroutine 23215 [running]:
runtime/debug.Stack(0x445617, 0x0, 0xc4418a6c80)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x79
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/NebulousLabs/Sia/build.Severe(0xc4418a6e58, 0x2, 0x2)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/build/critical.go:32 +0x92
github.com/NebulousLabs/Sia/persist.(*Logger).Severe(0xc420452700, 0xc4418a6e58, 0x2, 0x2)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/persist/log.go:71 +0xe0
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).commit.func2(0xc4378c24f0, 0xc4200a3e08, 0x0, 0x0, 0x0, 0xebc2b0, 0x0, 0x0)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:201 +0x357
created by github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).commit
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:209 +0x1e5
Severe error: Unable to properly initialize WAL file, crashing to prevent corruption: unable to write WAL metadata: invalid argument
goroutine 23215 [running]:
runtime/debug.Stack(0x445617, 0x0, 0xc4418a6aa0)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x79
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/NebulousLabs/Sia/build.Severe(0xc4418a6c18, 0x2, 0x2)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/build/critical.go:32 +0x92
github.com/NebulousLabs/Sia/persist.(*Logger).Severe(0xc420452700, 0xc4418a6c18, 0x2, 0x2)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/persist/log.go:71 +0xe0
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).appendChange(0xc4200a3e08, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlog.go:151 +0x46e
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).commit.func2(0xc4378c24f0, 0xc4200a3e08, 0x0, 0x0, 0x0, 0xebc2b0, 0x0, 0x0)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:208 +0x423
created by github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).commit
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:209 +0x1e5
Severe error: Unable to write state change to WAL: invalid argument
panic: unable to append a change to the WAL, crashing to prevent corruption

goroutine 23215 [running]:
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).appendChange(0xc4200a3e08, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlog.go:152 +0x4b8
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).commit.func2(0xc4378c24f0, 0xc4200a3e08, 0x0, 0x0, 0x0, 0xebc2b0, 0x0, 0x0)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:208 +0x423
created by github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).commit
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:209 +0x1e5

**Comment by jedo75** [comment] 2017-07-19 10:02
It happens when I put in the seed to restore the  wallet

**Comment by S-anasol** [comment] 2017-07-19 11:09
https://easyengine.io/tutorials/linux/increase-open-files-limit/

**Comment by altcoin725** [comment] 2017-07-21 03:04
Same problem here

**Comment by altcoin725** [comment] 2017-07-21 03:06
Loading...
(0/6) Loading siad...
listen tcp 127.0.0.1:9980: bind: Only one usage of each socket address (protocol/netwo(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 0.7582463 seconds

**Comment by lukechampine** [comment] 2017-07-28 23:14
duplicate of #1840

**Closed by lukechampine** 2017-07-28 23:14 UTC
