### ISSUE TITLE
Loading forever, then error.

### ISSUE THREAD

**Issue by HeroicVillain** [NebulousLabs/Sia#2516] opened 2017-12-09 03:00 UTC
**Environment**
* Sia version: 1.3.0
* OS: Windows 10

`A critical error loading Sia has occured: Siad unexpectedly exited. Error log: Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
goroutine 1387 [running]:
runtime/debug.Stack(0x44439e, 0x0, 0xc048fbba78)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x80
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x29
github.com/NebulousLabs/Sia/build.Severe(0xc048fbbbf0, 0x2, 0x2)
	/home/luke/go/src/github.com/NebulousLabs/Sia/build/critical.go:32 +0x99
github.com/NebulousLabs/Sia/persist.(*Logger).Severe(0xc067250700, 0xc048fbbbf0, 0x2, 0x2)
	/home/luke/go/src/github.com/NebulousLabs/Sia/persist/log.go:71 +0xe7
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).syncResources(0xc043284ae8)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:110 +0x6b0
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).commit(0xc043284ae8)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:147 +0x47
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).threadedSyncLoop(0xc043284ae8, 0xc0421e5aa0, 0xc0421e5b00)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:276 +0x149
created by github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).spawnSyncLoop
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:223 +0x103
Severe error: ERROR: could not rename temporary write-ahead-log in contract manager: rename E:\Blockchain-Stuff\SIA\SIA DATA\host\contractmanager\contractmanager.wal_temp E:\Blockchain-Stuff\SIA\SIA DATA\host\contractmanager\contractmanager.wal: The process cannot access the file because it is being used by another process.
goroutine 1387 [running]:
runtime/debug.Stack(0x44439e, 0x0, 0xc048fbba78)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x80
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x29
github.com/NebulousLabs/Sia/build.Severe(0xc048fbbbf0, 0x2, 0x2)
	/home/luke/go/src/github.com/NebulousLabs/Sia/build/critical.go:32 +0x99
github.com/NebulousLabs/Sia/persist.(*Logger).Severe(0xc067250700, 0xc048fbbbf0, 0x2, 0x2)
	/home/luke/go/src/github.com/NebulousLabs/Sia/persist/log.go:71 +0xe7
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).syncResources(0xc043284ae8)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:110 +0x6b0
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).commit(0xc043284ae8)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:147 +0x47
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).threadedSyncLoop(0xc043284ae8, 0xc0421e5aa0, 0xc0421e5b00)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:276 +0x149
created by github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).spawnSyncLoop
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:223 +0x103
Severe error: ERROR: could not rename temporary write-ahead-log in contract manager: rename E:\Blockchain-Stuff\SIA\SIA DATA\host\contractmanager\contractmanager.wal_temp E:\Blockchain-Stuff\SIA\SIA DATA\host\contractmanager\contractmanager.wal: The process cannot access the file because it is being used by another process.
goroutine 11953 [running]:
runtime/debug.Stack(0x44439e, 0x0, 0xc0437cddc8)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x80
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x29
github.com/NebulousLabs/Sia/build.Severe(0xc0437cdf20, 0x2, 0x2)
	/home/luke/go/src/github.com/NebulousLabs/Sia/build/critical.go:32 +0x99
github.com/NebulousLabs/Sia/persist.(*Logger).Severe(0xc067250700, 0xc0437cdf20, 0x2, 0x2)
	/home/luke/go/src/github.com/NebulousLabs/Sia/persist/log.go:71 +0xe7
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).syncResources.func1(0xc0421590b0, 0xc043284ae8)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:50 +0x4f1
created by github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).syncResources
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:52 +0x9a
Severe error: ERROR: unable to atomically copy the contract manager settings: rename E:\Blockchain-Stuff\SIA\SIA DATA\host\contractmanager\contractmanager.json_temp E:\Blockchain-Stuff\SIA\SIA DATA\host\contractmanager\contractmanager.json: The process cannot access the file because it is being used by another process.
goroutine 1387 [running]:
runtime/debug.Stack(0x44439e, 0x0, 0xc043075a78)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x80
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x29
github.com/NebulousLabs/Sia/build.Severe(0xc043075bf0, 0x2, 0x2)
	/home/luke/go/src/github.com/NebulousLabs/Sia/build/critical.go:32 +0x99
github.com/NebulousLabs/Sia/persist.(*Logger).Severe(0xc067250700, 0xc043075bf0, 0x2, 0x2)
	/home/luke/go/src/github.com/NebulousLabs/Sia/persist/log.go:71 +0xe7
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).syncResources(0xc043284ae8)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:110 +0x6b0
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).commit(0xc043284ae8)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:147 +0x47
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).threadedSyncLoop(0xc043284ae8, 0xc0421e5aa0, 0xc0421e5b00)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:276 +0x149
created by github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).spawnSyncLoop
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:223 +0x103
Severe error: ERROR: could not rename temporary write-ahead-log in contract manager: rename E:\Blockchain-Stuff\SIA\SIA DATA\host\contractmanager\contractmanager.wal_temp E:\Blockchain-Stuff\SIA\SIA DATA\host\contractmanager\contractmanager.wal: The process cannot access the file because it is being used by another process.
goroutine 1387 [running]:
runtime/debug.Stack(0x44439e, 0x0, 0xc042419a78)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x80
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x29
github.com/NebulousLabs/Sia/build.Severe(0xc042419bf0, 0x2, 0x2)
	/home/luke/go/src/github.com/NebulousLabs/Sia/build/critical.go:32 +0x99
github.com/NebulousLabs/Sia/persist.(*Logger).Severe(0xc067250700, 0xc042419bf0, 0x2, 0x2)
	/home/luke/go/src/github.com/NebulousLabs/Sia/persist/log.go:71 +0xe7
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).syncResources(0xc043284ae8)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:110 +0x6b0
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).commit(0xc043284ae8)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:147 +0x47
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).threadedSyncLoop(0xc043284ae8, 0xc0421e5aa0, 0xc0421e5b00)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:276 +0x149
created by github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).spawnSyncLoop
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:223 +0x103
Severe error: ERROR: could not rename temporary write-ahead-log in contract manager: rename E:\Blockchain-Stuff\SIA\SIA DATA\host\contractmanager\contractmanager.wal_temp E:\Blockchain-Stuff\SIA\SIA DATA\host\contractmanager\contractmanager.wal: The process cannot access the file because it is being used by another process.
goroutine 39035 [running]:
runtime/debug.Stack(0x44439e, 0x0, 0xc046ce1dc8)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x80
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x29
github.com/NebulousLabs/Sia/build.Severe(0xc046ce1f20, 0x2, 0x2)
	/home/luke/go/src/github.com/NebulousLabs/Sia/build/critical.go:32 +0x99
github.com/NebulousLabs/Sia/persist.(*Logger).Severe(0xc067250700, 0xc046ce1f20, 0x2, 0x2)
	/home/luke/go/src/github.com/NebulousLabs/Sia/persist/log.go:71 +0xe7
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).syncResources.func1(0xc0424c0000, 0xc043284ae8)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:50 +0x4f1
created by github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).syncResources
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:52 +0x9a
Severe error: ERROR: unable to atomically copy the contract manager settings: rename E:\Blockchain-Stuff\SIA\SIA DATA\host\contractmanager\contractmanager.json_temp E:\Blockchain-Stuff\SIA\SIA DATA\host\contractmanager\contractmanager.json: The process cannot access the file because it is being used by another process.
goroutine 50742 [running]:
runtime/debug.Stack(0x44439e, 0x0, 0xc0434a3dc8)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x80
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x29
github.com/NebulousLabs/Sia/build.Severe(0xc0434a3f20, 0x2, 0x2)
	/home/luke/go/src/github.com/NebulousLabs/Sia/build/critical.go:32 +0x99
github.com/NebulousLabs/Sia/persist.(*Logger).Severe(0xc067250700, 0xc0434a3f20, 0x2, 0x2)
	/home/luke/go/src/github.com/NebulousLabs/Sia/persist/log.go:71 +0xe7
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).syncResources.func1(0xc042428000, 0xc043284ae8)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:50 +0x4f1
created by github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).syncResources
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:52 +0x9a
Severe error: ERROR: unable to atomically copy the contract manager settings: rename E:\Blockchain-Stuff\SIA\SIA DATA\host\contractmanager\contractmanager.json_temp E:\Blockchain-Stuff\SIA\SIA DATA\host\contractmanager\contractmanager.json: The process cannot access the file because it is being used by another process.
goroutine 57952 [running]:
runtime/debug.Stack(0x44439e, 0x0, 0xc0427cbdc8)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x80
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x29
github.com/NebulousLabs/Sia/build.Severe(0xc0427cbf20, 0x2, 0x2)
	/home/luke/go/src/github.com/NebulousLabs/Sia/build/critical.go:32 +0x99
github.com/NebulousLabs/Sia/persist.(*Logger).Severe(0xc067250700, 0xc0427cbf20, 0x2, 0x2)
	/home/luke/go/src/github.com/NebulousLabs/Sia/persist/log.go:71 +0xe7
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).syncResources.func1(0xc042fb2000, 0xc043284ae8)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:50 +0x4f1
created by github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).syncResources
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:52 +0x9a
Severe error: ERROR: unable to atomically copy the contract manager settings: rename E:\Blockchain-Stuff\SIA\SIA DATA\host\contractmanager\contractmanager.json_temp E:\Blockchain-Stuff\SIA\SIA DATA\host\contractmanager\contractmanager.json: The process cannot access the file because it is being used by another process.
goroutine 1387 [running]:
runtime/debug.Stack(0x44439e, 0x0, 0xc04d31fa78)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x80
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x29
github.com/NebulousLabs/Sia/build.Severe(0xc04d31fbf0, 0x2, 0x2)
	/home/luke/go/src/github.com/NebulousLabs/Sia/build/critical.go:32 +0x99
github.com/NebulousLabs/Sia/persist.(*Logger).Severe(0xc067250700, 0xc04d31fbf0, 0x2, 0x2)
	/home/luke/go/src/github.com/NebulousLabs/Sia/persist/log.go:71 +0xe7
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).syncResources(0xc043284ae8)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:110 +0x6b0
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).commit(0xc043284ae8)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:147 +0x47
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).threadedSyncLoop(0xc043284ae8, 0xc0421e5aa0, 0xc0421e5b00)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:276 +0x149
created by github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).spawnSyncLoop
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:223 +0x103
Severe error: ERROR: could not rename temporary write-ahead-log in contract manager: rename E:\Blockchain-Stuff\SIA\SIA DATA\host\contractmanager\contractmanager.wal_temp E:\Blockchain-Stuff\SIA\SIA DATA\host\contractmanager\contractmanager.wal: The process cannot access the file because it is being used by another process.
goroutine 93691 [running]:
runtime/debug.Stack(0x44439e, 0x0, 0xc0476eddc8)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x80
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x29
github.com/NebulousLabs/Sia/build.Severe(0xc0476edf20, 0x2, 0x2)
	/home/luke/go/src/github.com/NebulousLabs/Sia/build/critical.go:32 +0x99
github.com/NebulousLabs/Sia/persist.(*Logger).Severe(0xc067250700, 0xc0476edf20, 0x2, 0x2)
	/home/luke/go/src/github.com/NebulousLabs/Sia/persist/log.go:71 +0xe7
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).syncResources.func1(0xc0427600d0, 0xc043284ae8)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:50 +0x4f1
created by github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).syncResources
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:52 +0x9a
Severe error: ERROR: unable to atomically copy the contract manager settings: rename E:\Blockchain-Stuff\SIA\SIA DATA\host\contractmanager\contractmanager.json_temp E:\Blockchain-Stuff\SIA\SIA DATA\host\contractmanager\contractmanager.json: The process cannot access the file because it is being used by another process.
goroutine 1387 [running]:
runtime/debug.Stack(0x44439e, 0x0, 0xc0432fba78)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x80
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x29
github.com/NebulousLabs/Sia/build.Severe(0xc042419bf0, 0x2, 0x2)
	/home/luke/go/src/github.com/NebulousLabs/Sia/build/critical.go:32 +0x99
github.com/NebulousLabs/Sia/persist.(*Logger).Severe(0xc067250700, 0xc042419bf0, 0x2, 0x2)
	/home/luke/go/src/github.com/NebulousLabs/Sia/persist/log.go:71 +0xe7
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).syncResources(0xc043284ae8)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:110 +0x6b0
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).commit(0xc043284ae8)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:147 +0x47
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).threadedSyncLoop(0xc043284ae8, 0xc0421e5aa0, 0xc0421e5b00)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:276 +0x149
created by github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).spawnSyncLoop
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:223 +0x103
Severe error: ERROR: could not rename temporary write-ahead-log in contract manager: rename E:\Blockchain-Stuff\SIA\SIA DATA\host\contractmanager\contractmanager.wal_temp E:\Blockchain-Stuff\SIA\SIA DATA\host\contractmanager\contractmanager.wal: The process cannot access the file because it is being used by another process.
(6/6) Loading renter...
goroutine 1387 [running]:
runtime/debug.Stack(0x44439e, 0x0, 0xc042419a78)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x80
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x29
github.com/NebulousLabs/Sia/build.Severe(0xc042419bf0, 0x2, 0x2)
	/home/luke/go/src/github.com/NebulousLabs/Sia/build/critical.go:32 +0x99
github.com/NebulousLabs/Sia/persist.(*Logger).Severe(0xc067250700, 0xc042419bf0, 0x2, 0x2)
	/home/luke/go/src/github.com/NebulousLabs/Sia/persist/log.go:71 +0xe7
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).syncResources(0xc043284ae8)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:110 +0x6b0
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).commit(0xc043284ae8)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:147 +0x47
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).threadedSyncLoop(0xc043284ae8, 0xc0421e5aa0, 0xc0421e5b00)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:276 +0x149
created by github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).spawnSyncLoop
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:223 +0x103
Severe error: ERROR: could not rename temporary write-ahead-log in contract manager: rename E:\Blockchain-Stuff\SIA\SIA DATA\host\contractmanager\contractmanager.wal_temp E:\Blockchain-Stuff\SIA\SIA DATA\host\contractmanager\contractmanager.wal: The process cannot access the file because it is being used by another process.
goroutine 1387 [running]:
runtime/debug.Stack(0x44439e, 0x0, 0xc042419a78)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x80
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x29
github.com/NebulousLabs/Sia/build.Severe(0xc042419bf0, 0x2, 0x2)
	/home/luke/go/src/github.com/NebulousLabs/Sia/build/critical.go:32 +0x99
github.com/NebulousLabs/Sia/persist.(*Logger).Severe(0xc067250700, 0xc042419bf0, 0x2, 0x2)
	/home/luke/go/src/github.com/NebulousLabs/Sia/persist/log.go:71 +0xe7
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).syncResources(0xc043284ae8)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:110 +0x6b0
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).commit(0xc043284ae8)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:147 +0x47
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).threadedSyncLoop(0xc043284ae8, 0xc0421e5aa0, 0xc0421e5b00)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:276 +0x149
created by github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).spawnSyncLoop
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:223 +0x103
Severe error: ERROR: could not rename temporary write-ahead-log in contract manager: rename E:\Blockchain-Stuff\SIA\SIA DATA\host\contractmanager\contractmanager.wal_temp E:\Blockchain-Stuff\SIA\SIA DATA\host\contractmanager\contractmanager.wal: The process cannot access the file because it is being used by another process.
goroutine 1387 [running]:
runtime/debug.Stack(0x44439e, 0x0, 0xc042419a78)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x80
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x29
github.com/NebulousLabs/Sia/build.Severe(0xc042419bf0, 0x2, 0x2)
	/home/luke/go/src/github.com/NebulousLabs/Sia/build/critical.go:32 +0x99
github.com/NebulousLabs/Sia/persist.(*Logger).Severe(0xc067250700, 0xc042419bf0, 0x2, 0x2)
	/home/luke/go/src/github.com/NebulousLabs/Sia/persist/log.go:71 +0xe7
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).syncResources(0xc043284ae8)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:110 +0x6b0
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).commit(0xc043284ae8)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:147 +0x47
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).threadedSyncLoop(0xc043284ae8, 0xc0421e5aa0, 0xc0421e5b00)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:276 +0x149
created by github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).spawnSyncLoop
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:223 +0x103
Severe error: ERROR: could not rename temporary write-ahead-log in contract manager: rename E:\Blockchain-Stuff\SIA\SIA DATA\host\contractmanager\contractmanager.wal_temp E:\Blockchain-Stuff\SIA\SIA DATA\host\contractmanager\contractmanager.wal: The process cannot access the file because it is being used by another process.
goroutine 1387 [running]:
runtime/debug.Stack(0x44439e, 0x0, 0xc042419a78)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x80
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x29
github.com/NebulousLabs/Sia/build.Severe(0xc042419bf0, 0x2, 0x2)
	/home/luke/go/src/github.com/NebulousLabs/Sia/build/critical.go:32 +0x99
github.com/NebulousLabs/Sia/persist.(*Logger).Severe(0xc067250700, 0xc042419bf0, 0x2, 0x2)
	/home/luke/go/src/github.com/NebulousLabs/Sia/persist/log.go:71 +0xe7
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).syncResources(0xc043284ae8)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:110 +0x6b0
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).commit(0xc043284ae8)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:147 +0x47
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).threadedSyncLoop(0xc043284ae8, 0xc0421e5aa0, 0xc0421e5b00)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:276 +0x149
created by github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).spawnSyncLoop
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:223 +0x103
Severe error: ERROR: could not rename temporary write-ahead-log in contract manager: rename E:\Blockchain-Stuff\SIA\SIA DATA\host\contractmanager\contractmanager.wal_temp E:\Blockchain-Stuff\SIA\SIA DATA\host\contractmanager\contractmanager.wal: The process cannot access the file because it is being used by another process.
goroutine 145615 [running]:
runtime/debug.Stack(0x44439e, 0x0, 0xc048333dc8)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x80
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x29
github.com/NebulousLabs/Sia/build.Severe(0xc048333f20, 0x2, 0x2)
	/home/luke/go/src/github.com/NebulousLabs/Sia/build/critical.go:32 +0x99
github.com/NebulousLabs/Sia/persist.(*Logger).Severe(0xc067250700, 0xc048333f20, 0x2, 0x2)
	/home/luke/go/src/github.com/NebulousLabs/Sia/persist/log.go:71 +0xe7
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).syncResources.func1(0xc043c8ce20, 0xc043284ae8)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:50 +0x4f1
created by github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).syncResources
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:52 +0x9a
Severe error: ERROR: unable to atomically copy the contract manager settings: rename E:\Blockchain-Stuff\SIA\SIA DATA\host\contractmanager\contractmanager.json_temp E:\Blockchain-Stuff\SIA\SIA DATA\host\contractmanager\contractmanager.json: The process cannot access the file because it is being used by another process.
Closing host...
Closing wallet...
Closing transaction pool...
Closing consensus...
Closing gateway...
invalid argument
`

**Comment by tbenz9** [comment] 2017-12-11 18:38
Duplicate of #2374

**Closed by tbenz9** 2017-12-11 18:38 UTC
