### ISSUE TITLE
Siad has exited unexpectedly. Please submit a bug report including the error log here.  Error Log:

### ISSUE THREAD

**Issue by acristofono** [NebulousLabs/Sia#2930] opened 2018-04-09 19:47 UTC
Sia Daemon v1.3.2
Git Revision 72938f5
Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 3.8572205999999998 seconds
panic: runtime error: slice bounds out of range

goroutine 5 [running]:
github.com/NebulousLabs/Sia/vendor/github.com/coreos/bbolt.(*branchPageElement).key(...)
	/home/luke/go/src/github.com/NebulousLabs/Sia/vendor/github.com/coreos/bbolt/page.go:106
github.com/NebulousLabs/Sia/vendor/github.com/coreos/bbolt.(*Cursor).searchPage.func1(0x2b1a, 0xc044370d00)
	/home/luke/go/src/github.com/NebulousLabs/Sia/vendor/github.com/coreos/bbolt/cursor.go:302 +0xc9
sort.Search(0x3978, 0xc042066548, 0x5ca535)
	/usr/local/go/src/sort/search.go:66 +0x5f
github.com/NebulousLabs/Sia/vendor/github.com/coreos/bbolt.(*Cursor).searchPage(0xc042066b68, 0xc044917da0, 0x20, 0x20, 0x20bb22000)
	/home/luke/go/src/github.com/NebulousLabs/Sia/vendor/github.com/coreos/bbolt/cursor.go:299 +0xdc
github.com/NebulousLabs/Sia/vendor/github.com/coreos/bbolt.(*Cursor).search(0xc042066b68, 0xc044917da0, 0x20, 0x20, 0x18bb32)
	/home/luke/go/src/github.com/NebulousLabs/Sia/vendor/github.com/coreos/bbolt/cursor.go:271 +0x1a9
github.com/NebulousLabs/Sia/vendor/github.com/coreos/bbolt.(*Cursor).searchPage(0xc042066b68, 0xc044917da0, 0x20, 0x20, 0x82026000)
	/home/luke/go/src/github.com/NebulousLabs/Sia/vendor/github.com/coreos/bbolt/cursor.go:314 +0x161
github.com/NebulousLabs/Sia/vendor/github.com/coreos/bbolt.(*Cursor).search(0xc042066b68, 0xc044917da0, 0x20, 0x20, 0x2036)
	/home/luke/go/src/github.com/NebulousLabs/Sia/vendor/github.com/coreos/bbolt/cursor.go:271 +0x1a9
github.com/NebulousLabs/Sia/vendor/github.com/coreos/bbolt.(*Cursor).searchPage(0xc042066b68, 0xc044917da0, 0x20, 0x20, 0x8259f000)
	/home/luke/go/src/github.com/NebulousLabs/Sia/vendor/github.com/coreos/bbolt/cursor.go:314 +0x161
github.com/NebulousLabs/Sia/vendor/github.com/coreos/bbolt.(*Cursor).search(0xc042066b68, 0xc044917da0, 0x20, 0x20, 0x25af)
	/home/luke/go/src/github.com/NebulousLabs/Sia/vendor/github.com/coreos/bbolt/cursor.go:271 +0x1a9
github.com/NebulousLabs/Sia/vendor/github.com/coreos/bbolt.(*Cursor).searchPage(0xc042066b68, 0xc044917da0, 0x20, 0x20, 0x82708000)
	/home/luke/go/src/github.com/NebulousLabs/Sia/vendor/github.com/coreos/bbolt/cursor.go:314 +0x161
github.com/NebulousLabs/Sia/vendor/github.com/coreos/bbolt.(*Cursor).search(0xc042066b68, 0xc044917da0, 0x20, 0x20, 0x2718)
	/home/luke/go/src/github.com/NebulousLabs/Sia/vendor/github.com/coreos/bbolt/cursor.go:271 +0x1a9
github.com/NebulousLabs/Sia/vendor/github.com/coreos/bbolt.(*Cursor).seek(0xc042066b68, 0xc044917da0, 0x20, 0x20, 0x0, 0x0, 0xc0448b89b8, 0xdeb3f0, 0x8, 0x8, ...)
	/home/luke/go/src/github.com/NebulousLabs/Sia/vendor/github.com/coreos/bbolt/cursor.go:159 +0xb8
github.com/NebulousLabs/Sia/vendor/github.com/coreos/bbolt.(*Bucket).Get(0xc0447222c0, 0xc044917da0, 0x20, 0x20, 0xdee0e0, 0xc0447222c0, 0x42cc6d)
	/home/luke/go/src/github.com/NebulousLabs/Sia/vendor/github.com/coreos/bbolt/bucket.go:260 +0xed
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).validateHeaderAndBlock(0xc0420d1b80, 0xdef860, 0xc0448b89a0, 0x200000000000000, 0x4f6edaf7ba6f4354, 0x94123c340326e9bf, 0x533c426f28b9ab23, 0xd9dc13c9, 0x5a9cce08, 0xc0453f83c0, ...)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/accept.go:47 +0x15e
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).managedAcceptBlocks.func1(0xc0448b89a0, 0xaf82d8, 0xc0448b89a0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/accept.go:248 +0x2c2
github.com/NebulousLabs/Sia/vendor/github.com/coreos/bbolt.(*DB).Update(0xc04206d2c0, 0xc0420672f8, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/vendor/github.com/coreos/bbolt/db.go:673 +0xa1
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).managedAcceptBlocks(0xc0420d1b80, 0xc044b7a000, 0xa, 0xa, 0x0, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/accept.go:244 +0x424
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).managedReceiveBlocks(0xc0420d1b80, 0xdf80e0, 0xc044474fe0, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:225 +0x500
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).(github.com/NebulousLabs/Sia/modules/consensus.managedReceiveBlocks)-fm(0xdf80e0, 0xc044474fe0, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:445 +0x45
github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).managedRPC(0xc0420c4840, 0xc04204b960, 0x12, 0xac7049, 0xa, 0xc0433862a0, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/rpc.go:66 +0x2c9
github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).RPC(0xc0420c4840, 0xc04204b960, 0x12, 0xac7049, 0xa, 0xc0433862a0, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/rpc.go:76 +0xd8
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).threadedInitialBlockchainDownload.func1(0xc0420d1b80, 0xc042067ef0, 0xc042067e98, 0xc042067ea0, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:580 +0x12e
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).threadedInitialBlockchainDownload(0xc0420d1b80, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:601 +0x151
github.com/NebulousLabs/Sia/modules/consensus.New.func1(0x1, 0xc04215e4f0, 0xc0420d1b80, 0xdf87e0, 0xc0420c4840)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/consensusset.go:151 +0x3eb
created by github.com/NebulousLabs/Sia/modules/consensus.New
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/consensusset.go:144 +0x656

**Comment by acristofono** [comment] 2018-04-09 20:00
I've been trying to open this wallet on this new laptop after installing it and it keeps giving me this message .
I've tried this latest version and still the same thing.
after I click the start siad it looks like it will start but then gives me this message:

Sia Daemon v1.3.2
Git Revision 72938f5
Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 4.0632324 seconds

**Comment by tbenz9** [comment] 2018-04-09 20:31
Duplicate of #2183 

The workaround is to remove your consensus.db file and restart the sync.  Instructions to remove your consensus.db file can be found here: https://gist.github.com/tbenz9/8066d74853ab28c23bd7bc1d3c7cdeda

**Closed by tbenz9** 2018-04-09 20:31 UTC

**Comment by acristofono** [comment] 2018-04-10 03:40
Thank you , it seam like its going to work it is now synchronizing without crashing but it started from 0% so this may take awhile ...
