### ISSUE TITLE
"Delayed timebomb" bug in the Explorer module

### ISSUE THREAD

**Issue by aerrejon** [NebulousLabs/Sia#2500] opened 2017-11-28 18:11 UTC
**Bug report:**
OS: Windows Server 2012 R2
Sia version: Daemon 1.3.0

My Sia daemon with the explorer module active crashed when it reached a block around 133570 with this log:

> (0/7) Loading siad...
> (1/7) Loading gateway...
> (2/7) Loading consensus...
> (3/7) Loading explorer...
> (4/7) Loading transaction pool...
> (5/7) Loading wallet...
> (6/7) Loading host...
> (7/7) Loading renter...
> Finished loading in 2.185519 seconds
> panic: page 1095537 already freed
> 
> goroutine 8 [running]:
> github.com/NebulousLabs/bolt.(*freelist).free(0xc042064b10, 0x209df, 0x38b761000
> )
>         /home/luke/go/src/github.com/NebulousLabs/bolt/freelist.go:121 +0x2a1
> github.com/NebulousLabs/bolt.(*node).spill(0xc047505f10, 0xc0447b3dc0, 0xde0d20)
>         /home/luke/go/src/github.com/NebulousLabs/bolt/node.go:363 +0x1e7
> github.com/NebulousLabs/bolt.(*node).spill(0xc047505ea0, 0xc0447b3da0, 0xde0d20)
>         /home/luke/go/src/github.com/NebulousLabs/bolt/node.go:350 +0xbb
> github.com/NebulousLabs/bolt.(*node).spill(0xc047505e30, 0x0, 0x0)
>         /home/luke/go/src/github.com/NebulousLabs/bolt/node.go:350 +0xbb
> github.com/NebulousLabs/bolt.(*node).spill(0xc049ecc7e0, 0xc0481bad80, 0xc046f94
> 8f0)
>         /home/luke/go/src/github.com/NebulousLabs/bolt/node.go:350 +0xbb
> github.com/NebulousLabs/bolt.(*Bucket).spill(0xc0463ef5c0, 0xc046f94a00, 0x8)
>         /home/luke/go/src/github.com/NebulousLabs/bolt/bucket.go:570 +0x182
> github.com/NebulousLabs/bolt.(*Bucket).spill(0xc04485fdd8, 0x34df4998, 0xee9fe0)
>         /home/luke/go/src/github.com/NebulousLabs/bolt/bucket.go:537 +0x8ff
> github.com/NebulousLabs/bolt.(*Tx).Commit(0xc04485fdc0, 0x0, 0x0)
>         /home/luke/go/src/github.com/NebulousLabs/bolt/tx.go:163 +0x12c
> github.com/NebulousLabs/bolt.(*DB).Update(0xc0421623c0, 0xc044ce8dd0, 0x0, 0x0)
>         /home/luke/go/src/github.com/NebulousLabs/bolt/db.go:610 +0xfe
> github.com/NebulousLabs/Sia/modules/explorer.(*Explorer).ProcessConsensusChange(
> 0xc042039f80, 0x98a776341c844602, 0xf976e5d2a600250, 0x89a266b20e335c9c, 0x9b4a5
> c6db45bf4b1, 0x0, 0x0, 0x0, 0xc042143260, 0x1, ...)
>         /home/luke/go/src/github.com/NebulousLabs/Sia/modules/explorer/update.go
> :280 +0x91
> github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).updateSubscribers(
> 0xc04242c000, 0x0, 0x0, 0x0, 0xc0444dc260, 0x1, 0x1)
>         /home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/subscrib
> e.go:114 +0x17a
> github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).managedAcceptBlock
> s(0xc04242c000, 0xc0460fd800, 0xa, 0xa, 0x0, 0x0, 0x0)
>         /home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/accept.g
> o:338 +0x750
> github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).managedReceiveBloc
> ks(0xc04242c000, 0xde41c0, 0xc04b753100, 0x0, 0x0)
>         /home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/synchron
> ize.go:225 +0x5be
> github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).(github.com/Nebulo
> usLabs/Sia/modules/consensus.managedReceiveBlocks)-fm(0xde41c0, 0xc04b753100, 0x
> 0, 0x0)
>         /home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/synchron
> ize.go:445 +0x45
> github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).managedRPC(0xc042172000,
> 0xc042360780, 0x12, 0xaddb78, 0xa, 0xc042cbb070, 0x0, 0x0)
>         /home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/rpc.go:66
> +0x339
> github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).RPC(0xc042172000, 0xc0423
> 60780, 0x12, 0xaddb78, 0xa, 0xc042cbb070, 0x0, 0x0)
>         /home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/rpc.go:76
> +0xd8
> github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).threadedInitialBlo
> ckchainDownload.func1(0xc04242c000, 0xc046f95ef0, 0xc046f95eb0, 0xc046f95eb8, 0x
> 0, 0x0)
>         /home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/synchron
> ize.go:580 +0x133
> github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).threadedInitialBlo
> ckchainDownload(0xc04242c000, 0x0, 0x0)
>         /home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/synchron
> ize.go:601 +0x30e
> github.com/NebulousLabs/Sia/modules/consensus.New.func1(0x1, 0xc04249fc60, 0xc04
> 242c000, 0xde4440, 0xc042172000)
>         /home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/consensu
> sset.go:151 +0x404
> created by github.com/NebulousLabs/Sia/modules/consensus.New
>         /home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/consensu
> sset.go:182 +0x641

Trying to start Sia again with the explorer module results in this crash:

> (0/7) Loading siad...
> (1/7) Loading gateway...
> (2/7) Loading consensus...
> (3/7) Loading explorer...
> Closing consensus...
> Closing gateway...
> panic: page 554940 already freed
> 
> goroutine 1 [running]:
> github.com/NebulousLabs/bolt.(*freelist).free(0xc0420d43c0, 0x209ff, 0x3077ac000
> )
>         /home/luke/go/src/github.com/NebulousLabs/bolt/freelist.go:121 +0x2a1
> github.com/NebulousLabs/bolt.(*node).spill(0xc0420765b0, 0xc04273cba0, 0xde0d20)
>         /home/luke/go/src/github.com/NebulousLabs/bolt/node.go:363 +0x1e7
> github.com/NebulousLabs/bolt.(*node).spill(0xc042076540, 0xc04273cb80, 0xde0d20)
>         /home/luke/go/src/github.com/NebulousLabs/bolt/node.go:350 +0xbb
> github.com/NebulousLabs/bolt.(*node).spill(0xc0420764d0, 0x0, 0x0)
> /home/luke/go/src/github.com/NebulousLabs/bolt/node.go:350 +0xbb
> github.com/NebulousLabs/bolt.(*node).spill(0xc042076460, 0x0, 0x0)
>         /home/luke/go/src/github.com/NebulousLabs/bolt/node.go:350 +0xbb
> github.com/NebulousLabs/bolt.(*node).spill(0xc042054230, 0xc042b7ea58, 0x20)
>         /home/luke/go/src/github.com/NebulousLabs/bolt/node.go:350 +0xbb
> github.com/NebulousLabs/bolt.(*Bucket).spill(0xc04200c780, 0xc042b7ec00, 0xc)
>         /home/luke/go/src/github.com/NebulousLabs/bolt/bucket.go:570 +0x182
> github.com/NebulousLabs/bolt.(*Bucket).spill(0xc04215cd38, 0x1e67a5ac, 0xee9fe0)
>         /home/luke/go/src/github.com/NebulousLabs/bolt/bucket.go:537 +0x8ff
> github.com/NebulousLabs/bolt.(*Tx).Commit(0xc04215cd20, 0x0, 0x0)
>         /home/luke/go/src/github.com/NebulousLabs/bolt/tx.go:163 +0x12c
> github.com/NebulousLabs/bolt.(*DB).Update(0xc0420f4000, 0xc042027098, 0x0, 0x0)
>         /home/luke/go/src/github.com/NebulousLabs/bolt/db.go:610 +0xfe
> github.com/NebulousLabs/Sia/modules/explorer.(*Explorer).ProcessConsensusChange(
> 0xc0420d4030, 0xa6e5609c3fc2d260, 0xdcbe9b5509c7e616, 0x2390483e255b3ec, 0xa0a18
> c2f53730b90, 0x0, 0x0, 0x0, 0xc0423ba3c0, 0x1, ...)
>         /home/luke/go/src/github.com/NebulousLabs/Sia/modules/explorer/update.go
> :280 +0x91
> github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).managedInitializeS
> ubscribe.func2(0xc04215c540, 0xb0b578, 0xc04215c540)
> 

Starting Sia without the explorer module does not present any issue, but trying again the explorer will result in a crash. This makes me suspect the issue is not on consensus, but on explorer.

I tried to restore several backups of my Sia node (including the full installation, with consensus and explorer databases). The older one 10 days before the crash. All of them initialized correctly and started to index blocks to catch up the blockchain, however all of them crashed again with the same error at the same blockchain height around 133570. This is why I call this a "delayed timebomb" bug: the bug/corruption can be acquired several days or weeks ago (in my case, more than 10 days ago) and while it will keep working normally, it will provoke the irreversible crash at certain target block.

This has 2 additional pernicious effects:
- No backup of a server can possibly restore an application that uses the explorer API and suffers this issue. The only solution is a fresh download and sync of the client. Considering the explorer + consensus syncing can take currently up to 2 days, that is a lot of downtime for applications. This is what is currently happening with SiaStats.info
- No bootstrapping of the explorer or public repository of the database (in the same way as the consensus.db is kept by SiaHub) can be trusted, as it can be already corrupted and provoke a crash after some time.

Tbenz suggested me on Discord this issue could be related to #2413 

The issue I am presenting, together with issue #2432  ,  are making me make very difficult to keep SiaStats.info reliably.

**Comment by tbenz9** [comment] 2017-11-29 00:42
@aerrejon thanks for opening this, you describe the problem well and it's always useful to get a variety of logs for bugs like this.  I believe this is a duplicate of #2413 and this issue will likely be closed as a duplicate in an effort to keep GitHub relatively organized.  If you don't think this is a duplicate, please comment below.

Recommendation to devs: close as duplicate of #2413.

**Comment by aerrejon** [comment] 2017-11-29 05:24
Sounds good @tbenz9. Thank you

**Closed** 2017-12-04 20:03 UTC
