### ISSUE TITLE
HELP FOR THIS PLS:  Siad has exited unexpectedly. Please submit a bug report including the error log here.  Error Log:

### ISSUE THREAD

**Issue by FilipMakedonski** [NebulousLabs/Sia#2409] opened 2017-10-07 14:55 UTC
HELP FOR THIS PLS

Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 0.6430368 seconds
panic: runtime error: slice bounds out of range

goroutine 18 [running]:

**Comment by lukechampine** [comment] 2017-10-07 17:06
Looks like a duplicate of https://github.com/NebulousLabs/Sia/issues/2183

**Closed by lukechampine** 2017-10-07 17:06 UTC
