### ISSUE TITLE
Siad has exited unexpectedly.

### ISSUE THREAD

**Issue by jamieantonelli** [NebulousLabs/Sia#1759] opened 2017-05-02 23:55 UTC
Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 21.853401864 seconds

Wallet: scanned to height 94139...
Wallet: scanned to height 94142...
Wallet: scanned to height 94144...
Wallet: scanned to height 94145...
Wallet: scanned to height 94148...
Wallet: scanned to height 94149...
Wallet: scanned to height 94150...
Wallet: scanned to height 94156...
Wallet: scanned to height 94157...
Wallet: scanned to height 94159...
Wallet: scanned to height 94163...
Wallet: scanned to height 94164...
Wallet: scanned to height 94165...
Wallet: scanned to height 94167...
Wallet: scanned to height 94169...
Wallet: scanned to height 94171...
Wallet: scanned to height 94173...
Wallet: scanned to height 94174...
Wallet: scanned to height 94176...
Wallet: scanned to height 94178...
Wallet: scanned to height 94179...
Wallet: scanned to height 94182...
Wallet: scanned to height 94184...
Wallet: scanned to height 94185...
Wallet: scanned to height 94188...
Wallet: scanned to height 94189...
Wallet: scanned to height 94191...
Wallet: scanned to height 94194...
Wallet: scanned to height 94197...
Wallet: scanned to height 94200...
Wallet: scanned to height 94204...
Wallet: scanned to height 94205...
Wallet: scanned to height 94206...
Wallet: scanned to height 94207...
Wallet: scanned to height 94209...
Wallet: scanned to height 94211...
Wallet: scanned to height 94212...
Wallet: scanned to height 94215...
Wallet: scanned to height 94216...
Wallet: scanned to height 94217...
Wallet: scanned to height 94219...
Wallet: scanned to height 94221...
Wallet: scanned to height 94223...
Wallet: scanned to height 94225...
Wallet: scanned to height 94226...
Wallet: scanned to height 94227...
Wallet: scanned to height 94228...
Wallet: scanned to height 94230...
Wallet: scanned to height 94237...
Wallet: scanned to height 94238...
Wallet: scanned to height 94240...
Wallet: scanned to height 94243...
Wallet: scanned to height 94245...
Wallet: scanned to height 94246...
Wallet: scanned to height 94248...
Wallet: scanned to height 94252...
Wallet: scanned to height 94255...
Wallet: scanned to height 94258...
Wallet: scanned to height 94261...
Wallet: scanned to height 94263...
Wallet: scanned to height 94264...
Wallet: scanned to height 94266...
Wallet: scanned to height 94269...
Wallet: scanned to height 94271...
Wallet: scanned to height 94272...
Wallet: scanned to height 94277...
Wallet: scanned to height 94282...
Wallet: scanned to height 94284...
Wallet: scanned to height 94286...
Wallet: scanned to height 94288...
Wallet: scanned to height 94290...
Wallet: scanned to height 94292...
Wallet: scanned to height 94293...
Wallet: scanned to height 94296...
Wallet: scanned to height 94298...
Wallet: scanned to height 94300...
Wallet: scanned to height 94301...
Wallet: scanned to height 94303...
Wallet: scanned to height 94306...
Wallet: scanned to height 94309...
Wallet: scanned to height 94313...
Wallet: scanned to height 94314...
Wallet: scanned to height 94315...
Wallet: scanned to height 94316...
Wallet: scanned to height 94320...
Wallet: scanned to height 94322...
Wallet: scanned to height 94323...
Wallet: scanned to height 94325...
Wallet: scanned to height 94327...
Wallet: scanned to height 94329...
Wallet: scanned to height 94332...
Wallet: scanned to height 94333...
Wallet: scanned to height 94336...
Wallet: scanned to height 94337...
Wallet: scanned to height 94338...
Wallet: scanned to height 94343...
Wallet: scanned to height 94345...
Wallet: scanned to height 94346...
Wallet: scanned to height 94347...
Wallet: scanned to height 94350...
Wallet: scanned to height 94353...
Wallet: scanned to height 94355...
Wallet: scanned to height 94356...
Wallet: scanned to height 94358...
Wallet: scanned to height 94360...
Wallet: scanned to height 94361...
Wallet: scanned to height 94363...
Wallet: scanned to height 94367...
Wallet: scanned to height 94370...
Wallet: scanned to height 94374...
Wallet: scanned to height 94377...
Wallet: scanned to height 94378...
Wallet: scanned to height 94379...
Wallet: scanned to height 94381...
Wallet: scanned to height 94382...
Wallet: scanned to height 94386...
Wallet: scanned to height 94388...
Wallet: scanned to height 94391...
Wallet: scanned to height 94392...
Wallet: scanned to height 94393...
Wallet: scanned to height 94394...
Wallet: scanned to height 94399...
Wallet: scanned to height 94406...
Wallet: scanned to height 94408...
Wallet: scanned to height 94410...
Wallet: scanned to height 94413...
Wallet: scanned to height 94416...
Wallet: scanned to height 94421...
Wallet: scanned to height 94423...
Wallet: scanned to height 94426...
Wallet: scanned to height 94427...
Wallet: scanned to height 94429...
Wallet: scanned to height 94430...
Wallet: scanned to height 94435...
Wallet: scanned to height 94437...
Wallet: scanned to height 94439...
Wallet: scanned to height 94440...
Wallet: scanned to height 94442...
Wallet: scanned to height 94444...
Wallet: scanned to height 94449...
Wallet: scanned to height 94450...
Wallet: scanned to height 94455...
Wallet: scanned to height 94457...
Wallet: scanned to height 94459...
Wallet: scanned to height 94461...
Wallet: scanned to height 94462...
Wallet: scanned to height 94464...
Wallet: scanned to height 94468...
Wallet: scanned to height 94470...
Wallet: scanned to height 94471...
Wallet: scanned to height 94474...
Wallet: scanned to height 94475...
Wallet: scanned to height 94477...
Wallet: scanned to height 94481...
Wallet: scanned to height 94483...
Wallet: scanned to height 94486...
Wallet: scanned to height 94488...
Wallet: scanned to height 94490...
Wallet: scanned to height 94493...
Wallet: scanned to height 94499...
Wallet: scanned to height 94503...
Wallet: scanned to height 94504...
Wallet: scanned to height 94506...
Wallet: scanned to height 94508...
Wallet: scanned to height 94510...
Wallet: scanned to height 94514...
Wallet: scanned to height 94515...
Wallet: scanned to height 94517...
Wallet: scanned to height 94522...
Wallet: scanned to height 94527...
Wallet: scanned to height 94528...
Wallet: scanned to height 94529...
Wallet: scanned to height 94532...
Wallet: scanned to height 94534...
Wallet: scanned to height 94535...
Wallet: scanned to height 94538...
Wallet: scanned to height 94542...
Wallet: scanned to height 94545...
Wallet: scanned to height 94550...
Wallet: scanned to height 94552...
Wallet: scanned to height 94556...
Wallet: scanned to height 94557...
Wallet: scanned to height 94559...
Wallet: scanned to height 94565...
Wallet: scanned to height 94566...
Wallet: scanned to height 94568...
Wallet: scanned to height 94569...
Wallet: scanned to height 94574...
Wallet: scanned to height 94577...
Wallet: scanned to height 94579...
Wallet: scanned to height 94582...
Wallet: scanned to height 94584...
Wallet: scanned to height 94585...
Wallet: scanned to height 94588...
Wallet: scanned to height 94589...
Wallet: scanned to height 94591...
Wallet: scanned to height 94593...
Wallet: scanned to height 94594...
Wallet: scanned to height 94599...
Wallet: scanned to height 94603...
Wallet: scanned to height 94606...
Wallet: scanned to height 94608...
Wallet: scanned to height 94611...
Wallet: scanned to height 94612...
Wallet: scanned to height 94618...
Wallet: scanned to height 94621...
Wallet: scanned to height 94622...
Wallet: scanned to height 94624...
Wallet: scanned to height 94626...
Wallet: scanned to height 94630...
Wallet: scanned to height 94631...
Wallet: scanned to height 94634...
Wallet: scanned to height 94637...
Wallet: scanned to height 94640...
Wallet: scanned to height 94643...
Wallet: scanned to height 94645...
Wallet: scanned to height 94646...
Wallet: scanned to height 94647...
Wallet: scanned to height 94648...
Wallet: scanned to height 94653...
Wallet: scanned to height 94655...
Wallet: scanned to height 94656...
Wallet: scanned to height 94658...
Wallet: scanned to height 94660...
Wallet: scanned to height 94663...
Wallet: scanned to height 94665...
Wallet: scanned to height 94666...
Wallet: scanned to height 94667...
Wallet: scanned to height 94669...
Wallet: scanned to height 94674...
Wallet: scanned to height 94676...
Wallet: scanned to height 94677...
Wallet: scanned to height 94681...
Wallet: scanned to height 94685...
Wallet: scanned to height 94687...
Wallet: scanned to height 94689...goroutine 1 [running]:
runtime/debug.Stack(0x1043857, 0x0, 0xc4213ab5f8)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x79
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/NebulousLabs/Sia/build.Critical(0xc4213ab948, 0x1, 0x1)
	/home/luke/go/src/github.com/NebulousLabs/Sia/build/critical.go:15 +0xa7
main.startDaemon(0x0, 0x0, 0x7fff5fbffd12, 0xe, 0x7fff5fbffd3e, 0x5, 0x7fff5fbffd2d, 0x5, 0x0, 0x7fff5fbffd4e, ...)
	/home/luke/go/src/github.com/NebulousLabs/Sia/siad/daemon.go:295 +0xaa9
main.startDaemonCmd(0xc420083200, 0xc420019400, 0x0, 0x5)
	/home/luke/go/src/github.com/NebulousLabs/Sia/siad/daemon.go:309 +0x6d
github.com/spf13/cobra.(*Command).execute(0xc420083200, 0xc42000e0d0, 0x5, 0x5, 0xc420083200, 0xc42000e0d0)
	/home/luke/go/src/github.com/spf13/cobra/command.go:648 +0x234
github.com/spf13/cobra.(*Command).ExecuteC(0xc420083200, 0x16c6004, 0x3b, 0xc420150aa0)
	/home/luke/go/src/github.com/spf13/cobra/command.go:734 +0x339
github.com/spf13/cobra.(*Command).Execute(0xc420083200, 0x1aa4520, 0x16af49d)
	/home/luke/go/src/github.com/spf13/cobra/command.go:693 +0x2b
main.main()
	/home/luke/go/src/github.com/NebulousLabs/Sia/siad/main.go:174 +0x7ac
Critical error: accept tcp 127.0.0.1:9980: accept: too many open files in system
Please submit a bug report here: https://github.com/NebulousLabs/Sia/issues
Closing renter...

**Comment by lukechampine** [comment] 2017-05-04 17:03
duplicate of #1757

**Closed by lukechampine** 2017-05-04 17:03 UTC
