### ISSUE TITLE
HTTP API calls to wallet failing

### ISSUE THREAD

**Issue by seveibar** [NebulousLabs/Sia#221] opened 2015-01-17 08:51 UTC
Seems to happen at random, have only accidentally reproduced.

Here's some useful debugging code for `siad/api.go` that prints all the http requests from the web interface
```go
type httpFunc func(w http.ResponseWriter, req *http.Request)

func HTTPDebugWrap(info string, f httpFunc) (g httpFunc) {
	return func(w http.ResponseWriter, req *http.Request) {
		println(info)
		f(w, req)
	}
}

// TODO: timeouts?
func (d *daemon) handle(addr string) {
	// Web Interface
	http.HandleFunc("/", d.webIndex)
	http.Handle("/lib/", http.StripPrefix("/lib/", http.FileServer(http.Dir(d.styleDir))))

	// Host API Calls
	//
	// TODO: SetConfig also calls announce(), there should be smarter ways to
	// handle this.
	http.HandleFunc("/host/config", HTTPDebugWrap("/host/config", d.hostConfigHandler))
	http.HandleFunc("/host/setconfig", HTTPDebugWrap("/host/setconfig", d.hostSetConfigHandler))

	// Miner API Calls
	http.HandleFunc("/miner/start", HTTPDebugWrap("/miner/start", d.minerStartHandler))
	http.HandleFunc("/miner/status", HTTPDebugWrap("/miner/status", d.minerStatusHandler))
	http.HandleFunc("/miner/stop", HTTPDebugWrap("/miner/stop", d.minerStopHandler))

	// Wallet API Calls
	http.HandleFunc("/wallet/address", HTTPDebugWrap("/wallet/address", d.walletAddressHandler))
	http.HandleFunc("/wallet/send", HTTPDebugWrap("/wallet/send", d.walletSendHandler))
	http.HandleFunc("/wallet/status", HTTPDebugWrap("/wallet/status", d.walletStatusHandler))

	// File API Calls
	http.HandleFunc("/file/upload", HTTPDebugWrap("/file/upload", d.fileUploadHandler))
	http.HandleFunc("/file/download", HTTPDebugWrap("/file/download", d.fileDownloadHandler))
	http.HandleFunc("/file/status", HTTPDebugWrap("/file/status", d.fileStatusHandler))

	// Misc. API Calls
	http.HandleFunc("/sync", HTTPDebugWrap("/sync", d.syncHandler))
	http.HandleFunc("/peer/add", HTTPDebugWrap("/peer/add", d.peerAddHandler))
	http.HandleFunc("/peer/remove", HTTPDebugWrap("/peer/remove", d.peerRemoveHandler))
	http.HandleFunc("/status", HTTPDebugWrap("/status", d.statusHandler))
	http.HandleFunc("/update/check", HTTPDebugWrap("/update/check", d.updateCheckHandler))
	http.HandleFunc("/update/apply", HTTPDebugWrap("/update/apply", d.updateApplyHandler))
	http.HandleFunc("/stop", HTTPDebugWrap("/stop", d.stopHandler))

	http.ListenAndServe(addr, nil)
}
```

**Comment by seveibar** [comment] 2015-01-17 08:55
Debugging output after the rror was reproduced...
```
/wallet/status
/file/status
/host/config
/status
/miner/status
Added a HSOT
/wallet/status
/miner/status
/status
/host/config
/file/status
/update/check
/wallet/status
/status
/miner/status
/host/config
/file/status
/wallet/status
/status/host/config

/miner/status
/file/status
/wallet/status
/miner/status
/status
/host/config
/file/status
/wallet/status
/status
/miner/status
/host/config
/file/status
/wallet/status
/host/config
/status
/miner/status
/file/status
/file/status/host/config/miner/status


/wallet/status/status

/wallet/status
/miner/status
/status
/file/status/host/config

/wallet/status
/miner/status
/status
/host/config
/file/status
/miner/status
/wallet/status
/status
/host/config
/file/status
/miner/status
/status
/wallet/status
/host/config
/file/status
/wallet/status
/miner/status
/status
/host/config
/file/status
/wallet/status
/miner/status
/status
/host/config
/file/status
/wallet/status
/miner/status
/status
/host/config
/file/status
/update/check
/wallet/status
/miner/status
/status
/file/status
/host/config
/wallet/status
/miner/status
/status
/host/config
/file/status
/wallet/status
/miner/status
/status
/host/config
/file/status
/miner/stop
/wallet/status
/miner/status
/status
/host/config
/file/status
/wallet/status
/miner/status
/status
/host/config
/file/status
/host/setconfig
/wallet/status
/miner/status
/status
/host/config
/file/status
/wallet/status
/host/config/status

/miner/status
/file/status
/wallet/status
/miner/status
/status
/host/config
/file/status
/wallet/status
/miner/status
/status
/host/config
/file/status
/file/upload
Accepted contract
/wallet/status
/miner/status
/status
/host/config
/file/status
/miner/status
/status
/file/status
Problem from NegotiateContract: could not read length prefix
/miner/status
/status
/file/status
/wallet/status
/miner/status
/status
/host/config
/file/status
/wallet/status
/miner/status
/status
/host/config
/file/status
/update/check
/miner/status
/status
/file/status
```

**Comment by lukechampine** [comment] 2015-01-19 08:52
API has changed, so I'm closing this until it can be reproduced.

**Closed by lukechampine** 2015-01-19 08:52 UTC

**Comment by DavidVorick** [comment] 2015-01-19 16:51
I'm about to fix it anyway. I know why the problem is happening - state mutexes are inconsistent and difficult to program correctly, and don't follow convention.
