### ISSUE TITLE
Siad for Windows have some sort af slow memory leak

### ISSUE THREAD

**Issue by MaxMaximus** [NebulousLabs/Sia#2425] opened 2017-10-13 23:56 UTC
Hello

Sia demon for windows x64 platform (I am testing on Windows 7 64 bit Pro) have some sort of memory leaks. 
Or may be it some sort of aggressive DB caching, but i did not find it in docs. Then please point me where i can read and config it.

But fact is simple: after starting siad on windows it consume only about 200-250 Мб of RAM (with 6 modules: gateway + consensus + transaction pool + wallet + host + renter). But over a time this amount slowly increasing. More client is running without restarts - more memory it use (especially physical memory - working set).
Soon after fresh start ~ 200-250 MB
After 3 days of online work ~ 500 MB
After 1 week ~ 800 MB
After 1 month ~ 1300-1400 MB
Current record (~40 days online 24/7) ~ 1500-1600 MB

**Comment by doctord919** [comment] 2017-10-17 10:17
And more ...
Win8.1x64 sia-ui 1.3.0 and RAM: 8 GB Memory.
I decided to save 77GB of data ... saved ... waited 24 hours. But siad.exe has a size of 3.9GB. That is, I again have a 4GB computer :).
Is it possible to reduce the appetite of siad.exe or somehow compress it directly in memory?
Is it real to use siad.exe on RAM machines: 2-4 GB of memory?

**Comment by lukechampine** [comment] 2017-10-17 20:27
This is likely due to a bug in the current renter code, which we are in the process of overhauling. @KaiRo-at posted a profile [here](https://gist.github.com/KaiRo-at/7dc56754f6f4f65f26e1511051ba6ed3) which suggests that `managedDownloadChunkData` is responsible.

**Comment by MaxMaximus** [comment] 2017-10-18 15:13
Interesting. I do not use renting at all - this data is from 100% hosting machine. But renter module was enabled all along, so it still can affect RAM usage. Via maintaining of hostdb for example and regular scans of other hosts.
I will try to restart siad with renter module disabled and check few days later: will abnormal RAM consumption cease or not?
Right now it over 650 MB of RAM after just 2 days online since previous restart.

P.S.
I have noticed what siad also has HUGE virtual size(virtual memory). 
This memory not actually allocated("virtual size" is huge but "private bytes" in reasonable range) but i never saw such high values for this parameter - right now it >45 500 Mb (yes, 42.5 GB). 
It is a possible reason why sia does not work on win32 platform properly. It simply can not address such crazy memory volumes with 32 bit addressing.

**Comment by lukechampine** [comment] 2017-10-18 17:29
Yeah, the virtual memory is caused by our database (bolt) which mmap's the entire database file. So it will report tons of virtual memory usage, but in reality it will release physical memory to the OS if there's contention.

**Comment by MaxMaximus** [comment] 2017-10-23 01:39
Update.
Looks like renter module do not cause this issue. And memory leak in renter module is a separate independed issue.
Because I have been running siad with renter module disabled (-M gctwh command line option) for few last days and still see similar behavior. Physical RAM usage have grown from <100 Mb after start and full sync to ~ 1150 Mb range. Or x10 times more in about 4 days.

I take snapshot of memory details after 4 days online: https://drive.google.com/open?id=0Bxy0NGbyM6mdSWRfQ0VwV1lFZEU (screenshot from process explorer)

Most of physical RAM usage grow come from RAM marked as shareable section of working set, but only tiny fraction of it actually shared with other programs (and this amount remain  at about same level ~3-5 MB), while total amount constantly grows.
So may be it some sort of system (windows) dlls being connected and loaded by siad to RAM without releasing it after use? Or file handlers or other sort of system resources.

P.S.
I also noticed that siad creates many thread inside main process. 55 threads right now. Are such quantity actually needed and such number is expected?

**Comment by rbj325** [comment] 2018-02-18 14:46
I believe this memory leak has gotten worse.  I have to restart my WinServer2016 every two days due to siad consuming 98% of memory and Sia-UI becoming completely broken.  In the UI the hosting section says that the wallet is locked and the wallet screen says it's unlocked and unsynchronized.  At this point you can not even kill the siad process and are required to reboot the server.

I am using Sia-Ui 1.3.1.

**Comment by lukechampine** [comment] 2018-02-18 16:28
@rbj325 can you try just running siad without Sia-UI?

**Comment by rbj325** [comment] 2018-02-18 16:46
@lukechampine Sure, it's running standalone now.  I will report back in a day or two if the memory usage shoots up again.  

Also for reference this server has 24GB of RAM, 30+GB of VRAM and is hosting ~40TB of space on the network.

Let me know if there are any other diagnostic steps I can take to help pinpoint the issue.

**Comment by lukechampine** [comment] 2018-02-19 03:07
The most precise would be a memory profile. If you run siad with `--profile=m`, it will dump a memory profile to the `profiles` directory at regular intervals. Then we could inspect two profiles a few hours apart (for example) and try to determine which allocations were leaking.

**Comment by rbj325** [comment] 2018-02-22 18:24
@lukechampine Running siad standalone does not result in the memory leak after 4 days.  Can I invoke that command line parameter via Sia-UI somehow?

**Comment by lukechampine** [comment] 2018-02-22 19:52
If `siad` alone isn't leaking memory, it's probably something in the UI, although I suppose it's possible that the UI is making requests to `siad` in a way that causes `siad` to leak memory.
If you run `siad` with `--profile=m` and then start Sia-UI, Sia-UI will connect to the running `siad` instead of starting a new process. So you can try that and see if `siad` leaks.

While you're running that test, might as well try to determine if Sia-UI itself is leaking memory. You should be able to bring up the developer tools by pressing Ctrl+Shift+P in Sia-UI. I believe the dev tools can help diagnose memory leaks; see https://developers.google.com/web/tools/chrome-devtools/memory-problems/#visualize_memory_leaks_with_timeline_recordings

**Comment by rbj325** [comment] 2018-02-24 23:42
@lukechampine After running Sia-UI for two days, since running siad standalone, I have not been able to reproduce the memory leak.  I don't think anything has changed but I will report back with those results if it pops up again.

**Comment by rbj325** [comment] 2018-02-26 18:37
Two days later and the leak is back.  I believe it has something to do with hosting using Sia-UI and then having intermittent connection issues.  In the console window there were 100+(and growing) errors pointing to the following locations:

https://github.com/NebulousLabs/Sia-UI/blob/6629b14235e4e3391e335892f8904fba4b1a1085/plugins/Hosting/js/sagas/saga.js#L255 

https://github.com/NebulousLabs/Sia-UI/blob/6629b14235e4e3391e335892f8904fba4b1a1085/plugins/Hosting/js/sagas/saga.js#L266 

https://github.com/NebulousLabs/Sia-UI/blob/6629b14235e4e3391e335892f8904fba4b1a1085/plugins/Hosting/js/sagas/saga.js#L241 

The error message is, "error fetching host status: Error: ESOCKETTIMEDOUT".  I'm not sure if this is a cause or an effect but I will try to reproduce with siad memory profiling enabled.  It seems like the UI is making rapid succession requests to siad until it runs out of memory and then is throttled by that.

Also I'm not sure if this is better suited as a Sia-UI issue or not.

**Comment by lukechampine** [comment] 2018-02-26 19:07
Interesting. A socket timeout would happen if siad is deadlocked or overwhelmed with requests. A deadlock seems unlikely, but you can check by making a manual request to siad with `siac host`. So my guess is that the UI is sending requests faster than siad can process them.
If that is the case, we should figure out a way to 1) measure the frequency of API requests, and 2) identify the code that's responsible for sending requests too fast. For 1), hopefully the Dev Tools provide some means of seeing which requests are being made. Alternatively, you could probably point Sia-UI at an HTTP proxy that records the requests.

**Comment by rbj325** [comment] 2018-02-27 13:03
I used the dev tools to take a Heap allocation timeline, not sure if it's helpful at all.  At the time of recording, the UI had reported 650+ exceptions and threw at least 6 while I was recording.  Let me know if you need more time recorded, etc.

Recording the network traffic resulted in no requests being captured so I'll look into the HTTP proxy.

[Heap-timeline-20180227T045517.zip](https://github.com/NebulousLabs/Sia/files/1762959/Heap-timeline-20180227T045517.zip)

**Comment by rbj325** [comment] 2018-03-20 06:29
I think the 1.3.2 release fixed the memory leak.  I still see the socket timeout exception but not as often and I can't reproduce the leak after updating.

**Comment by tbenz9** [comment] 2018-03-20 21:17
I'm going to close this, feel free to reopen if it comes back or you can reproduce it again.

**Closed by tbenz9** 2018-03-20 21:17 UTC
Labels: Bug
