### ISSUE TITLE
panic: bolt.DB.meta(): invalid meta pages

### ISSUE THREAD

**Issue by elivnjak** [NebulousLabs/Sia#2602] opened 2018-01-03 05:59 UTC
I set up my wallet and it was syncing. at 29.2% it said syncing stopped so i restarted the wallet. When i opened it again i get the following error: 

Sia Daemon v1.3.1
Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 8.3125405 seconds
panic: bolt.DB.meta(): invalid meta pages

goroutine 1404 [running]:
github.com/NebulousLabs/bolt.(*DB).meta(0xc04206f2c0, 0xc044e58940)
	/home/luke/go/src/github.com/NebulousLabs/bolt/db.go:830 +0xc9
github.com/NebulousLabs/bolt.(*meta).copy(...)
	/home/luke/go/src/github.com/NebulousLabs/bolt/tx.go:50
github.com/NebulousLabs/bolt.(*Tx).init(0xc044e1d340, 0xc04206f2c0)
	/home/luke/go/src/github.com/NebulousLabs/bolt/tx.go:50 +0xb3
github.com/NebulousLabs/bolt.(*DB).beginTx(0xc04206f2c0, 0xc0420d3d44, 0x4426e9, 0xbd0f0ac2c)
	/home/luke/go/src/github.com/NebulousLabs/bolt/db.go:491 +0xab
github.com/NebulousLabs/bolt.(*DB).Begin(0xc04206f2c0, 0xc000000000, 0xc042170a80, 0x473414, 0x828757)
	/home/luke/go/src/github.com/NebulousLabs/bolt/db.go:468 +0x75
github.com/NebulousLabs/bolt.(*DB).View(0xc04206f2c0, 0xc0423b1c38, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/bolt/db.go:618 +0x4d
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).CurrentBlock(0xc0420d3b80, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/consensusset.go:259 +0x114
github.com/NebulousLabs/Sia/api.(*API).consensusHandler(0xc042180510, 0xdea8c0, 0xc043e768c0, 0xc04351c100, 0x0, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/api/consensus.go:24 +0x52
github.com/NebulousLabs/Sia/api.(*API).(github.com/NebulousLabs/Sia/api.consensusHandler)-fm(0xdea8c0, 0xc043e768c0, 0xc04351c100, 0x0, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/api/routes.go:23 +0x6d
github.com/julienschmidt/httprouter.(*Router).ServeHTTP(0xc04204af40, 0xdea8c0, 0xc043e768c0, 0xc04351c100)
	/home/luke/go/src/github.com/julienschmidt/httprouter/router.go:344 +0x7a0
github.com/NebulousLabs/Sia/api.RequireUserAgent.func1(0xdea8c0, 0xc043e768c0, 0xc04351c100)
	/home/luke/go/src/github.com/NebulousLabs/Sia/api/routes.go:173 +0xc1
net/http.HandlerFunc.ServeHTTP(0xc0421bbc50, 0xdea8c0, 0xc043e768c0, 0xc04351c100)
	/usr/local/go/src/net/http/server.go:1918 +0x4b
github.com/NebulousLabs/Sia/api.cleanCloseHandler.func1.1(0xc042040840, 0xde5f80, 0xc0421bbc50, 0xdea8c0, 0xc043e768c0, 0xc04351c100)
	/home/luke/go/src/github.com/NebulousLabs/Sia/api/routes.go:143 +0x80
created by github.com/NebulousLabs/Sia/api.cleanCloseHandler.func1
	/home/luke/go/src/github.com/NebulousLabs/Sia/api/routes.go:141 +0xbe

Windows 8.1
Sia version: 1.3.1
OS: Windows 8.1 64bit

Any idea whats causing this?

**Comment by tbenz9** [comment] 2018-01-03 17:48
Duplicate of #2318 

This is caused by a corruption in the Consensus DB usually caused by Sia not being shut down properly or the computer going to sleep while a database operation is happening.

Steps to fix it are here: https://gist.github.com/tbenz9/8066d74853ab28c23bd7bc1d3c7cdeda

**Closed by tbenz9** 2018-01-03 17:48 UTC
