### ISSUE TITLE
Siacoin wallet won't syn

### ISSUE THREAD

**Issue by Mooman8** [NebulousLabs/Sia#2244] opened 2017-08-17 19:42 UTC
hi
The syn is stuck on 89.3%. I get error message below.
Please advise.

Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 1.1988392 seconds

**Comment by nikkuppp** [comment] 2017-08-29 09:33
![screenshot_1](https://user-images.githubusercontent.com/31436032/29814476-1612efba-8ccb-11e7-9f26-8ac836472f16.png)


what happend with wallet plzz help me

**Comment by tbenz9** [comment] 2017-10-17 18:21
Duplicate of #2148 
looks like an obscure boltdb bug. Try redownloading the blockchain with v1.3.0.  If you continue to have issues try asking for help on the Sia Discord.

Recommendation to devs: Close

**Closed** 2017-10-17 20:24 UTC
