### ISSUE TITLE
make release-std fails

### ISSUE THREAD

**Issue by dhensen** [NebulousLabs/Sia#2610] opened 2018-01-04 21:10 UTC
# BUG REPORT

**Stack Trace or error message**
```
$ make release-std
go install -tags 'netgo' -a -ldflags='-s -w' ./api ./build ./compatibility ./crypto ./encoding ./modules ./modules/consensus ./modules/explorer ./modules/gateway ./modules/host ./modules/host/contractmanager ./modules/renter ./modules/renter/contractor ./modules/renter/hostdb ./modules/renter/hostdb/hosttree ./modules/renter/proto ./modules/miner ./modules/wallet ./modules/transactionpool ./persist ./cmd/siad ./cmd/siac ./sync ./types
go install runtime/internal/sys: open /usr/lib/go/pkg/linux_amd64/runtime/internal/sys.a: permission denied
make: *** [Makefile:75: release-std] Error 1
```

**Expected Behavior**

**How to reproduce it (as minimally and precisely as possible)**

```
go get -u github.com/NebulousLabs/Sia/...
cd $GOPATH/src/github.com/NebulousLabs/Sia
make release-std
```

**Environment**
* Sia version: 1.3.0 currently, trying to build latest master (NebulousLabs/Sia@62ef2aad1c4af6696ebe07dbebcfffa81e2af892)
* OS: Arch Linux.

```
$ echo $GOPATH
/home/dino/go
$ uname -r
4.14.4-1-ARCH
$ go version
go version go1.9.2 linux/amd64
```

**Comment by dhensen** [comment] 2018-01-04 21:14
Oh....
```
$ ls -sla /usr/lib/go/pkg/linux_amd64/runtime/internal/sys.a
8 -rw-r--r-- 1 root root 5830 Oct 30 15:58 /usr/lib/go/pkg/linux_amd64/runtime/internal/sys.a
```

Should this be ran as root or should those files in /usr/lib/go/pkg have more open permissions?

**Comment by tbenz9** [comment] 2018-01-04 21:26
I've seen this issue before, I believe it's related to your Go environment and not Sia directly.

Googling around I've found it reported with a couple different projects.
https://github.com/golang/go/issues/15433
https://github.com/golang/go/issues/18981

I'm going to close this issue as it's not caused by Sia, but if you find a good solution please comment with it here!

**Closed by tbenz9** 2018-01-04 21:26 UTC
