### ISSUE TITLE
Collateral ratio penalty could not be working properly, depleting renter's allowance

### ISSUE THREAD

**Issue by hakkane84** [NebulousLabs/Sia#2978] opened 2018-05-02 05:08 UTC
**Collateral ratio penalty could not be working properly, depleting renter's allowance (potential Bug)**

# BUG REPORT

**Stack Trace or error message**
No error. This report comes from blockchain data analysis

**Expected Behavior**
The scoring system of hosts promote to increase their collateral, but after certain ratio of collateral vs storage cost the score should decrease to prevent renters from paying excessive Siafund fees (as they pay a 3.9% from the allowance + collateral). Long ago, I remember Taek mentioned the threshold to start decreasing the score should be around 3x-4x in this ratio collateral/storageprice. In another post, I remember Taek mentioned a renter usually ends up paying a 10% of their allowance in fees

**How to reproduce it (as minimally and precisely as possible)**
I am building a new Explorer for Sia. Among its features, I am curating and representing the metadata of file contracts included on the blockchain. One of the parameters I show is how much in SF fees a contract is paying and the percentage they represent, compared with the allowance paid by the renter. Take a look at the following examples from my Explorer prototype:

1 - https://siastats.info/navigator?search=d7683975103a0073b63aeb89f3592bb4c09ea3c4a8d6c856b469a6c4f1601d05 --> 51%

2- https://siastats.info/navigator?search=8e4e806122c3fff863fd760d12656b30fc205d76ebdfcc2edc31d345d2b1b6df --> 65%

3 - https://siastats.info/navigator?search=0b2afaf0675ac7a003f4c906ca1058626b0cf85acbe85ddb6638c1f8bcea0dad --> 40%

4- https://siastats.info/navigator?search=09b88f82881a98ee667b01bf35886b423c69f6d36fcb8d202d25702c9dec614d --> 28%

In the left side of the transaction schematic you can see the inputs, labelled as the renter allowance and the host's collateral. In the table bellow you can find the amount paid as SF fees and the % they represent of the renter's allowance.

While these cases are not the majority of contracts, there are multiple contracts where the renter is expending up to, and more than, 50% of their allowance in paying SF fees. This makes me believe that the part of the host scoring system that penalizes hosts with unproportioned collateral is not working as expected.

The case number 1 is very shocking, as it is a contract as small as 2.5SC in allowance. After paying SF fees and the contract formation fees, there is only 0.25SC remaining for actual uploads. This number of 0.25 can be deduced from the `missed contract output` number 0, that in this contract, not yet revised, represents the amount to be retuned to the renter in case of failed contract (discounting SF fees and contract formation fees). In my table it is shown as `Conditions upon failed contract > Returned allowance`. While this case is very extreme, overall this contract is expending a 90% of the allowance in fees

**Comment by nielscastien** [comment] 2018-05-02 15:43
I agree this is not good for the renter. Host 82.220.99.82 (ranked 6 on Siahub) has a ratio of 50:1 (collateral:storage price). This results in a standard contract fee of 67% of the allowance, no matter how high the allowance.

The problem is that most hosts are unaware of this, and think they are a good host when they put in more collateral. The majority of hosts in the top ten have a collateral/storage price ratio that is higher than 10:1.

**Comment by ChrisSchinnerl** [comment] 2018-05-02 20:40
We took a look at it and the math seems to be fine but it seems like a linear collateral adjustment is a bit too strong for the price penalty to show any significant effects. We opened a [PR](https://github.com/NebulousLabs/Sia/pull/2982) to weaken the collateral adjustment.

**Comment by ChrisSchinnerl** [comment] 2018-05-02 21:21
I'll close this for now since we merged the [PR](https://github.com/NebulousLabs/Sia/pull/2982). We can reopen the issue once 1.3.3 is released if necessary.

**Closed by ChrisSchinnerl** 2018-05-02 21:21 UTC
