### ISSUE TITLE
Adding a folder/drive

### ISSUE THREAD

**Issue by grigzy28** [NebulousLabs/Sia#3108] opened 2018-06-15 14:00 UTC
I have been trying to add a 3rd folder/drive to siad hosting (windows), it will add the folder/drive but then will just stop responding and I have to reboot the machine to get it to respond.  But then it will stop responding once again if you don't immediately remove the folder/drive.  This has occurred since 1.3.1 (when I started).  I have just not worried about it till now when I have been filling up my 2 folder/drives.

Update:  I removed one of the folders/drives (of the two) and added a 3.6tb folder/drive (1 @ 3.6tb and 1 @ 2.5tb) to the system for a total of 6.1tb.  Came home and found it locked up like it would with 3 folders in the siad host but with only 2 in the host.  

I am trying to re-add the 3.6tb folder to the system by splitting it up into two separate folders of 2.0 and 1.6.  Will see if it locks up again.

2nd update:  system locked up after about 45 minutes. with the 2.0 and 1.6 folder added to the 2.5.  Trying just 2 2.5tb now.

3rd update: the 2 2.5tb didn't work either, locked up.  removed them and re-added the original 1.9tb drive and now it locks up with it as well.

There are no error messages listed in the siad window.

**Expected Behavior**
Add folder/drives to system and continue as normal.

**How to reproduce it (as minimally and precisely as possible)*
Not sure yet, doing some testing.

**Environment**
* Sia version: 1.3.3
* OS: Windows 10x64.16299.492

**Comment by tbenz9** [comment] 2018-06-19 16:45
Check the logs for any errors, and paste anything suspicious here.  I also suspect that the UI might be to blame, have you tried running Sia without the user interface?

Use this to find your logs: https://gist.github.com/tbenz9/8066d74853ab28c23bd7bc1d3c7cdeda

**Comment by grigzy28** [comment] 2018-06-19 16:54
I do not use the gui interface, I only use the siad.exe and siac.exe.

Looked in the log file location and there are no log files at all.  Just a preference file for the UI and a config.json file, nothing under sia folder.

**Comment by tbenz9** [comment] 2018-06-19 22:11
I'm not sure what to tell you, I briefly looked through your logs and didn't see anything too egregious.  You might have better luck asking for help in the #HELP channel of the Sia Discord.  We try to keep support requests like this to Discord.

**Comment by tbenz9** [comment] 2018-06-19 22:12
You should monitor your computer resource usage when you try to add/remove the folders.  Is it running out of RAM or thrashing your disks or anything obvious?

**Comment by tbenz9** [comment] 2018-06-21 23:02
@MSevey do you know if the zeroing of a storage folder is supposed to happen asynchronously.  And if not, can we make it so?

**Comment by MSevey** [comment] 2018-06-25 15:19
@tbenz9 @grigzy28 currently the code is not set up to run this process asynchronously.  One reason is that we want to notify the host if they are unable to add/remove/resize storage folders.  If this was to run asynchronously then the host would be responsible for remembering to go through the log files to know if the command was successful or not.

Since it sounds like nothing is broken, and it is more of a UX thing, my recommendation would be to just update the documentation for the host API to better explain the expected behavior so hosts know to run these commands in a separate terminal screen so that they are not locked up waiting for the process to finish.  

I will close this issue.  @tbenz9 do you have time to quickly update the documentation to clarify the expected behavior? If not maybe just submit a separate issue requesting the change.

**Closed by MSevey** 2018-06-25 15:19 UTC
