### ISSUE TITLE
at the 94.5% Synchronizing level (after 4 days) and got this error

### ISSUE THREAD

**Issue by Me326** [NebulousLabs/Sia#2586] opened 2017-12-28 01:36 UTC
Sia Daemon v1.3.1
Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
listen tcp :9981: bind: address already in use
goroutine 2099 [running]:
runtime/debug.Stack(0x1045e47, 0xc421021cc0, 0xc421021c88)
	/usr/local/go/src/runtime/debug/stack.go:24 +0xa7
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/NebulousLabs/Sia/build.Severe(0xc421021e58, 0x2, 0x2)
	/home/luke/go/src/github.com/NebulousLabs/Sia/build/critical.go:32 +0x85
github.com/NebulousLabs/Sia/persist.(*Logger).Severe(0xc420310bc0, 0xc421021e58, 0x2, 0x2)
	/home/luke/go/src/github.com/NebulousLabs/Sia/persist/log.go:71 +0xcc
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).commit.func2(0xc420644d00, 0xc4200b8308, 0x0, 0x0, 0x0, 0x1b20b60, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:196 +0x1d1
created by github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).commit
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:188 +0x1e5
Severe error: ERROR: unable to create write-ahead-log: open /Users/kevinstroesser/Library/Application Support/Sia-UI/sia/host/contractmanager/contractmanager.wal_temp: too many open files in system
goroutine 2098 [running]:
runtime/debug.Stack(0x1045e47, 0xc42105cd98, 0xc42105cd60)
	/usr/local/go/src/runtime/debug/stack.go:24 +0xa7
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/NebulousLabs/Sia/build.Severe(0xc42105cec0, 0x2, 0x2)
	/home/luke/go/src/github.com/NebulousLabs/Sia/build/critical.go:32 +0x85
github.com/NebulousLabs/Sia/persist.(*Logger).Severe(0xc420310bc0, 0xc42105cec0, 0x2, 0x2)
	/home/luke/go/src/github.com/NebulousLabs/Sia/persist/log.go:71 +0xcc
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).commit.func1(0xc420644d00, 0xc4200b8308)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:167 +0x1d0
created by github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).commit
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:159 +0x15d
Severe error: Unable to open temporary settings file for writing: open /Users/kevinstroesser/Library/Application Support/Sia-UI/sia/host/contractmanager/contractmanager.json_temp: too many open files in system
goroutine 2099 [running]:
runtime/debug.Stack(0x1045e47, 0xc421021cc0, 0xc421021c88)
	/usr/local/go/src/runtime/debug/stack.go:24 +0xa7
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/NebulousLabs/Sia/build.Severe(0xc421021e98, 0x2, 0x2)
	/home/luke/go/src/github.com/NebulousLabs/Sia/build/critical.go:32 +0x85
github.com/NebulousLabs/Sia/persist.(*Logger).Severe(0xc420310bc0, 0xc421021e98, 0x2, 0x2)
	/home/luke/go/src/github.com/NebulousLabs/Sia/persist/log.go:71 +0xcc
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).commit.func2(0xc420644d00, 0xc4200b8308, 0x0, 0x0, 0x0, 0x1b20b60, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:201 +0x29e
created by github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).commit
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:188 +0x1e5
Severe error: Unable to properly initialize WAL file, crashing to prevent corruption: unable to write WAL metadata: invalid argument
goroutine 2099 [running]:
runtime/debug.Stack(0x1045e47, 0xc421021b28, 0xc421021af0)
	/usr/local/go/src/runtime/debug/stack.go:24 +0xa7
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/NebulousLabs/Sia/build.Severe(0xc421021c40, 0x2, 0x2)
	/home/luke/go/src/github.com/NebulousLabs/Sia/build/critical.go:32 +0x85
github.com/NebulousLabs/Sia/persist.(*Logger).Severe(0xc420310bc0, 0xc421021c40, 0x2, 0x2)
	/home/luke/go/src/github.com/NebulousLabs/Sia/persist/log.go:71 +0xcc
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).appendChange(0xc4200b8308, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlog.go:151 +0x2e9
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).commit.func2(0xc420644d00, 0xc4200b8308, 0x0, 0x0, 0x0, 0x1b20b60, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:205 +0x36a
created by github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).commit
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:188 +0x1e5
Severe error: Unable to write state change to WAL: invalid argument
panic: unable to append a change to the WAL, crashing to prevent corruption

goroutine 2099 [running]:
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).appendChange(0xc4200b8308, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlog.go:152 +0x305
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).commit.func2(0xc420644d00, 0xc4200b8308, 0x0, 0x0, 0x0, 0x1b20b60, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:205 +0x36a
created by github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).commit
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:188 +0x1e5

**Comment by tbenz9** [comment] 2017-12-31 23:46
Duplicate of #2406

**Closed by tbenz9** 2017-12-31 23:46 UTC
Labels: Bug
