### ISSUE TITLE
Siad has exited unexpectedly

### ISSUE THREAD

**Issue by Avversario** [NebulousLabs/Sia#2236] opened 2017-08-15 18:25 UTC
Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 0.491189173 seconds

Wallet: scanned to height 118056...
Wallet: scanned to height 118474...
Done!
goroutine 1 [running]:
runtime/debug.Stack(0x1043947, 0x0, 0xc4200615c0)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x79
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/NebulousLabs/Sia/build.Critical(0xc420061930, 0x1, 0x1)
	/home/luke/go/src/github.com/NebulousLabs/Sia/build/critical.go:16 +0xa7
main.startDaemon(0x0, 0x0, 0x7fff5fbffcac, 0xe, 0x7fff5fbffcd8, 0x5, 0x7fff5fbffcc7, 0x5, 0x0, 0x7fff5fbffd33, ...)
	/home/luke/go/src/github.com/NebulousLabs/Sia/siad/daemon.go:311 +0xaa9
main.startDaemonCmd(0xc420095200, 0xc4200971d0, 0x0, 0x5)
	/home/luke/go/src/github.com/NebulousLabs/Sia/siad/daemon.go:335 +0x162
github.com/spf13/cobra.(*Command).execute(0xc420095200, 0xc42006e070, 0x5, 0x5, 0xc420095200, 0xc42006e070)
	/home/luke/go/src/github.com/spf13/cobra/command.go:653 +0x299
github.com/spf13/cobra.(*Command).ExecuteC(0xc420095200, 0x16fce88, 0x3b, 0xc42016ca00)
	/home/luke/go/src/github.com/spf13/cobra/command.go:728 +0x339
github.com/spf13/cobra.(*Command).Execute(0xc420095200, 0x1aefba0, 0x16e58f7)
	/home/luke/go/src/github.com/spf13/cobra/command.go:687 +0x2b
main.main()
	/home/luke/go/src/github.com/NebulousLabs/Sia/siad/main.go:174 +0x7aa
Critical error: accept tcp 127.0.0.1:9980: accept: too many open files in system
Please submit a bug report here: https://github.com/NebulousLabs/Sia/issues
Closing renter...

**Comment by tbenz9** [comment] 2017-10-06 18:17
too many open files, https://stackoverflow.com/a/923369

Duplicate of #2228

**Closed** 2017-10-07 00:05 UTC
