### ISSUE TITLE
Siad has exited unexpectedly. OSX 10.10.5

### ISSUE THREAD

**Issue by goodc0re** [NebulousLabs/Sia#2574] opened 2017-12-22 05:43 UTC
Bug Report
==========

**Environment**

Sia version: v1.3.0 (Capricorn)
OSX 10.10.5
16 GB RAM
2,7 GHz Intel Core i7

**Any useful logs**
Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 0.730492381 seconds
goroutine 1 [running]:
runtime/debug.Stack(0x1043947, 0x0, 0x421c655c0)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x79
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/NebulousLabs/Sia/build.Critical(0x421c65930, 0x1, 0x1)
	/home/luke/go/src/github.com/NebulousLabs/Sia/build/critical.go:16 +0xa7
main.startDaemon(0x0, 0x0, 0x7fff5fbffd54, 0xe, 0x7fff5fbffd80, 0x5, 0x7fff5fbffd6f, 0x5, 0x0, 0x7fff5fbffdd3, ...)
	/home/luke/go/src/github.com/NebulousLabs/Sia/siad/daemon.go:311 +0xaa9
main.startDaemonCmd(0x421c85200, 0x421c15270, 0x0, 0x5)
	/home/luke/go/src/github.com/NebulousLabs/Sia/siad/daemon.go:335 +0x162
github.com/spf13/cobra.(*Command).execute(0x421c85200, 0x421c0a0d0, 0x5, 0x5, 0x421c85200, 0x421c0a0d0)
	/home/luke/go/src/github.com/spf13/cobra/command.go:653 +0x299
github.com/spf13/cobra.(*Command).ExecuteC(0x421c85200, 0x16fce88, 0x3b, 0x421d548c0)
	/home/luke/go/src/github.com/spf13/cobra/command.go:728 +0x339
github.com/spf13/cobra.(*Command).Execute(0x421c85200, 0x1aefba0, 0x16e58f7)
	/home/luke/go/src/github.com/spf13/cobra/command.go:687 +0x2b
main.main()
	/home/luke/go/src/github.com/NebulousLabs/Sia/siad/main.go:174 +0x7aa
Critical error: accept tcp 127.0.0.1:9980: accept: too many open files in system
Please submit a bug report here: https://github.com/NebulousLabs/Sia/issues
Closing renter...
Closing host...

**Comment by tbenz9** [comment] 2017-12-22 17:35
Duplicate of #2406 

Fix is in this document: https://gist.github.com/tbenz9/8066d74853ab28c23bd7bc1d3c7cdeda

**Closed by tbenz9** 2017-12-22 17:35 UTC
