### ISSUE TITLE
Critical error: Host entry scan history not sorted.

### ISSUE THREAD

**Issue by jeffreybasurto** [NebulousLabs/Sia#1799] opened 2017-05-16 07:14 UTC
No idea why but recently when I start siad I get:
```
goroutine 54 [running]:
runtime/debug.Stack(0x44433e, 0x0, 0xc043cc6870)
        /usr/local/go/src/runtime/debug/stack.go:24 +0x80
runtime/debug.PrintStack()
        /usr/local/go/src/runtime/debug/stack.go:16 +0x29
github.com/NebulousLabs/Sia/build.Critical(0xc043cc69e8, 0x1, 0x1)
        /home/luke/go/src/github.com/NebulousLabs/Sia/build/critical.go:15 +0xae
github.com/NebulousLabs/Sia/persist.(*Logger).Critical(0xc042397c80, 0xc043cc69e8, 0x1, 0x1)
        /home/luke/go/src/github.com/NebulousLabs/Sia/persist/log.go:37 +0xe7
github.com/NebulousLabs/Sia/modules/renter/hostdb.(*HostDB).uptimeAdjustments(0xc042048500, 0x1, 0x1100000, 0x3330, 0x1100000, 0xc043551f80, 0x14, 0x636960800, 0x400000, 0x29e8d60800, ...)
        /home/luke/go/src/github.com/NebulousLabs/Sia/modules/renter/hostdb/hostweight.go:287 +0x27f
github.com/NebulousLabs/Sia/modules/renter/hostdb.(*HostDB).calculateHostWeight(0xc042048500, 0x1, 0x1100000, 0x3330, 0x1100000, 0xc043551f80, 0x14, 0x636960800, 0x400000, 0x29e8d60800, ...)
        /home/luke/go/src/github.com/NebulousLabs/Sia/modules/renter/hostdb/hostweight.go:343 +0x1ae
github.com/NebulousLabs/Sia/modules/renter/hostdb.(*HostDB).(github.com/NebulousLabs/Sia/modules/renter/hostdb.calculateHostWeight)-fm(0x1, 0x1100000, 0x3330, 0x1100000, 0xc043551f80, 0x14, 0x636960800, 0x400000, 0x29e8d60800, 0x8f546f0283d19b36, ...)
        /home/luke/go/src/github.com/NebulousLabs/Sia/modules/renter/hostdb/hostdb.go:107 +0x66
github.com/NebulousLabs/Sia/modules/renter/hostdb/hosttree.(*HostTree).Modify(0xc042397ca0, 0x1, 0x1100000, 0x3330, 0x1100000, 0xc043551f80, 0x14, 0x636960800, 0x400000, 0x29e8d60800, ...)
        /home/luke/go/src/github.com/NebulousLabs/Sia/modules/renter/hostdb/hosttree/hosttree.go:257 +0x12f
github.com/NebulousLabs/Sia/modules/renter/hostdb.(*HostDB).updateEntry(0xc042048500, 0x1, 0x1100000, 0x3330, 0x1100000, 0xc043551f80, 0x14, 0x636960800, 0x400000, 0x29e8d60800, ...)
        /home/luke/go/src/github.com/NebulousLabs/Sia/modules/renter/hostdb/scan.go:185 +0x49c
github.com/NebulousLabs/Sia/modules/renter/hostdb.(*HostDB).managedScanHost(0xc042048500, 0x1, 0x1100000, 0x3330, 0x1100000, 0xc043551f80, 0x14, 0x636960800, 0x400000, 0x29e8d60800, ...)
        /home/luke/go/src/github.com/NebulousLabs/Sia/modules/renter/hostdb/scan.go:241 +0x3c3
github.com/NebulousLabs/Sia/modules/renter/hostdb.(*HostDB).threadedProbeHosts(0xc042048500)
        /home/luke/go/src/github.com/NebulousLabs/Sia/modules/renter/hostdb/scan.go:278 +0x357
created by github.com/NebulousLabs/Sia/modules/renter/hostdb.newHostDB
        /home/luke/go/src/github.com/NebulousLabs/Sia/modules/renter/hostdb/hostdb.go:173 +0x6f2
Critical error: Host entry scan history not sorted.
Please submit a bug report here: https://github.com/NebulousLabs/Sia/issues
```

**Comment by lukechampine** [comment] 2017-05-16 07:31
this can happen if your system clock changes. siad should continue running.
@DavidVorick maybe we should just always sort and not raise an error?

**Comment by DavidVorick** [comment] 2017-05-16 13:11
What version are you running?

Sorting is not the right answer it'll screw up the internal calculations, and really throw off the accuracy. Would be better to throw away the points that don't make sense than to sort, I believe.

But, I thought we already wrote code to handle this?

**Comment by lukechampine** [comment] 2017-07-28 21:12
closing for now. Please reopen if this is reproducible in v1.3.0

**Comment by Coren** [comment] 2017-07-31 16:54
Hi,

I got the same error here with v1.3.0.

Regards,

**Comment by tbenz9** [comment] 2017-11-08 04:04
Recommendation to devs: label "Bug"

**Comment by MichelSakr** [comment] 2018-02-07 22:48
Any clue when this issue will be solved?

**Comment by ChrisSchinnerl** [comment] 2018-02-08 16:35
@MichelSakr The current code should ignore unsorted entries in a Release build and only crash in Debug builds even if it shows the error output.
@lukechampine @DavidVorick  should we stop printing the error in Release builds? Might be confusing.

**Comment by MichelSakr** [comment] 2018-02-08 16:40
@ChrisSchinnerl thank you for the feedback, indeed the error should not block the access to the wallet or other features.. not too user oriented.. 
I restored from backup to solve the issue, (now facing a synch hang) however it is not a fix for users who do not have backups..

**Closed** 2018-03-05 19:11 UTC
Labels: Bug

**Comment by MichelSakr** [comment] 2018-03-05 19:13
What was the resolution Luke?

**Comment by ChrisSchinnerl** [comment] 2018-03-05 19:21
@MichelSakr The PR changes it to only crash a debug build. Release builds will simply log a warning in the log without printing anything in the terminal and ignore the corrupted entries.

**Comment by MichelSakr** [comment] 2018-03-05 19:24
Thanks Chris, since a new build was not released for the UI, the ticket closing did not make sense to me ...
