### ISSUE TITLE
Failed during syncing the new wallet

### ISSUE THREAD

**Issue by ZsZolee** [NebulousLabs/Sia#2564] opened 2017-12-20 17:44 UTC
Bug Report
==========
Check to see if a bug report already exists.  If you still want to create a new issue please include the information below.

**Stack Trace or error message**

Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 103.6486844 seconds
panic: page 4485 already freed

goroutine 29 [running]:
github.com/NebulousLabs/bolt.(*freelist).free(0xc042065dd0, 0x6ad, 0x201175000)
	/home/luke/go/src/github.com/NebulousLabs/bolt/freelist.go:121 +0x2a1
github.com/NebulousLabs/bolt.(*node).spill(0xc04212ddc0, 0xc0438e1b20, 0xde0d20)
	/home/luke/go/src/github.com/NebulousLabs/bolt/node.go:363 +0x1e7
github.com/NebulousLabs/bolt.(*node).spill(0xc04212dd50, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/bolt/node.go:350 +0xbb
github.com/NebulousLabs/bolt.(*node).spill(0xc042128a10, 0xc0438e0d00, 0xde0d20)
	/home/luke/go/src/github.com/NebulousLabs/bolt/node.go:350 +0xbb
github.com/NebulousLabs/bolt.(*node).spill(0xc0420f6310, 0xc0420d6480, 0xc042149a28)
	/home/luke/go/src/github.com/NebulousLabs/bolt/node.go:350 +0xbb
github.com/NebulousLabs/bolt.(*Bucket).spill(0xc0420382c0, 0xc042149b00, 0x15)
	/home/luke/go/src/github.com/NebulousLabs/bolt/bucket.go:570 +0x182
github.com/NebulousLabs/bolt.(*Bucket).spill(0xc0420780f8, 0x2b765f90, 0xee9fe0)
	/home/luke/go/src/github.com/NebulousLabs/bolt/bucket.go:537 +0x8ff
github.com/NebulousLabs/bolt.(*Tx).Commit(0xc0420780e0, 0xc04201b040, 0xc042149e80)
	/home/luke/go/src/github.com/NebulousLabs/bolt/tx.go:163 +0x12c
github.com/NebulousLabs/Sia/modules/transactionpool.(*TransactionPool).syncDB(0xc042500000)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/transactionpool/persist.go:54 +0x4e
github.com/NebulousLabs/Sia/modules/transactionpool.(*TransactionPool).threadedRegularSync(0xc042500000)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/transactionpool/persist.go:44 +0x17e
created by github.com/NebulousLabs/Sia/modules/transactionpool.(*TransactionPool).initPersist
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/transactionpool/persist.go:126 +0x3f6

**Environment**
* Sia version: 1.3.0
* OS: Windows 10 PRO N

**Any useful logs**

Just stopped at 84.7% of synchronization and even after restart is not working.

Feature Request
===============
Check to see if the feature is on the roadmap.  If it is not on the roadmap then clearly describe your feature request and why it would benefit Sia.

[Sia roadmap](https://trello.com/b/Io1dDyuI/sia-public-roadmap)

**Comment by tbenz9** [comment] 2017-12-20 18:27
Duplicate of #2413 

Take a look at this page for a fix: https://gist.github.com/tbenz9/8066d74853ab28c23bd7bc1d3c7cdeda

**Closed by tbenz9** 2017-12-20 18:27 UTC
