### ISSUE TITLE
bug report

### ISSUE THREAD

**Issue by sparkie73** [NebulousLabs/Sia#3128] opened 2018-06-28 20:11 UTC
# BUG REPORT

**Stack Trace or error message**

**Expected Behavior**

**How to reproduce it (as minimally and precisely as possible)**

**Environment**
* Sia version:
* OS:

**Comment by sparkie73** [comment] 2018-06-28 20:12
Sia Daemon v1.3.3
Git Revision 94ea84e
Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 0.6153389 seconds
panic: bolt.DB.meta(): invalid meta pages

goroutine 513 [running]:
github.com/NebulousLabs/Sia/vendor/github.com/coreos/bbolt.(*DB).meta(0xc042132780, 0xc04297de00)
	/home/luke/go/src/github.com/NebulousLabs/Sia/vendor/github.com/coreos/bbolt/db.go:894 +0xc9
github.com/NebulousLabs/Sia/vendor/github.com/coreos/bbolt.(*Tx).init(0xc0449ae000, 0xc042132780)
	/home/luke/go/src/github.com/NebulousLabs/Sia/vendor/github.com/coreos/bbolt/tx.go:50 +0xb3
github.com/NebulousLabs/Sia/vendor/github.com/coreos/bbolt.(*DB).beginTx(0xc042132780, 0xf21930, 0xf21920, 0xc042421bc8)
	/home/luke/go/src/github.com/NebulousLabs/Sia/vendor/github.com/coreos/bbolt/db.go:546 +0x9f
github.com/NebulousLabs/Sia/vendor/github.com/coreos/bbolt.(*DB).Begin(0xc042132780, 0x0, 0xc042421bf8, 0x42b320, 0xc000000008)
	/home/luke/go/src/github.com/NebulousLabs/Sia/vendor/github.com/coreos/bbolt/db.go:523 +0x75
github.com/NebulousLabs/Sia/vendor/github.com/coreos/bbolt.(*DB).View(0xc042132780, 0xc042421c38, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/vendor/github.com/coreos/bbolt/db.go:688 +0x43
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).CurrentBlock(0xc04213d400, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/consensusset.go:283 +0x114
github.com/NebulousLabs/Sia/node/api.(*API).consensusHandler(0xc04217e990, 0xb5eca0, 0xc042cce000, 0xc04222a000, 0x0, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/node/api/consensus.go:173 +0x52
github.com/NebulousLabs/Sia/node/api.(*API).(github.com/NebulousLabs/Sia/node/api.consensusHandler)-fm(0xb5eca0, 0xc042cce000, 0xc04222a000, 0x0, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/node/api/routes.go:23 +0x6d
github.com/julienschmidt/httprouter.(*Router).ServeHTTP(0xc0420495c0, 0xb5eca0, 0xc042cce000, 0xc04222a000)
	/home/luke/go/src/github.com/julienschmidt/httprouter/router.go:334 +0x7a3
github.com/NebulousLabs/Sia/node/api.RequireUserAgent.func1(0xb5eca0, 0xc042cce000, 0xc04222a000)
	/home/luke/go/src/github.com/NebulousLabs/Sia/node/api/routes.go:178 +0xc1
net/http.HandlerFunc.ServeHTTP(0xc042380540, 0xb5eca0, 0xc042cce000, 0xc04222a000)
	/usr/local/go/src/net/http/server.go:1947 +0x4b
github.com/NebulousLabs/Sia/node/api.cleanCloseHandler.func1.1(0xc042210240, 0xb5a7e0, 0xc042380540, 0xb5eca0, 0xc042cce000, 0xc04222a000)
	/home/luke/go/src/github.com/NebulousLabs/Sia/node/api/routes.go:149 +0x80
created by github.com/NebulousLabs/Sia/node/api.cleanCloseHandler.func1
	/home/luke/go/src/github.com/NebulousLabs/Sia/node/api/routes.go:147 +0xa7

**Comment by tbenz9** [comment] 2018-06-29 16:54
Duplicate of #2318

**Closed by tbenz9** 2018-06-29 16:54 UTC
