### ISSUE TITLE
Errors in contractmanager - Access is denied

### ISSUE THREAD

**Issue by betaboot** [NebulousLabs/Sia#2121] opened 2017-07-12 15:53 UTC
Sia-UI-v1.3.0-RC4, Win10
I have two errors in contractmanager.log

2017/07/12 14:05:25.329335 writeaheadlogsync.go:110: SEVERE: ERROR: could not rename temporary write-ahead-log in contract manager: rename C:\Users\Cube\AppData\Roaming\Sia-UI\sia\host\contractmanager\contractmanager.wal_temp C:\Users\Cube\AppData\Roaming\Sia-UI\sia\host\contractmanager\contractmanager.wal: Access is denied.

2017/07/12 15:43:55.296361 writeaheadlogsync.go:50: SEVERE: ERROR: unable to atomically copy the contract manager settings: rename C:\Users\Cube\AppData\Roaming\Sia-UI\sia\host\contractmanager\contractmanager.json_temp C:\Users\Cube\AppData\Roaming\Sia-UI\sia\host\contractmanager\contractmanager.json: Access is denied.

**Comment by lukechampine** [comment] 2017-07-28 23:09
were you able to resolve this? I'm not sure why you'd be getting a permissions error here.

**Comment by betaboot** [comment] 2017-07-29 05:13
No, i still get them with the official v1.3.0.

**Comment by tbenz9** [comment] 2017-10-12 21:38
Duplicate of #2189 

Recommendation to devs: Close.

**Closed** 2017-10-12 22:44 UTC
