### ISSUE TITLE
panic: Critical error: negative currency not allowed

### ISSUE THREAD

**Issue by gls4** [NebulousLabs/Sia#2863] opened 2018-03-14 12:50 UTC
Wallet: scanned to height 145517...
Done!
goroutine 215328 [running]:
runtime/debug.Stack(0x445d87, 0x0, 0xc42142fef8)
        /usr/local/go/src/runtime/debug/stack.go:24 +0xa7
runtime/debug.PrintStack()
        /usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/NebulousLabs/Sia/build.Critical(0xc42142ffb0, 0x1, 0x1)
        /root/Sia/src/github.com/NebulousLabs/Sia/build/critical.go:16 +0x99
github.com/NebulousLabs/Sia/types.Currency.Sub(0x0, 0xc421b9c210, 0x2, 0x6, 0x0, 0xc42037a140, 0x2, 0x7, 0xc421b9cf00, 0xc421b9c210, ...)
        /root/Sia/src/github.com/NebulousLabs/Sia/types/currency.go:179 +0x12e
github.com/NebulousLabs/Sia/modules/host.renewContractCollateral(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc422990d80, 0x2, ...)
        /root/Sia/src/github.com/NebulousLabs/Sia/modules/host/negotiaterenewcontract.go:44 +0xa6
github.com/NebulousLabs/Sia/modules/host.(*Host).managedVerifyRenewedContract(0xc42010e000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc422990d80, ...)
        /root/Sia/src/github.com/NebulousLabs/Sia/modules/host/negotiaterenewcontract.go:266 +0x61b
github.com/NebulousLabs/Sia/modules/host.(*Host).managedRPCRenewContract(0xc42010e000, 0xb5e240, 0xc42000e178, 0x0, 0x0)
        /root/Sia/src/github.com/NebulousLabs/Sia/modules/host/negotiaterenewcontract.go:126 +0x41d
github.com/NebulousLabs/Sia/modules/host.(*Host).threadedHandleConn(0xc42010e000, 0xb5e240, 0xc42000e178)
        /root/Sia/src/github.com/NebulousLabs/Sia/modules/host/network.go:286 +0x7cb
created by github.com/NebulousLabs/Sia/modules/host.(*Host).threadedListen
        /root/Sia/src/github.com/NebulousLabs/Sia/modules/host/network.go:322 +0xc3
Critical error: negative currency not allowed
Please submit a bug report here: https://github.com/NebulousLabs/Sia/issues
panic: Critical error: negative currency not allowed
Please submit a bug report here: https://github.com/NebulousLabs/Sia/issues

goroutine 215328 [running]:
github.com/NebulousLabs/Sia/build.Critical(0xc42142ffb0, 0x1, 0x1)
        /root/Sia/src/github.com/NebulousLabs/Sia/build/critical.go:20 +0x103
github.com/NebulousLabs/Sia/types.Currency.Sub(0x0, 0xc421b9c210, 0x2, 0x6, 0x0, 0xc42037a140, 0x2, 0x7, 0xc421b9cf00, 0xc421b9c210, ...)
        /root/Sia/src/github.com/NebulousLabs/Sia/types/currency.go:179 +0x12e
github.com/NebulousLabs/Sia/modules/host.renewContractCollateral(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc422990d80, 0x2, ...)
        /root/Sia/src/github.com/NebulousLabs/Sia/modules/host/negotiaterenewcontract.go:44 +0xa6
github.com/NebulousLabs/Sia/modules/host.(*Host).managedVerifyRenewedContract(0xc42010e000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc422990d80, ...)
        /root/Sia/src/github.com/NebulousLabs/Sia/modules/host/negotiaterenewcontract.go:266 +0x61b
github.com/NebulousLabs/Sia/modules/host.(*Host).managedRPCRenewContract(0xc42010e000, 0xb5e240, 0xc42000e178, 0x0, 0x0)
        /root/Sia/src/github.com/NebulousLabs/Sia/modules/host/negotiaterenewcontract.go:126 +0x41d
github.com/NebulousLabs/Sia/modules/host.(*Host).threadedHandleConn(0xc42010e000, 0xb5e240, 0xc42000e178)
        /root/Sia/src/github.com/NebulousLabs/Sia/modules/host/network.go:286 +0x7cb
created by github.com/NebulousLabs/Sia/modules/host.(*Host).threadedListen
        /root/Sia/src/github.com/NebulousLabs/Sia/modules/host/network.go:322 +0xc3

How to Reproduce: It seems to happen after a couple of hours, but I've no idea why. siad ran fine for a  month until March 10, when this started happening.

Sia version: 1.3.2
OS: FreeBSD 11.1

**Comment by ChrisSchinnerl** [comment] 2018-03-14 18:24
@gls4 What is your ContractPrice set to? 0 SC ?

**Comment by tbenz9** [comment] 2018-03-14 18:54
Duplicate of #2733

**Closed by tbenz9** 2018-03-14 18:54 UTC
