### ISSUE TITLE
Unlock wallet issue

### ISSUE THREAD

**Issue by radegeddon** [NebulousLabs/Sia#2593] opened 2017-12-31 00:35 UTC
Bug Report
==========
Check to see if a bug report already exists.  If you still want to create a new issue please include the information below.

**Stack Trace or error message**
When trying to unlock the wallet, it asks multiple time, reporting "error when calling /wallet/unlock: provided encryption key is incorrect", until it works after x times and shows "Scanning on Blockchain".
Then it locks after a couple of seconds, and asks for unlock password again.
Trying it in terminal yields the same.
Also, when unlocked, generating new Receive address gives nothing.

**Expected Behavior**

**Environment**
* Sia version: v1.3.1
* OS: Windows 7 Ultimate x64

**Any useful logs**

Feature Request
===============
Check to see if the feature is on the roadmap.  If it is not on the roadmap then clearly describe your feature request and why it would benefit Sia.

[Sia roadmap](https://trello.com/b/Io1dDyuI/sia-public-roadmap)

**Comment by tbenz9** [comment] 2017-12-31 02:04
Possibly related to #2587

**Comment by tbenz9** [comment] 2017-12-31 03:02
I'm marking this as a duplicate of #2587, the devs are aware of the issue.

**Closed by tbenz9** 2017-12-31 03:02 UTC
