### ISSUE TITLE
I have no idea what im doing but i got an error and it led me here.

### ISSUE THREAD

**Issue by ryanchappell85** [NebulousLabs/Sia#3089] opened 2018-06-08 02:02 UTC
# BUG REPORT

**Stack Trace or error message**

**Expected Behavior**

**How to reproduce it (as minimally and precisely as possible)**

**Environment**
* Sia version:
* OS:

Sia Daemon v1.3.3
Git Revision 910034d
Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 6.310953 seconds
panic: bolt.DB.meta(): invalid meta pages

goroutine 306 [running]:
github.com/NebulousLabs/Sia/vendor/github.com/coreos/bbolt.(*DB).meta(0xc04220e000, 0xc04e670000)
	/home/luke/go/src/github.com/NebulousLabs/Sia/vendor/github.com/coreos/bbolt/db.go:894 +0xc9
github.com/NebulousLabs/Sia/vendor/github.com/coreos/bbolt.(*Tx).init(0xc04df8e620, 0xc04220e000)
	/home/luke/go/src/github.com/NebulousLabs/Sia/vendor/github.com/coreos/bbolt/tx.go:50 +0xb3
github.com/NebulousLabs/Sia/vendor/github.com/coreos/bbolt.(*DB).beginTx(0xc04220e000, 0x3869b05d1, 0xc04a56dbe0, 0x46f224)
	/home/luke/go/src/github.com/NebulousLabs/Sia/vendor/github.com/coreos/bbolt/db.go:546 +0x9f
github.com/NebulousLabs/Sia/vendor/github.com/coreos/bbolt.(*DB).Begin(0xc04220e000, 0xc000000000, 0xc04a56dbf8, 0x42b320, 0xc000000008)
	/home/luke/go/src/github.com/NebulousLabs/Sia/vendor/github.com/coreos/bbolt/db.go:523 +0x75
github.com/NebulousLabs/Sia/vendor/github.com/coreos/bbolt.(*DB).View(0xc04220e000, 0xc04a56dc38, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/vendor/github.com/coreos/bbolt/db.go:688 +0x43
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).CurrentBlock(0xc04213b400, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/consensusset.go:283 +0x114
github.com/NebulousLabs/Sia/node/api.(*API).consensusHandler(0xc049f68ea0, 0xb5e6e0, 0xc04df8fc00, 0xc04b654100, 0x0, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/node/api/consensus.go:173 +0x52
github.com/NebulousLabs/Sia/node/api.(*API).(github.com/NebulousLabs/Sia/node/api.consensusHandler)-fm(0xb5e6e0, 0xc04df8fc00, 0xc04b654100, 0x0, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/node/api/routes.go:23 +0x6d
github.com/julienschmidt/httprouter.(*Router).ServeHTTP(0xc04dbb7c40, 0xb5e6e0, 0xc04df8fc00, 0xc04b654100)
	/home/luke/go/src/github.com/julienschmidt/httprouter/router.go:334 +0x7a3
github.com/NebulousLabs/Sia/node/api.RequireUserAgent.func1(0xb5e6e0, 0xc04df8fc00, 0xc04b654100)
	/home/luke/go/src/github.com/NebulousLabs/Sia/node/api/routes.go:178 +0xc1
net/http.HandlerFunc.ServeHTTP(0xc04b5087b0, 0xb5e6e0, 0xc04df8fc00, 0xc04b654100)
	/usr/local/go/src/net/http/server.go:1947 +0x4b
github.com/NebulousLabs/Sia/node/api.cleanCloseHandler.func1.1(0xc0421e8a80, 0xb5a220, 0xc04b5087b0, 0xb5e6e0, 0xc04df8fc00, 0xc04b654100)
	/home/luke/go/src/github.com/NebulousLabs/Sia/node/api/routes.go:149 +0x80
created by github.com/NebulousLabs/Sia/node/api.cleanCloseHandler.func1
	/home/luke/go/src/github.com/NebulousLabs/Sia/node/api/routes.go:147 +0xa7

**Comment by tbenz9** [comment] 2018-06-08 21:17
Duplicate of #2318

**Closed by tbenz9** 2018-06-08 21:17 UTC
