### ISSUE TITLE
v1.3.0 Download Failed: Insufficient hosts to recover file

### ISSUE THREAD

**Issue by alamcordeiro** [NebulousLabs/Sia#2213] opened 2017-08-02 20:54 UTC
**Case of Use:** Trying download a file of 14mb uploaded yesterday using Sia GUI
**SO**: macOS Sierra 10.12.5
**Sia UI version:**:  v1.3.0
**Sia version:**:  v1.3.0

![captura de tela 2017-08-02 as 16 03 21](https://user-images.githubusercontent.com/1471463/28894982-366171b8-779c-11e7-8751-22258509b7ed.png)

`goroutine 118 [running]:
runtime/debug.Stack(0x1043947, 0x0, 0xc425875bf0)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x79
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/NebulousLabs/Sia/build.Critical(0xc425875d70, 0x3, 0x3)
	/home/luke/go/src/github.com/NebulousLabs/Sia/build/critical.go:16 +0xa7
github.com/NebulousLabs/Sia/persist.(*Logger).Critical(0xc4202a0500, 0xc425875d70, 0x3, 0x3)
	/home/luke/go/src/github.com/NebulousLabs/Sia/persist/log.go:37 +0xe0
github.com/NebulousLabs/Sia/modules/renter.(*Renter).managedDownloadIteration(0xc420961440, 0xc425875f20)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/renter/download.go:365 +0x67d
github.com/NebulousLabs/Sia/modules/renter.(*Renter).threadedDownloadLoop(0xc420961440)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/renter/download.go:635 +0x37e
created by github.com/NebulousLabs/Sia/modules/renter.newRenter
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/renter/renter.go:220 +0x3e3
Critical error: ERROR: the renter is idle, but tracking 4 active pieces; resetting to zero`

**Comment by alamcordeiro** [comment] 2017-08-03 03:37
Is there any a alternative to test status (available or unavailable) of all files from folder ? Because redundancy show at 3.2x but result in fail download.

**Comment by alamcordeiro** [comment] 2017-08-04 21:39
If necessary I send all databases (transactionpool.db, host.db, etc) to debug

**Comment by suprnrdy** [comment] 2017-10-15 05:51
I am getting the same thing.  File shows 3.7x redundancy and as soon as I click download I get this message.  I get a warning Icon in the download toolbar with the downloading of that selected file sitting with a progress bar. Progress bar shows more pieces downloaded but taking over 1 minute.

**Comment by tbenz9** [comment] 2017-10-19 16:39
`Critical error: ERROR: the renter is idle, but tracking 4 active pieces; resetting to zero` is a duplicate of #2395.  Are you seeing other errors besides that one?  If yes, add them and reopen this issue.

Recommendation to devs: close

**Closed** 2017-10-19 17:30 UTC
