### ISSUE TITLE
Sia crashes on start

### ISSUE THREAD

**Issue by enricodetoma** [NebulousLabs/Sia#2252] opened 2017-08-21 15:38 UTC
Sia crashes almost immediately on start.
Here is the log:

Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 1.0924356 seconds
panic: runtime error: slice bounds out of range

goroutine 27 [running]:
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).getBlockTotals(0xc042139b80, 0xc04292f0a0, 0x2500000000000000, 0x41e2ef26e006330a, 0xdb97e3e150a16660, 0x2d069274ed76710b, 0xc0433e3340, 0x0, 0x0, 0x0, ...)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/difficulty.go:120 +0x13b
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).newChild(0xc042139b80, 0xc04292f0a0, 0xc042594000, 0x2500000000000000, 0x41e2ef26e006330a, 0xdb97e3e150a16660, 0x2d069274ed76710b, 0x8548f2d, 0x59876aa5, 0xc0433e3340, ...)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/processedblock.go:135 +0x1a8
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).addBlockToTree(0xc042139b80, 0xc04292f0a0, 0x2500000000000000, 0x41e2ef26e006330a, 0xdb97e3e150a16660, 0x2d069274ed76710b, 0x8548f2d, 0x59876aa5, 0xc0433e3340, 0x1, ...)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/accept.go:151 +0xa3
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).managedAcceptBlocks.func1(0xc04292f0a0, 0xb0b570, 0xc04292f0a0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/accept.go:262 +0x23a
github.com/NebulousLabs/bolt.(*DB).Update(0xc042106780, 0xc0435692e8, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/bolt/db.go:603 +0xa6
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).managedAcceptBlocks(0xc042139b80, 0xc04203d400, 0xa, 0xa, 0x0, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/accept.go:283 +0x520
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).managedReceiveBlocks(0xc042139b80, 0xde41c0, 0xc0422e93e0, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:225 +0x5be
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).(github.com/NebulousLabs/Sia/modules/consensus.managedReceiveBlocks)-fm(0xde41c0, 0xc0422e93e0, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:445 +0x45
github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).managedRPC(0xc042076dc0, 0xc0421a1700, 0x13, 0xaddb78, 0xa, 0xc04236cda0, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/rpc.go:66 +0x339
github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).RPC(0xc042076dc0, 0xc0421a1700, 0x13, 0xaddb78, 0xa, 0xc04236cda0, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/rpc.go:76 +0xd8
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).threadedInitialBlockchainDownload.func1(0xc042139b80, 0xc043569ef0, 0xc043569eb0, 0xc043569eb8, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:580 +0x133
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).threadedInitialBlockchainDownload(0xc042139b80, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:601 +0x30e
github.com/NebulousLabs/Sia/modules/consensus.New.func1(0x1, 0xc042248a40, 0xc042139b80, 0xde4440, 0xc042076dc0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/consensusset.go:151 +0x404
created by github.com/NebulousLabs/Sia/modules/consensus.New
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/consensusset.go:182 +0x641

**Comment by tlightsky** [comment] 2017-09-25 05:15
same error: ` slice bounds out of range`

**Comment by tbenz9** [comment] 2017-10-12 21:32
Duplicate of issue #2183 

Recommendation to devs: close

**Closed** 2017-10-12 22:44 UTC
