### ISSUE TITLE
Sia crashing along with Chrome (Mac)

### ISSUE THREAD

**Issue by WalnutWood** [NebulousLabs/Sia#1929] opened 2017-06-14 02:09 UTC
New Sia user here. I'm trying to host and also use Sia for storage, and the experience has been quite buggy. Here are my issues:

**Uploading/Storing**: I allocated 5,000 SC for storage contracts. After initiating the allowance, random amounts of SC started to be pulled from my wallet totaling about 900, but no contracts were ever formed. My balance reads 0 SC Spent / 0 Allocated, 0 Contracts. 

**Hosting**: After running the host for some period of time, both Sia and Google Chrome (Mac) crash, resulting in lengthy error logs. I didn't copy the error logs this time, but assuming it happens again, I can paste them in tomorrow if that's needed to diagnose the issue...

**Comment by WalnutWood** [comment] 2017-06-14 12:04
Here's the error message it gives: 

> 
![image](https://user-images.githubusercontent.com/29418173/27131307-bcb5f462-50cf-11e7-9b00-121d99083f98.png)

**Comment by lukechampine** [comment] 2017-07-28 21:40
duplicate of #1840

**Closed by lukechampine** 2017-07-28 21:40 UTC
