### ISSUE TITLE
Error when running "stop" (4 days, only 35% synced, Windows Server 2008)

### ISSUE THREAD

**Issue by reincarnated** [NebulousLabs/Sia#2695] opened 2018-01-27 09:08 UTC
Sia Daemon v1.3.1
Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 7.0914056 seconds
goroutine 1057349 [running]:
runtime/debug.Stack(0x446d5e, 0xc042bade20, 0xc042badde8)
	/usr/local/go/src/runtime/debug/stack.go:24 +0xae
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x29
github.com/NebulousLabs/Sia/build.Severe(0xc042badfa0, 0x2, 0x2)
	/home/luke/go/src/github.com/NebulousLabs/Sia/build/critical.go:32 +0x8c
github.com/NebulousLabs/Sia/persist.(*Logger).Severe(0xc042168660, 0xc042badfa0, 0x2, 0x2)
	/home/luke/go/src/github.com/NebulousLabs/Sia/persist/log.go:71 +0xd3
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).syncResources.func1(0xc04404c010, 0xc04228e308)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:50 +0x402
created by github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).syncResources
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:25 +0x9a
Severe error: ERROR: unable to atomically copy the contract manager settings: rename C:\Users\Administrator\AppData\Roaming\Sia-UI\sia\host\contractmanager\contractmanager.json_temp C:\Users\Administrator\AppData\Roaming\Sia-UI\sia\host\contractmanager\contractmanager.json: Access is denied.
goroutine 65 [running]:
runtime/debug.Stack(0x446d5e, 0xc04226dab0, 0xc04226da78)
	/usr/local/go/src/runtime/debug/stack.go:24 +0xae
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x29
github.com/NebulousLabs/Sia/build.Severe(0xc04226dbf0, 0x2, 0x2)
	/home/luke/go/src/github.com/NebulousLabs/Sia/build/critical.go:32 +0x8c
github.com/NebulousLabs/Sia/persist.(*Logger).Severe(0xc042168660, 0xc04226dbf0, 0x2, 0x2)
	/home/luke/go/src/github.com/NebulousLabs/Sia/persist/log.go:71 +0xd3
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).syncResources(0xc04228e308)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:110 +0x6a5
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).commit(0xc04228e308)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:147 +0x47
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).threadedSyncLoop(0xc04228e308, 0xc04203ea80, 0xc04203eae0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:276 +0xa3
created by github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).spawnSyncLoop
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:223 +0xf4
Severe error: ERROR: could not rename temporary write-ahead-log in contract manager: rename C:\Users\Administrator\AppData\Roaming\Sia-UI\sia\host\contractmanager\contractmanager.wal_temp C:\Users\Administrator\AppData\Roaming\Sia-UI\sia\host\contractmanager\contractmanager.wal: Access is denied.
goroutine 1161131 [running]:
runtime/debug.Stack(0x446d5e, 0xc043575e20, 0xc043575de8)
	/usr/local/go/src/runtime/debug/stack.go:24 +0xae
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x29
github.com/NebulousLabs/Sia/build.Severe(0xc043575fa0, 0x2, 0x2)
	/home/luke/go/src/github.com/NebulousLabs/Sia/build/critical.go:32 +0x8c
github.com/NebulousLabs/Sia/persist.(*Logger).Severe(0xc042168660, 0xc043575fa0, 0x2, 0x2)
	/home/luke/go/src/github.com/NebulousLabs/Sia/persist/log.go:71 +0xd3
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).syncResources.func1(0xc04217f880, 0xc04228e308)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:50 +0x402
created by github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).syncResources
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:25 +0x9a
Severe error: ERROR: unable to atomically copy the contract manager settings: rename C:\Users\Administrator\AppData\Roaming\Sia-UI\sia\host\contractmanager\contractmanager.json_temp C:\Users\Administrator\AppData\Roaming\Sia-UI\sia\host\contractmanager\contractmanager.json: Access is denied.
goroutine 1373466 [running]:
runtime/debug.Stack(0x446d5e, 0xc042d11e20, 0xc042d11de8)
	/usr/local/go/src/runtime/debug/stack.go:24 +0xae
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x29
github.com/NebulousLabs/Sia/build.Severe(0xc042d11fa0, 0x2, 0x2)
	/home/luke/go/src/github.com/NebulousLabs/Sia/build/critical.go:32 +0x8c
github.com/NebulousLabs/Sia/persist.(*Logger).Severe(0xc042168660, 0xc042d11fa0, 0x2, 0x2)
	/home/luke/go/src/github.com/NebulousLabs/Sia/persist/log.go:71 +0xd3
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).syncResources.func1(0xc0459d0500, 0xc04228e308)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:50 +0x402
created by github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).syncResources
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:25 +0x9a
Severe error: ERROR: unable to atomically copy the contract manager settings: rename C:\Users\Administrator\AppData\Roaming\Sia-UI\sia\host\contractmanager\contractmanager.json_temp C:\Users\Administrator\AppData\Roaming\Sia-UI\sia\host\contractmanager\contractmanager.json: Access is denied.
goroutine 65 [running]:
runtime/debug.Stack(0x446d5e, 0xc04226dab0, 0xc04226da78)
	/usr/local/go/src/runtime/debug/stack.go:24 +0xae
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x29
github.com/NebulousLabs/Sia/build.Severe(0xc04226dbf0, 0x2, 0x2)
	/home/luke/go/src/github.com/NebulousLabs/Sia/build/critical.go:32 +0x8c
github.com/NebulousLabs/Sia/persist.(*Logger).Severe(0xc042168660, 0xc04226dbf0, 0x2, 0x2)
	/home/luke/go/src/github.com/NebulousLabs/Sia/persist/log.go:71 +0xd3
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).syncResources(0xc04228e308)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:110 +0x6a5
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).commit(0xc04228e308)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:147 +0x47
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).threadedSyncLoop(0xc04228e308, 0xc04203ea80, 0xc04203eae0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:276 +0xa3
created by github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).spawnSyncLoop
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:223 +0xf4
Severe error: ERROR: could not rename temporary write-ahead-log in contract manager: rename C:\Users\Administrator\AppData\Roaming\Sia-UI\sia\host\contractmanager\contractmanager.wal_temp C:\Users\Administrator\AppData\Roaming\Sia-UI\sia\host\contractmanager\contractmanager.wal: Access is denied.
2018/01/25 13:01:21 http: multiple response.WriteHeader calls
2018/01/25 13:36:41 http: multiple response.WriteHeader calls
2018/01/25 14:24:33 http: multiple response.WriteHeader calls
2018/01/25 21:57:25 http: multiple response.WriteHeader calls
goroutine 2408528 [running]:
runtime/debug.Stack(0x446d5e, 0xc0424abe20, 0xc0424abde8)
	/usr/local/go/src/runtime/debug/stack.go:24 +0xae
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x29
github.com/NebulousLabs/Sia/build.Severe(0xc0424abfa0, 0x2, 0x2)
	/home/luke/go/src/github.com/NebulousLabs/Sia/build/critical.go:32 +0x8c
github.com/NebulousLabs/Sia/persist.(*Logger).Severe(0xc042168660, 0xc0424abfa0, 0x2, 0x2)
	/home/luke/go/src/github.com/NebulousLabs/Sia/persist/log.go:71 +0xd3
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).syncResources.func1(0xc0429615e0, 0xc04228e308)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:50 +0x402
created by github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).syncResources
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:25 +0x9a
Severe error: ERROR: unable to atomically copy the contract manager settings: rename C:\Users\Administrator\AppData\Roaming\Sia-UI\sia\host\contractmanager\contractmanager.json_temp C:\Users\Administrator\AppData\Roaming\Sia-UI\sia\host\contractmanager\contractmanager.json: Access is denied.
goroutine 2421391 [running]:
runtime/debug.Stack(0x446d5e, 0xc0447d7e20, 0xc0447d7de8)
	/usr/local/go/src/runtime/debug/stack.go:24 +0xae
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x29
github.com/NebulousLabs/Sia/build.Severe(0xc0447d7fa0, 0x2, 0x2)
	/home/luke/go/src/github.com/NebulousLabs/Sia/build/critical.go:32 +0x8c
github.com/NebulousLabs/Sia/persist.(*Logger).Severe(0xc042168660, 0xc0447d7fa0, 0x2, 0x2)
	/home/luke/go/src/github.com/NebulousLabs/Sia/persist/log.go:71 +0xd3
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).syncResources.func1(0xc0424dfee0, 0xc04228e308)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:50 +0x402
created by github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).syncResources
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:25 +0x9a
Severe error: ERROR: unable to atomically copy the contract manager settings: rename C:\Users\Administrator\AppData\Roaming\Sia-UI\sia\host\contractmanager\contractmanager.json_temp C:\Users\Administrator\AppData\Roaming\Sia-UI\sia\host\contractmanager\contractmanager.json: Access is denied.
2018/01/26 05:48:54 http: multiple response.WriteHeader calls
goroutine 65 [running]:
runtime/debug.Stack(0x446d5e, 0xc043033ab0, 0xc043033a78)
	/usr/local/go/src/runtime/debug/stack.go:24 +0xae
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x29
github.com/NebulousLabs/Sia/build.Severe(0xc04226dbf0, 0x2, 0x2)
	/home/luke/go/src/github.com/NebulousLabs/Sia/build/critical.go:32 +0x8c
github.com/NebulousLabs/Sia/persist.(*Logger).Severe(0xc042168660, 0xc04226dbf0, 0x2, 0x2)
	/home/luke/go/src/github.com/NebulousLabs/Sia/persist/log.go:71 +0xd3
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).syncResources(0xc04228e308)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:110 +0x6a5
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).commit(0xc04228e308)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:147 +0x47
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).threadedSyncLoop(0xc04228e308, 0xc04203ea80, 0xc04203eae0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:276 +0xa3
created by github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).spawnSyncLoop
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:223 +0xf4
Severe error: ERROR: could not rename temporary write-ahead-log in contract manager: rename C:\Users\Administrator\AppData\Roaming\Sia-UI\sia\host\contractmanager\contractmanager.wal_temp C:\Users\Administrator\AppData\Roaming\Sia-UI\sia\host\contractmanager\contractmanager.wal: Access is denied.
goroutine 2597126 [running]:
runtime/debug.Stack(0x446d5e, 0xc045515e20, 0xc045515de8)
	/usr/local/go/src/runtime/debug/stack.go:24 +0xae
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x29
github.com/NebulousLabs/Sia/build.Severe(0xc045515fa0, 0x2, 0x2)
	/home/luke/go/src/github.com/NebulousLabs/Sia/build/critical.go:32 +0x8c
github.com/NebulousLabs/Sia/persist.(*Logger).Severe(0xc042168660, 0xc045515fa0, 0x2, 0x2)
	/home/luke/go/src/github.com/NebulousLabs/Sia/persist/log.go:71 +0xd3
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).syncResources.func1(0xc044b8c070, 0xc04228e308)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:50 +0x402
created by github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).syncResources
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:25 +0x9a
Severe error: ERROR: unable to atomically copy the contract manager settings: rename C:\Users\Administrator\AppData\Roaming\Sia-UI\sia\host\contractmanager\contractmanager.json_temp C:\Users\Administrator\AppData\Roaming\Sia-UI\sia\host\contractmanager\contractmanager.json: Access is denied.
2018/01/26 08:51:47 http: multiple response.WriteHeader calls
goroutine 65 [running]:
runtime/debug.Stack(0x446d5e, 0xc0442d5ab0, 0xc0442d5a78)
	/usr/local/go/src/runtime/debug/stack.go:24 +0xae
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x29
github.com/NebulousLabs/Sia/build.Severe(0xc0442d5bf0, 0x2, 0x2)
	/home/luke/go/src/github.com/NebulousLabs/Sia/build/critical.go:32 +0x8c
github.com/NebulousLabs/Sia/persist.(*Logger).Severe(0xc042168660, 0xc0442d5bf0, 0x2, 0x2)
	/home/luke/go/src/github.com/NebulousLabs/Sia/persist/log.go:71 +0xd3
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).syncResources(0xc04228e308)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:110 +0x6a5
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).commit(0xc04228e308)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:147 +0x47
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).threadedSyncLoop(0xc04228e308, 0xc04203ea80, 0xc04203eae0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:276 +0xa3
created by github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).spawnSyncLoop
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:223 +0xf4
Severe error: ERROR: could not rename temporary write-ahead-log in contract manager: rename C:\Users\Administrator\AppData\Roaming\Sia-UI\sia\host\contractmanager\contractmanager.wal_temp C:\Users\Administrator\AppData\Roaming\Sia-UI\sia\host\contractmanager\contractmanager.wal: Access is denied.
goroutine 65 [running]:
runtime/debug.Stack(0x446d5e, 0xc0442d5ab0, 0xc0442d5a78)
	/usr/local/go/src/runtime/debug/stack.go:24 +0xae
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x29
github.com/NebulousLabs/Sia/build.Severe(0xc0442d5bf0, 0x2, 0x2)
	/home/luke/go/src/github.com/NebulousLabs/Sia/build/critical.go:32 +0x8c
github.com/NebulousLabs/Sia/persist.(*Logger).Severe(0xc042168660, 0xc0442d5bf0, 0x2, 0x2)
	/home/luke/go/src/github.com/NebulousLabs/Sia/persist/log.go:71 +0xd3
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).syncResources(0xc04228e308)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:110 +0x6a5
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).commit(0xc04228e308)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:147 +0x47
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).threadedSyncLoop(0xc04228e308, 0xc04203ea80, 0xc04203eae0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:276 +0xa3
created by github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).spawnSyncLoop
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:223 +0xf4
Severe error: ERROR: could not rename temporary write-ahead-log in contract manager: rename C:\Users\Administrator\AppData\Roaming\Sia-UI\sia\host\contractmanager\contractmanager.wal_temp C:\Users\Administrator\AppData\Roaming\Sia-UI\sia\host\contractmanager\contractmanager.wal: Access is denied.
2018/01/26 13:24:09 http: multiple response.WriteHeader calls
goroutine 65 [running]:
runtime/debug.Stack(0x446d5e, 0xc0442d5ab0, 0xc0442d5a78)
	/usr/local/go/src/runtime/debug/stack.go:24 +0xae
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x29
github.com/NebulousLabs/Sia/build.Severe(0xc0442d5bf0, 0x2, 0x2)
	/home/luke/go/src/github.com/NebulousLabs/Sia/build/critical.go:32 +0x8c
github.com/NebulousLabs/Sia/persist.(*Logger).Severe(0xc042168660, 0xc0442d5bf0, 0x2, 0x2)
	/home/luke/go/src/github.com/NebulousLabs/Sia/persist/log.go:71 +0xd3
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).syncResources(0xc04228e308)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:110 +0x6a5
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).commit(0xc04228e308)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:147 +0x47
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).threadedSyncLoop(0xc04228e308, 0xc04203ea80, 0xc04203eae0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:276 +0xa3
created by github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).spawnSyncLoop
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:223 +0xf4
Severe error: ERROR: could not rename temporary write-ahead-log in contract manager: rename C:\Users\Administrator\AppData\Roaming\Sia-UI\sia\host\contractmanager\contractmanager.wal_temp C:\Users\Administrator\AppData\Roaming\Sia-UI\sia\host\contractmanager\contractmanager.wal: Access is denied.
goroutine 65 [running]:
runtime/debug.Stack(0x446d5e, 0xc0442d5ab0, 0xc0442d5a78)
	/usr/local/go/src/runtime/debug/stack.go:24 +0xae
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x29
github.com/NebulousLabs/Sia/build.Severe(0xc0442d5bf0, 0x2, 0x2)
	/home/luke/go/src/github.com/NebulousLabs/Sia/build/critical.go:32 +0x8c
github.com/NebulousLabs/Sia/persist.(*Logger).Severe(0xc042168660, 0xc0442d5bf0, 0x2, 0x2)
	/home/luke/go/src/github.com/NebulousLabs/Sia/persist/log.go:71 +0xd3
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).syncResources(0xc04228e308)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:110 +0x6a5
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).commit(0xc04228e308)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:147 +0x47
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).threadedSyncLoop(0xc04228e308, 0xc04203ea80, 0xc04203eae0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:276 +0xa3
created by github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).spawnSyncLoop
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:223 +0xf4
Severe error: ERROR: could not rename temporary write-ahead-log in contract manager: rename C:\Users\Administrator\AppData\Roaming\Sia-UI\sia\host\contractmanager\contractmanager.wal_temp C:\Users\Administrator\AppData\Roaming\Sia-UI\sia\host\contractmanager\contractmanager.wal: Access is denied.
2018/01/26 16:37:19 http: multiple response.WriteHeader calls
2018/01/26 16:37:19 http: multiple response.WriteHeader calls
goroutine 3280612 [running]:
runtime/debug.Stack(0x446d5e, 0xc043af9e20, 0xc043af9de8)
	/usr/local/go/src/runtime/debug/stack.go:24 +0xae
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x29
github.com/NebulousLabs/Sia/build.Severe(0xc043af9fa0, 0x2, 0x2)
	/home/luke/go/src/github.com/NebulousLabs/Sia/build/critical.go:32 +0x8c
github.com/NebulousLabs/Sia/persist.(*Logger).Severe(0xc042168660, 0xc043af9fa0, 0x2, 0x2)
	/home/luke/go/src/github.com/NebulousLabs/Sia/persist/log.go:71 +0xd3
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).syncResources.func1(0xc0427fa0d0, 0xc04228e308)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:50 +0x402
created by github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).syncResources
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:25 +0x9a
Severe error: ERROR: unable to atomically copy the contract manager settings: rename C:\Users\Administrator\AppData\Roaming\Sia-UI\sia\host\contractmanager\contractmanager.json_temp C:\Users\Administrator\AppData\Roaming\Sia-UI\sia\host\contractmanager\contractmanager.json: Access is denied.
goroutine 3469345 [running]:
runtime/debug.Stack(0x446d5e, 0xc043e8beb8, 0xc043e8be80)
	/usr/local/go/src/runtime/debug/stack.go:24 +0xae
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x29
github.com/NebulousLabs/Sia/build.Severe(0xc043e8bf18, 0x2, 0x2)
	/home/luke/go/src/github.com/NebulousLabs/Sia/build/critical.go:32 +0x8c
github.com/NebulousLabs/Sia/api.cleanCloseHandler.func1.2(0xc046274780, 0xc049938f00, 0xc043435200)
	/home/luke/go/src/github.com/NebulousLabs/Sia/api/routes.go:159 +0x18d
created by github.com/NebulousLabs/Sia/api.cleanCloseHandler.func1
	/home/luke/go/src/github.com/NebulousLabs/Sia/api/routes.go:154 +0x1e3
Severe error: api call is taking more than 60 minutes to return: /consensus
2018/01/27 01:19:07 http: multiple response.WriteHeader calls
2018/01/27 05:03:38 http: multiple response.WriteHeader calls
2018/01/27 05:03:38 http: multiple response.WriteHeader calls
goroutine 65 [running]:
runtime/debug.Stack(0x446d5e, 0xc0442d5ab0, 0xc0442d5a78)
	/usr/local/go/src/runtime/debug/stack.go:24 +0xae
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x29
github.com/NebulousLabs/Sia/build.Severe(0xc0442d5bf0, 0x2, 0x2)
	/home/luke/go/src/github.com/NebulousLabs/Sia/build/critical.go:32 +0x8c
github.com/NebulousLabs/Sia/persist.(*Logger).Severe(0xc042168660, 0xc0442d5bf0, 0x2, 0x2)
	/home/luke/go/src/github.com/NebulousLabs/Sia/persist/log.go:71 +0xd3
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).syncResources(0xc04228e308)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:110 +0x6a5
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).commit(0xc04228e308)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:147 +0x47
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).threadedSyncLoop(0xc04228e308, 0xc04203ea80, 0xc04203eae0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:276 +0xa3
created by github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).spawnSyncLoop
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:223 +0xf4
Severe error: ERROR: could not rename temporary write-ahead-log in contract manager: rename C:\Users\Administrator\AppData\Roaming\Sia-UI\sia\host\contractmanager\contractmanager.wal_temp C:\Users\Administrator\AppData\Roaming\Sia-UI\sia\host\contractmanager\contractmanager.wal: Access is denied.
goroutine 65 [running]:
runtime/debug.Stack(0x446d5e, 0xc0442d5ab0, 0xc0442d5a78)
	/usr/local/go/src/runtime/debug/stack.go:24 +0xae
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x29
github.com/NebulousLabs/Sia/build.Severe(0xc0442d5bf0, 0x2, 0x2)
	/home/luke/go/src/github.com/NebulousLabs/Sia/build/critical.go:32 +0x8c
github.com/NebulousLabs/Sia/persist.(*Logger).Severe(0xc042168660, 0xc0442d5bf0, 0x2, 0x2)
	/home/luke/go/src/github.com/NebulousLabs/Sia/persist/log.go:71 +0xd3
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).syncResources(0xc04228e308)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:110 +0x6a5
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).commit(0xc04228e308)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:147 +0x47
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).threadedSyncLoop(0xc04228e308, 0xc04203ea80, 0xc04203eae0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:276 +0xa3
created by github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).spawnSyncLoop
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:223 +0xf4
Severe error: ERROR: could not rename temporary write-ahead-log in contract manager: rename C:\Users\Administrator\AppData\Roaming\Sia-UI\sia\host\contractmanager\contractmanager.wal_temp C:\Users\Administrator\AppData\Roaming\Sia-UI\sia\host\contractmanager\contractmanager.wal: Access is denied.
2018/01/27 05:35:17 http: multiple response.WriteHeader calls
goroutine 65 [running]:
runtime/debug.Stack(0x446d5e, 0xc0442d5ab0, 0xc0442d5a78)
	/usr/local/go/src/runtime/debug/stack.go:24 +0xae
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x29
github.com/NebulousLabs/Sia/build.Severe(0xc0442d5bf0, 0x2, 0x2)
	/home/luke/go/src/github.com/NebulousLabs/Sia/build/critical.go:32 +0x8c
github.com/NebulousLabs/Sia/persist.(*Logger).Severe(0xc042168660, 0xc0442d5bf0, 0x2, 0x2)
	/home/luke/go/src/github.com/NebulousLabs/Sia/persist/log.go:71 +0xd3
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).syncResources(0xc04228e308)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:110 +0x6a5
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).commit(0xc04228e308)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:147 +0x47
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).threadedSyncLoop(0xc04228e308, 0xc04203ea80, 0xc04203eae0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:276 +0xa3
created by github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).spawnSyncLoop
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:223 +0xf4
Severe error: ERROR: could not rename temporary write-ahead-log in contract manager: rename C:\Users\Administrator\AppData\Roaming\Sia-UI\sia\host\contractmanager\contractmanager.wal_temp C:\Users\Administrator\AppData\Roaming\Sia-UI\sia\host\contractmanager\contractmanager.wal: Access is denied.
Closing renter...

**Comment by tbenz9** [comment] 2018-01-29 23:50
Duplicate of #2374 

Workaround listed here: https://gist.github.com/tbenz9/8066d74853ab28c23bd7bc1d3c7cdeda

**Closed by tbenz9** 2018-01-29 23:50 UTC
