### ISSUE TITLE
Siad has exited unexpectedly. Please submit a bug report including the error log here.

### ISSUE THREAD

**Issue by hklkf200553** [NebulousLabs/Sia#2186] opened 2017-07-26 17:06 UTC
Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 0.4651088 seconds

got these error once updated to 1.3

**Comment by hklkf200553** [comment] 2017-07-26 17:08
Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 0.4188763 seconds
panic: runtime error: slice bounds out of range

goroutine 27 [running]:
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).getBlockTotals(0xc042125b80, 0xc0430ea9a0, 0x2d00000000000000, 0x204bd0054a706416, 0x48e6d4e4d1fe687f, 0x9cdfb0295c44c24, 0xc04316e1c0, 0x0, 0x0, 0x0, ...)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/difficulty.go:120 +0x13b
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).newChild(0xc042125b80, 0xc0430ea9a0, 0xc043c094a0, 0x2d00000000000000, 0x204bd0054a706416, 0x48e6d4e4d1fe687f, 0x9cdfb0295c44c24, 0x8cc706c400465f48, 0x5978ca6b, 0xc04316e1c0, ...)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/processedblock.go:135 +0x1a8
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).addBlockToTree(0xc042125b80, 0xc0430ea9a0, 0x2d00000000000000, 0x204bd0054a706416, 0x48e6d4e4d1fe687f, 0x9cdfb0295c44c24, 0x8cc706c400465f48, 0x5978ca6b, 0xc04316e1c0, 0x1, ...)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/accept.go:151 +0xa3
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).managedAcceptBlocks.func1(0xc0430ea9a0, 0xb0b570, 0xc0430ea9a0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/accept.go:262 +0x23a
github.com/NebulousLabs/bolt.(*DB).Update(0xc0420f2780, 0xc043b6d2e8, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/bolt/db.go:603 +0xa6
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).managedAcceptBlocks(0xc042125b80, 0xc04237d380, 0x2, 0x2, 0x0, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/accept.go:283 +0x520
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).managedReceiveBlocks(0xc042125b80, 0xde41c0, 0xc043c14440, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:225 +0x5be
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).(github.com/NebulousLabs/Sia/modules/consensus.managedReceiveBlocks)-fm(0xde41c0, 0xc043c14440, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:445 +0x45
github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).managedRPC(0xc042066c60, 0xc0421967c0, 0x13, 0xaddb78, 0xa, 0xc042dbc620, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/rpc.go:66 +0x339
github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).RPC(0xc042066c60, 0xc0421967c0, 0x13, 0xaddb78, 0xa, 0xc042dbc620, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/rpc.go:76 +0xd8
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).threadedInitialBlockchainDownload.func1(0xc042125b80, 0xc043b6def0, 0xc043b6deb0, 0xc043b6deb8, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:580 +0x133
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).threadedInitialBlockchainDownload(0xc042125b80, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:601 +0x30e
github.com/NebulousLabs/Sia/modules/consensus.New.func1(0x1, 0xc042234b10, 0xc042125b80, 0xde4440, 0xc042066c60)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/consensusset.go:151 +0x404
created by github.com/NebulousLabs/Sia/modules/consensus.New
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/consensusset.go:182 +0x641


got another version when i reboot the system and start again

**Comment by lukechampine** [comment] 2017-07-26 17:46
Looks like a duplicate of #2183.

**Closed by lukechampine** 2017-07-26 17:46 UTC
