### ISSUE TITLE
First time syncing gives error "Siad has exited unexpectedly"

### ISSUE THREAD

**Issue by Beshr458** [NebulousLabs/Sia#2315] opened 2017-09-13 10:24 UTC
Hi,

I am syncing Sia UI for first time install and on 33.4% I get this error "Siad has exited unexpectedly"

Any help please?

The logs are:
Loading...
(0/6) Loading siad...
listen tcp 127.0.0.1:9980: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted.
Closing host...
panic: bolt.DB.meta(): invalid meta pages
	panic: bolt.DB.meta(): invalid meta pages

goroutine 14 [running]:
github.com/NebulousLabs/bolt.(*DB).meta(0xc0420dc780, 0x104a)
	/home/luke/go/src/github.com/NebulousLabs/bolt/db.go:830 +0xed
github.com/NebulousLabs/bolt.(*Tx).rollback(0xc04ab52e00)
	/home/luke/go/src/github.com/NebulousLabs/bolt/tx.go:255 +0x88
github.com/NebulousLabs/bolt.(*DB).Update.func1(0xc04ab52e00)
	/home/luke/go/src/github.com/NebulousLabs/bolt/db.go:595 +0x45
panic(0x9f3160, 0xc0479b34e0)
	/usr/local/go/src/runtime/panic.go:489 +0x2dd
github.com/NebulousLabs/bolt.(*DB).meta(0xc0420dc780, 0x104a)
	/home/luke/go/src/github.com/NebulousLabs/bolt/db.go:830 +0xed
github.com/NebulousLabs/bolt.(*Tx).rollback(0xc04ab52e00)
	/home/luke/go/src/github.com/NebulousLabs/bolt/tx.go:255 +0x88
github.com/NebulousLabs/bolt.(*Tx).Commit(0xc04ab52e00, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/bolt/tx.go:164 +0x8a0
github.com/NebulousLabs/bolt.(*DB).Update(0xc0420dc780, 0xc0490552e8, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/bolt/db.go:610 +0xfe
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).managedAcceptBlocks(0xc042115b80, 0xc04b90c000, 0xa, 0xa, 0x0, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/accept.go:283 +0x520
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).managedReceiveBlocks(0xc042115b80, 0xde41c0, 0xc0469722c0, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:225 +0x5be
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).(github.com/NebulousLabs/Sia/modules/consensus.managedReceiveBlocks)-fm(0xde41c0, 0xc0469722c0, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:445 +0x45
github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).managedRPC(0xc04205cc60, 0xc042174100, 0x13, 0xaddb78, 0xa, 0xc046a64230, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/rpc.go:66 +0x339
github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).RPC(0xc04205cc60, 0xc042174100, 0x13, 0xaddb78, 0xa, 0xc046a64230, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/rpc.go:76 +0xd8
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).threadedInitialBlockchainDownload.func1(0xc042115b80, 0xc04480fef0, 0xc04480feb0, 0xc04480feb8, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:580 +0x133
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).threadedInitialBlockchainDownload(0xc042115b80, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:601 +0x30e
github.com/NebulousLabs/Sia/modules/consensus.New.func1(0x1, 0xc0421ecd80, 0xc042115b80, 0xde4440, 0xc04205cc60)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/consensusset.go:151 +0x404
created by github.com/NebulousLabs/Sia/modules/consensus.New
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/consensusset.go:182 +0x641

**Comment by tbenz9** [comment] 2017-10-06 20:06
`listen tcp 127.0.0.1:9980: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted.` means you already have a process listening on port 9980.  Make sure you are not already running `siad` or try changing the default port that sia uses.  Simply rebooting typically solves this problem also.

If you're still having problems try asking for help at https://discord.gg/sia

The `panic: bolt.DB.meta invalid meta pages` looks like a duplicate of issue #2349 

Recommendation to devs: close this issue

**Closed** 2017-10-07 00:40 UTC
