### ISSUE TITLE
running "renter allowance cancel" from SIA-UI terminal crashes siad

### ISSUE THREAD

**Issue by cyjambo** [NebulousLabs/Sia#2873] opened 2018-03-15 22:23 UTC
# BUG REPORT
I am trying to cancel my allowance (basically remove all my files from renter and stop using the renter function. Siad crashes when I try to run "renter allowance cancel" from the UI terminal. Attached is the log.
[log.txt](https://github.com/NebulousLabs/Sia/files/1817304/log.txt)

**Expected Behavior**
I want to cancel all of my allowance with the command "renter allowance cancel". It should just work :)

**How to reproduce it (as minimally and precisely as possible)**
Have lots of files under renter and issue the command renter allowance cancel from the SIA GUI terminal.

**Environment**
VM on VMWare with dual-core Xeon E3-1265L V2 @ 2.5Ghz and 8Gb of memory.

* Sia version:
SIA-GUI 1.3.2

* OS:
Windows 10 64-bit

**Comment by tbenz9** [comment] 2018-03-15 23:36
I spoke with this user on Discord.  They are running out of RAM, and report that they have "lots of files" and "most of them less than 40MB".  This looks like a duplicate of #2850 where the user is running out of RAM due to many small files.  

The devs are very aware that Sia performs suboptimally with files smaller than 40MB. Smaller file support is on the feature roadmap, and the devs are actively working on improving this limitation.

**Closed by tbenz9** 2018-03-15 23:36 UTC
